### ISSUE TITLE
TextField: Does not render tooltip "Please fill out this field." on hover in IE/Edge

### ISSUE THREAD

**Issue by thuy-n-lu** [OfficeDev/office-ui-fabric-react#10066]
### Environment Information

- **Package version(s)**: (fill this out)
7
- **Browser and OS versions**: (fill this out if relevant)
IE11/Edge

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/anon/pen/mNpRpN
#### Actual behavior:
When a TextField with the required property is hovered over in IE11/Edge, a tooltip that says 'Please fill out this field.' does not show, unlike Chrome/Firefox/Edge Anaheim

#### Expected behavior:
When a TextField with the required property is hovered over in IE11/Edge, a tooltip that says 'Please fill out this field.' shows

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No
Requested priority: (Blocking, High, Normal, Low)
Low

**Comment by jdhuntington** [comment]
Hi @thuy-n-lu - I believe the behavior you are seeing is built in to the browser and shows on any required text field. It looks like IE/Edge does not include this functionality, which is why you aren't seeing it there.

It would be possible to include the Fabric tooltip control on a required field yourself, but it's not an out-of-the-box feature of the text field.
