### ISSUE TITLE
Dialog scrolls to the top when open

### ISSUE THREAD

**Issue by aslanovsergey** [OfficeDev/office-ui-fabric-react#10083]
### Environment Information

- **Package version(s)**: 6.195.5
- **Browser and OS versions**: Windows 10, Chrome (Latest)

#### Actual behavior:

I don't understand what causes Dialog to scroll to the top if I'm opening an item from below of a list.

To better understand what I mean the last example(called Modeless Dialog) on Office UI Fabric library site shows exactly this thing. https://developer.microsoft.com/en-us/fabric#/controls/web/dialog

Although it returns back when I close dialog it's not what I want. All other examples will save scroll position in document. I have the same problem in my project where I use Dialog component and I can't figure out what makes difference...

**Comment by jdhuntington** [comment]
Hi @aslanovsergey - The scrolling behavior is related to the dialog being `modeless`. If the dialog is modeless, the dialog is absolutely positioned and the browser is scrolled to that location. Otherwise an overlay is used and no scrolling is required. This demo shows an example of a dialog with and without `isModeless` set: https://codepen.io/jdh-msft/pen/QeQXab?editors=0010

Does that mirror what you're seeing in your application?

**Comment by aslanovsergey** [comment]
@jdhuntington Thanks a lot for the example but in my product it doesn't work for some reasons, I will try to build a demo
