### ISSUE TITLE
Fabric component cause re-rendering

### ISSUE THREAD

**Issue by tenaciousd93** [OfficeDev/office-ui-fabric-react#10123]
### Environment Information

- office-ui-fabric-react: **^7.22.1**
- react: **^16.9.0**
- react-dom: **^16.9.0**
- react-router-dom: **^5.0.1**
- react-scripts: **3.1.0**

### How to reproduce:
* Create a new react project and install fabric UI:
```
$ create-react-app test-bug
$ cd test-bug
$ npm install office-ui-fabric-react --save
$ npm start
```

* Open App.js and add the Fabric component:
```
return (
      <Fabric className="App">
     ....
     </Fabric>
);

```
#### Descriptinon:

Open Chrome developer tools, got o React tab (Need React developer tools: https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi ) and enabled "Highlight Updates".

For each click inside page you will see the whole container flash for re-render:

![problem](https://user-images.githubusercontent.com/3415752/62849057-6254d880-bcde-11e9-8bf1-7bb9047c01d7.gif)

This should cause the problem I've already reported in StackOverflow ( https://stackoverflow.com/questions/57323517/react-re-render-anything-anytime ): re-render 1000+ elements cause huge latency for UX.

**Comment by JasonGore** [comment]
I've created [a CodePen](https://codepen.io/jasongore/pen/KOjwez) that's similar to your example. You may have to fork it and choose `Change View` => `Debug mode` to see highlights (or try [this link](https://s.codepen.io/jasongore/debug/KOjwez/xnMabZodxQxr).)

As you said, React is highlighting updates on the `Fabric` component because `Fabric` has an `onMouseDown` handler that changes internal state. I do not, however, see React rerendering any of the children. I've created a `TestComponent` that logs output in the render `function` and it is only called on initial page load.

I believe what you're seeing is React highlighting the fact that `Fabric` update its internal state, but I do not see evidence of its children rerendering.
