### ISSUE TITLE
TextField will be readonly if there is no onChange and onBlur defined

### ISSUE THREAD

**Issue by nguyentoantuit** [OfficeDev/office-ui-fabric-react#10121]
We have a strict like bellowing:
You provided a 'value' prop to a TextField without an 'onChange' handler. This will render a read-only field. If the field should be mutable use 'defaultValue'. Otherwise, set 'onChange' or 'readOnly'.

Sometimes I use onBlur instead of onChange to increase performance. Can we support both onChange and onBlur? So the textfield will be readonly if there is no onChange or onBlur defined.

**Comment by JasonGore** [comment]
A `TextField` can be used in both *controlled* and *uncontrolled* scenarios. 

A *controlled* scenario means you control exactly what is shown in the `TextField`, including any changes made by the user that you want to reflect. In order for this to work you need to provide both `value` and `onChange` props.

An *uncontrolled* scenario means you want the `TextField` to automatically update its internal state based on user input, which means it will reflect user input as the user types into the `TextField`.

The reason you are seeing a warning is that you have provided only part of what is required for a *controlled* scenario. If you want to specify `value`, then you should also specify `onChange`. However, it does seem that `onBlur` should also be considered for *controlled* scenarios to prevent the warning from appearing. @ecraig12345 what do you think?

We can't automatically make the control readonly if neither are provided because it is interpreted as an *uncontrolled* scenario. The `readOnly` prop allows you to explicitly set this behavior.

**Comment by ecraig12345** [comment]
The TextField intentionally doesn't do internal state tracking when controlled, so it's not possible to make `onBlur` work with `value` the way you want. This mirrors the behavior of React's built-in `input` elements.

If you want to use only `onBlur` to track changes, there are a couple possible approaches:

1. Use the `defaultValue` prop rather than `value`, so the TextField will be uncontrolled and track its state internally. Caveat: updates to `defaultValue` aren't respected, so if you need to update the value after blur in response to validation or whatever, you can update the TextField's `key` prop to force it to be re-created with the new `defaultValue` (this handling of `key` updates is a React feature, not specific to TextField).

2. Continue using `value`, but provide an `onChange` handler to track the intermediate value in your component's state, and update the TextField's `value` based on the intermediate value

If you need TextFields with this behavior in multiple places, either approach above could be encapsulated in a small wrapper component.

**Comment by JasonGore** [comment]
@nguyentoantuit Does this feedback help? Please let us know if you have any other questions.

**Comment by nguyentoantuit** [comment]
Using defaultValue and key to force it re-create new instance seems work for me. 
The reason I don't want to use onChange because I don't want to update the same for single change, I just want to update state of my component when use finish typing data.
Thanks for your info and suggestion @JasonGore @ecraig12345

**Comment by JasonGore** [comment]
If you are satisfied and don't have any other question or issue, please close the issue. Thanks!

**Comment by lukasbash** [comment]
From what I got from the discussion above, the behavior of being readonly is intended.
But why did it work in a previous version? Was it a bug then?

I remember having it working with something like 6.192.0.

**Comment by ecraig12345** [comment]
Yes, it was a bug--see #1350.

**Comment by lukasbash** [comment]
@ecraig12345 Thank you for the fast response! And many thanks for clarifying it!
