### ISSUE TITLE
[Accessibility] MessageBar focus order is not correct

### ISSUE THREAD

**Issue by rsemenov** [OfficeDev/office-ui-fabric-react#1018]
### Bug Report

- __Package version(s)__: master

#### Describe the issue:

Multi-line MessageBar with dismiss callback and focusable element in the text receives focus on dismiss button before focusable element inside the message.

#### Expected behavior:

Focus should be set to the focusable element inside the text, and then after user press tab to the dismiss element.

### If applicable, please provide a codepen repro:

https://codepen.io/rsemenov/pen/QdPqgM

**Comment by dzearing** [comment]
I checked out the DOM. It is defined in the incorrect order. Which is really surprising because flexbox is used here, which makes this problem really trivial to avoid an absolute positioned button.

@mdahamiwal or @jdhuntington This may also impact your use cases. If you have cycles can you fix? Please feel free to assign to yourselves.

**Comment by rsemenov** [comment]
@dzearing, I actually already started fixing it. I will send pr soon
