### ISSUE TITLE
getParent returns non-HTMLElement values

### ISSUE THREAD

**Issue by chenxinyanc** [OfficeDev/office-ui-fabric-react#10199]
### Environment Information

- **Package version(s)**: 7.21.0
- **Browser and OS versions**: Edge 78.0.244.0 Dev on Windows 10

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/xinychen/pen/qBWaxry

#### Actual behavior:
![image](https://user-images.githubusercontent.com/50703224/63319297-2f4cbd80-c34c-11e9-8a0e-f1cf8b02fb76.png)

#### Expected behavior:
We should not see `#document` node in the output, because `document` is not a `HTMLElement`.

https://github.com/OfficeDev/office-ui-fabric-react/blob/f0097f821ad499049f8e43c6b854ecc9419ecf7b/packages/utilities/src/dom/getParent.ts#L9-L11

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: -

**Comment by kenotron** [comment]
@maxwellred - please confirm that this behavior is indeed NOT desired with people who wrote it (look up git blame) and then follow up with them if you're actually making a behavior change. You may also decide that this isn't a desired behavior change because of risk, etc.

**Comment by maxwellred** [comment]
@chenxinyanc Thank you for opening the issue about the getParent() function returning the document object! Since getParent() isn't part of the public API we are going to leave it as is. You can reach me on Teams to discuss further what you are trying to accomplish if you'd like? You can access the DOM element's parentNode through myRef.current.parentNode if that helps. An interesting note is that parentNode natively returns the document object as its considered the parent node of the <html> tag. Let me know if there's anything more I can clarify and thanks again!

**Comment by chenxinyanc** [comment]
I need to find the logic ancestor of a drop-down item from DOM tree (i.e. given a DOM item in the drop-down list, I want to find its owner), and using `getParent(..., true)` makes such traversal possible. Since this function returns `document` node, perhaps declaring returning `Node` instead of `HTMLElement` might be more accurate.

I think keeping this function untouched won't affect me that much. I simply need to add an `instanceof` expression to filter it out and all will be fine.
