### ISSUE TITLE
Cards CodePen example doesn't work

### ISSUE THREAD

**Issue by rhalaly** [OfficeDev/office-ui-fabric-react#10203]
### Environment Information

- **Package version(s)**: Latest
- **Browser and OS versions**: Chrome, Edge, Edge Beta. Windows 10

### Please provide a reproduction of the bug in a codepen:
https://developer.microsoft.com/en-us/fabric#/controls/web/card

#### Actual behavior:

The examples in CodePen are empty

#### Expected behavior:

The examples should appear

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Low

Products/sites affected: (if applicable)

**Comment by kenotron** [comment]
@khmakoto - can you take a look?

**Comment by khmakoto** [comment]
It makes sense that the codepen examples are not rendering, because the generated code is trying to import the `Cards` from the `office-ui-fabric-react` package. [Here is a link](https://codepen.io/khmakoto/pen/VwZKowP?&editable=true) to the vertical cards example working on a codepen.

I'll take a look to see if this is something easily fixable or if we should disable the export to codepen functionality in the `Card` component at least until it is not experimental anymore.

**Comment by kenotron** [comment]
I think we should disable the codepen link for now like you said...
