### ISSUE TITLE
SyntaxError: Unexpected token: string (./components/Spinner/index)

### ISSUE THREAD

**Issue by bhedayatian** [OfficeDev/office-ui-fabric-react#10215]
I recently upgraded office-ui-fabric-react to @7.25.1 
webpack version is: ^1.13.1

I am getting this error when tried to run this 
webpack --config webpack.config.production.js && gulp compile

ERROR in ./build/app.build.js from UglifyJs
SyntaxError: Unexpected token: string (./components/Spinner/index) [./~/office-ui-fabric-react/lib/Spinner.js:1,0]

**Comment by kenotron** [comment]
Several things:

1. webpack 1.x is pretty old - you should really use webpack 4 these days as we've moved to ESM which I'm not sure if webpack 1.x supported
2. it would be much more helpful if you can provide a minimal repro as it is impossible for us to know what the root cause here is without that

I'm fairly certain at this point that your problem is in the use of an old webpack version. I'll be marking this as by design. If you have tried upgrading to wp4 and it still fails, then feel free to reply with a repro sample repo or something similar.

**Comment by bhedayatian** [comment]
it's resolved. thanks
