### ISSUE TITLE
Callout beak disappears after re-render (when target is inside CommandBar)

### ISSUE THREAD

**Issue by szmarci** [OfficeDev/office-ui-fabric-react#10220]
### Environment Information

- **Package version(s)**: 7.25.0
- **Browser and OS versions**: Chrome (latest)

### Please provide a reproduction of the bug in a codepen:

codesandbox:
https://codesandbox.io/s/youthful-minsky-i0082?fontsize=14

#### Actual behavior:

When the callout target is inside CommandBar as a custom rendered CommandBarButton, the beak for the callout disappears in subsequent renders, after the initial render.

1. Click on Save
2. (It is fine on first render)
3. Click Cancel, then Save again.
4. Beak is gone.

#### Expected behavior:

Expected the beak present in every render.

**Comment by szmarci** [comment]
Just updated the codepen with another scenario.
After any re-render, the beak and both the position of the callout is lost.

1. First hit re-render in the updated codepen.
2. Then click Save.
3. Now beak and position is lost.

**Comment by kenotron** [comment]
There's some timing funkiness here. The ref is set when onRender is called inside commandbar, so it's .current doesn't have the right element when the focustrapcallout is rendered... you should be able to to pass in the actual ref instead of the current snapshot of the ref to callout per the work done in #9666 

@joschect and I were looking at this, and he suggested you can use an id as a workaround:
https://codesandbox.io/s/compassionate-smoke-tbvvf

This still seems suboptimal, but this could be a good workaround for you for now. We will see if we can make this case work by delaying the .current call to when you do update the props. If this works, please close this bug, we'll follow up separately with a fix to callout.

**Comment by szmarci** [comment]
@kenotron This solution works for me, thank you for the investigation.
