### ISSUE TITLE
A11y_Dynamics for Microsoft_Quick Create: Labor Entry_Screen Reader: Narrator is not reading the previous and next buttons in the calendar properly

### ISSUE THREAD

**Issue by Accessibility56** [OfficeDev/office-ui-fabric-react#10265]
[Check out Accessibility Insights!](https://microsoft.sharepoint.com/teams/msenable/Pages/accessibility-tools.aspx) - Identify accessibility bugs before check-in and make bug fixing faster and easier

**Environment Details:**
**URL:**  https://cs-labor-test.crm.dynamics.com/main.aspx
Server version: 9.1.0000.6228
Client version: 1.3.1948-190626-193951
OS: Windows 10 , Version 1903 , OS Build 18362.239
Browser & Version: Edge  44.18362.1.0 , Chrome 75.0.3770.142
Screen Reader: Narrator

**NOTE:** NVDA is reading as "button" for the previous and next buttons in the Calendar for year

**Repro Steps:**
1. Start Narrator. Hit the url: https://cs-labor-test.crm.dynamics.com/main.aspx and login with valid credentials
2. Tab till "New Time Entry" button and press enter
3. Tab till "Date" textbox and press enter. Calendar control will open
4. Tab till previous and next buttons 
5. Check if narrator is reading the buttons properly

**Actual Result:**
Narrator is not reading the buttons properly. Narrator is reading the button as "date_navigate_previous_month may" button

**Expected Result:**
Narrator should read the buttons as Previous/Next month button for months and Previous/Next year button for years
NOTE: NVDA is reading the buttons properly for Month.

**User Impact:**
Screen reader users will find it difficult to use the calendar

**MAS Reference:**
[MAS 1.3.1](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7b54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4%7d)
[Bug_10265.pptx](https://github.com/OfficeDev/office-ui-fabric-react/files/3540890/Bug_10265.pptx)

**Comment by lorejoh12** [comment]
Hmm. We have a property on Calendar component, `strings: ICalendarStrings`, which has properties on it for the previous and next month/year buttons. But those buttons have defaults if not defined, which default to the English 'Go to previous month' etc., defined here: https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/date-time/src/components/Calendar/Calendar.base.tsx

The fact that the bug states "date_navigate_previous_month may", that first part "date_navigate_previous_month" is not a string that exists anywhere in Fabric. I wonder if they're using the property for passing these labels, but not correctly localizing the string they're passing it. That certainly looks like a locstring name to me. So instead of it reading "Go to next month May", as expected, we're getting "locstringname May" instead.

The repro provided is in the CRM app, not a codepen repro, and I don't have permission to log into it so I can't see what's going on. But I'd suspect this is a bug to fix on their end, not in Fabric. However, it would probably be beneficial to add some accessibility guidance to the docs regardless.
