### ISSUE TITLE
How to call removeItem from a FloatingPicker 

### ISSUE THREAD

**Issue by bhedayatian** [OfficeDev/office-ui-fabric-react#10293]
I am using FloatingPicker and ExtendedSelectedItem and need to overwrite the remove item method with a custom method. can you please help?

**Comment by bhedayatian** [comment]
@joschect @Adjective-Object any tips? I am stuck!

**Comment by maxwellred** [comment]
Hi @bhedayatian Sorry for the delayed response. I'll take a look at this and get back to you.

**Comment by bhedayatian** [comment]
Yaaay! Thanks Max

**Comment by maxwellred** [comment]
Hi @bhedayatian I got a [codepen](https://codepen.io/CodeMax/pen/LYPLMZX) started with FloatingPeoplePicker but was hoping you could add some of the code to it that you are having trouble with in order to troubleshoot better? Also, are you speaking about the `public removeItem` method found in BaseSelectedItemsList.tsx?

**Comment by bhedayatian** [comment]
@maxwellred I used something like this and it works.. thanks for your help

{
    this.state.selectedUsers.map((user, index) =>
     <ExtendedSelectedItem key={`esi-${index}`} index={index} item={user}
         onRemoveItem={() => this._onItemDeleted(user)}
        />)
  }

**Comment by maxwellred** [comment]
@bhedayatian I'm glad you were able to get what you needed! I was hoping you could close the issue if there's nothing left you need from me, thanks!
