### ISSUE TITLE
Panel: make z-index configurable via a style property

### ISSUE THREAD

**Issue by JeanMarie1971** [OfficeDev/office-ui-fabric-react#10334]
#### Describe the feature that you would like added

The Panel now by default uses an inline style of z-index:100000. This causes some other applications to have trouble cause they're dynamic content is hidden behind the panel.
It would be great if the panel had a property that allowed a developer to configure the z-index so we can control how panels are layered.
This would solve a big issue when combining e.g. Tiny MCE with panels. The dialogs from Tiny MCE are hidden below the panel, because the Tiny MCE dialogs have a z-index of 65535, which is below te Panel's 100000.

#### What component or utility would this be added to

Panel

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

As statet in the description, this feature would greatly improve the flexibility of configuring how the panel is layered compared to other components on the page / react component.

**Comment by KevinTCoughlin** [comment]
The above seems like a reasonable request @JeanMarie1971. Let me see if we can allow for that style property to be overridden without regressing existing scenarios. My hope is that we can!

**Comment by JeanMarie1971** [comment]
OK. Thanks for investigating @KevinTCoughlin

**Comment by KevinTCoughlin** [comment]
@JeanMarie1971, it turns out that this can be done with the existing code, though it took me a bit to figure out. See the below diff for the changes required:

```diff
diff --git a/packages/office-ui-fabric-react/src/components/Panel/examples/Panel.SmallRight.Example.tsx b/packages/office-ui-fabric-react/src/components/Panel/examples/Panel.SmallRight.Example.tsx
index df5fdf167..b3bd00440 100644
--- a/packages/office-ui-fabric-react/src/components/Panel/examples/Panel.SmallRight.Example.tsx
+++ b/packages/office-ui-fabric-react/src/components/Panel/examples/Panel.SmallRight.Example.tsx
@@ -20,6 +20,7 @@ export class PanelSmallRightExample extends React.Component<{}, IPanelSmallRight
           isOpen={this.state.showPanel}
           type={PanelType.smallFixedFar}
           onDismiss={this._hidePanel}
+          layerProps={{ styles: { root: { zIndex: 1337 } } }}
           headerText="Panel - Small, right-aligned, fixed, with footer"
           closeButtonAriaLabel="Close"
           onRenderFooterContent={this._onRenderFooterContent}
```

Applying the above diff results in the following DOM output:

![image](https://user-images.githubusercontent.com/706967/64556938-4ea88c00-d2f5-11e9-919c-1fcb7888b85b.png)

Note that the `z-index` is set on `Layer` with this LoC:

https://github.com/OfficeDev/office-ui-fabric-react/blob/dcc6d8189a612b931d31df34ce8846b242fa76b2/packages/office-ui-fabric-react/src/components/Layer/Layer.styles.ts#L23

I hope the above unblocks you!
