### ISSUE TITLE
First item in detailslist can get selected when selectionMode is none

### ISSUE THREAD

**Issue by joshualamusga1** [OfficeDev/office-ui-fabric-react#10399]
1. Render a detailslist
2. Tab to the column headers in the detailslist. (Not to the rows.)
3. Press the down arrow so the first item is selected.

#### Actual behavior:
The first item is selected and focus is on the first item.

#### Expected behavior:
The first item should not be selected nor have a visible selection state.

### Priorities and help requested:
Are you willing to submit a PR to fix? *No*

Requested priority: *Normal*

**Comment by natalieethell** [comment]
Thanks for reporting this, @joshualamusga1! I definitely see this bug in our examples; we'll investigate.

**Comment by natalieethell** [comment]
My initial thinking is that this is happening because the `selection` object's mode defaults to `multiple` when arrowing down to the first item, even when the `selectionMode` prop is given a different value. We also aren't explicitly setting mode in `selection`'s initialization. 

The fix will either be to use `selection`'s mode or `selectionMode` by default. I'll discuss with the team.
