### ISSUE TITLE
Allow custom attributes

### ISSUE THREAD

**Issue by XuYan** [OfficeDev/office-ui-fabric-react#10397]
#### Describe the feature that you would like added

Allowing custom attribute on component is useful. For example, I want to set dialog's tabindex to -1 so that it's convenient to support hot keys inside a dialog.

#### What component or utility would this be added to

Dialog. I think the feature may be useful on other components as well.

#### Have you discussed this feature with our team, and if so, who

Not yet.

**Comment by natalieethell** [comment]
Hey @XuYan very valid ask. Standardizing where office-ui-fabric-react uses `getNativeProps` is something the team has discussed a couple times in the past. Here's an issue opened for it where there's a short thread: https://github.com/OfficeDev/office-ui-fabric-react/issues/8471. It looks like it hasn't been updated since March, though, so I'll check with the team and see where we are with this effort! 

I'll close this issue in favor of that one, so please don't hesitate to comment on that issue if you have any other questions.
