### ISSUE TITLE
Multiple DetailList Components

### ISSUE THREAD

**Issue by AndrewCarterBreakwaterIT** [OfficeDev/office-ui-fabric-react#10390]
I'd like to know whether it is possible to have multiple DetailList components within the same webpart.

I am looking to provide a Stepper like experience with a DetailList at each stage to display content for the user to select. I have managed to get this to work with MatierialUI stepper, but I cannot seem to get the selection to work for each List.

I have multiple Selection objects and I pass the relevant one through to the props of the DetailList when it is initialised. However, when I make any selections the only Selection object to get used is the initial one.

What I want to get in the state is the selected items from each DetailList, is this possible?

**Comment by natalieethell** [comment]
Hey @AndrewCarterBreakwaterIT this seems like it technically would be possible. If you're having trouble with it and could provide an isolated repro for us, we could try to help you debug the issue.

**Comment by AndrewCarterBreakwaterIT** [comment]
@natalieethell many thanks for coming back to me..
I have to admit I am a little green around the gills with all this, so I have created a repo and added you as a collaborator.

I hope this is correct :-)

Andrew

**Comment by natalieethell** [comment]
@AndrewCarterBreakwaterIT Yes, that should work. Thanks for providing a repro! We'll take a look.

**Comment by KevinTCoughlin** [comment]
@AndrewCarterBreakwaterIT can you also add me as a collaborator to the project to debug? Thanks!

One theory is that DOM diffing leads to the React keeping the _same_ instance of `GroupedList` present which is retaining the first instance of `Selection`.

**Comment by natalieethell** [comment]
@AndrewCarterBreakwaterIT What Kevin mentions above might actually be the issue here. 

Since selection is only set in the constructor of `DetailsList`, if React keeps the same instance of the object, that constructor isn't called to set a new selection object. 

We would suggest one of the following two options:

1) Render all of the `DetailsList` (`GroupList` in your case) elements and hide the ones that are not in use. This way, most of the work is done on initial render and when switching from list to list, React won't have to re-render each list every time.

2) Add a `key` value to each of your `DetailsList`s. The keys will force React to infer that the component has actually been substituted and will create a new one from scratch, giving it the full component lifecycle. Note that this will likely impact performance quite a bit, but it's up to you. 

Let us know if either of these options works for you!

**Comment by AndrewCarterBreakwaterIT** [comment]
@natalieethell @KevinTCoughlin ,

Many thanks for coming back with some information.
I will take a look at some refactoring, and see how I get on.
Many Thanks

**Comment by natalieethell** [comment]
Let us know if you have any other questions! Otherwise feel free to close this issue.
