### ISSUE TITLE
How to use calendarAs property in DatePicker Component of Fabric UI?

### ISSUE THREAD

**Issue by ashitvora** [OfficeDev/office-ui-fabric-react#10442]
Cross-posting from https://stackoverflow.com/questions/57917901/how-to-use-calendaras-property-in-datepicker-component-of-fabric-ui as most questions on Stackoverflow are going unnoticed :(

I am trying to show different date picker/calendar for different scenarios.
I need the following types and came across calendarAs property but couldn't find any example for implement that.

I would like to have...
- Date Time Picker (not sure if this is available)
- Date Picker (the one that comes by default)
- Month Picker
- Year Picker
- Quarter Picker (not sure if this is available)

**Comment by natalieethell** [comment]
Hey @ashitvora so sorry about your question going unnoticed! Here's a basic example of DatePicker using `calendarAs`: https://codepen.io/naethell/pen/eYOLxGb. You should be able to change the props passed into Calendar to also display the month picker and/or year picker.

I also see that the "See Code" isn't super helpful for the DatePicker examples, since each example is dependent on props passed into the picker in a separate file ([Calendar.doc.tsx](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Calendar/Calendar.doc.tsx)). The team will take note of this and see if we can expose it better in the sample code.

Let me know if the CodePen above fits your need and if you have any other questions! Hope that helps.

**Comment by ashitvora** [comment]
Hi @natalieethell 

thanks for the demo.
In your codepen, selecting the date does not update the date picker textbox.
Is this an expected behavior?

Is there any plan to add a Quarter Picker? Or is there a way we can add customer pickers?

**Comment by natalieethell** [comment]
@ashitvora Whoops, sorry about that! I updated the CodePen and cleaned it up a bit - looks like it was just missing a props spread. https://codepen.io/naethell/pen/eYOLxGb

I don't believe there are currently any plans to support a Quarter Picker. However, as long as the control you're passing into the DatePicker takes in `ICalendarProps`, it should work.
