### ISSUE TITLE
Office UI Fabric Icons tool is extremly slow

### ISSUE THREAD

**Issue by e-gallis** [OfficeDev/office-ui-fabric-react#10462]
Hi,
Generating a subset from the Office UI Fabric Icons is extremly slow. In fact, I stopped the generation after 10mn for just one icon. I tried refreshing the page and restarted the generation but it didn't help.
Any clues on why it's so slow ? Anyone else noticed this or am I the only one ?
FYI: I'm located in Europe (France)...
Thx,
Emmanuel

**Comment by dzearing** [comment]
@Jahnp would have a better idea.

**Comment by Jahnp** [comment]
Thanks for the heads-up @dzearing  and thanks for reporting this, @e-gallis . So sorry for the inconvenience!

Short answer: I think I know the issue and can make a short-term patch to provide immediate relief.

Longer answer: I'll need to investigate to verify, but I believe the tool has been hitting bottlenecks lately due to some infrastructure limitations. Essentially, the tool is likely hitting storage limits from leaving generated subsets directly on the server vs dropping them in something built for this purpose like blob storage. The symptoms of this limitation has been cropping up more frequently in the last month or so, which means we'll need to do some work to patch the storage/package generation issue.

I'll report back when I've made the short-term fix and will keep this updated as I look into longer-term solutions.

**Comment by Jahnp** [comment]
I've done the short-term fix, which should provide some relief for now. You should be able to generate subsets again. I'll start looking into longer-term fixes soon, too.

**Comment by e-gallis** [comment]
> I've done the short-term fix, which should provide some relief for now. You should be able to generate subsets again. I'll start looking into longer-term fixes soon, too.

Great job @Jahnp ... Thanks a lot... Works fine...

**Comment by Jahnp** [comment]
Hey folks, sorry for the delay. Wanted to share that we've made the infrastructure improvements to the icons site, so we shouldn't be hitting these bottlenecks anymore. Please let me know if you hit any further issues with the site. Thanks again for reporting this one!

**Comment by e-gallis** [comment]
Fantastic... Just tested it with a selection of multiple icons: took about 4s to generate the zip file. Great job, thanks!

**Comment by e-gallis** [comment]
Closing the issue...
