### ISSUE TITLE
DatePicker does not display selected date when focus in other component

### ISSUE THREAD

**Issue by mfdezvil** [OfficeDev/office-ui-fabric-react#10520]
### Environment Information

- **Package version(s)**: 6.204.0 and 7.35.0
- **Browser and OS versions**: Google Chrome 77.0.3865.75  (64 bits)

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/mfdezvil/pen/mdbzYbb

#### Actual behavior:

I have implemented two DatePicker components, with a defined "onSelectDate" function. I select one date in the first DatePicker and it works fine, but when I focus on the second DatePicker and click in order to select the other date, first DatePicker "loses" the display selected date and does not show it. Internally, value is not lost. I have tested too with a DatePicker and a Dropdown component: I select the date but when I click on the dropdown, selected date disappears. Check the codepen to test an example.

#### Expected behavior:

Displaying selected date shouldn't lost when you clicks in another component, because internal value is not losting.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by aneeshack4** [comment]
Confirmed repro. Thanks for reporting this @mfdezvil! @lorejoh12 @OfficeDev/uifabric-calendar. I see that `selectedDate` is storied in state in DatePicker.base.tsx - is there a missing link in this variable's state management?

**Comment by lorejoh12** [comment]
DatePicker is a fully-controlled component, which means it expects you to pass it a value. In the given codepen, you aren't passing the value to the component. So you have something like
```
<Datepicker onSelectDate={_onSelectDateCallback} value={undefined} />
```
which results in the DatePicker initializing to a blank date, and keeping track of it's internal state. However, as soon as the parent rerenders (which happens when you call setState), the DatePicker sees that it's prop for "value" == undefined, so it goes back to it's initialized internal state.

If you do something like:
```
<DatePicker value={this.state.date1} onSelectDate={(date) => this.setState({date1: date})} />
```
then you keep the value in sync with the internally selected date, and the control works as expected.

**Comment by mfdezvil** [comment]
Hi @lorejoh12 , it works like you said :)
Thank you all and sorry for any inconvenience!
