### ISSUE TITLE
Open up _getVisibleText on ComboBox

### ISSUE THREAD

**Issue by thomasgassmann** [OfficeDev/office-ui-fabric-react#10555]
#### Describe the feature that you would like added

I'd like to automatically filter dropdown items of the `ComboBox` as the user types. As far as I have seen, there is no way to get the current text value of the `ComboBox` (as the user types, not the actual selected or auto-completed item value). To do this, I had to access the private `_getVisibleValue()` method on the `componentRef` in the `onKeyUp` event.

```javascript
<ComboBox
    autoComplete={'on'}
    componentRef={ref}
    onKeyUp={
      new Async().debounce((event: React.KeyboardEvent<IComboBox>) => {
        if (event && event.target && ref.current) {
          ref.current.focus(true);
          const visibleValue = (ref.current as any)._getVisibleValue();
          setSearchText(visibleValue);
        }
      })
    }
   {...} />
``` 

I then filter the `options` based on my `searchText` value here.
Would it be possible to open up the `_getVisibleValue()` method or add an event like `onTextChange` to the `ComboBox`? Or is this something the `ComboBox` deliberately does not have?

#### What component or utility would this be added to

`ComboBox`

#### Have you discussed this feature with our team, and if so, who

No

**Comment by aneeshack4** [comment]
@thomasgassmann Access to ComboBox's current value should be done through callbacks and that is intentional however you can use [`onPendingValueChanged`](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.types.ts#L86). You can see in ComboBox.tsx that this gets updated in [_`processInputchangeWithFreeform`.](https://github.com/OfficeDev/office-ui-fabric-react/blob/ecbdfdb38009cede4aebb1052ed0aaea501b1f43/packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx#L664).
