### ISSUE TITLE
Toggle: onChange have (sometimes) event.target.id == ""

### ISSUE THREAD

**Issue by gioce90** [OfficeDev/office-ui-fabric-react#10620]
### Environment Information

- **Package version(s)**: 6.202.0 (in the codepen example I use the 7, 
- **Browser and OS versions**: Chrome (maybe also on other browsers)

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/gioce90/pen/JjPzJeQ

#### Actual behavior:

When I use the toggle's onChange callback, I use event.target.id, but sometimes this id is equal to an empty string.
At start I was thinking this was totally unpredictable, but after I while I noticed that this occurs when I clic on the little circle inside of the toggle. Outside of that, or on the label, the id is filled correctly. Please try yourself on codepen.

#### Expected behavior:

The id must always be consistent.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: (High)

Products/sites affected: ... all?

**Comment by joschect** [comment]
@gioce90 This is working as intended. event.target refers to [the element](https://developer.mozilla.org/en-US/docs/Web/API/Event/target) that trigged the event. So when you're using it to get id, sometimes the target is an underlying div, which does not have the same id applied.
![image](https://user-images.githubusercontent.com/20801176/65808806-c5de7c80-e14b-11e9-921a-3aaf7b0a9173.png)

I made a slight change to the [codepen](https://codepen.io/slimemold/pen/GRKaJGB) you provided and you can see what's happening with it. It also uses currentTarget instead of target which refers to the element that captured the event, rather than the element that initiated the event.

**Comment by gioce90** [comment]
> @gioce90 This is working as intended. event.target refers to [the element](https://developer.mozilla.org/en-US/docs/Web/API/Event/target) that trigged the event. So when you're using it to get id, sometimes the target is an underlying div, which does not have the same id applied.
> ![image](https://user-images.githubusercontent.com/20801176/65808806-c5de7c80-e14b-11e9-921a-3aaf7b0a9173.png)
> 
> I made a slight change to the [codepen](https://codepen.io/slimemold/pen/GRKaJGB) you provided and you can see what's happening with it. It also uses currentTarget instead of target which refers to the element that captured the event, rather than the element that initiated the event.

Thank you @joschect
