### ISSUE TITLE
DocumentCard: Focus indicator is not properly visible

### ISSUE THREAD

**Issue by khmakoto** [OfficeDev/office-ui-fabric-react#10661]
### Environment Information

- **Package version(s)**: 7.39.2
- **Browser**: Microsoft Edge (does not repro on Chrome)

### Please provide a reproduction of the bug in a codepen:

The bug is clearly visible in the [website](https://developer.microsoft.com/en-us/fabric#/controls/web/documentcard). 

#### Actual behavior:

The focus indicator clips around images on the `DocumentCard`:

![DocumentCard](https://user-images.githubusercontent.com/7798177/65807911-d8ee4e00-e145-11e9-90aa-ad8c5b75f293.gif)

#### Expected behavior:

The focus indicator is visible across the entire `DocumentCard`.

#### Notes
Bug 2 in #10646 - DocumentCard A11y Pass

**Comment by micahgodbolt** [comment]
![doc card](https://user-images.githubusercontent.com/1434956/69587795-87264080-0f9b-11ea-885c-b940ce69720e.gif)

Looking at recent work by @betrue-final-final i wanted to make sure focus rect was not just different color, but different size. 

Also note, Edge 'worked' in the past, but it was merely the default browser default. My fix will be more intentional.
