### ISSUE TITLE
Tooltip is not available on sitemap button.

### ISSUE THREAD

**Issue by bhagwatshelke1047** [OfficeDev/office-ui-fabric-react#10703]
Environment Details:
Application Name: Virtual Agent Bot
Browser Version: Microsoft Edge 44.18362.267.0, Chrome Version 76.0.3809.100 (Official Build) (64-bit)
Windows Version: Windows10
Mas Violated: MAS1.1.1

Steps to Reproduce:
1.Open application Virtual agent bot
2. Home page should open for Virtual Agent Bots.​
3. Navigate to Hamburger Menu at the left side of the screen.​

Actual:
Tooltip is not available on sitemap button.

Expected:
Tooltip should be available on sitemap button.

User Impact:
Keyboard only user are unable to access the tooltip.

**Comment by khmakoto** [comment]
Hi @bhagwatshelke1047, I think what you're logging is an application bug that needs to be investigated by someone from the Name Virtual Agent Bot team since we it is not clear if this is indeed a Fabric bug. Please contact that team first and, if it is indeed a Fabric issue then we can start working on it. Thanks!

**Comment by bhagwatshelke1047** [comment]
+@Ravi Kumar Kalivarapu (HCL America Inc)<mailto:v-kalra@microsoft.com>

Hi Ravi,

Can you please look into this  https://github.com/OfficeDev/office-ui-fabric-react/issues/10703 and provide the necessary details.

Regards,
Bhagwat Shelke
TCS - Microsoft Global Relationship | v-bhshel<mailto:v-bhshel>
C+AI Accessibility

[cid:image001.jpg@01D57AAE.676D6B60]
