### ISSUE TITLE
CommandBar button doesn't work in overflow mode

### ISSUE THREAD

**Issue by gsbelarus** [OfficeDev/office-ui-fabric-react#10737]
office-ui-fabric-react@7.45.0 on Firefox 69.0.2

CommandBar button works when CommandBar is not shrunk:

![image](https://user-images.githubusercontent.com/5175764/66383560-ea491d00-e9c5-11e9-82ed-3e600647cb7f.png)

But doesn't work when CommandBar in overflow mode:

![image](https://user-images.githubusercontent.com/5175764/66383636-0f3d9000-e9c6-11e9-997b-6ce9e08c3bff.png)

I have a custom renderer for the button provided through `commandBarButtonAs`:
```ts
    {
      key: 'editEntity',
      disabled: !entities || !entities.size,
      text: 'Edit',
      iconProps: {
        iconName: 'Edit'
      },
      commandBarButtonAs: entities && entities.size ? linkCommandBarButton(`entityDlg/${entities.getString('name')}`) : undefined
    },
```
Where it is rendered as `react-router's` `Link` component:
```ts
export interface ILinkCommandBarButtonProps extends IComponentAsProps<ICommandBarItemProps> {
  link: string;
  supText?: string;
  onClick?: () => void;
};

export class LinkCommandBarButton extends BaseComponent<ILinkCommandBarButtonProps> {
  public render(): JSX.Element {
    const { defaultRender, link, supText, onClick, ...buttonProps } = this.props;

    const onRenderText = supText ? (props: IButtonProps) => <>{props.text}<sup>{supText}</sup></> : undefined;
    const DefaultRender = defaultRender ? defaultRender as any : CommandBarButton;

    const render = (
      <DefaultRender {...buttonProps} onRenderText={onRenderText}/>
    );
    if (buttonProps.disabled) {
      return render;
    } else {
      return (
        <Link to={link} onClick={onClick}>
          {render}
        </Link>
      );
    }
  }
};

export const linkCommandBarButton = (link: string, supText?: string, onClick?: () => void) => (props: IComponentAsProps<ICommandBarItemProps>) => {
  return <LinkCommandBarButton {...props} link={link} supText={supText} onClick={onClick} />;
};
```
So, it is seem as custom renderer is somehow lost when `CommandBar` is in overflow mode.

**Comment by ecraig12345** [comment]
I see that same behavior with this minimal repro: https://codepen.io/ecraig12345/pen/VwwLaPV 
![image](https://user-images.githubusercontent.com/5864305/66611659-17d3c900-eb74-11e9-93c7-33c8d5dbbe5e.png)
(In general, it's helpful to include a minimal live repro when filing an issue--you can start from the "Export to CodePen" link on one of the [component examples](https://developer.microsoft.com/en-us/fabric#/controls/web/commandbar).)

This behavior is actually **by design**, because it's unlikely that the same component will be able to render properly as *both* a command bar item and a menu item. To demonstrate this issue, the second CommandBar in the codepen forces both item types to render with the same `CommandBarButton` wrapper (as you can see, it doesn't work very well):
![image](https://user-images.githubusercontent.com/5864305/66533376-8ad33600-eac7-11e9-9ac4-05a83d15a7ce.png)

A better approach is to make a separate custom renderer for context menu items only, as demonstrated by the third CommandBar in the codepen.
![image](https://user-images.githubusercontent.com/5864305/66536363-83b12580-ead1-11e9-91b8-2dbfc6c03ce0.png)
The code for this is basically: 
```tsx
const CustomMenuItem: React.FunctionComponent<IContextualMenuItemProps> = props => {
  const origItem = props.item;
  // or some other implementation as you prefer
  const item = { ...origItem, name: undefined, text: 'menu ' + (origItem.text || origItem.name) };
  return <ContextualMenuItem {...props} item={item} />;
};

<CommandBar
  // ... other props ...
  overflowButtonProps={{
    menuProps: { contextualMenuItemAs: CustomMenuItem, items: [] }
  }}
/>
```

**Comment by ecraig12345** [comment]
To get this working with `react-router`: if you're using the latest version, there's [a new `Link` prop called `component`](https://github.com/ReactTraining/react-router/pull/6462) (doesn't seem to be documented yet) which lets you pass in a custom component for the link to render as, while still doing routing behavior on click. That seems like it would be ideal for your use case, though if you're unable to upgrade, there should be a way to achieve something similar using react-router or history APIs in click handlers (instead of using Link).

Here's a demo of using `<Link component={...}>` and custom CommandBarButton/ContextMenuItem wrappers to make a CommandBar which does routing on click. https://codepen.io/ecraig12345/pen/oNNjEQP

**Comment by gsbelarus** [comment]
Thank you for so detailed explanation. I will try to fix our code using your advice. It would be nice to add an example of overriding renderer when CommandBar in overflow mode to the official documentation.

**Comment by ecraig12345** [comment]
Good point, I'm actually going to reopen this for now as a reminder to add something like the codepen I wrote to the documentation.
