### ISSUE TITLE
DetailsRowFields isn't exported at the package root

### ISSUE THREAD

**Issue by brandonthomas** [OfficeDev/office-ui-fabric-react#10731]
I need to wrap DetailsRowFields and it's not exported by office-ui-fabric-react. I have to import from the path instead.

#### Actual behavior:
I can't do `import {DetailsRowFields} from 'office-ui-fabric-react';`

#### Expected behavior:
I can do `import {DetailsRowFields} from 'office-ui-fabric-react';`

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes, at some point but not immediately.

Requested priority: (Blocking, High, Normal, Low) Normal

**Comment by ecraig12345** [comment]
In general `DetailsRowFields` seems like it ought to be an internal component, but since `DetailsRow` has a `rowFieldsAs` prop (defaulting to `DetailsRowFields`), I can see the justification for exporting it to wrap in a custom component.

@brandonthomas If you have a chance to make a PR for this that would be great; otherwise I'll get to it at some point.

**Comment by KevinTCoughlin** [comment]
https://github.com/OfficeDev/office-ui-fabric-react/pull/10772

**Comment by ecraig12345** [comment]
Thanks Kevin!
