### ISSUE TITLE
Tag Picker overflows container by default

### ISSUE THREAD

**Issue by HarryGifford** [OfficeDev/office-ui-fabric-react#10745]
Tag picker overflows it's parent div by default.

### Environment Information

- **Package version(s)**: office-ui-fabric-react 7.45.1
- **Browser and OS versions**:
Version 77.0.3865.90 (Official Build) (64-bit)

### Please provide a reproduction of the bug in a codepen:

Same as from #10744. Codepen to repro the issue: https://codepen.io/hegi/pen/bGGddYE

#### Actual behavior:

What it looks like using the Chrome element inspector:
![image](https://user-images.githubusercontent.com/21968002/66430110-4a43c180-e9ce-11e9-8180-7bfdbbc6d5a5.png)

#### Expected behavior:

Input should line up with that of `TextField`.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: Dynamics 365 Field Service

This bug was created from #10744.

**Comment by ecraig12345** [comment]
Thanks for reporting this! @joschect Any ideas on the fix for this one?

**Comment by ecraig12345** [comment]
Thanks for reporting this! @joschect Any ideas on the fix for this one?

**Comment by ecraig12345** [comment]
Looking at the styles, `min-width` of BasePicker is set to 180px.
https://github.com/OfficeDev/office-ui-fabric-react/blob/501065930ba3f51355f521857e01d921838ab370/packages/office-ui-fabric-react/src/components/pickers/BasePicker.styles.ts#L38

It's been that way for at least a couple years, but I'm guessing it was an intentional design decision at some point, and pickers are just not meant to be used at widths less than 180px. @joschect Do you remember the reason for the 180px min-width?

**Comment by joschect** [comment]
@ecraig12345 It was just a default value that was chosen. It can be overridden if the consumer wishes to have a smaller picker, but generally it needs a fair amount of space to fit both the tags and text field. This by design seeing as the user can change the styles to their liking.

**Comment by joschect** [comment]
@HarryGifford here is a [link to a codepen](https://codepen.io/slimemold/pen/WNNRpPw) that shows how you can limit the text fields size.

**Comment by HarryGifford** [comment]
Thanks for the work around. We can certainly override it in our code.
