### ISSUE TITLE
Announced component should be a <span> not a <div>

### ISSUE THREAD

**Issue by philipzloh** [OfficeDev/office-ui-fabric-react#10743]
#### Actual behavior:

`Announced` component returns `<div>` but has nothing inside that requires it to be a block element, this causing a lot of nesting issues when teams use `Announced` inside `<span>` and similar inline elements.

#### Expected behavior:

Announced component returns `<span>`

### Priorities and help requested:

Are you willing to submit a PR to fix? No (I could and would but my machine isn't currently setup)

Requested priority: Normal

Products/sites affected: Outlook Web

**Comment by ecraig12345** [comment]
Since the component has already been released, it's probably best to leave it as a div by default to avoid messing up people's existing layouts. 

However, I could add support for setting root-level styles on Announced so you can override the display setting (right now it doesn't support setting root-level styles, aside from via a className). It would look like this:
```tsx
<Announced styles={{ root: { display: 'inline' } }}>content</Announced>
```
