### ISSUE TITLE
Tag Picker doesn't respect theme

### ISSUE THREAD

**Issue by HarryGifford** [OfficeDev/office-ui-fabric-react#10746]
When switching to a dark theme, you can see that some of the colors in the Tag Picker don't match the generated theme. The input field's text color is black, even though the background color is also black.

Aside: The incorrect font (Times New Roman) in the picker items may also be part of a similar issue, although that only repros in Storybooks or in Codepen.

### Environment Information

- **Package version(s)**: office-ui-fabric-react 7.45.1
- **Browser and OS versions**:
Version 77.0.3865.90 (Official Build) (64-bit)

### Please provide a reproduction of the bug in a codepen:

Codepen to repro the issue: https://codepen.io/hegi/pen/vYYONzy

#### Actual behavior:

What it looks like:
![image](https://user-images.githubusercontent.com/21968002/66432784-bbd23e80-e9d3-11e9-96c5-3950cf2f650b.png)

#### Expected behavior:

Input should look similar to `TextField`.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: Dynamics 365 Field Service

This bug was created from #10745.

**Comment by ecraig12345** [comment]
Thanks for reporting this! I think the issue is that the tag picker isn't setting the color of input elements' text at all. TextField works since it has a line in its `field` styles (the class used on its `input`) to set `color: semanticColors.inputText`--so we ought to add the same style in TagPicker (actually in BasePicker).

I'm not sure why the font isn't getting set or what the proper way is to make sure fonts get passed down, but I can look into that too.

**Comment by ecraig12345** [comment]
@xugao Maybe you could look at this one as well?
