### ISSUE TITLE
ChoiceGroup: In scan mode, Narrator reads label and selected option in wrong order

### ISSUE THREAD

**Issue by 999-Dev** [OfficeDev/office-ui-fabric-react#10758]
> **NOTE**: This was logged as a bug with Panel but is actually a bug with ChoiceGroup. See https://github.com/OfficeDev/office-ui-fabric-react/issues/10758#issuecomment-541799098.

Track the Bug Details on [SharePoint](https://microsoft-my.sharepoint.com/:x:/r/personal/v-amaver_microsoft_com/_layouts/15/Doc.aspx?sourcedoc=%7B5afd015d-fc38-4e4b-ae9b-a0ad778c0ea7%7D&action=default&uid=%7B5AFD015D-FC38-4E4B-AE9B-A0AD778C0EA7%7D&ListItemId=1850&ListId=%7B395E1ECB-5002-440E-81C5-6A090E98077C%7D&odsp=1&env=prodbubble&cid=5bae63ae-f014-462e-a679-e706631598a6)

Bug18: [Usable : Panel Control] : Narrator announces extra information when focus moves to the 'Pick One' text.

**Test Environment:** 
OS: Version: RS5_Prerelease(1903 OS Build 18999.1) 
URL: https://developer.microsoft.com/en-us/fabric#/controls/web/panel
Edge Browser Version: 
Microsoft Edge: 44.18999.1.0
Microsoft EdgeHTML: 18.18999
Chrome Browser Version:
Chrome Version: 76.0.3809.132

### Repro Steps
1. Open https://developer.microsoft.com/en-us/fabric#/controls/web/panel in Edge and turn on Narrator.      
2. Navigate to 'Open Panel' in the example **Panel - Small Panel, Anchored Right, Fixed Width** by using Tab key and activate it.      
3. The panel will appear.      
4. Switch narrator to Scan mode (Caps + Space).      
5. Navigate to ‘Pick One’ by using down arrow keys and verify the issue.

**Actual result**: Narrator announces, ‘Option B selected option contains four items pick one Asterisk’.

**Expected result**: Narrator should only announce ‘Pick One Asterisk’.

Working Fine with NVDA+Chrome.

**User impact**: Narrator user will be confused if narrator will convey extra information when narrator focus moves to ‘Pick One’ text.

**Comment by ecraig12345** [comment]
Hi, in the future when filing these bugs, can you please give each one a descriptive title? For example **Panel A11y Pass: Narrator announces extra information when focus moves to the 'Pick One' text**. This will make it easier for us to distinguish and triage the bugs.

**Comment by ecraig12345** [comment]
It would also be more helpful to have the complete details included in the issue, rather than in an internal-only spreadsheet.

**Comment by ecraig12345** [comment]
This is an issue with ChoiceGroup, not Panel. It more simply repros on the ChoiceGroup page:

1. In Edge with Narrator on, navigate to https://developer.microsoft.com/en-us/fabric#/controls/web/choicegroup
2. Navigate focus to just before one of the examples (easiest way to do this is to click a "Show code" button twice--show then hide the code but leave the button focused)
3. Switch to scan mode
4. Navigate with down arrows to the ChoiceGroup

**Actual**: Narrator reads "Option B selected. Selection contains 4 items. Pick one asterisk."

**Expected**: If you turn off scan mode and focus into the control by pressing tab, the output seems more reasonable: "Pick one, selected, Option B, radio button, required. 2 of 4."

I suspect this is actually an issue with Narrator, not our markup (since it's read correctly in non-scan mode), but I need to investigate further.

**Comment by micahgodbolt** [comment]
This is actually consistent with the role="radiogroup" behavior.

https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20160317/examples/radio/radio.html

Go to "Radio Example" turn on scan mode, navigate to "Pizza Crust" and you'll hear the same thing as you do in our example.
