### ISSUE TITLE
Changing the defaultValue does not update the value that is displayed in the Textbox

### ISSUE THREAD

**Issue by ashitvora** [OfficeDev/office-ui-fabric-react#10759]
### Environment Information

- **Package version(s)**: 7.25.0
- **Browser and OS versions**: Windows 7 & Chrome Latest

### Please provide a reproduction of the bug in a codepen:

Codepen: https://codepen.io/ashitvora/pen/KKKpXea?editors=1111

#### Actual behavior:

Default Value gets updated only once.

#### Expected behavior:

Should have updated whenever the state variable value changes

**Comment by cliffkoh** [comment]
This is by design - use `value` instead if you want the textfield to operate in a controlled manner.

**Comment by ashitvora** [comment]
In that case, since the TextField is controlled, is there a way to have correct value reflected in the TextField (the value is received as a prop) but not call onChange on every keystroke but debounce it?

Having onChange called on every keystroke results in too many re-renders :(

**Comment by ecraig12345** [comment]
Repeatedly re-rendering just the TextField shouldn't be a big issue (this is actually the expected pattern for controlled fields), but I guess depending on where your `onChange` comes from, it could cause a chain of re-renders in more complicated components. 

You can find some suggested workarounds in https://github.com/OfficeDev/office-ui-fabric-react/issues/10121#issuecomment-520575817. I might also add a scenario like this to the examples on the website since it keeps coming up repeatedly.
