### ISSUE TITLE
Slider control is not usable in Firefox with Windows High Contrast Mode

### ISSUE THREAD

**Issue by jlukosky** [OfficeDev/office-ui-fabric-react#10764]
### Environment Information

- **Browser and OS versions**: Firefox and Windows 10 

### Describe the issue:

When using Windows High Contrast Mode and Firefox, the basic pieces of the slider controls do not appear. This renders the control unusable.

### Please provide a reproduction of the issue in a codepen:

The issue is apparent by going to the [Fabric Slider control page](https://developer.microsoft.com/en-us/fabric/#/controls/web/slider) using Firefox while using Windows High Contrast Mode.

#### Actual behavior:

Using Firefox and Windows High Contrast Mode the Slider control mostly does not appear except for the marker for adjustment.

#### Expected behavior:

Using Firefox and Windows High Contrast Mode the Slider control will fully appear. This will expose the functionality to to the user.

### Documentation describing expected behavior

- I've created a simple[ Fabric High Contrast Code Pen](https://codepen.io/jluko/pen/wvvavWd) to demonstrate one way this can be addressed.
- More high contrast techniques can be found in [Windows high contrast web development techniques](https://microsoft.sharepoint.com/teams/msenable/Pages/WindowsHighContrastWebDevelopment.aspx)

**Comment by ecraig12345** [comment]
Thanks for reporting this. We already apply high contrast-specific color adjustments to the slider track (and other parts of the slider), and I just verified they're respected in Edge. So if Firefox isn't respecting those adjustments, it's an issue with Firefox, not our code.

**Comment by jlukosky** [comment]
> So if Firefox isn't respecting those adjustments, it's an issue with Firefox, not our code.

Firefox is not going to respect background colors in high contrast. Firefox supports Windows High Contrast so how is saying it's on Firefox helpful? If a method works for Microsoft browsers AND Firefox that's the successful solution.

**Comment by ecraig12345** [comment]
We appreciate the feedback, but unfortunately there isn't much we can do about this under the current web standards and our design constraints.

As documented on our [Accessibility wiki page](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Accessibility), we can only guarantee high contrast will work on Edge in Windows. This is because currently, only Edge provides a way to use high contrast-specific styling (`-ms-high-constrast`). Firefox doesn't provide a similar mechanism. 

While unconditionally applying `WindowText` and other system colors (regardless of whether high contrast mode is on) would solve high contrast issues in Firefox, we can't go that route because the system colors are unlikely to match the specific colors dictated by our design/brand. 

The good news for the future is that there's a proposed media query [`prefers-contrast`](https://drafts.csswg.org/mediaqueries-5/#prefers-contrast) which will provide a cross-browser way to do high-contrast styles. Once that's finalized and implemented, it's definitely something we'd like to use in Fabric.

(cc @paulgildea)
