### ISSUE TITLE
NormalPeoplePicker list close when other element changes its scroll

### ISSUE THREAD

**Issue by rhalaly** [OfficeDev/office-ui-fabric-react#10779]
### Environment Information

- **Package version(s)**:7.47.0
- **Browser and OS versions**: Chrome, Edge, Edge Beta, Windows 10

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/hraz/pen/BaaoNGy?editors=0010

Start filling the NormalPeoplePicker (for example, type `a` inside)

#### Actual behavior:

When the `div` below changes its scroll position, the people picker selector is closed.
If you'll check the checkbox "Use getTextFromItem" that defines the prop "getTextFromItem", you will get an `alert` of the selected people, since it triggers `onChange`

Note that the focus of the PeoplePicker didn't changed (the text box is still have the focus) just the list is gone

#### Expected behavior:

PeoplePicker will still wait for user input and not close itself because of the scrollbar of another `div`

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: Internal Microsoft Product

**Comment by khmakoto** [comment]
Hi @rhalaly, thanks for filing this issue! This behavior is by design since the `Callout` component, which is used to show suggestions, dismisses on scroll. There is a prop to override this behavior however, and you can set it using the `pickerCalloutProps` prop and setting `preventDismissOnScroll` to `true`.

I've done this in [this codepen](https://codepen.io/khmakoto/pen/eYYZRgW?editors=0010) and you can see in there that it correctly matches the behavior you seek. Let me know if you need anything else!

**Comment by rhalaly** [comment]
Thank you very much @khmakoto! I submit this issue after lot of digging inside the docs.

Maybe you should consider to make it more clear there :)

**Comment by khmakoto** [comment]
@rhalaly thanks for the feedback, we'll take it into account!
