### ISSUE TITLE
Callout: Incorrect position when target is off-screen (doNotLayer)

### ISSUE THREAD

**Issue by Zhephyr54** [OfficeDev/office-ui-fabric-react#10776]
### Environment Information

- **Package version(s)**: 7.39.1
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/Zhephyr54/pen/ZEEbGWO
(Scroll down to the "Show callout" button)

#### Actual behavior:

Using a Callout with doNotLayer, preventDismissOnScroll and preventDismissOnLostFocus (for a fully controlled component), when the Callout is actually displayed while the target element is off-screen (not visible at this moment), the Callout positioning is incorrect (it appears to be the closest to the target element while being still visible on screen).

#### Expected behavior:

The Callout positions itself properly in relation to the target element even when the target element is not visible on screen.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

### Remarks

I am not sure if this behavior is actually supposed to be supported or if it would be hard to implement.

**Comment by ecraig12345** [comment]
Thanks for reporting this! @joschect Any ideas?

**Comment by khmakoto** [comment]
Sorry, the PR above was meant for another issue and not this one.

**Comment by ecraig12345** [comment]
I'm guessing that the inability to force the Callout to position off-screen is intentional, but @joschect would know better.

**Comment by joschect** [comment]
@ecraig12345 and @Zhephyr54 this is by design, the callout is really only supposed to be shown on screen. It defaults to positioning itself within the window. If you want to provide an alternative bounds to allow the callout to position outside of the visible window, you can through the bounds property. I modified your [codepen](https://codepen.io/slimemold/pen/PooWJww?editors=1111) to do that here.
