### ISSUE TITLE
OnClick behavior for split button is lost across devices. 

### ISSUE THREAD

**Issue by ajain17** [OfficeDev/office-ui-fabric-react#10796]
### Environment Information

- **Package version(s)**: 6.157.3
- **Browser and OS versions**: Chrome, Windows 10.

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/cleverBassi/pen/qBBbOee?editors=0010

#### Actual behavior:
When we click on the "Save and Exit" text in the split button, it shows an alert and when we click on the chevron, it opens the dropdown menu. If you change the browser to mobile/tablet view, touching on save and exit does nothing  but touching the chevron works perfect. The onClick behavior is lost on changing the device. 

#### Expected behavior:
The onClick behavior should not be lost on changing device. 

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) Microsoft internal.

**Comment by khmakoto** [comment]
Hi @ajain17, this behavior is by design and more rationale can be found in #8230 and #9653.

You can take a look there for more background, but basically this happens because:
1. The split menu should have all options available including the primary action;
2. The touch target is not large enough to only execute the menu, so to resolve the ambiguity all split buttons react to touch this way (act as a menu button).

I hope this is understandable but please let us know if there is anything else we can do to help!
