### ISSUE TITLE
[Accessibility][Keyboard navigation]: User is not able to access all facepile controls using keyboard. (Bug 2)

### ISSUE THREAD

**Issue by jdhuntington** [OfficeDev/office-ui-fabric-react#10856]
Tracking all of the issues brought up with the 1/4 accessibility pass on Facepile control 
Details on individual bugs can be found on [SharePoint](https://microsoft-my.sharepoint.com/:x:/r/personal/v-amaver_microsoft_com/_layouts/15/Doc.aspx?sourcedoc=%7Bfd43fcc5-515d-47d8-946d-0d4862a56278%7D&action=default&uid=%7BFD43FCC5-515D-47D8-946D-0D4862A56278%7D&ListItemId=1647&ListId=%7B395E1ECB-5002-440E-81C5-6A090E98077C%7D&odsp=1&env=prodbubble) 

Breakout of issue #7534

**Comment by micahgodbolt** [comment]
Okay, oddity here is that all peronas in a facepile look clickable, so you'd expect keyboard access to them, but it turns out that only some are rendered as buttons.

**Comment by micahgodbolt** [comment]
problem isn't access, its that only the 3rd persona (AL) is actually a button, and can receive focus. The other personas appear actionable due to some css. I cleaned up that css so there wouldn't be confusion.

![image](https://user-images.githubusercontent.com/1434956/69755562-536b2800-110d-11ea-8c7d-02e3fef01810.png)
