### ISSUE TITLE
Component API for Fabric grid layout

### ISSUE THREAD

**Issue by dcowen91** [OfficeDev/office-ui-fabric-react#10874]
In order to use the [fabric grid layout](https://developer.microsoft.com/en-us/fabric#/styles/web/layout), you have to import the entire fabric css, and manually specify classnames on divs. Can a react component API be built to encapsulate this?

```
<GridRow >
  <GridCol sizes={{sm: 6, md: 4, lg: 2}}>
    {content}
  </GridCol>
</GridRow/>
```

#### What component or utility would this be added to

New components for Grid,GridRow, GridCol.

**Comment by cliffkoh** [comment]
Pinging @pgills.

**Comment by JandersonConstantino** [comment]
Hi, this will go to be developed?

**Comment by ecraig12345** [comment]
Since CSS now has [first-class support for grid layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout), we're not likely to implement a component for applying the Fabric Core grid classes at this point. 

However, we do have an issue #5418 for adding a component which encapsulates the built-in CSS grid. No current ETA for when we'll get that done, but it's definitely on our radar.
