### ISSUE TITLE
Bug: flexBasis with Number disappears

### ISSUE THREAD

**Issue by phkuo** [OfficeDev/office-ui-fabric-react#11057]
Using flexBasis with a Number doesn't throw an error, but it also doesn't show up in the output. It should default to pixels, like height and padding.

**Comment by JasonGore** [comment]
I see `flex-basis` is explicitly excluded in [provideUnits.ts](https://github.com/OfficeDev/office-ui-fabric-react/blob/b1e230edd27c9dbbead34db6d47235015bc34788/packages/merge-styles/src/transforms/provideUnits.ts#L4). I checked with @dzearing to see if there are any subtle regressions, but we can't think of any. The fix is easy enough.

**Comment by JasonGore** [comment]
One possible styling regression is that a couple of components were using numbers (like [PeoplePicker](https://github.com/OfficeDev/office-ui-fabric-react/blob/2e9ee9fbd147196e970a1be19b8afbb5e17b6d87/packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/PeoplePickerItems/PeoplePickerItem.styles.ts#L127)). These currently have no effect but will take effect when `flex-basis` gets a default unit. I will check these components for styling regressions when doing the fix.

**Comment by phkuo** [comment]
Since flex-basis was doing nothing for these components, we should just remove it from them altogether.
