### ISSUE TITLE
Allow MaskedTextField to format IP address, requires optional feaure

### ISSUE THREAD

**Issue by khowling** [OfficeDev/office-ui-fabric-react#11058]
#### Describe the feature that you would like added

I would like to MaskedTextField to mask IP addresses and CIDRs.
This would need to allow a mask of 999.999.999.999, but also some are only 1or 2 digits, for example 192.169.0.10.  This user experience is currently not great, I cannot create a masks to allow for this range.  This would need support for a regex range quantifiers {}, for example '*': /[0-9]{1-3}/ mask format

#### What component or utility would this be added to

MaskedTextField (web)

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

None

**Comment by JasonGore** [comment]
This raises a lot of UI questions, like what happens when a number that's too high gets entered? Does the 8-bit value get cleared, stop allowing entry, or go to the next 8-bit value? 

I think this is a bit too much to ask from the mask functionality. As you mentioned, it's more for masking out static values from a field, rather than adapting to dynamic ranges. I think a better UI experience would be to use the validate props like `onGetErrorMessage` and flag fields that aren't valid with an explanation to the user.

**Comment by khowling** [comment]
Thanks for the reply, I agree, its more than a masking requirement, its more a guided input validation (ie when the user presses'.' the cursor will jump to the next segment.   I'll look to see what I can do in JS.  I'm loving the library, keep up the great work.

**Comment by JasonGore** [comment]
If you are happy with the resolution, please feel free to close the issue. Thanks!

**Comment by khowling** [comment]
closed
