### ISSUE TITLE
Panel medium size near

### ISSUE THREAD

**Issue by davidnimmagadda** [OfficeDev/office-ui-fabric-react#11109]
#### Describe the feature that you would like added

Currently PanelType medium doesn't have near side render config.

#### What component or utility would this be added to

Panel

#### Have you discussed this feature with our team, and if so, who

no

**Comment by JasonGore** [comment]
This may be by design but I can check and see. In the meantime, you should be able to use `customNear` with `customWidth`.

**Comment by angallison** [comment]
This is by design. The "Small, near side" panel is used for navs (invoked via hamburger menu) in breakpoints up to 1023px wide. In breakpoints 1024px and larger, we show the nav on the app canvas.
![large breakpoint_left nav](https://user-images.githubusercontent.com/14059817/68510000-430b1000-0227-11ea-9edf-8fac667bd875.JPG)
![xlarge breakpoint_left nav](https://user-images.githubusercontent.com/14059817/68510001-430b1000-0227-11ea-9800-a6de68891ee0.JPG)

**Comment by JasonGore** [comment]
Thanks Angela!
