### ISSUE TITLE
DetailsList: When initialFocusedIndex is set, the row is focused, but no visible indication for auto focused/selected row

### ISSUE THREAD

**Issue by niadak** [OfficeDev/office-ui-fabric-react#1112]
Hi,
We are using initialFocusedIndex  in Detailslist to auto focus relevant row. On render, the focus is on the row but there is not visual indication for where the focus is. We need to press arrow keys to see the focused row.

Is it a known issue?

**Comment by mohitbagra** [comment]
+1.

**Comment by petdun2519** [comment]
+1

**Comment by vashit** [comment]
+1

**Comment by kristoferbrown** [comment]
@niadak @mohitbagra @petdun2519 @vashit, I'm currently seeing DetailsLists with initialFocusedIndex set render so that the initially focused item gains the focus outline on when the details list itself gains focus, which I believe is the desired behavior so I'm closing this issue. If you still see a problem here please reopen this issue with more details.
