### ISSUE TITLE
Calendar: Upon Selecting the date, calendar dialog box blinks and focus moves to the arrow.

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#11143]
Tracking all of the issues brought up with the 03/15 accessibility pass on Calendar fabric control
Details on individual bugs can be found on [Sharepoint](https://microsoft-my.sharepoint.com/:x:/r/personal/v-amaver_microsoft_com/_layouts/15/Doc.aspx?sourcedoc=%7B8cfe67c5-ce76-4083-b60e-4190dbd38206%7D&action=default&uid=%7B8CFE67C5-CE76-4083-B60E-4190DBD38206%7D&ListItemId=1872&ListId=%7B395E1ECB-5002-440E-81C5-6A090E98077C%7D&odsp=1&env=prodbubble)

**Comment by lorejoh12** [comment]
Two issues identified here. First, when month is selected, focus is supposed to go to the first day in the month. Currently, it goes nowhere. This is less severe, just would be nice if it did that for you. This repros in both OUFR Calendar and date-time calendar.

Second, when day is selected, the control should close and no re-open. Currently, it closes, then immediately re-opens, requiring the user to use the ESC key to close it again. This is actually fixed in date-time calendar.

Since the more severe issue is fixed in date-time, I'd like to close this, but I'll leave it open while we evaluate the auto-moving focus when selecting the month.
