### ISSUE TITLE
Textarea - Screenreader is not reading the Placeholder text for Text field

### ISSUE THREAD

**Issue by sagaranandani17** [OfficeDev/office-ui-fabric-react#11171]
### Environment Information

- **Package version(s)**: 7.24.0
- **OS version:** 1903 (OS Build: 18326.295)
- **Browser:** Edge(Microsoft Edge 44.18362.267.0)

**User Experience:** 
If narrator is not providing the Placeholder text information to its users then it would be difficult for them whether any action is performing over the screen or not.

**Actual behavior:**
Screen Reader is not providing the "Placeholder"  text information.

**Expected behavior:**
 Screen Reader should provide the "Placeholder"  text information.

**Please find the attachment**
![image](https://user-images.githubusercontent.com/57341535/68733660-67873380-05fd-11ea-996b-26f655d33173.png)

**Comment by kenotron** [comment]
PlaceHolder text is a visual only element and isn't meant to be read aloud:

https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Placeholder_Research
https://stackoverflow.com/questions/48646450/placeholder-text-best-practices-for-accessibility

Thanks for the suggestion, I think the proper thing to do is to create proper LABELs for your input TextField so that it is clear what the purpose is for the input.
