### ISSUE TITLE
need option to adjust height of the panel

### ISSUE THREAD

**Issue by nli8n** [OfficeDev/office-ui-fabric-react#11186]
#### Describe the feature that you would like added

Currently Panel has a full height and don't seem to have an option for adjusting the height.

#### What component or utility would this be added to

Style

#### Have you discussed this feature with our team, and if so, who

no

**Comment by kenotron** [comment]
I don't believe Panel is the right component to be using in that case. If you want a non-full height panel, it could be a Callout:

https://developer.microsoft.com/en-us/fabric#/controls/web/callout

or a Modal:

https://developer.microsoft.com/en-us/fabric#/controls/web/modal

We likely will not be adding a new component to the design language to do otherwise.

**Comment by kenotron** [comment]
Tagging @aneeshack4 who's the code owner here.

**Comment by aneeshack4** [comment]
@kenotron @nli8n for now, I'd also recommend Callout or Modal - we can consider this height change option when we make the new Panel for Fluent UI.

**Comment by nli8n** [comment]
hi @aneeshack4 @kenotron ,
I need a side panel on the right side, just below the header component of my web-app (similar to how it is in azure portal).
I think modal is used for pop-ups and Callout also doesn't serve the purpose. Do you have any idea on how to adjust height of Panel or is there any other relevant component apart from Modal or Callout ?

**Comment by xugao** [comment]
@nli8n - panel by design opens with full height. can you share a design of what you are trying to build here? I checked [azure portal](https://ms.portal.azure.com/#home) and their panels look full height to me
