### ISSUE TITLE
[Accessibility][Keyboard navigation]: 'Home' and 'End' key does not take the focus to first / last option of the combo box.

### ISSUE THREAD

**Issue by joschect** [OfficeDev/office-ui-fabric-react#11211]
Split out of issue #6920

**Comment by xugao** [comment]
[Comment](https://microsoft-my.sharepoint-df.com/:x:/p/mgodbolt/EWp6C5th0sZMgOON89z0g4kBPi12LZ_vfhZQk6gfyc81nw?e=iu0nhL) from JSPURLIN:

This is by design. If a comboBox is allowFreeform HOME/END acts on the content in the input, if allowFreeform is false HOME/END does take the user to the first/last option in the list.      Even if this was a bug, it would not be a MAS bug, at most it would be a usability bug.... Not a bug/MAS bug
