### ISSUE TITLE
IE11. Object doesn't support property or method 'focus' Popup.js

### ISSUE THREAD

**Issue by prashant1587** [OfficeDev/office-ui-fabric-react#11221]
I have a svg element that deletes after a popup closes. 
after the delete action i get 
SCRIPT438: Object doesn't support property or method 'focus'
it happens on Popup.js

It happens because the popup opened up from svg element hence the focus goes back to the SVGElement.
Since focus on SVGElement does not work on IE. I get the above issue.

The issue is at:

 if (this._originalFocusedElement) {
        this._originalFocusedElement.focus();
      }

if the originalFocusedElement could be checked for SVGElement. This issue would not arise.

**Comment by micahgodbolt** [comment]
Any chance of getting a repro of this in a codepen? yes, codepen doesn't work in ie11, but you can go to debug view and open that in ie11

**Comment by micahgodbolt** [comment]
Can you have focus originate from some wrapper around the SVG?

**Comment by kenotron** [comment]
To address this, the app needs to participate in the solution. We won't be adding code to check for presence of a focus() method before calling it - this kind of code appears everywhere. Also, the implication here is that the focus would be either lost or incorrect.  In that case, the app suffers from strange accessibility issues.

The workaround should be to have a wrapper or something over SVG so that the focus originate over this wrapper rather than the SVG. Another strategy in general is to AVOID SVG for IE11 altogether because of inconsistent support for things like this.
