### ISSUE TITLE
Missing HTML Markup Core Components in Documentation

### ISSUE THREAD

**Issue by mateuscmsp** [OfficeDev/office-ui-fabric-react#11230]
As you can see, the documentation is teaching how to use the Button component in TypeScript, but it is NOT showing the use of Fabric UI Core (Component HTML Markup) for non-React.

To start off using this framework, we need a rich documentation guide with HTML Markup instructions for each component, otherwise it will be crazy to guess.

API Button Component URL: https://developer.microsoft.com/en-us/fabric#/controls/web/button#BaseButton

**Comment by kenotron** [comment]
We definitely would love to get more documentation in place for Fabric Core. However, this isn't the priority of the team that manages this exact repository. For the Fabric Core documentation, make sure to communicate your desire for it here:

https://github.com/OfficeDev/office-ui-fabric-core/issues/1200

I concur with this, but it seems the resources have shifted towards React internally within MSFT. Marking this "external" because the issue is duped across to the actual repo that would contain this doc.
