### ISSUE TITLE
Narrator in scan mode reads header elements behind modal dialog

### ISSUE THREAD

**Issue by clmori** [OfficeDev/office-ui-fabric-react#11241]
### Environment Information

- Package version(s): 7.60.1
- Browser and OS versions: Microsoft Edge 44.18362.449.0

### Describe the issue:

When in scan mode, Narrator is reading header elements that are behind the modal dialog.

### Please provide a reproduction of the issue in a codepen:
Dialog: https://codepen.io/rkalivarapu/pen/NWWEyzE
Modal: https://codepen.io/rkalivarapu/pen/mddQXzX

#### Actual behavior:

On the codepen above, set narrator to Scan mode and press H. After going through the elements in the dialog, narrator is reading the elements on the page behind it

#### Expected behavior:
Narrator should not read header elements behind the dialog

**Comment by aneeshack4** [comment]
This doesn't repro on Edge + Narrator which is the primary use case we support - are you sure you're using this combo? @clmori

**Comment by clmori** [comment]
@aneeshack4  can you try "Shift+H" which will take you back? It's reading the elements behing when I try that.

**Comment by aneeshack4** [comment]
@clmori Shift + H does make this go back 
![image](https://user-images.githubusercontent.com/4161791/69367476-617cfc80-0c66-11ea-936b-827eae79d389.png)
But why would Shift + H be used here? I believe the primary way to navigate back is Shift + Tab

**Comment by clmori** [comment]
I believe the usage is "H" to go to the next header, and "Shift+H" to go to the previous header. Tab would navigate through all the elements in the tabbing order.

**Comment by rkalivarapu** [comment]
Reference:
https://support.microsoft.com/en-us/help/22809/windows-10-narrator-using-scan-mode

**Comment by aneeshack4** [comment]
I found a reference example where Shift + H doesn't go outside to other headings on the page: https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html 

I spoke with the component owner offline and it seems like this might still be a Narrator scan mode problem because the differences between the w3 reference example and the fabric one seem to be in DOM structure and scan mode breaks/ignores DOM hierarchy.

**Comment by dzearing** [comment]
I tried this with https://jquerymodal.com modals and Narrator on Edge and Chrome, and scan mode allows reader to move behind dialogs. This has been reported a number of times and I'm not sure how this can be fixed from the component library perspective, without relying on the `dialog` element, which is not cross browser compatible.

Scan mode takes over the browser's behaviors so normal eventing does not occur as expected.

If you could provide an example that does not exhibit the behavior, we could investigate how it's approached. Otherwise, I don't see a way to resolve this.
