### ISSUE TITLE
Narrator: Editable table item is read as both "readonly" and "edit"

### ISSUE THREAD

**Issue by clmori** [OfficeDev/office-ui-fabric-react#11267]
### Environment Information

- **Package version(s)**: 7.60.1
- **Browser and OS versions**: Microsoft Edge 44.18362.449.0

### Describe the issue:

On the codepen below, narrator reads the editable items in the table as both "readonly" and "edit" when navigating with Ctr+Alt+Arrow keys. .

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/saisubrahmanya/pen/XWWGPzR

#### Actual behavior:

Narrator reads:

"**Readonly**, column header 'Name', column 4 of 10, **Edit**, 'One'"

#### Expected behavior:

Narrator should not say it's readonly, and may say "press right to edit" or something similar.

**Comment by aneeshack4** [comment]
Hi @clmori, I believe this is correct behavior because it's saying read only when the focus is on the outer cell but when the focus is on the textbox inside that's editable, it says "edit": 
![image](https://user-images.githubusercontent.com/4161791/69366692-e0713580-0c64-11ea-9a64-705cbb743a67.png)

**Comment by smhigley** [comment]
@aneeshack4 I looked at this and talked with an engineer on @clmori's team, and agree this is the correct behavior -- the cell itself is readonly, and the edit is within it.

I think this can be closed, thanks!

**Comment by aneeshack4** [comment]
@smhigley Sounds good!
