### ISSUE TITLE
HoverCard add Callout Props

### ISSUE THREAD

**Issue by Taaqif** [OfficeDev/office-ui-fabric-react#11272]
#### Describe the feature that you would like added
It would be great to have the ability to override the callout props of the hover card. 
Really just looking for the ability to add a beak to the hovercard layout

#### What component or utility would this be added to

The hovercard component

#### Have you discussed this feature with our team, and if so, who

N/A

#### Additional context/screenshots

The functionality already seems to be in place as the hover card already uses the callout as the parent container. Having the ability to add to the props i.e. adding isBeakVisible or GapSize would be really nice to have.

**Comment by aneeshack4** [comment]
Hi @Taaqif, thanks for reaching out to us. 

We've added Beaks to components like [Slider through TooltipHost](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/experiments/src/components/Slider/Slider.base.tsx#L139) in order to use all of the CalloutProps but I spoke with component owners and that might not be recommended in the case of HoverCard because Tooltip has conflicting mouse events. So we think adding CalloutProps would be better too. I'm adding this to the feature backlog for review.
