### ISSUE TITLE
Week Selection

### ISSUE THREAD

**Issue by DuncanFisher** [OfficeDev/office-ui-fabric-react#11322]
#### Describe the feature that you would like added

Date time picker could be even a greater asset if a Date Range could be selected.
For instance, selecting a Week instead of a Day.

#### What component or utility would this be added to
DatePicker Component

Week Selection / Range Selection.
getRange() returning IRangeSelection with First and Last day of the Range.

#### Have you discussed this feature with our team, and if so, who

No, not really.

#### Additional context/screenshots

For applications that require Week selection like scheduling or reporting.

**Comment by khmakoto** [comment]
Hi @DuncanFisher thanks for filing out this feature request! @lorejoh12 do you know if this is something we have in our roadmap or if we have something today that offers a similar degree of support to this?

**Comment by lorejoh12** [comment]
nothing on our roadmap right now to add this by default.

You can get most of the functionality by doing something like:
```
render() {
  const dateRangeType = DateRangeType.Week;
  return (
    <DatePicker
      formatDate={this.formatDate}
      onSelectDate={this.onSelectDate}
      calendarProps={
        {
          dateRangeType: dateRangeType,
        }
      }
    />
}
 
  private computeRange = date => {
    return {start: startOfWeek(date), end: endOfWeek(date)};
  }

  private formatDate = date => {
    const range = this.computeRange(date);
    return range.start.toDateString() + ' - ' + range.end.toDateString();
  }
  
  private onSelectDate = date => {
    const range = this.computeRange(date);
    // whatever you want with the range
  }
```

codepen here: https://codepen.io/lorejoh12/pen/JjoGZjv

Downsides are that you'd have to write the formatDate functions yourself, and that you'd have to store the dateRangeType yourself so that your formatDate function has access to it (since our function definition doesn't include the parameter). You'd also probably have to keep track of settings like FirstDayOfWeek and FirstWeekOfYear to pass to your computeRange function if you let the user customize those.

It gets a little tricky because of localization, although there is a moment-js plugin called `moment-range` that can probably handle it if you go this route.

**Comment by DuncanFisher** [comment]
This seems to work. Thank you.
