### ISSUE TITLE
Scrollbar is not shown on first render of a card, but on second time hover or click of the card.

### ISSUE THREAD

**Issue by EliasKaplan** [OfficeDev/office-ui-fabric-react#11384]
### Environment Information

- **Package version(s)**: office-ui-fabric-react@7.69.1
- **Browser and OS versions**: Chrome, Windows
### Please provide a reproduction of the bug in a codepen:

Problem seem to be here:
  public componentDidMount(): void {
    this._checkNeedsScroll();
  }

Instead of doing the check on DidMount, has to be done  on firstFrameRendered, so the card show scrollbar on first render, when needed.

#### Actual behavior:

Repro with Location Card in OWA, for rooms that have room features the LC is expanded and requires a scrollbar vertical. On 1st hover or click the card the bar doesn't show, hover out of the card and hover again over the location, now it shows the bar.

#### Expected behavior:
show the scrollbar whenever the Card size is greater than default size, scrollbar required.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
Y.
Requested priority: (Blocking, High, Normal, Low)
Normal.
Products/sites affected: (if applicable)
OWA location Card.

**Comment by xugao** [comment]
@EliasKaplan  - i could not repro this bug [here](https://codepen.io/xugao/pen/KKwpJxB)
Pls provide a minimal repro in a codepen.

**Comment by acamargob** [comment]
Our problem might be that we use Shimmer elements to fake the content while server load finishes.
Once that is completed, we replace the Shimmers with actual content, and the actual content might be larger than the shimmers.

Since the check for needs scroll is performed on first render, it wrongly takes the height of the Shimmers and not the actual content.

Subsequent renders are fine because there is no delay in the retrieving of the data.

@EliasKaplan Let's sync up on Monday. We can mitigate this on our end by:
1. Adjusting the delay time for the extended portion of the card and/or
2. Kicking of the data service earlier (I think we already do this, but it wouldn't hurt to double check)

@xugao I'll try to craft a repro codepen too.
