### ISSUE TITLE
Calendar: Empty string at the end of the array of localized month names causes extra button to appear

### ISSUE THREAD

**Issue by HarryGifford** [OfficeDev/office-ui-fabric-react#11382]
### Environment Information

- **Package version(s)**: office-ui-fabric-react@7.69.1
- **Browser and OS versions**: Not relevant

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/hegi/pen/qBEdMEp

#### Summary
Adding an extra empty string to the end of the array of localized names causes an extra button to appear.

#### Background
Microsoft's .NET Framework provides [localized strings for month names](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.datetimeformatinfo.monthnames?view=netframework-4.8), but they normalize the array to always be exactly 13 elements long. For a 12 month calendar they add an extra empty string for the last month. We use these strings, but we have to filter them manually.

#### Actual behavior:

If we don't remove the last empty string, then you will see the following clickable button on the calendar control:
![image](https://user-images.githubusercontent.com/21968002/70265050-74a3c800-174e-11ea-885c-c0d8d8463ca1.png)

#### Expected behavior:

It would be convenient if we could pass an array containing an empty string in the last month position and Fabric would automatically remove the empty string.

This is obviously a minor issue and isn't necessarily a bug, but it can be tricky to track down this issue and it would be nice to be able to directly pass through these settings from a web server running Windows.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: Dynamics 365

**Comment by xugao** [comment]
@HarryGifford  - after some thinking, this is a case it's better to defer the component user to pass us the right props. 
your case is a very corner case. and yes we can add the logic to filter out empty values in the prop (which is something we need to do on every render since it's a prop), but then majority of the use cases are paying this unnecessary cost.
And if i'm not mistaken, this is very cheap to do on your side :)

Hope this makes sense & thanks for your understanding
