### ISSUE TITLE
Callout with reference target is not rendering beak

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#11417]
Using an ID reference works fine, but reference targets don't render a beak and always render at the top of the referenced element. 

![image](https://user-images.githubusercontent.com/1434956/70552861-f7ea6280-1b2e-11ea-8a18-792682e24180.png)

https://codepen.io/micahgodbolt/pen/VwYaKYb?editors=0010

**Comment by joschect** [comment]
@micahgodbolt I think this is happening in this case because the element is a react element rather than a dom element. If you look at what goes into the ref it's not a div.

**Comment by micahgodbolt** [comment]
@joschect same issue with ref placed on the div above.

**Comment by joschect** [comment]
@micahgodbolt Correct, because at the time that the component first render, ref.current won't contain the actual element because it hasn't mounted yet. Instead just pass the ref itself into the picker as it will handle checking to see if it has an actual element. Check it out in this [codepen](https://codepen.io/slimemold/pen/zYxqoeL?editors=0010)

**Comment by micahgodbolt** [comment]
OH sheesh. I didn't even notice the .current on that ref. I gotcha now.
