### ISSUE TITLE
Color Picker Control:  User not able to change the slider in the saturation or alpha slider with the help of left/right arrow keys while narrator application is running.

### ISSUE THREAD

**Issue by navkuma** [OfficeDev/office-ui-fabric-react#11416]
### Environment Information

Package version(s): 7.69.3 (or latest)
Browser and OS versions: Microsoft Edge 44.18362.449.0 and Windows 10 Enterprise version 1903 OS build 18362.476

### Describe the issue:
User Impact:
People with Visual impairment will not be able to access the sliders with Narrator 
In the Color picker control, With the  Narrator  application running, sliders in the color picker control can't be changed with the help of left right arrow keys.

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/16f4cae9-74df-4efe-af3b-485541d4fa53/pen/wvBGByO?&editable=true

#### Actual behavior:

In the Color picker control, With the  Narrator  application running, sliders in the color picker control can't be changed with the help of left right arrow keys.

#### Expected behavior:
With the help of left and right arrow keys user should be able to change the slider with narrator application running.

**Comment by joschect** [comment]
@navkuma I think that is because narrator is in scan mode. With narrator out of scan mode arrowing works as expected. I believe that this is intended  behavior because scan mode is typically used to navigate around the page quickly and it intercepts all arrow keys. You can exit scan mode and test yourself by <Narrator> + space. Narrator is typically assigned to the caps lock key.
