### ISSUE TITLE
[Accessibility] In High Contrast the calendar picker doesn't show the today's date correctly.

### ISSUE THREAD

**Issue by nishaant95** [OfficeDev/office-ui-fabric-react#11455]
### Environment Information
- **Browser and OS versions**: 
Chromium Edge Browser.

### Describe the issue:

In high contrast black or white the calendar picker doesn't show the today's date correctly.

#### Actual behavior:

![image](https://user-images.githubusercontent.com/58846033/70790552-5461b200-1dbb-11ea-8ee8-b33f33c1db19.png)

#### Expected behavior:

![image](https://user-images.githubusercontent.com/58846033/70790578-63486480-1dbb-11ea-81e8-e6ee107e4f38.png)

**Comment by joschect** [comment]
@nishaant95 , could you confirm that you're using the new chromium edge browser and not the old one? Also could you link a codepen? Are you using the calendar from the date-time package?

**Comment by nishaant95** [comment]
@joschect i am using Version 80.0.355.1 which is latest.
Also this issue is reproable in office fabric site as well.
Go this this page and switch to high contrast mode.
You will see the issue.
https://developer.microsoft.com/en-us/fabric#/controls/web/calendar

Let me know if any additional thing is required.

**Comment by joschect** [comment]
@nishaant95 It looks like it's reproducible on the main site because there is some css that overwrites the calendar colors which is unrelated to fabric. You can see that it is not reproducible when you use it in [isolation](https://codepen.io/slimemold/pen/GRgNWvr?&editable=true).

Here's a screenshot of the overriding css.
<img width="425" alt="Screen Shot 2019-12-16 at 9 35 51 AM" src="https://user-images.githubusercontent.com/20801176/70929427-f4038800-1fe7-11ea-92e5-dbb47fa58594.png">
