### ISSUE TITLE
Text and some other components doesnt change their colors on loadTheme()

### ISSUE THREAD

**Issue by aminmashayekhi** [OfficeDev/office-ui-fabric-react#11459]
### Environment Information

- **Package version(s)**: (7.73)
- **Browser and OS versions**: (Win10-Chrome79)

**Comment by joschect** [comment]
@aminmashayekhi Could you link to a codepen and add a bit more information regarding the problem and where/when you're experiencing it?

**Comment by aminmashayekhi** [comment]
sorry, here you are:
https://codepen.io/aminmashayekhi/pen/BayLLgO

**Comment by joschect** [comment]
@aminmashayekhi Thanks for the codepen! That helps clear things up. At least for the Text component, looking at the code it looks like it explicitly is supposed to inherit from whatever contains it, just a like a default div would. You can theme it by providing a [font](https://codepen.io/slimemold/pen/WNbodpX).

There is no color placed on the body background because it isn't a fabric component. It's up the apps to decide if that gets themed or not. I know that there was a discussion about providing a component that would place a theme on the body, but there might be more to an app than just theming the body background.

Right now this theming is working as designed, although it is confusing and could be better documented.
