### ISSUE TITLE
Is it possible to keep Details list under grouped list?

### ISSUE THREAD

**Issue by ymihir** [OfficeDev/office-ui-fabric-react#11457]
I want to create GroupedList which will contain DetailsList under each GroupedList. Is it possible?

**Comment by joschect** [comment]
@ymihir You could probably do something like that. What are you trying to accomplish by nesting a details list within a groupedlist? GroupedList already supports multiple levels of nesting and details list supports groups within it already.

**Comment by ymihir** [comment]
@joschect true, it will support for multiple levels. But for dynamic data it is becoming hard to create such kind of json object by specifying indexes.

**Comment by joschect** [comment]
@ymihir Can you be more specific with what you're trying to achieve? It sounds like you want there to be multiple details lists each with their own data source hosted within one details list so that way each one updates separately. 

There is no reason you cannot have a details list nested, although I'm not sure about performance, accessibility, and other concerns. It's not something that will be handled by the details list natively so you'll likely need to do some fine tuning. To help you get started here is a [codepen](https://codepen.io/slimemold/pen/MWYEerz?editors=0010) that has a details list which in turn renders groups and will render each row as another details list.
