### ISSUE TITLE
Calendar Picker styling is different in mobile view

### ISSUE THREAD

**Issue by abithap** [OfficeDev/office-ui-fabric-react#11468]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
Open https://developer.microsoft.com/en-us/fabric#/controls/web/calendar, in mobile view of a browser (by opening developer tool in chrome and choose mobile view)

Scroll to the Usage - Inline Calendar section, the font and header line height is different from the non-mobile view.

![image](https://user-images.githubusercontent.com/7987995/70835462-098f6c80-1db2-11ea-9584-22eb4dded442.png)

#### Actual behavior:
In mobile view Calendar picker header line-height and font-size are different from the web view calendar picker

#### Expected behavior:
Should have the same styling even in mobile view

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by joschect** [comment]
@abithap This looks to be intentional. There is a specific media query that changes font size and line height based on screen size. I believe this is working as designed. You can override the sizes if you'd rather have them small. 

However, I believe that the calendar exported from the [date-time package](https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/date-time) does not specify font sizes based on screen size, so that might be a better option.

**Comment by abithap** [comment]
@joschect the line-height in the media query is set to 28px but the actual line height we get for this component is 44px which is why the header arrows look weird. Similarly for the font-size we get 15px which is not explicitly set in the media query. Any help / thoughts would be appreciated.

**Comment by lorejoh12** [comment]
I can confirm that date-time package does not have specific media queries on it, and seems to work correctly in this case (chrome emulation of iPhone 6 has it working at least). For this, and multiple other bugs that exist in the OUFR version but have been fixed in date-time, I'd suggest moving over. :)

**Comment by joschect** [comment]
@abithap I spoke with @lorejoh12 offline and it seems that moving to the newer date-time packaged calendar component is your best bet. You can find some more information about it here https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/date-time

**Comment by abithap** [comment]
@joschect thanks for the update, sure I will switch the code to use date/time package. Are you guys planning to eventually replace the Calendar component in office-ui-fabric-react with @uifabric/date-time? or it should always be installed as a separate package?

**Comment by joschect** [comment]
@lorejoh12 Correct me if I'm wrong but I believe it will always be a separate package from now on, although it should be able to replace the current datepicker without much if any tweaking. 

@dzearing might also be able to chime in with plans for the datepicker.
