### ISSUE TITLE
initializeIcons doesn't remove dependency on sharepointonline CDN

### ISSUE THREAD

**Issue by kgnugur** [OfficeDev/office-ui-fabric-react#11477]
I work on on-premises project, because of the security reasons there is no internet access. I can't get icons to work from own CDN.

### Environment Information

- **Package version(s)**:
  - @microsoft/sp-core-library: ~1.4.0
  - react: 15.6.2
  - @uifabric/icons: 5.2.0

#### Actual behavior:

- Several CSS/Font assets have to be fetched from CDN every time.
-  Using initializeIcons(/* own CDN */') does not do anything.
  - Network requests stay same. There is no request for own CDN.

#### Expected behavior:
-  Using initializeIcons(/* own CDN */')  icons to be served from from own CDN.
- All CSS/Font dependencies should be included as part of the NPM package.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No
Requested priority: (Blocking, High, Normal, Low)
High
Products/sites affected: (if applicable)
Any that needs to have its assets prepackaged/bundled.

**Comment by ecraig12345** [comment]
If you remove your custom code from the page, do you still see the CDN requests? If so, I suspect this is actually an issue that needs to be resolved in SharePoint--something in the built-in code may be calling initializeIcons with the default CDN. Not very likely but worth checking.

If the custom requests go away when your code is removed, a couple questions:
1. Is this in a webpart, or some other context? 
2. At what point in your code are you calling initializeIcons? (It should be called once during initialization before you render any components.)

**Comment by ecraig12345** [comment]
In addition to the questions in my previous comment, can you share exactly what CDN resource URLs are being loaded? Would help to narrow down where the problem is.

I noticed that as of icons@5.2.0, the URL is actually spoprod-a.akamaihd.net not sharepointonline.com. 
https://github.com/OfficeDev/office-ui-fabric-react/blob/7bd70ca910f147560e0c0e8a536a2659730b5f13/packages/icons/src/index.ts#L17

But fonts do use sharepointonline.com by default. To change the CDN for fonts, you can set `window.FabricConfig.fontBaseUrl`--this is something we need to document better.
https://github.com/OfficeDev/office-ui-fabric-react/blob/bd6c54145bebb9d2ec29e9f3c5f1c690385d92e8/packages/styling/src/styles/DefaultFontStyles.ts#L8

**Comment by kgnugur** [comment]
@ecraig12345 Hi,

> Is this in a webpart, or some other context?

Webpart, built with spfx@~1.4.0

> At what point in your code are you calling initializeIcons? (It should be called once during initialization before you render any components.)

I tried to call it inside *WebPart.ts file in `protected onInit(): Promise<void>{}`  -> Does not change anything.
I tried to call it in `compenentDidMount` and `componentWillmount`  -> Does not change anything.

Three of them gives me `warn.js:77 Some icons were re-registered. Applications should only call registerIcons for any given icon once.` warning.

## Further details

Project is generated with `@microsoft/generator-sharepoint` choosing `onprem19`


### Working icons without custom webpart 
I did remove my custom webpart, I refreshed an empty sharepoint page and there is no request to `https://static2.sharepointonline.com/files/fabric/assets` and the icons are working.

![emptyPageIconsWorking](https://user-images.githubusercontent.com/28161197/70965866-32f61400-20a2-11ea-88b4-7ff4281c36b1.PNG)
![emptyPageRequests](https://user-images.githubusercontent.com/28161197/70965870-35f10480-20a2-11ea-970f-63be7caede06.PNG)

### Now working icons with custom webpart built with  spfx@~1.4.0
Now if I add my webpart: all fonts are gone for a second, than already working and addational icons will not be rendered. Untill  ~6  `https://static2.sharepointonline.com/files/fabric/assets`  requests failed. After all `static2.sharepointonline.com` requests  fail icons will start working again. (Not all of them some icons are still missing). There is no request for `spoprod`.


![fontIsGone](https://user-images.githubusercontent.com/28161197/70966057-e0692780-20a2-11ea-8374-b2ce2e835016.PNG)
Fonts are not working for a second.
![somealreadyworkingiconsgone](https://user-images.githubusercontent.com/28161197/70966071-f1b23400-20a2-11ea-9d7e-71710804bef8.PNG)
Icons are gone.
![notworkingrequest](https://user-images.githubusercontent.com/28161197/70966087-ff67b980-20a2-11ea-84b2-b52a18280c97.PNG)
Network requests related to icons.

### Font requests
![unnamed](https://user-images.githubusercontent.com/28161197/70967206-b154b500-20a6-11ea-9326-2ff91f3031ac.png)

**Comment by ecraig12345** [comment]
Sorry about the delay getting back to you on this. Some more questions and suggestions.

### Text fonts

In the network tools, do you see any requests for Segoe fonts which are coming from your local server? Based on the location of the successfully-loaded icons fonts, I'm guessing the Segoe fonts are also available somewhere under `http://spkagan/_layouts/15`.

Once you find the URL where the default fonts are located, try adding this in the root file of your webpart **before** you import anything from Fabric (not inside a component):
```
window.FabricConfig = {
  fontBaseUrl: 'http://<location of default font files>'
};
```
The unfortunate thing here is that since the webpart is sharing the page with other code, setting this global may cause side effects or not work as expected. And at least in Fabric 5, I'm not aware of a way to change the text font location or prevent the fonts from loading without a global.

### Icon fonts: `initializeIcons`

What happens if you entirely remove the `initializeIcons` call? The default icons should already be present on the page, unless there are version mismatches between the Fabric version used by the page itself and the one used by your app.

### Icon fonts: other

Are you loading `office-ui-fabric-core` in your webpart? If so, I think the `fabricmdl2icons` fonts may be coming from there, since we don't directly use any fonts with that name in fabric react.

**Comment by ecraig12345** [comment]
Please also take a look at the comment I added on this other issue and see if it helps clarify anything. https://github.com/OfficeDev/office-ui-fabric-react/issues/10363#issuecomment-572908081
