### ISSUE TITLE
dir="auto" in PersonaBase shadows global RTL settings

### ISSUE THREAD

**Issue by njenia** [OfficeDev/office-ui-fabric-react#11539]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

`PersonaBase` renders a `dir="auto"` on the primary / secondary text containers: 
https://dev.azure.com/dynamicscrm/OneCRM/_git/CRM.SalesInsights.UI/pullrequest/397106
which shadows any dir attribute higher in the element tree (like on the body).

#### Expected behavior:

I'd like to be able to set the dir in one central place like `<body>`, and have all descendant components inherit this value.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by cliffkoh** [comment]
@mtennoe @Markionium do you know if the `dir="auto"` in Persona is intentional?

**Comment by cliffkoh** [comment]
Hey @njenia because it is the holidays season and many people are OOF, it might be sometime before we can get an answer to this. I'll let @micahgodbolt follow up/follow through on this issue.

**Comment by micahgodbolt** [comment]
This change was added back on April 5th #8621

Was an issue of truncation of latin characters.

**Comment by njenia** [comment]
@micahgodbolt so what's the recommended way to have the text components in persona support RTL? because of the shadowing it doesn't answer to higher `dir` attributes.

**Comment by Markionium** [comment]
@njenia I think the fix that was linked above was done because the text direction of the name is often unknown.

Assuming you're using Persona for people who might have names in RTL or LTR languages wouldn't that seem like the correct thing? If you set it globally you might run into the bug mentioned in the PR.

If my thinking is not correct perhaps you could give some more context on why you have the use case to set it on the `body` instead of letting the browser decide based on the content?
