### ISSUE TITLE
Dropdown isn't RTL compatible

### ISSUE THREAD

**Issue by njenia** [OfficeDev/office-ui-fabric-react#11543]
### Please provide a reproduction of the bug in a codepen:

https://codepen.io/jenian/pen/xxbdBXE?&editable=true#anon-signup

#### Actual behavior:
Dropdown control's caret doesn't change direction when dir is RTL.

#### Expected behavior:
In LTR - the caret should stick to the right (as it is now).
In RTL - the caret should stick to the left (currently it's to the right).

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by micahgodbolt** [comment]
A couple things....We don't currently support contextual RTL in the way that you are doing it. There's a number of CSS calculations that need to change for RTL to work, and we only look to the root direction value to determine how to calculate those CSS rules.

We do provide a React contextual way to set RTL via the theme. This React context will be passed into CSS calculations functions (like right/margin-right etc) to flip them to left/margin-left. 

Unfortunately I noticed a few bugs in this feature (which was just recently added). Turns out you can't create a theme with RTL in it. Secondly, you still need to provide `dir="rtl"` in a wrapping div like you did, but Layers are rendered outside of that DOM tree, so we need to look into the current theme and set RTL on that layer when flipped in the theme. 

I've created a PR to resolve these 2 issues.
