### ISSUE TITLE
<IconButton /> style not responding correctly

### ISSUE THREAD

**Issue by BrianD91** [OfficeDev/office-ui-fabric-react#11628]
### Environment Information

- **Package version(s)**: 
office-ui-fabric-core: ^10.1.0
office-ui-fabric-react: ^7.49.0

- **Browser and OS versions**: 
Chrome: 79.0.3945.88
Mac OS: Catalina v10.15.1

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/Bridelic/pen/LYEQbWy

#### Actual behavior:

When you hover over of the `<button>` element the color value is set to `color: rgb(16, 110, 190);` even though I set the component styles so that the color value would be `color: #C01212` on hover. I know am I using selectors properly because if I set something like `text-decoration: underline` to be added when the element is hovered that will work fine, it seems only the color doesn't respond properly.

#### Expected behavior:

When you hover over the `<button>` element it should use the values I set in the styles prop of the component.

### Priorities and help requested:

Are you willing to submit a PR to fix? Sure if I can be provided with more insight on why this might be happening in the first place

Requested priority: Normal

Products/sites affected: Presumably every site that uses the `<IconButton />` component.

**Comment by khmakoto** [comment]
Hi @BrianD91, this happens because the `styles` object in the `Button` has a particular `rootHovered` style that is overriding your provided selector. You can use this, as can be seen in [this fork of your codepen](https://codepen.io/khmakoto/pen/gObvLQZ?editors=0010), to set the hovered color easily. Hope this helps and if you need anything else feel free to ask!

**Comment by BrianD91** [comment]
Thanks, @khmakoto
