### ISSUE TITLE
Hide eye icon needed

### ISSUE THREAD

**Issue by srnitk** [OfficeDev/office-ui-fabric-react#11688]
In the current Fabric icons, there is no icon like the one shown below, please make this available for us:

![image](https://user-images.githubusercontent.com/55491991/72253236-14465700-3627-11ea-9701-4a5711647f71.png)

### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by dzearing** [comment]
Tagging @Jahnp

**Comment by Jahnp** [comment]
Thanks for the heads-up @dzearing!

@srnitk , we have three icons similar to the one in your screenshot in the Fabric font today. 
ED1A - Hide
![image](https://user-images.githubusercontent.com/307118/72280686-c2350f80-35ed-11ea-8249-93c64e9cbbe4.png)

EF89 - Hide2
![image](https://user-images.githubusercontent.com/307118/72280729-d711a300-35ed-11ea-80ee-a917ed434bc4.png)

F6AC - Hide3
![image](https://user-images.githubusercontent.com/307118/72280747-e5f85580-35ed-11ea-9b11-0e92a719e659.png)

I pulled these from the [Fabric icons tool](https://uifabricicons.azurewebsites.net/), and all three of them are available in the latest version of Fabric React.

Will one of those be sufficient for your purpose? We generally try to avoid adding additional variations of existing metaphors unless necessary.

**Comment by srnitk** [comment]
Hi Jahnp

I'm from an internal team in Microsoft. I've gone through the icons you've shared. But none of them is similar to the one I shared. The one I shared is in New edge browser to hide password in settings page. Our team needs that sort of icon.

**Comment by srnitk** [comment]
Similar icon I requested is available even in font awesome, but not in Fabric React. It'll be great to have this icon as well.

**Comment by angallison** [comment]
@srnitk - It may be a good idea to start an internal email thread with Matt Ropel. He can help determine which icon to use based on the metaphor, localization, etc.

**Comment by Jahnp** [comment]
I'd agree with @angallison's point that it'd be good to start a mail thread with Matt. That can lead to us opening a new icon font request if needed.

@srnitk , I think this is the UX you're referring to, right?
![image](https://user-images.githubusercontent.com/307118/72282191-fbbb4a00-35f0-11ea-8e85-6bac5ed4adad.png)

I will say that as a regular user of that UX, IMO it's kind of hard to distinguish the "Hide" from "Show" actions because the icons aren't visually that different from one another. That's fairly evident from the screenshot above.

If you'd be open to using a different icon, ED1A Hide seems to use the same "eye" metaphor as E7B3 - RedEye (see below) and could make a good pairing.
![image](https://user-images.githubusercontent.com/307118/72282434-7ab08280-35f1-11ea-8b06-b912058f4a0a.png)

Perhaps those would be worth considering?
