### ISSUE TITLE
[ContextualMenu][Accessibility][ScreenReader] Incorrect readout sequence

### ISSUE THREAD

**Issue by MightySameerDesai** [OfficeDev/office-ui-fabric-react#11745]
### Environment Information

- **Package version(s)**: 7.34.0
- **Browser and OS versions**: Edge 44.18362.449.0 , Windows 10 Enterprise 1909

### Describe the issue:
For contextual menu buttons, when using narrator, the narrator reads out the menuopen and menu closed readouts incorrectly (sequence).

### Please provide a reproduction of the issue in a codepen:

Can look at any of the contextual menus in the documentation page. Just open narrator and check with menu open and close. 

#### Actual behavior:

**_On Click_** - (Aria) Label + "group"
	On click (to close the menu) - Label "Expanded" + Label "Collapsed"  (together at once)

#### Expected behavior:

I believe that on click, when menu is opened, it should read out that "<Label> is expanded" and on close, "<Label> closed"

**Comment by khmakoto** [comment]
Hi @MightySameerDesai I can confirm this behavior, however, I think this is an issue that is half expected behavior, half behavior that happens because of unexpected use.

The part about opening the menu and Narrator not announcing the `expanded` state of the menu is expected because when you open the menu the focus goes to the menu itself, with the `expanded` state being on the button.

The part about closing the menu and it announcing both `expanded` and `collapsed` states I think comes from how Narrator propagates events and it's why you see different behavior if you just use keyboard interaction and why this only happens when you use the mouse and the focus is already on the button.

If you use keyboard interaction these are the things that happen:
1. You put focus on the button with the menu. Narrator announces the button and its collapsed state.
2. You use space/enter to open the menu and focus goes inside of it. Narrator announces the first option in the menu.
3. You select an option or use the Escape key to close the menu, focus goes back to the button and Narrator announces the button and its collapsed state again.

If you use mouse interaction these are the things that happen:
1. You put focus on the button with the menu. Narrator announces the button and its collapsed state.
2. You click on the button to open the menu and focus goes to the menu itself. Narrator announces aria label + group.
3. You click on the button again to close the menu. Here is where it gets interesting:
3.1. The focus immediately goes back to the button, with Narrator announcing it and its expanded state.
3.2. The menu closes.
3.3. The expanded state of the button changes back to collapsed, with Narrator announcing the button again, but now with a collapsed state.

As you can see, this is expected behavior from how Narrator works and there's not much we can do about it since we're adhering to the correct aria specifications.

**Comment by MightySameerDesai** [comment]
@khmakoto, Thanks for resolving my query.
