### ISSUE TITLE
A11y_D365ManualAdjustmentDialogFeature_Adjust_Adjustment_ScreenReader: The seprators in the dialog are announced.

### ISSUE THREAD

**Issue by fsteffi** [OfficeDev/office-ui-fabric-react#11787]
Repro Steps:​​
1.Launch the url :https://developer.microsoft.com/en-us/fabric#/controls/web/separator
2.Launch screen reader as narrator.
3.Naviaget using caps+arrow to section "Basic separator with text"
4.Navigate to the separator. 

Actual:​
On navigating  using caps+arrow key to the separators present  there is an announcement made for it.

Expected:​​
The separators should not be announced.

User Impact:​
Screen reader users will receive information that is not present on screen.

[A11y_D365ManualAdjustmentDialogFeature_Adjust_Adjustment_ScreenReader.pptx](https://github.com/OfficeDev/office-ui-fabric-react/files/4108399/A11y_D365ManualAdjustmentDialogFeature_Adjust_Adjustment_ScreenReader.pptx)

**Comment by khmakoto** [comment]
Hi @fsteffi, the behavior you're experiencing happens because when using Caps+Arrows in Narrator you're telling it to go through every part of the DOM tree, regardless of our intent in focus. Since this behavior is expected to break with the author's intent regarding focus and Narration there is not much we can do about it and is considered by design by Narrator.
