### ISSUE TITLE
Narrator is reading the TextField content twice in case of type of TextField  is number in Edge browser, In rest of browsers narrator is reading only one time.

### ISSUE THREAD

**Issue by HarkeshS** [OfficeDev/office-ui-fabric-react#11826]
Narrator is reading the TextField content twice in case of type of TextField  is number in Edge browser, In rest of browsers narrator is reading only one time.

### Environment Information

OS: Win 10 Enterprise N
Browser:  Edge

### Describe the issue:

Narrator is reading the TextField content twice in case of type of TextField  is number in Edge browser, In rest of browsers narrator is reading only one time.

### Please provide a reproduction of the issue in a codepen:
Office UI link-https://developer.microsoft.com/en-us/fabric#/controls/web/textfield

Code pen repro link-
https://codepen.io/anubhuti14/pen/MWYdjNG?editable=true

Above code pen link contains two TextField sample, One TextField is type of Number and other is not type of number, 
The type of number TextField contents are read by narrator twice in Edge browser and without type of number TextField  contents are read by narrator only one time in Edge browser.

#### Actual behavior:

Narrator is reading the TextField content twice in case of type of TextField  is number in Edge browser, In rest of browsers narrator is reading only one time.

#### Expected behavior:

Narrator should read the TextField content only one time in case of type of TextField  is number in Edge browser, as in rest of browsers, narrator is reading only one time.

**Comment by khmakoto** [comment]
Hi @HarkeshS, thanks for filing this issue! I'm encountering something different from what you're explaining. In both cases (number and non-number type `Textfields`) I'm finding that the contents are announced, then the type of font, and then the contents again. Is this the behavior you're experiencing? If it is, this behavior is due to a bug in Edge where the focus is going on the text inside inputs and not on the inputs themselves, you can check this out [in this codepen](https://codepen.io/khmakoto/pen/OJPYago) where you can experience the same behavior on regular html input tags.

**Comment by HarkeshS** [comment]
@khmakoto -- Contents are announced but in case of type Number, Narrator is reading same content twice only in Edge, others browsers narrator is reading only one time.
In your code pen shared, second Textfields, narrator is reading its content twice, when first time focus comes on the blank Textfields.

**Comment by khmakoto** [comment]
Hi @HarkeshS, like I said, this is due to a bug in Edge that's being tracked, we can't do anything about it on Fabric's side.
