### ISSUE TITLE
MaskedTextField focus not leaving the textbox in IE when setState is called in onBlur Event

### ISSUE THREAD

**Issue by vipuliflex** [OfficeDev/office-ui-fabric-react#11835]
Hi,

MaskedTextField focus not leaving the textbox when clicking outside of the textbox/in some other control if setState is used in onBlur event assigned to MaskedTextField to rerender the form.

it's only happening in Interenet Explorere(Version 11) it's working fine in Chrome,Firefox and IE Edge.

Please suggest a solution.

**Comment by khmakoto** [comment]
Hi @vipuliflex, thanks for filing this issue! Could you create a codepen with a minimal repro of the bug to investigate it further? If not don't worry, I'll try to repro it on my side!

**Comment by vipuliflex** [comment]
Hi @khmakoto Thanks for the reply i tried to create a CodePen for this issue but could not succeed as CodePen is not supported on IE Browser hence not able to replicate the issue using CodePen.Please let me know if anything is required

**Comment by cwdata** [comment]
Hi @khmakoto ,
we are having the same issue. It seems not to be related to the onBlur event. We also see this without any event bound to the control. So it should be easy to reproduce.
Version used: office-ui-fabric-react@6.195.2
Browser: Internet Explorer 11 on Windows 10

**Comment by khmakoto** [comment]
@vipuliflex can you confirm your version of Fabric like @cwdata did so we can determine if this is an issue with Fabric 6 only or if it's also happening on Fabric 7?

**Comment by vipuliflex** [comment]
Hi @khmakoto Fabric version:6.176.3 browser:IE explorer 11

**Comment by khmakoto** [comment]
Hi @cwdata and @vipuliflex, I was able to repro this in [here](https://cdpn.io/khmakoto/debug/mdJbLyq/yoAZEOyzeLdr). However, this appears to be a bug with how Internet Explorer handles focus itself after re-renders and not a problem with our component. You can see this by the fact that you can blur by doing Shift+Tab in the example I'm attaching instead of just Tab or clicking away. Unfortunately, there is little we can do here, so I'd suggest giving feedback to IE11 itself. Let us know if there is anything else we can help with.

**Comment by cwdata** [comment]
For anyone who is also affected by this issue:
As a workaround we are now checking the browser. If we detect IE11 we show a normal TextField and for all other browsers we show the MaskedTextField. 

@khmakoto 
> However, this appears to be a bug with how Internet Explorer handles focus itself after re-renders and not a problem with our component.

I don't agree with you on that. As it may well be not the _fault_ of your component it is in fact a _problem_ with your component. We all hate IE11 and wish it had never been created, but to my knowledge IE11 is a supported browser in Office UI Fabric. That means, a component like MaskedTextField which is completely unusable in IE11 would fall under this support.
Given that, the UI fabric team should either
1) Open a support ticket with the IE11 folks to clarify what they need to change in IE to get it working
or
2) Change their code to something that also works with IE11. (Which should be doable because the other components of UI fabric can blur in IE11 without issues.)
or
3) At least change the documentation to tell people that MaskedTextField is not working with IE11

Telling us to call IE11 support is generally speaking in no way helpful. We haven't developed that component and therefore could not explain what exactly is going wrong and what they need to fix. They will just tell us that this is a problem of the component...

BTW: How where you able to reproduce the problem in codepen using IE11? When I open the link you provided I get an error message "unsupported browser" without any "Ignore and Continue" button. How can this be opened in IE11?

**Comment by khmakoto** [comment]
Hi @cwdata, my coworker @xugao found a fix that is now in. It should be ready for consumption starting tomorrow.

@xugao, could you backport this to Fabric 6?

**Comment by vipuliflex** [comment]
Hi @khmakoto Thanks for the fix.please detail out the steps need to be done for fixing the issue in our project

**Comment by khmakoto** [comment]
Hi @vipuliflex, you'd need to update to the latest version of Fabric, we're working on backporting this to Fabric 6 as well so customers still on 6 can have the fix as well.

**Comment by cwdata** [comment]
Thanks @khmakoto 
I can confirm that this is working for us now using IE11 and fabric version 6.211.3

**Comment by khmakoto** [comment]
Glad to hear that @cwdata!
