### ISSUE TITLE
Question:  Can't post my question on StackExchange... am I doing something wrong?

### ISSUE THREAD

**Issue by mikezimm** [OfficeDev/office-ui-fabric-react#11839]
I tried to post a question on Stack Exchange like the recommendation but seem to not know what I'm doing.

I filled out the question, got the message saying my question is ready to publish! went to the bottom, pressed the blue "Post your question" button and it says I can only post once every 90 minutes.  But I have not posted in months.  Just to be sure I hadn't published an incomplete question, I also went to my profile and checked.  Last question was October.  If there was a head-bang emoji in here I could use it.

After doing it a few dozen times I am quite frustrated.

**Comment by khmakoto** [comment]
Huh, sorry to hear that @mikezimm, I don't know what could be happening with Stack Exchange to make you do that. Feel free to post the question as an issue here. I'll answer to it without pointing you to Stack Exchange since now I have some background on this. Please close this issue when you open the new one with your question. Thanks!

**Comment by mikezimm** [comment]
Resubmitted as #11840 per khmakoto's suggestion.
