### ISSUE TITLE
DetailsList does not use SemanticColors "listText" property

### ISSUE THREAD

**Issue by miwlekli** [OfficeDev/office-ui-fabric-react#11896]
### Environment Information

- **Package version(s)**: ^7.60.0

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/miwlekli/pen/jOPOQoK

#### Actual behavior:

Using createTheme I set listText in the semanticColors property of a ITheme object to be a certain color and DetailsList does not use the listText property. Instead it appears that IDetailsRow is setting the non-header text to be neutralSecondary.

#### Expected behavior:

The text in DetailsList rows should use listText semanticColor. If this is not the case the documentation should make this clear that this is not the use case of listText.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by xugao** [comment]
@miwlekli - thanks for reporting! This slot is indeed not working as expected. We currently do realize that we have flaws with our semantic color definitions. In order to fix this, we actually need to add more slots to semanticColor interface. Since we are actively working on a better way of doing theming for our next major release, I hesitate to fix this now.

With that being said, we will improve our documentation [here](https://developer.microsoft.com/en-us/fabric#/controls/web/references/isemanticcolors) to warn people about this.

Let me know if you are completely blocked here

**Comment by miwlekli** [comment]
@xugao - Thanks for the response! This is not a blocking issue at the moment. I have found a workaround using css selectors to select `.ms-DetailsRow`.
