### ISSUE TITLE
Select  a row by only click the checkbox button in DetailsList

### ISSUE THREAD

**Issue by lvybriage** [OfficeDev/office-ui-fabric-react#11934]
#### Describe the feature that you would like added

In this [demo](https://codepen.io/xugao/pen/zYGGzYd),
could I select a row only by click the `checkbox` button?
and now I click anywhere in this row, it was selected. It's strange.

**Comment by xugao** [comment]
@lvybriage - not perfect but there is a way for you to do this. Example in [this codepen](https://codepen.io/kevintcoughlin/pen/WNvQKwe)

The solution is you define the rendering of each row:
```
onRenderRow={(props: any) => <DetailsRow {...props} data-selection-disabled={true} onClick={(ev?: any) => {
if (ev.target.classList.contains('ms-Check-check')) {
this._selection.setKeySelected(props.item.key, !this._selection.isKeySelected(props.item.key))
}
}} />}
```
The key here is to set `data-selection-disabled={true}` to disable selection control done in our code, and add your own event handlers to manage selections

**Comment by fernion** [comment]
With the proposed solution I had to add to the DetailsList the following prop (to prevent selection when navigating the list with the keyboard):
`selectionZoneProps={{
              selection: this._selection,
              isSelectedOnFocus: false
            }}`

But I still have two issues I am not sure how to solve: 
1. When there is no selection and the focus is on the first row, pressing up (goes to header) and down (returns to first row) automatically selects the row (checks the checkbox).
1. Cannot find a way to use space to select the focused row (we can use the enter key and the onItemInvoked callback, but that was not what I was aiming for, because we might need to use this callback for other actions)

Is there a way to solve this?
