### ISSUE TITLE
[Programmatic Access -AutoML-Recent Automated ML] Incorrect role is define for 'New Automated ML run' button under 'Automated ML' home screen.

### ISSUE THREAD

**Issue by kattepalli** [OfficeDev/office-ui-fabric-react#11993]
URL:-  https://master.ml.azure.com/automl/welcomenew?wsid=/subscriptions/ee85ed72-2b26-48f6-a0e8-cb5bcf98fbd9/resourcegroups/MT/workspaces/zhanxiaAML&flight=ignite

**User Experience:**
When standard controls from accessible technologies are not correctly define and if the user interface elements are not used according to specification, Assistive Technologies (AT) will not be able to gather information about, activate(or set) and keep up to date on the status of user interface controls in the content.

**Repro Steps:​**
1. Open Url: https://master.ml.azure.com/automl/welcomenew?wsid=/subscriptions/ee85ed72-2b26-48f6-a0e8-cb5bcf98fbd9/resourcegroups/MT/workspaces/zhanxiaAML&flight=ignite
2. Navigate to "Automated ML" option from left pane.
3. Home Screen or dashboard page will open.
4. Navigate to "Documentation and How it work Section  " section .
5. Navigate through all the controls appearing under "Documentation and How it work  " section.
6. Verify the issue

**Actual Behavior:** 
Incorrect role is define for 'New Automated ML run' button  under 'Automated ML' home screen.
Screen reader is announcing like: 'New Automated ML run' menu item.

**Expected Behavior:**  
Role should be define as 'Button' For 'New Automated ML run'

**Note:**
1. This issue also exits with Chrome + JAWs and Chrome + NVDA.

**MAS Reference:**
MAS 4.1.2 - Name, Role, Value

Accessibility Insights! - Identify accessibility bugs before check-in and make bug fixing faster and easier.

**External Bug Process:** If this bug belongs to external team, mark it as resolved/done and assign it back to the tester with notes on where to file/route the bug. For more information please use this Link.

![MAS4 1 2_Button](https://user-images.githubusercontent.com/30458420/74808241-73774580-5310-11ea-8633-bbb14efd6e89.png)

**Comment by kattepalli** [comment]
same issue can be found in your examples page:
https://developer.microsoft.com/en-us/fabric#/controls/web/commandbar

**Comment by aneeshack4** [comment]
Hi @kattepalli, thanks for reaching out to us! This is indeed showing up in our examples as well, not just in the Azure ML page:
![image](https://user-images.githubusercontent.com/4161791/74866628-0a8bcf80-5308-11ea-8dbf-63a8e3e1db14.png)
However, this was an intentional choice to set CommandBar's and it is done according to ARIA standards. You can see the explanation behind all this in the original PR that made this change https://github.com/OfficeDev/office-ui-fabric-react/pull/6421. Basically, CommandBar buttons are meant to be used in a menu which is why they have a `role` of `menuitem`.
