### ISSUE TITLE
Spin button losses its border for zoom 80 and 90

### ISSUE THREAD

**Issue by vineetrawat** [OfficeDev/office-ui-fabric-react#12023]
### Environment Information

- **Package version(s)**: (Reproduces on the Office fabric site https://developer.microsoft.com/en-us/fabric#/controls/web/spinbutton)
- **Browser and OS versions**: (Chrome  80.0.3987.87 , Windows 10)

#### Actual behavior:

When the zoom is set to 90 or less, for the following type of examples Stateful SpinButton and Custom Style buttons some parts of the border are not visible.  I noticed the same behaviour in my product.

#### Expected behavior:

The border should not get invisible

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low)
Normal

Products/sites affected: (if applicable)
Dynamics 365 Universal Resource Scheduling

**Comment by aneeshack4** [comment]
Hi @vineetrawat, thanks for reaching out to us. This doesn't repro for me on Chrome or Edge on Windows or on Safari on Mac but it does repro for me on Chrome on Mac... which is really strange it looks like it might just be a quirk of the browser/os combination because if you look at this comparison of Chrome on Mac where it does repro (the first) vs Chrome on Windows where it doesn't repro (the second), there's really no difference in the border styles... 
![image](https://user-images.githubusercontent.com/4161791/75079277-081ea680-54bd-11ea-9e06-85a371acfb0f.png)

**Comment by vineetrawat** [comment]
It is a consistent repro for me on the office UI site. I agree the border might be the same but the output is not desired. I assume has to do some other related styles what I am not sure. But somehow I noticed this only for this control on my form.

![image](https://user-images.githubusercontent.com/17751166/75087027-0a4e2880-54f0-11ea-9b2c-391d8801da3e.png)

**Comment by xugao** [comment]
@aneeshack4 - i can repro this bug. but `TextField` doesn't repro. i will look into a fix

**Comment by aneeshack4** [comment]
@xugao Ok thank you! I still can't repro... when I compare the border styles in Inspect they all look identical across browsers....

**Comment by xugao** [comment]
@vineetrawat - this problem only repros in Mac + Chrome and related to [sub-pixel rendering](https://www.chenhuijing.com/blog/about-subpxiel-rendering-in-browsers/#%F0%9F%91%9F). 

Even though there is a way to fix it (by moving from simply setting border to after content with border), the fix can potentially be a breaking change for users who use `styles` prop today to overwrite the border style. 

Unfortunately I cannot justify making the fix here. Let me know if you strongly disagree, otherwise I will close the issue as a won't fix.

**Comment by vineetrawat** [comment]
@xugao Somehow I see consistent repro on machine Win 10. Can someone in your team do a screen share with me on this? I will also check with others in my team if they also have a repro on their machines.

It's not a blocking issue but rather a dent in terms of quality of UI controls delivered.

Maybe with this we should consider creating a new control. This way those who are looking for a fix can switch to the other version.

**Comment by xugao** [comment]
chatted with @vineetrawat offline. This problem happens with specific screen resolution. in his repro case, it's 1920x1080. Given that the UI looks quite bad, and it's a popular resolution and it impacts different browsers, I am to make a PR to fix this
