### ISSUE TITLE
DetailsList Documentaion not linked in controls overview page, fabric ui web

### ISSUE THREAD

**Issue by sumanthapamagar** [OfficeDev/office-ui-fabric-react#12031]
The DetailsList Link in the Fabric UI web overview page does not work.

https://developer.microsoft.com/en-us/fabric#/controls/web.

**Comment by khmakoto** [comment]
Hi @sumanthapamagar, thanks for filing this issue! I can definitely see that the link is not navigating anywhere when clicked. We'll fix this as soon as we can!

**Comment by aneeshack4** [comment]
So the DetailsList link on the Controls page isn't directing to anything - because it's a button without a link whereas the other control names are all links with hrefs:
![image](https://user-images.githubusercontent.com/4161791/75379184-d1180e80-5889-11ea-9389-8fa1e49b2cc5.png)

It's due to the use of subPages in web.tsx: https://github.com/OfficeDev/office-ui-fabric-react/blob/master/apps/fabric-website/src/SiteDefinition/SiteDefinition.pages/Controls/web.tsx#L43 @ecraig12345 is looking into this further. The same issue is happening for Announced also.
