### ISSUE TITLE
Role menuitemcheckbox is not present for Toggle

### ISSUE THREAD

**Issue by priagarw** [OfficeDev/office-ui-fabric-react#12071]
Role menuitemcheckbox is not available in IToggleProps for cases when a Toggle is used inside a menu

#### Actual behavior:

menuitemcheckbox is not available

#### Expected behavior:

menuitemcheckbox should also be present

**Comment by SavannahBourgeois** [comment]
To add a little more context, we would like IToggleProps to expose "role" so we can set the role. Right now in Toggle.view the role is always set to 'switch' which generally works and is good as the default. However since we also have toggles in menus, we need to also be able to set 'menuitemcheckbox' as the role as well.

**Comment by xugao** [comment]
agreed. we should add 'menuitemcheckbox' to https://github.com/OfficeDev/office-ui-fabric-react/blob/9c8bdb25734312d3b3c3c8d34e22f65d54ce4653/packages/office-ui-fabric-react/src/components/Toggle/Toggle.types.ts#L112
