### ISSUE TITLE
ContextualMenus: Add support for sorting of items during render

### ISSUE THREAD

**Issue by ajaypantangi** [OfficeDev/office-ui-fabric-react#1252]
It would be great if we could pass rank/order to contextual menu items. This would enable scenarios where menu items are fetched asynchronously.

**Comment by hross** [comment]
You shouldn't need any modifications to the existing context menu to re-order by rank/order. Because React is using keys to keep track of your DOM state, you just want to re-render the context menu with a new set of items in the order you want. [Here is an example codepen where I re-render the context menu with a new item at a random position every time](http://codepen.io/pogostick_snowman/pen/KWmqyp).

**Comment by micahgodbolt** [comment]
@ajaypantangi does this answer your question?

**Comment by ajaypantangi** [comment]
@hross I agree with you. But in our case, we have a wrapper (similar to your codepen example, but our async menu-items popup while the context menu is still open) that keeps track of these menu-items and calls re-render every-time there is a new resolved menu-item. The problem we have is the wrapper must expose different props and then convert it to IContextualMenuProps every-time. If fabric controls supports rank, then the caller will be able to pass in menu-items in any order, rather than having a wrapper and ordering ourselves.
