### ISSUE TITLE
React Router support discussion

### ISSUE THREAD

**Issue by fantua** [OfficeDev/office-ui-fabric-react#1315]
I want to discuss issue with React Router support. In CommandBar/ContextualMenu/etc. there is `href` prop, but it's doesn't work with React Router. Now I'm handling `onClick` event and then call router `push` method. But it's not a good solution, because it's not a link, I can't open this in new tab/copy link/etc. in browser.

What is the best way to implement this? 

My vision is:

```js
onHrefRender?: (item: React.ReactNode, anchorProps: any) => React.ReactNode;
```

and using: 

```js
import { Link } from 'react-router';
//...
{
    key: 'homepage',
    name: 'Home',
    onHrefRender: (item, aProps) => <Link { ...aProps } to="/index" >{ item }</Link>
};
```

**Comment by dzearing** [comment]
I don't totally understand why they made the Link component for react-router, which generates DOM, rather than a utility to return an href or onClick handler that they can interpret. Is there a method in react-router to generate an href for a normal link? I can't find one in their documentation.

e.g. this would make sense to me.

```tsx
import { routeHref, routeClick } from 'react-router';

<IconButton href={ routeHref('/index') } />
<NavItem onClick={ routeClick('/index') } />
```

In this case the router can work as expected, but you can use whatever presentation you'd like.

We have logic in the BaseButton to use an anchor if there is an href, otherwise a button. That way anchors have the consistent anchor behaviors, like ctrl/cmd-clicking and status bar on hover, while non-href based things don't. But you can have them look consistent.

This is what we want to standardize on for all clicky components, so the Link, *Button, ContextualMenuItem, NavItem, etc are just variants of the base button. React-router fights against this because it wants to own the DOM element too, which adds confusion regarding the right way to handle this.

One option is to have a mode for all buttons that is "presentation only" which renders the presentation of the button without the A or the BUTTON wrapper... Then you can wrap that in a Link:

```tsx
<Link to={...}><IconButton presentationOnly /></Link>
```

**Comment by dzearing** [comment]
For container components like ContextualMenu and Nav, no matter what, the child render methods should always be override-able via onRender* IRenderFunction overrides, allowing you to support something like this.

**Comment by fantua** [comment]
>  Is there a method in react-router to generate an href for a normal link?
There is [createHref](https://github.com/ReactTraining/react-router/blob/v3/docs/API.md#createhrefpathorloc-query), but it's do this:
```js
console.log(this.context.router.createHref('/home'));  // /home
```
Generate only path, and doesn't handle click on `a` or something like this.

I need this only for ContextualMenu/CommandBar, Buttons I always cover via Link. 
So we can add `onHrefRender` for  ContextualMenu or add rendered Item (React.Node) to `onRender` via param, to allow me cover Item via Link.

**Comment by fantua** [comment]
@dzearing I think afterRender* for `ContextualMenu` will resolve this.

```js
afterRender?: (renderedItem: React.ReactNode, item: any) => React.ReactNode;
```

If this ok, I'll create PR.

**Comment by cschleiden** [comment]
@fantua @dzearing I think we should change the `ContextualMenuItem` `onRender` prop to follow the the `IRenderFunction` convention of passing in the `defaultRender` function.

**Comment by fantua** [comment]
@cschleiden looks like that is exactly what I need!

**Comment by dzearing** [comment]
@fantua @cschleiden I'd love all onRender* methods to follow the IRenderFunction convention and would gladly welcome that change.

That said; I don't think it will improve the Link usage. Link will still want to render the A tag, so rendering a nested BUTTON or A inside of an A doesn't work correctly in the browser.

But, I could be wrong. So If you'd like to convert it to onRenderItem: `IRenderFunction<IButtonProps>` I think that would be awesome!

**Comment by fantua** [comment]
I can't convert `ContextualMenuItem` `onRender` prop to `IRenderFunction`. Because `IRenderFunction` accept only 1 param which always is `item`, but `ContextualMenu` render methods need more params.

```js
private _renderNormalItem(item: IContextualMenuItem, index: number, hasCheckmarks: boolean, hasIcons: boolean): React.ReactNode {
    if (item.onRender) {
      return [item.onRender(item)];
    }
    if (item.href) {
      return this._renderAnchorMenuItem(item, index, hasCheckmarks, hasIcons);
    }
    return this._renderButtonItem(item, index, hasCheckmarks, hasIcons);
  }
```

How override this to `IRenderFunction `?

**Comment by fantua** [comment]
@dzearing @cschleiden how to solve this?

**Comment by vertonghenb** [comment]
Any thoughts on this issue? It's quite something fundamental. I'd love to pitch in if we know the direction were heading with this.

**Comment by cschleiden** [comment]
@fantua You could have something like `IContextualMenuItemRenderProps` that groups all of these props

**Comment by blrchen** [comment]
So what is the suggested way to use fabric react nav and react-router together?

**Comment by davidhenley** [comment]
Bumping so this doesn't get closed.

**Comment by micahgodbolt** [comment]
I know this is a long time coming (especially for such a small change). But this codepen using React Router will work once the new release is pushed out tonight.

There are a few styling differences, but nothing too horrible. I'll try to update once the code is released.

https://codepen.io/micahgodbolt/pen/EOVXGQ?editors=1010
