### ISSUE TITLE
DocumentCardActivity not alternating colors for initials

### ISSUE THREAD

**Issue by donschuy** [OfficeDev/office-ui-fabric-react#1332]
### Bug Report

- __Package version(s)__: (fill this out)
office-ui-fabric-react 2.5.2
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No
Requested priority: (Blocking, High, Normal, Low) 
Normal
#### Describe the issue:
DocumentCardActivity is a component to render avatars in a document card.  It is missing the logic in Persona that calculates an initials display background color based on the person name and instead always renders the background with the primary color.

#### Actual behavior:
Renders the initials background in the primary color.

#### Expected behavior:
Leverages the same logic used in Persona to alternate the initials color background color.

**Comment by mikewheaton** [comment]
Let's consider using actual Persona components here, instead of recreating that component. Other than the size being smaller I don't think there's any difference. Another option to consider would be creating a FacePile variant for this "two stacked personas" view, and to use it within the DocumentCard.

**Comment by dzearing** [comment]
@donschuy should be fixed now.
