### ISSUE TITLE
Purpose of FocusZone?

### ISSUE THREAD

**Issue by rickyp-ms** [OfficeDev/office-ui-fabric-react#1349]
Going to the documentation of FocusZone 
http://dev.office.com/fabric#/components/focuszone

You get a lovely "FocusZones are awesome" type description but it doesn't actually explain what the best usage of a focus zone is. So...
 Is the purpose to replace tabbing in general and start a new design to use arrow keys to move from element to element? Basically this means I should be able to navigate around the whole application using arrow keys instead of tab. So should I wrap my SuiteNav, LeftNav and Page content in a FocusZone even though they are not conceptually similar objects?
Is the purpose to make groups of similar objects (e.g. ul elements> easier to navigate?

**Comment by dzearing** [comment]
No, you should not wrap your app in a focus zone. 

The tab key is normally meant to transition between areas of intractability. By default, every individual hyperlink and button is considered a tab stop. In cases of lists of items or buttons, this may not be the desired intention. 

For example, if you had a command bar with commands, above a list of items, it would be more intuitive to tab between zones rather than individual items. You could then tab to the list, select some items, shift tab back to the command bar, arrow to the command, and press enter.

By default, the browser would make you tab through every individual row, all the way back to the command bar. This just wouldn't work. Hence you need code to create a "Zone", to track the active item, and to ensure other items aren't part of the tab stop. This lets a component act as a single tab stop, even though it may have multiple buttons or anchors.

Doing this would involve a lot of code. You'd need to handle keyboarding events. You'd need to push tab indexes to the right links. Instead of doing that, you can just wrap a bunch of links/buttons with FocusZone. This creates a simple consistent implementation for this behavior.

If that helps we can update the docs

**Comment by rickyp-ms** [comment]
That makes sense. I would update the docs with possibly a more complicated scenario where there is a general command bar, a list of items, and then each list item has tabbable content. I feel that this is not only more common but also extends the point that even though the list item has content that you could "FocusZone" you should leave it tabbable.

Thanks David!
