### ISSUE TITLE
Version 2.10.5 includes .ts files which should not be there and which breaks building

### ISSUE THREAD

**Issue by wobba** [OfficeDev/office-ui-fabric-react#1397]
### Bug Report

- __Package version(s)__: 2.10.5
- __Browser and OS versions__: Windows

#### Priorities and help requested (not applicable if asking question):

Requested priority: (High) 

#### Describe the issue:

I'm adding Office UI Fabric to my react project with *npm --save install office-ui-fabric-react*. When trying to use the components I get errors like:

```
Module parse failed: C:\repos\react-archiving-app\node_modules\office-ui-fabric-react\lib\components\Image\Image.Props.ts Unexpected token (3:7)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (3:7)`
```
#### Actual behavior:
For many of the Props types there are .ts files in the folder, which should not be there. Removing these and keeping the .ds.t files solves the issue.

#### Expected behavior:
No issues transpiling a component.

**Comment by dzearing** [comment]
Are you using webpack? I found that my modules had this: 
```js
resolve: {
    extensions: ['.ts', '.tsx', '.js']
  },
```

and switching the order to this helped:

```js
    extensions: ['.js', '.ts', '.tsx']
```

Basically having the .ts files there should not cause issues if you're prioritizing js over ts. If you tell webpack to prioritize ts over js, then it will become confused trying to parse ts files.

If this doesn't resolve your issue, let us know; the reason they're useful to have there is for autodocumentation utilities, but if they're causing issues, we'll find a way to tweak it.

**Comment by cschleiden** [comment]
@dzearing The content of the `.d.ts` and the `.ts` is basically the same, since it's the second issue on that topic, can't we just use the d.ts for the autodoc? 

https://unpkg.com/office-ui-fabric-react@2.10.5/lib/components/Button/Button.Props.ts  https://unpkg.com/office-ui-fabric-react@2.10.5/lib/components/Button/Button.Props.d.ts

**Comment by wobba** [comment]
Hi,
I tried to do as quick a solution as possible and went with https://github.com/wmonk/create-react-app-typescript. Could be that solution should be optimized to prioritize js over ts in webpack. I'll see if I can figure that out.

I noticed that SPFx web parts don't have the props.ts files when uisng yeoman, which is how I tracked this down sort of.

And having the d.ts is what I need in VSCode anyways when looking at defs.

**Comment by dzearing** [comment]
@cschleiden It's super complicated. What you're saying only applies to the Props. I need the same thing for the Examples to render source code. Here's what's going on:

for the `npm start` webpack.serve.config.js pipeline for the fast build, to get the autodocing working, I need a webpack way to access the string resources of those files.

I need that import to also work in the "library" scenario, e.g. the website app needs to import the raw string from a Props or Example file.

So the import needs to work in both scenarios. What would that look like?

Right now it looks like:
```ts
const DropdownBasicExampleCode = require('!raw-loader!./examples/Dropdown.Basic.Example.tsx') as string;
```

So... this isn't going to work with d.ts for examples because I need the actual source code to embed for the sample.

I could *maybe* use an alias and just include the src directory in the npm publish. Something like this:

const DropdownBasicExampleCode = require('!raw-loader!office-ui-fabric-react/src/components/DropDown/examples/Dropdown.Basic.Example.tsx') as string;

If I don't exclude src/**Props.ts and Examples.ts from npmignore.

**Comment by dzearing** [comment]
Hmmm i can give that a shot.

**Comment by cschleiden** [comment]
Examples I get, but they are usually in a separate folder so maybe we can include only them?

**Comment by dzearing** [comment]
I think we can do the same for both

**Comment by wobba** [comment]
Awesome reading the points on a toolstack I'm getting to grips with. Thanks for taking my input into your thought chain :)

**Comment by dzearing** [comment]
@wobba happy to help reduce friction. :) I've made a PR which should remove them on the next publish, which should avoid having to work around the issue.

**Comment by dzearing** [comment]
Will be published tonight, I think 1.10.6 (or 1.11.0 if we have some minor changes, which we may.)

**Comment by dzearing** [comment]
This is now resolved. No ts files in here:

https://unpkg.com/office-ui-fabric-react@2.10.6/lib/components/Breadcrumb/

**Comment by wobba** [comment]
Thank you @dzearing. Updated, tested, and minimal path to awesomeness achieved 🎆 :)
