### ISSUE TITLE
Documentation - Collect all form data from fabric components

### ISSUE THREAD

**Issue by hankanman** [OfficeDev/office-ui-fabric-react#1407]
Hi, what is the best way to collect all the values from multiple input components (TextField, Dropdown etc.) into a single array?

The OnChanged component member allows you to specify a function, but there is no way i can see to differentiate which input it is coming from, and each value returned can be different based on the component, TextField returns a string DropDown returns an object etc.

```
<TextField onChanged={this.getValues} label='Name' value={this.state.name} />
<Dropdown label='State' selectedKey={this.selectedKey} onChanged={this.getValues}
options={[
{ key: 'Active', text: 'Active' },
{ key: 'Inactive', text: 'Inactive' },
{ key: 'On Hold', text: 'On Hold' },
{ key: 'Complete', text: 'Complete' }
]} />

public getValues(value) {
     console.log(value);
}
```

**Comment by japrogramer** [comment]
I use too use an event and get the name of the component from the event but this components act differently, I still haven't seen an example login form that works with this components I have looked far and wide. I can only find Issues related to them that end up close due to a pull request but never a code example.

**Comment by japrogramer** [comment]
My solution is to have a function in the component that take a name and a value than sets that pair in the state and on submit, get the values from the state.
