### ISSUE TITLE
Multiple Message Bars have wrong margins

### ISSUE THREAD

**Issue by lupine86** [OfficeDev/office-ui-fabric-react#1409]
### Bug Report

- __Package version(s)__: 2.10.4 and latest
- __Browser and OS versions__: n/a

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Low

Products/sites affected: VSTS

#### Describe the issue:

When you have multiple Message Bars the margins are not correct.  The first and second Message have no space between them.  The 2nd and 3rd have 6 pixels.  So does the 3rd and 4th and so on.

#### Actual behavior:
No space between first and second MessageBar

#### Expected behavior:

Message Bars should have consistent spacing.  

### If applicable, please provide a codepen repro:

http://codepen.io/lupine86/pen/zZXvOZ

**Comment by mikewheaton** [comment]
The issue is caused by this style on [line 149](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/MessageBar/MessageBar.scss#L149):

```
// Add space between adjacent MessageBars.
.root + .root {
  margin-bottom: 6px;
}
```

That [combinator selector](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Combinators_and_multiple_selectors) targets any MessageBar that immediately follows another. So it should be `margin-top` instead of `margin-bottom`.
