### ISSUE TITLE
Dropdown: ellipsis for dropdown items with long strings

### ISSUE THREAD

**Issue by prashkan90** [OfficeDev/office-ui-fabric-react#1521]
### Bug Report

- __Package version(s)__: 2.10.3

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No.

Requested priority: Normal.

Products/sites affected: Visual Studio Team Services - Package Management

#### Describe the issue:

Dropdown items having long strings tend to overflow instead of being truncated:
https://postimg.org/image/bv32vad8r/

Adding a maximum width and ellipsis would be great.

**Comment by dzearing** [comment]
I think you're on an old build. Here's what I see:

http://codepen.io/dzearing/pen/YpVbYY?editors=0011

![image](https://cloud.githubusercontent.com/assets/1110944/25068941/281dd486-2227-11e7-8068-83794aae1b86.png)

It could also be that there is styling affecting it. You should be able to add a className to it and style the container to be a fixed with or have a max width.

**Comment by prashkan90** [comment]
@dzearing I actually meant the text oveflows when the dropdown is open. Screenshot from your codepen, slightly modified:
![image](https://cloud.githubusercontent.com/assets/10136561/25098345/05d321a6-235d-11e7-8ac7-4b5f80022682.png)

**Comment by micahgodbolt** [comment]
Ah yeah, we did similar work for tag picker. Seems we should do it for dropdown too.
