### ISSUE TITLE
DatePicker has 17px margin at the bottom

### ISSUE THREAD

**Issue by fengyue1013** [OfficeDev/office-ui-fabric-react#1594]
#### Describe the issue:

The DatePick component has 17px margin-button on `root` compoennt, which seeems strange.
If there are other compoents below the datePicker on page, the margin in between seems unreasonably large.

#### Actual behavior:

![datepicker](https://cloud.githubusercontent.com/assets/12523937/25373759/7dd797ec-29cd-11e7-9778-7bdbb687b08e.jpg)

**Comment by micahgodbolt** [comment]
Right now there is bottom margin on most inputs so that when placed into a form, there is proper vertical rhythm. You are correct that this causes problems when wanting to use the element on its own. We are looking to update all of the form elements to work without bottom margins, but this will be a bit of a breaking change so needs to be done all at the same time.
