### ISSUE TITLE
DatePicker: Header color and style needs to match the blue in the XD Spec

### ISSUE THREAD

**Issue by battletoilet** [OfficeDev/office-ui-fabric-react#1709]
### Bug Report

All versions. 

#### Describe the issue:

Update the design of date picker to match the style and color of the design inside the adobe XD toolkit.

**Comment by micahgodbolt** [comment]
Tried to dive into this quick, it's not a 1 line change.  Might take some refactoring to make it match our designs.

**Comment by johannao76** [comment]
Looks like this has been open since May. are you guys still doing anything here or can this issue be closed? The OWA calendar team is making a lot of styling changes to the component after discussions with Angela Allison and Ben Truelove. The pull request with our changes is here: https://github.com/OfficeDev/office-ui-fabric-react/pull/2565

**Comment by micahgodbolt** [comment]
yeah, these were old inconsistencies found between our design redlines and existing components. It's pretty out of date, so i'll close this up.
