### ISSUE TITLE
Dropdown - provide alternative experience for Office add-ins

### ISSUE THREAD

**Issue by Reezaali** [OfficeDev/office-ui-fabric-react#1728]
Office add-in task panes are not wide. Fabric's dropdown menu changes to a panel that slides in from the right. For Office add-ins, it would be great to have the option to choose which behavior the developer wants - the ordinary dropdown menu, or the panel that slides in. 

- __Package version(s)__: 2.6.0 & 2.24.2
- __Browser and OS versions__: IE11, Windows 10

Are you willing to submit a PR to fix? (Yes, No) - maybe.

Requested priority: (Blocking, High, Normal, Low) - Normal

Products/sites affected: (if applicable) - Office add-in developer experience.

Thanks,
Reeza.

**Comment by dzearing** [comment]
Here are the options:

```tsx
<Dropdown options={ ... } renderBehavior={ DropdownRenderBehavior.full | auto | mobile } />
```

or separate out a separate mobile friendly variant:

```tsx
<Dropdown options={ ... } /> (normal expected dropdown without the auto Panel)
<ResponsiveDropdown options={ ... } />
```

I like the second one better.

**Comment by micahgodbolt** [comment]
I agree with 2nd option. I never liked the idea that our base dropdown would sometimes render as a completely different component.

**Comment by Plotist** [comment]
It seems like Dropdown component have undocumented `responsiveMode` prop which determines whether dropdown will be rendered as Callout or not. 
Passing 2 or greater will cause dropdown to render as it should.
`<Dropdown
     responsiveMode={2}
     options={options}
   />`

**Comment by micahgodbolt** [comment]
Well, i took a quick stab at breaking these out, and it's looking pretty complicated, but doable. Here's the files I'd probably create.

![image](https://cloud.githubusercontent.com/assets/1434956/26225131/997dc2d6-3bda-11e7-8372-8fe7bec2c773.png)

Since both panel and dropdown versions share the same list items and render functions, it seems to make sense to break content into it's own component. This will allow us to create a dropdown.panel that uses the same content/render methods as the dropdown itself.

So now that we have 2 components that render the same content/render functions, we can create a responsive component that flips between the two depending on screen width.

This is a bit more complex than just turning the panel on and off, but it would support a lot more scenarios as well.

**Comment by Reezaali** [comment]
I can't comment on the number of files you need, but if that implements what @dzearing mentioned above as the 2nd choice, that would be great! Thank you!
