### ISSUE TITLE
DetailsList, Selection: I need way to tell DetailsList which item is selected

### ISSUE THREAD

**Issue by martlaboloa** [OfficeDev/office-ui-fabric-react#1741]
1)**You pass Selection to DetailsList, and then select items with mouse**, _what i want is that:_ you render DL with items already selected, without user interaction, like when it renders there is already item(s) selected. one way to do it is that after creating selector for DL, you invoke setKeySelected(or setIndexSelected) method on that selector, but the problem is that only after DL constructor stuffs items that you passed to DL into Selection(which also you passed to DL), that you can invoke those selection methods(setKeySelected, setIndexSelected), so you have to create selection first and then you pass it to DL and then DL's constructor runs, and now you can call those methods on Selection object but you already passed Selection to DL, so what you need is that you(as component who is rendering DL) need to invoke method only after constructor of your child runs, i tried to do it in lifecycle methods but didnt word, it needed to forceUpdate DL because what you are changing is inside of Selection, so props of DL does not change, ofcourse selection changes but only it's internal stuff, so rerender of DL does not accour, and forceUpdate does not look like most correct way. so maybe there should be way to tell DL which items is already selected, like you give props to DL which tell it which items are selected and it selects them itself, or maybe you give that props to selection and DL read's those props and selects items after it stuffs all items to Selection(with **setItems**, it is internal method of selection).
2) on the related note, can i use setItems method of selection, myself to stuff items in it  and then call selection methods? that not good way either but it solves problem, anyway feature of preselection items  should still be added

**Comment by dzearing** [comment]
The `selection` object has change events which the `DetailsList` observes. If at any time, before or after render, you called `setItems` or `setIndexSelected` or any of the selection methods, the `DetailsList` should render the correct thing.

Whenever your set changes, and you're managing the `selection` object yourself, you should call `setItems` with the new set of items. After that, you can take the opportunity to call selection changing methods. 

If you are doing this while the DetailsList is rendered, you may also want to suppress the change events so that you don't cause unnecessary re-renders. You can do this using the `setChangeEvents(isEnabled)` method to turn them off/on.

Does this help?

**Comment by martlaboloa** [comment]
yes that helps, thanks. As I understand I can use setItems even through detailsList manages it too.
