### ISSUE TITLE
change button color

### ISSUE THREAD

**Issue by oknoorap** [OfficeDev/office-ui-fabric-react#1753]
I can't set button color on hover

```
<PrimaryButton className="ms-bgColor-orangeLight" text="My Button" />
```

**Comment by micahgodbolt** [comment]
To apply hover colors, you'd need to use the hover version

`<PrimaryButton className="ms-bgColor-orangeLight--hover" text="My Button" />`

The problem is that Primary button already has a hover color specified, so the winning style would come down to load order. Since load order is hard to control, you'd probably be better off writing your own styles. Those color class names are meant for styling unstyled elements, not fabric components. 

```
<style>
  .my-Component .my-Button:hover {
    background-color: $ms-bgColor-orangeLight;
  }
</style>

<div classname='my-Component'>
  <PrimaryButton className='my-Button' text="My Button" />
</div>
```

This gives you the best possible control, scopes your changes to your use case, and makes sure that your specificity is higher than ours.
