### ISSUE TITLE
Hard to override inner styles of TextField

### ISSUE THREAD

**Issue by YusongLiu** [OfficeDev/office-ui-fabric-react#1754]
Previously we could use `inputClassName` to override the inner style of TextField.

Now we added `fieldGroup` div between the outer div and inner input:
[`<div className={ css(styles.fieldGroup, isFocused && styles.fieldGroupIsFocused) }>`](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/TextField/TextField.tsx#L153)

It becomes not elegant to override styles like border for TextField.

**Comment by dzearing** [comment]
@YusongLiu can you provide an example where you want to override the styles? I want to make absolutely sure we understand the exact use case before committing to a design improvement.

Recently we added a `borderless` flag to turn off borders. This would be a better approach rather than reaching into sub elements and styling them individually.

**Comment by YusongLiu** [comment]
Oh great! Currently I am trying to override the border which could be done with `borderless`. No issue now.
