### ISSUE TITLE
If we have large text inside Textfeild, onblur the text is not displaying from starting and the ellipsis is also not displaying in Firefox and Edge browsers

### ISSUE THREAD

**Issue by shaikshavalis** [OfficeDev/office-ui-fabric-react#1761]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__:  Firefox and Edge

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) 
**No**
Requested priority: (Blocking, High, Normal, Low) 
**High**
Products/sites affected: (if applicable)
VSTS
#### Describe the issue:
If we have large text inside textbox and  user tabbed out of the text box then the text should be displayed from starting but it is remains where the cursor was . This is working fine in Chrome but not working as expected in firefox and edge.
 I tried using comp.setSelectionRange(0,0) but it seems not effecting  the component. 

#### Actual behavior:
Suppose if there is really a big text in the Text field and when user tabbed out (blur) then the text inside is displaying as is and the ellipsis is also not coming.

#### Expected behavior:

When user has large text in text field and tabbed out of the field , then text should be displayed from the starting and it should display ellipsis at the end. Which is working fine in Chrome but not working firefox and edge browsers.

**Comment by dzearing** [comment]
I don't see how this would even be normal priority, let alone high. this is not a visual bug, or a functional bug. Why mark this as high pri? Is there some functionality that is broken or visual misalignment?

This is the default browser behavior. On chrome, if you include an `input` element on your page and do what you said, it will reset to the start of the string. On Edge, it will leave the last section as visible without resting. Honestly I think I prefer the Edge behavior. But I'm also fine with the Chrome behavior.

Regardless, this is not something that should be fixed in Fabric.

**Comment by shaikshavalis** [comment]
I agree that it's a browser behavior, but I want to implement the expected behavior. Is there a way to implement that for the textfield component inline in my code . Can you please suggest me solution.
