### ISSUE TITLE
ChoiceGroup: Selected input does not set 'checked' attribute

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#1800]
### Bug Report

- __Package version(s)__: Latest
- __Browser and OS versions__: All

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

#### Describe the issue:

The ChoiceGroup component contains a hidden `<input type="radio">` element. When an item is selected, the input's `checked` attribute should be set.

#### Actual behavior:

The `checked` attribute is not used.

#### Expected behavior:

The `checked` attribute will be added to any radio button that is checked.

### If applicable, please provide a codepen repro:

http://codepen.io/dzearing/pen/rWWZPW

**Comment by cschleiden** [comment]
Maybe we should also set the `value` to `key` for each item? In your codepen all of them have `value` set to `"on"`?

**Comment by mikewheaton** [comment]
@cschleiden That's a good point, we should definitely give `value` some meaningful content.

**Comment by SpoonsJTD** [comment]
Is this an internal consistency issue, or does it actually cause issues? I made a modified version of the codepen here: http://codepen.io/SpoonsJTD/pen/gWVdjm that demonstrates an issue I am having where the selection click only registers every other time.

If you create a onChange handler, are you expected to take over management of the selectedKey as in http://codepen.io/dzearing/pen/rWWZPW? The code similar to my codepen was working in my project until I updated recently. I am just not clear if my codepen demonstrates a bug (and if it's the bug this issue was created for) or if it demonstrates a lack of understanding on my part w/r/t managing selectedKey.
