### ISSUE TITLE
Search box icon is misaligned 

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#1813]
### Bug Report

Are you willing to submit a PR to fix? (Yes)

Requested priority: (Normal)

#### Describe the issue:
The top example has an icon that is too high.

Expect: the icon in the top example should be vertically aligned with the text like the example below it.

Image to follow soon.

**Comment by mdahamiwal** [comment]
Doesn't look like a issue to me. Its using flex-box with centered vertically.

![image](https://cloud.githubusercontent.com/assets/12109362/26205784/6edb1ae4-3c00-11e7-8b18-754c088e6271.png)

**Comment by betrue-final-final** [comment]
I'm responding to a screenshot in another PR. We may want to check that code to see if it's regressing it.
![image](https://cloud.githubusercontent.com/assets/20363037/26206575/133a4c70-3b9a-11e7-8852-38a7d89e3de8.png)
The PR is https://github.com/OfficeDev/office-ui-fabric-react/issues/1811

**Comment by micahgodbolt** [comment]
As of master branch today
![image](https://cloud.githubusercontent.com/assets/1434956/26211748/22164d6c-3ba8-11e7-8b89-8511bfaedb0c.png)

![image](https://cloud.githubusercontent.com/assets/1434956/26211767/2d59eae4-3ba8-11e7-9126-2bc230fe98f4.png)


I don't love the lack of padding before the text, but it's certainly not as broken as that original image.

Btw, I wouldn't suggest adding padding to the text in all modes. The spacing is very specific in the spec and having the text flush left of the input was very intentional to get animations looking correct.

I'd either only add padding in high contrast mode, or remove the border all together.

**Comment by micahgodbolt** [comment]
Oh, this bug is more interesting than I thought. The box around the icon isn't actually on the icon element, it's the outline of the whole search box, but it appears to be collapsing due to a flexbox bug in high contrast mode or some craziness.
