### ISSUE TITLE
Breadcrumb - Issue with styling

### ISSUE THREAD

**Issue by nikhilexe** [OfficeDev/office-ui-fabric-react#1824]
Repro steps:

1) Browse to http://codepen.io/nikhilexe/pen/GmXoqZ?editors=0110
2) You can see one breadcrumb item
3) Now apply css on this
.my-custom-class {
display: inline-block;
}

Now with this, sometime it doesn't show the item itself or if you zoom in further then it vanishes.

Ideally it should always show one item. Not sure what display css causing issue.

**Comment by micahgodbolt** [comment]
putting inline-block onto the container messes with the way the breadcrumb measures the available space. Do you need to have breadcrumb set to inline-block for some reason? If you do, you might also need to set a width to it.

**Comment by nikhilexe** [comment]
Thanks Micah for the reply. Before breadcrumb I need to put icon and after that one textbox and all three needs to be in the same line, hence putting inline-block. I tried putting width but it didn't work for me. Maybe I am missing something here?

**Comment by micahgodbolt** [comment]
this is going to be tricky with the current code. Breadcrumb was built to be a block level element (expanding to fill up as much space as it could), so dynamically allocating space to it with inline-block, or flex-box is going to be difficult. 

We'll probably be redoing the breadcrumb eventually using overflowSet and resizeGroup, but I'm not sure when that's going to be.

The best option right now is probably to use the onRenderItem prop to pass in your icon and text box to the breadcrumb itself, so that those items are included in the width measurements.

**Comment by trevorsg** [comment]
@micahgodbolt We hit this as well, except in our case the Breadcrumb is a flex-item. We have content before and after the breadcrumb. As a stop-gap, can we add a prop that disables the auto-collapsing behavior for available horizontal space? Here is a PR for that: #1999

**Comment by micahgodbolt** [comment]
@trevorsg we've been wanting to rework the breadcrumb resizing logic to use resizeGroup, so i took this opportunity to do that. It reduces the component complexity quite a bit and allows you to override `onReduceData={ (data) => undefined }` so that it'll automatically display whatever you pass in (without any truncation).

Can you take a look and see if this works for you?

**Comment by trevorsg** [comment]
@micahgodbolt Super, thanks! I will try it out on Monday since I'm of the rest of this week.

**Comment by micahgodbolt** [comment]
Example of inline breadcrumbs using flexbox https://codepen.io/micahgodbolt/pen/ZEvwLXz?editors=0010
