### ISSUE TITLE
Slider: onRenderValue

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#1856]
```
<Slider
  label='Last Modified'
  min={ 1 }
  max={ 13 }
  step={ 1 }
  defaultValue={ 13 }
  onRenderValue={ (props) => {
    if (props.value == props.max) {
      return (
        'Anytime'
      )
    } else {
      return (
        `within last ${props.value} months` 
      )
    } }
  }
/>
```

**Comment by mikewheaton** [comment]
The request here is to add a new prop?

**Comment by micahgodbolt** [comment]
Yeah, I was just trying to append a string to the end of the value and realized I couldn't. Sure, I could create my own state object and change it when the slider changes, but that seems annoying just to tweak that string.

I could also see wanting to change the value when number is equal to max/min

**Comment by jair-cazarin** [comment]
why pass all props rather than just the current value?

**Comment by micahgodbolt** [comment]
because i might want to change the value to "end" if props.value == props.max

**Comment by jair-cazarin** [comment]
That makes sense, we just need to be careful in the implementation to pass a copy of the props rather than the actual reference so that we don't let external code inadvertently mutate the props object. I think ideally we would explicit pass the arguments that are needed like min, max, value. I'm not sure if min and max are needed because the same parent component that specifies the callback also specify those values but I guess it would be nice to have them there.

Get Outlook for iOS<https://aka.ms/o0ukef>
_____________________________
