### ISSUE TITLE
Fabric CSS styles not working in SPFX webpart

### ISSUE THREAD

**Issue by russgove** [OfficeDev/office-ui-fabric-react#1948]
Hi, I'm trying to use the fabric List component in an spfx webpart. 
The code below was taken directly from https://dev.office.com/fabric#/components/list
```
   return (
         <div >
          <div className='ms-ListItem is-unread is-selectable'>
          <span className='ms-ListItem-primaryText'>Title</span>
          <span className='ms-ListItem-tertiaryText'>Description</span>
        </div>
        )
```

The Title and description appear in exactly the same font. Is there something special I need to do to get the fabric css included in an spfx webpart?

**Comment by russgove** [comment]
OK, I got it working by including the following in my spfx webpart
require('../../../../node_modules/office-ui-fabric/dist/css/fabric.components.css');
require('../../../../node_modules/office-ui-fabric-react/dist/css/fabric.css');

So now the 'ms-ListItem-primaryText' and secondary text appear correctly. 
But after the change, my DatePickers no longer appear correctly.  The width gets set to 298.011px and the height to 16.9886px

Which css files need to be include and in what order?

**Comment by russgove** [comment]
I needed to remove all the require css statements. They broke the datepicker and the dropdowns on my page. 

So, back to my original issue...The css in office-ui-fabric-react does not contain any classes for  ms-listitem-primary text. Or anything for ms-listitem anything. 

How do we get these css  classes into an spfx webpart?

**Comment by Jahnp** [comment]
Hey @russgove, so sorry for the delay on this! 

There's a few things to work through here:
1. **fabric.components.css** is part of the much older Office UI Fabric, the latter of which is not under active development since it was separated into [Fabric Core](https://github.com/OfficeDev/office-ui-fabric-core) and [Fabric JS](https://github.com/OfficeDev/office-ui-fabric-js/)--see [this blog post](https://dev.office.com/fabric?id=1#/blog/blog-post).
2. **fabric.components.css**'s CSS classes are not supported or supplied in Fabric React. We strive to not supply global CSS classes in Fabric React since they're not a strong control contract and can conflict when multiple versions of a given library exist on a page simultaneously; such is the case with SPFx web parts.
3. Because of 2, **fabric.components.css** is not officially supported in SPFx since its classes conflict with Fabric React and can potentially conflict with other web parts using those classes. See this [document in sp-dev-docs](https://github.com/SharePoint/sp-dev-docs/blob/60f1a1259164d6e2c041f77cf3f58be86bd33b3f/docs/spfx/web-parts/guidance/office-ui-fabric-integration.md#currently-unsupported-features) for more details, as well as guidance & best practices on moving forward. If at all possible, it's *highly* recommended to use Fabric React components as they are rather than extracting their CSS styles to use standalone.

Also, @manishgarg1 (SPFx dev) as a heads-up here. Please clarify or keep me honest if any of this is inaccurate. I'm not the best expert on SPFx-specific guidance. :)

With this in mind, I'll go ahead and close this for now since this usage is not supported, but please feel free to re-open or clarify if this doesn't address the issues you're encountering.
