### ISSUE TITLE
Convert high contrast colors to system variables.

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#2115]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes)

Requested priority: (Normal) 

#### Describe the issue:

In a study done a number of years ago, but seems valid as things haven't really changed, is that a majority of high contrast users customize their colors to suit their specific needs. This means that if we don't support the system color variables which they change, we will be breaking their experience on the web. Up to this point, we could do nothing about it, but today we can.

Here's a codepen showing it in action. This works in Edge, Chrome and Firefox.
https://codepen.io/AmeliaBR/pen/JbaZLX

**Comment by kristoferbrown** [comment]
The handy codepen you mentioned here helped us use system variables to to assign high-contrast color borders to TagPicker items. It's as simple as just using one of these system color names as the color in a css rule like the following example. In order to close this ticket we'd need to replace all our existing high-contrast rules with rules like these.

```
  @media screen and (-ms-high-contrast: active) {
    border: 1px solid WindowText;
  }
```

**Comment by betrue-final-final** [comment]
@Jahnp, what would it take to do this? @phkuo ?
