### ISSUE TITLE
Question: Collapse GroupedList / DetailsList by Default

### ISSUE THREAD

**Issue by ThatCarterMcBride** [OfficeDev/office-ui-fabric-react#2176]
### Bug Report

- __Package version(s)__: 1.14.3, bundled in Sharepoint Framework

#### Question

Is there a way to have the groups in GroupedList / DetailsList collapsed upon mounting?

It doesn't seem like there are any available public methods to call on any of the components in the mounting cycle, and changing the `isAllGroupsCollapsed` in `groupProps` affects this?

**Comment by elliottsj** [comment]
You can have groups collapsed upon mounting by setting the value `isCollapsed: true` in any group passed through the `groups` prop.

**Comment by kristoferbrown** [comment]
@ThatCarterMcBride, feel free to reopen this issue if the previous comment did not resolve your question.

**Comment by didii** [comment]
This does not work if virtualisation is in place. Group headers that are far down will be mounted again when scrolled into view and will always be collapsed, no matter how you manipulated it before.

E.g.: open up the last group of the table, then the first one. When enough items are in the first group, the second will unmount due to virtualisation and will re-mount when visible again, thus re-applying the `isCollapsed: true`. For this to properly work you should keep the collapsed state of every group in the parent and pass it through which results in a lot of unnessary boilerplate code for such a simple feature.

My opinion is that if a `DetailsList` is using groups, they should always be collapsed by default. Groups are used primarily when a lot of data is present and having it collapsed by default will first give the user an overview of what can be found in the table before they start digging deeper per group.
When all groups are opened by default, a user is overwhelmed by only a small subset of the data and cannot have an overview of what (type of) data is present.
Also add into the assumption that groups are chosen smartly, a user should only be concerned of the data in a single group at the time.
