### ISSUE TITLE
Callout needs z-layering fine tuning

### ISSUE THREAD

**Issue by erjohnms** [OfficeDev/office-ui-fabric-react#2178]
Callout component doesn't allow for top level class name or fine tuning of its z-index. We have a layering situation where the callout of a background element appears on top of a modal dialog. It should be layered behind the modal dialog but on top of everything else and I don't see an easy way to control the z-ordering of this specific callout without impacting all callouts on the page.

I experimented with doNotLayer but that caused a lot of overflow issues and so didn't seem like a way to work around it.

I also don't want to mess with the z-layering of our modal dialog framework. So this is a feature request to give me a way to be able to specify a layer for this specific callout that places it in-between the two while still allowing callouts that belong to the dialog to appear on top of it.

Like this:

![image](https://user-images.githubusercontent.com/19472252/28086117-e5351b70-664b-11e7-8c2a-913fe9a2e406.png)

**Comment by micahgodbolt** [comment]
Yeah, `doNotLayer` controls weather the callout is placed into a 'Layer' component or just rendered directly into the DOM.

**Comment by vertonghenb** [comment]
Same issues with Fullscreen modes.

Example if you're using Fullscreen from "react-full-screen", the Tooltip, Contextmenu's etc everything that uses the Layer component are not shown since a fullscreen component requires the Z-index of 2147483647 (max) since the component are rendered outside the main div you'll have issues...

//No workaround (yet)
