### ISSUE TITLE
CSS broken in SSR?

### ISSUE THREAD

**Issue by VincentBailly** [OfficeDev/office-ui-fabric-react#2232]
### Bug Report

- __Package version(s)__: 4.19.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: Live Persona Card

#### Describe the issue:

While doing server side rendering we do not get any CSS for the fabric.React components. I have not found any documentation on how to do SSR with Fabric.React so it is hard to tell if I am missing something or if SSR is broken. What is the recommended way to get the CSS when doing SSR?

**Comment by dzearing** [comment]
Just curious, what exactly are you server rendering from the Live Persona Card experience?

The server rendering support has always been not great as it hasn't been a priority and mainly has been a pain to get working due to the sass pipeline, which has prompted the move to a better css registration system. But right now, I believe it is broken and we'll keep this open to track.
