### ISSUE TITLE
Directional icon fonts in IconClassNames are not mirrored in RTL

### ISSUE THREAD

**Issue by MLoughry** [OfficeDev/office-ui-fabric-react#2285]
### Bug Report

- __Package version(s)__: 4.21.4

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: Outlook Web

#### Describe the issue:

Per the [Fabric website](http://dev.office.com/fabric#layout), referencing certain directional icons from the style-sheet are automatically mirrored in RTL. However, this behavior was lost in the move to IconClassNames and the styles-in-script effort.

#### Codepen repro: https://codepen.io/MLoughry/pen/LjPxBY

**Comment by martellaj** [comment]
@MLoughry Are you working on a fix for this issue?

**Comment by MLoughry** [comment]
@dzearing, in a sync meeting, sounded like he actively didn't want this work done.

**Comment by martellaj** [comment]
Why's that? I'm mostly concerned about the "Back" icon facing the wrong way in RTL.

**Comment by betrue-final-final** [comment]
Most icons don't change, but ones that refer to direction and layout, like the back button, should...and the question mark in Arabic.

**Comment by martellaj** [comment]
FWIW, I fixed this for the back button in the share UI by using a CSS transformation in RTL.

**Comment by dzearing** [comment]
@MLoughry I misspoke on the phone call; Peter and I are talking about what it would take to have this be supported. I do think from a 3rd party perspective that it would be better not to think about this and just use the "back" icon and have it pick the right code or transform to render correctly in RTL. Otherwise we'd end up with inconsistent solutions.
