### ISSUE TITLE
Allow for right-aligned commands 

### ISSUE THREAD

**Issue by sbatbold** [OfficeDev/office-ui-fabric-react#2303]
Please support right-aligned commands for the command bar v2. It seems we need an "auto" width instead of an explicit width.

**Comment by micahgodbolt** [comment]
Can you give a visual example of how you'd want this to look? Do you mean all the buttons on the right, or individual buttons aligned right?

**Comment by sbatbold** [comment]
Hi Micah, 

Apologies for the delay here. We need an option so all the commands appear on the right of the page. 
![image](https://user-images.githubusercontent.com/18745503/29281292-47831240-80d3-11e7-9e46-0e4c3a662b1f.png)

**Comment by micahgodbolt** [comment]
if you have content on the left side already, just wrap the 2 in flex-box, and flex-grow:1 the left side, and the command bar will sit on the right side.

**Comment by sbatbold** [comment]
@micahgodbolt 
@nkirchem tried this and unfortunately I don't think it works =/ The CommandBar moves the commands into an overflow "..." menu when there is a flex-grow item to the left of it. He mentioned the Breadcrumb has the same problem, and that you have pending changes to the new CommandBar to resolve this issue. Maybe you can help us understand ETA for that work? I'd really like to preview with the commands right aligned.

**Comment by micahgodbolt** [comment]
if you want to do this today I'd suggest creating a new component that has your breadcrumbs on the left, and render some buttons with an overflowSet on the right (nothing needs to go into overflow). Wrap it up with flexbox and be done. You could even wrap the whole thing in a resizeGroup and handle what happens when the left and right side overlap.

Happy to give you a hand with the general architecture if you want. It'd look pretty similar to the new commandBar code.
