### ISSUE TITLE
[Checkbox] Label text not wrapping properly

### ISSUE THREAD

**Issue by nikhilexe** [OfficeDev/office-ui-fabric-react#2317]
I see checkbox label text not wrapping properly, see below images with different experience with different version. With 4.9.2 version it was working fine and in between it got changed. Is this expected?

**React Latest Version (4.24.0) (Not formatted Properly)**

![image](https://user-images.githubusercontent.com/25940082/28666458-03c9a81c-72e5-11e7-8579-ca03d62245e9.png)

**React Version ( 4.17.1) (Broken - Not showing Full Text)**

![image](https://user-images.githubusercontent.com/25940082/28670738-ae9bafbc-72f7-11e7-8621-1343e906b8a1.png)

**React Version (4.9.2) (Expected)**

![image](https://user-images.githubusercontent.com/25940082/28670780-d4add23e-72f7-11e7-844f-5ed5eedaded2.png)

Code Pen link: https://codepen.io/nikhilexe/pen/vJObEX

**Comment by erichdev** [comment]
Looks like the change in alignment occurred after this commit where Checkbox is now contained in a button, since button's default style is to center text https://github.com/OfficeDev/office-ui-fabric-react/commit/9440c73f17ce503100d8f908db0d44a5adac5b0a#diff-c67edd8cc40e32a606cf1597c95dad82

I believe it can be fixed by adding this style to `Checkbox.styles.ts`: 
```javascript
 label: {
           //...
           textAlign: 'left'
         }
```
