### ISSUE TITLE
Some icons for IconButton don't render

### ISSUE THREAD

**Issue by cobbs-totem** [OfficeDev/office-ui-fabric-react#2337]
If I create an IconButton with:

<IconButton iconProps={{iconName: 'Add'}} />

The "Add" icon shows up fine.  But, if I choose 'Delete', or 'TestParameter', for example, it will not render those icons.

I'm using release office-ui-fabric-react@4.25.1.  I've tried including a few different stylesheet versions, including 7.1 and 5.0.1, with no luck.

**Comment by micahgodbolt** [comment]
There was a mistake at one point putting Delete into the icon list. It should be 'Trash'. As for 'TestParameter', there are some icons in the icon font that are only supported via class names, and not added to fabric react yet (adding all the names adds a LOT of weight).

Here's a list of the currently supported icons in Fabric React

https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/styling/src/styles/IconCodes.ts

Probably in 5.0 we'll support subsetting icons so that you'll be able to provide your own custom IconCodes file. But we aren't there yet.

**Comment by cobbs-totem** [comment]
Great, thank you!
