### ISSUE TITLE
Dropdown: Add a prop for styling the dropdown down chevron button

### ISSUE THREAD

**Issue by melvsparks** [OfficeDev/office-ui-fabric-react#2369]
### Dropdown: Add a prop for styling the dropdown down chevron button
I would like to add a prop so the color of the down chevron can be changed.

#### Priorities and help requested:
Are you willing to submit a PR to fix? Yes
Products/sites affected: OWA Calendar

**Comment by micahgodbolt** [comment]
There are 2 routes for doing this, one would be to add onRenderChevron or something like that, so that you can pass in a custom icon with custom styles.

Or else (the more complete solution) would be to convert the component over to Glamor so that you can pass a styles param into the component

```
<Dropdown
  styles={{ caretDown: { color: 'blue'} }}
/>
```

Feel free to reach out if you're interested in implementing either approach. I'd be happy to help you with the process.

**Comment by melvsparks** [comment]
I would like to implement the more complete solution. I'm fairly new to this, can you send me some documentation for glamor?

Thanks for the help
Melina

________________________________

**Comment by dzearing** [comment]
@micahgodbolt Don't think we should recommend @melvsparks to convert the component to use glamor styling.

@melvsparks You can do this in css for now:

1. Add a `className` on your Dropdown. Let's call it `foo`.
2. Target `.foo .ms-Dropdown-caretDown` and add styling.

https://codepen.io/dzearing/pen/XgrRGX
