### ISSUE TITLE
Checkbox control not to design spec

### ISSUE THREAD

**Issue by suztocco** [OfficeDev/office-ui-fabric-react#2371]
### Bug Report

- __Package version(s)__: https://dev.office.com/fabric#/components/checkbox
- __Browser and OS versions__: Mac on Chrome and Safari

#### Priorities and help requested (not applicable if asking question):

**Are you willing to submit a PR to fix?** No

Requested priority: High

Products/sites affected: OWA calendar

#### Describe the issue:

The design of the checkbox control on the XD file shows a medium size font which matches the rest of the basic controls nicely. 

#### Actual behavior:

On the coded Fabric site https://dev.office.com/fabric#/components/checkbox and in the build for my feature the font is rendering small and looks very out of place with the rest of the composition. 

#### Expected behavior:

For the checkbox control font to be **ms-font-m**

Issue (see small font):
![screen shot 2017-08-02 at 12 45 51 pm](https://user-images.githubusercontent.com/20954039/28891838-b1bb6466-7780-11e7-9851-4c63ca2646a0.png)

![image](https://user-images.githubusercontent.com/20954039/28891865-c2ad121a-7780-11e7-8547-403fb829ec9f.png)

Expected:
![image](https://user-images.githubusercontent.com/20954039/28891881-d73e54aa-7780-11e7-9acd-cce92c4cce6d.png)

**Comment by micahgodbolt** [comment]
This bug was fixed just last week. It probably hasn't gotten out to the website yet. 

https://github.com/OfficeDev/office-ui-fabric-react/commit/21e9f3cb32e33e534faa8929d1301bd2adc8de8e#diff-ef49aa7eadc2f5217014f2b9ba1391d3

What version of Fabric are you using? 

It was fixed in 4.23.0

 https://github.com/OfficeDev/office-ui-fabric-react/releases/tag/office-ui-fabric-react_v4.23.0

**Comment by suztocco** [comment]
I am a designer so I do not know what "package" we are using. I can check with the developer.
