### ISSUE TITLE
[DetailsList] Make last column to grow to take whole horizontal space

### ISSUE THREAD

**Issue by ankitk94** [OfficeDev/office-ui-fabric-react#2436]
#### Describe the issue:

Not able to find way to make last column to details list to grow to take full width.
I was not able to find any property to make any column auto adjust to width. Also tried using flexbox, but not able to use it also because DetailsRow renders 2 children (checkbox and details row fields). detailsRowField is not taking whole width, while parent of detailsRowField is able to take whole width.

Due to above, following issue is also occurring on high contrast mode (taken from dev.office.com/fabric):
 
![image](https://user-images.githubusercontent.com/6390909/29114438-f7c0b10a-7d11-11e7-98a9-69597f7394f4.png)

An additional line is shown below header which are not being rendered

**Comment by Hardhik** [comment]
More on this: This issue is because the columns containing text( Name and Value) overlap the space intended for the horizontal line, if you try to reduce the height of those columns(or alternatively increase size for the row), the line is visible for the whole of row (which I think is the actual expected behavior)

Issue can be reproduced here: http://dev.office.com/fabric#/components/detailslist

1) Navigate to “Rendering custom item columns with sorting”
2) Open Developer tools and go to the details lists’ header with class “ms-DetailsHeader” and change the height property to 33px and notice the difference( we can see that the line now appears below the row)
![image](https://user-images.githubusercontent.com/2673006/30737007-a152cb24-9fa2-11e7-9f2b-7928231e01f4.png)
