### ISSUE TITLE
Possible bug, <Nav /> gives wrong behavior on *icon* and *onClick* attrs 

### ISSUE THREAD

**Issue by Aaron2Ti** [OfficeDev/office-ui-fabric-react#2518]
### Bug Report

- __Package version(s)__: "office-ui-fabric-react": "^4.30.0"
- __Browser and OS versions__: Chrome 60

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) 
Normal

Products/sites affected: (if applicable)

#### Describe the issue:

```html
        <Nav
            groups={
                [
                    {
                        links:
                        [
                            {
                                name: 'Home',
                                icon: 'Edit',
                                url: '',
                                links: [{
                                    name: 'Activity',
                                    url: '',
                                    icon: 'Edit',
                                    key: 'key1'
                                },
                                {
                                    name: 'News',
                                    url: '',
                                    onClick: (e) => {},
                                    icon: 'Edit',
                                    key: 'key2'
                                }],
                                isExpanded: true
                            },
                        ]
                    }
                ]
            }
            selectedKey={ 'key1' }
        />

```
#### Actual behavior:

1. The first menu 'Activity' has no icon.
2. The second menu is highlighted(selected).

#### Expected behavior:
1. The first menu 'Activity' has a mail icon.
2. The second menu should not be highlighted(selected).

**Comment by Aaron2Ti** [comment]
![screen shot 2017-08-16 at 5 43 08 pm](https://user-images.githubusercontent.com/13595/29357797-678833ac-82ab-11e7-8664-bb719a14e16c.png)

**Comment by MLoughry** [comment]
I did a bit of investigation. All of these issues arise from the unresolved differences between [`_renderAnchorLink`](https://github.com/OfficeDev/office-ui-fabric-react/blob/72c218322ac10247c6f2693d68abc2e3df9ba7af/packages/office-ui-fabric-react/src/components/Nav/Nav.tsx#L132) and [`_renderButtonLink`](https://github.com/OfficeDev/office-ui-fabric-react/blob/72c218322ac10247c6f2693d68abc2e3df9ba7af/packages/office-ui-fabric-react/src/components/Nav/Nav.tsx#L163).

`_renderAnchorLink` does not observe the `icon` property, which is why it doesn't show up for Activity in your repro

`_renderButtonLink` uses `CommandButton`, whereas `_renderAnchorLink` "rolls its own" for styling, and the two are not in sync. The `CommandButton` styles are what's rendering "News" in the themePrimary color.

As a separate issue, I'm not sure of the design intention when rendering items with and without icons side-by-side; whether we want to keep the text aligned with each other, or have the current effect you see in the repro.

If @mikewheaton or another Fabric designer can clarify the design intent of this component, I can resolve the differences highlighted in this bug one way or another.

**Comment by Aaron2Ti** [comment]
@MLoughry thanks a lot for your reviewing

**Comment by erichdev** [comment]
@Aaron2Ti Nav has had some refactoring and I can't repro this bug anymore. I'm going to go ahead and close this issue, please reopen if you continue to experience issues with it

**Comment by Aaron2Ti** [comment]
@erichdev thanks a lot
