### ISSUE TITLE
Drop down: regression of DropDown not opening up when rendered at bottom of its containter

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#2545]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: Chrome/Edge

#### Priorities and help requested (not applicable if asking question):

Requested priority: (High) 

Products/sites affected: (web parts property pane)

#### Describe the issue:

The drop down is used to open as "drop-up" when the DropDown is rendered at the bottom of page or its container.

#### Actual behavior:

(from: https://officedevcentersite-devx.azurewebsites.net/fabric#/components/dropdown)
![image](https://user-images.githubusercontent.com/7711735/29446170-40f37fd0-841d-11e7-8c0d-db445d589798.png)
The drop down opened at bottom with scroll bar, looks bad when there is not enough space after drop down control. (See CodePen at the bottom to see the case where it looks bad)

#### Expected behavior:

(from: https://dev.office.com/fabric#/components/dropdown)
![image](https://user-images.githubusercontent.com/7711735/29446183-5f65b046-841d-11e7-98d8-0b99918f238e.png)
The drop down opened at top.

### If applicable, please provide a codepen repro:

https://codepen.io/anon/pen/OjQyzp

Scroll to bottom and open the drop down.
Note: I assume codepen should be using the latest version.

**Comment by micahgodbolt** [comment]
This was an intentional change to make dropdowns actually dropdown (they were popping out to the side previously). I would support maybe popping up, but at some point the options will need to scroll to fit onto the page, so it's not 100% cut and dry.

**Comment by spplante** [comment]
I also have the same issue. When it was popping on the side like previously, at least the list would show you all the items. Now it does drop "down" but you lose half your items because the list overflows the bottom of the screen, which makes it impossible to select lower items.

This is definitely a bug to me...

**Comment by JllyGrnGiant** [comment]
+1 to @mshmelev 's example of the dropdown at the bottom of a page opening as an unusable artifact.

I have small real estate to work with in an iframe and I have a combobox at the bottom. The control is completely unusable because opening the dropdown gets that scrunched callout. It only opens upward once you've obscured part of the bottom of the combobox with the bottom of the page/iframe.

**Comment by micahgodbolt** [comment]
Fixed by #3719
