### ISSUE TITLE
Vertical Scrollbar in "new" Datepicker

### ISSUE THREAD

**Issue by LeopoldLerch** [OfficeDev/office-ui-fabric-react#2726]
With version 4.40 the Calendar in Datepicker was styled according to OWA. However, I do have now vertical scrollbars in my date-pickers. 

Seems to have to do with this style setting:

@media (min-device-width: 460px)
.holder_db7e99dd {
    width: 212px;
    height: 240px;
}

however, the font-size used is also coming from the picker.

**Comment by micahgodbolt** [comment]
What browser are you in, and can you provide screenshots?

**Comment by LeopoldLerch** [comment]
![image](https://user-images.githubusercontent.com/28888039/30096921-42a295ec-92db-11e7-85f6-a67c625c3447.png)

I tried in both IE and Chrome

**Comment by evfirs** [comment]
I can see the scroll bar even on your own demo site now (using IE11):
https://officedevcentersite-devx.azurewebsites.net/fabric#/components/datepicker

![capture](https://user-images.githubusercontent.com/16862501/30144805-1a8ff834-93c0-11e7-9d13-68b3e6d57592.png)

**Comment by LeopoldLerch** [comment]
on the mentioned dev-site, it shows the scrollbars also in chrome.

however, on official site 

https://dev.office.com/fabric#/components/datepicker

it works

**Comment by micahgodbolt** [comment]
I think the problem is due to the absolute positioning of the monthPicker and the optionGrid being too tall.

[cid:6006fa03-041e-42ab-882d-e8afe0cbef34]



If you remove the optionGrid height, the scrollbars disappear.


[cid:0cc106b4-b4ae-4ab8-abc9-f34aff4d9b6a]


Is it possible to not use absolute position for the two halves of the calendar? Flexbox would take care of it nicely without resorting to floats.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by dzearing** [comment]
@micahgodbolt Confused; if this is reproing in the demo site, don't we have a bug?

**Comment by evfirs** [comment]
There is a bug, demo site only one of the examples. We have repro on eDog as well.

**Comment by micahgodbolt** [comment]
@dzearing i was just pointing to the problem in the CSS that was causing this.
