### ISSUE TITLE
CommandBar: ContextualMenuItemType not being honored (e.g., not divider)

### ISSUE THREAD

**Issue by Kanupriya9898** [OfficeDev/office-ui-fabric-react#2749]
### Bug Report

- __Browser and OS versions__: (Chrome: 60.0.3112.113)

Requested priority: High

#### Describe the issue:

I am trying to use Divider for ContextualMenuItemType to insert a divider/splitter between two buttons on my commandbar as shown below in the highlighted color between two buttons. 

#### Actual Behavior:
I used divider but I am just getting a space between the two buttons and no divider structure.
I passed contextualmenuitem to command bar inside items so as to get the shown toolbar.
![divider](https://user-images.githubusercontent.com/31690904/30105532-86252cb8-9316-11e7-9cee-2180ba6747ef.PNG)

#### Expected behavior:

I want some visible splitter/divider between the two buttons in the highlighted space which is what should come up if I am using divider for contextualMenuItemType.
The following type of divider should come up between the two buttons.
![divider2](https://user-images.githubusercontent.com/31690904/30106329-b7b7fe52-9318-11e7-89c0-385d5371599d.PNG)

**Comment by cschleiden** [comment]
The documentation looks like it's supported while it's not. We should either update the docs or support it (probably the latter)

**Comment by magellantoo** [comment]
It looks like there are no plans to support this feature right now as CommandBar is being rewritten to give the user much more flexibility than the current CommandBar allows. For now, you can pass in a divider item with a custom renderer that renders a `VerticalDivider` component.

**Comment by chenxinyanc** [comment]
The bug seems to be reappearing in recent versions. (on v6.189.1 and v7.12.0). See chenxinyanc/fabric-test@3a35f26a6f8962ac9d2d2f0a714f881c43a4a981 . The code was

https://github.com/chenxinyanc/fabric-test/blob/3a35f26a6f8962ac9d2d2f0a714f881c43a4a981/src/app.tsx#L13-L21

The screenshots:
![image](https://user-images.githubusercontent.com/50703224/61627034-62e6ea00-acb1-11e9-9e86-e438809c872f.png)

I'm expecting there being a vertical divider between Item3 and Item4, but there is no more a button there.

However, the overflow menu seems to recognize the item type:

![image](https://user-images.githubusercontent.com/50703224/61627011-54003780-acb1-11e9-8a59-b411b8126b90.png)
