### ISSUE TITLE
Missing Rocket Icon

### ISSUE THREAD

**Issue by smoralesd** [OfficeDev/office-ui-fabric-react#2761]
### Bug Report

Using ms-Icon--Rocket doesn't render the Rocket icon
```typescript
<i class="ms-Icon ms-Icon--Rocket" aria-hidden="true"></i>
```
- __Package version(s)__: 1.0.0 (commit hash: 635eb7474f7c71379dd52989736112786a9114aa)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

#### Describe the issue:

Using ms-Icon--Rocket on an *i* tag doesn't properly render the Rocket icon (it doesn't render anything at all).
I think the issues is on this [file](https://github.com/OfficeDev/office-ui-fabric-react/blob/b4eee571f31db3c0950938e40aafea9313f73003/packages/styling/src/styles/IconCodes.ts), where rocket definition is missing. In contrast, the rocket icon is being defined in the office-ui-fabric-core repo in this [file](https://github.com/OfficeDev/office-ui-fabric-core/blob/master/src/data/icons.json#L853)

#### Actual behavior:
Rocket Icon not being rendered

#### Expected behavior:
Rocket Icon should be properly rendered

**Comment by dzearing** [comment]
Unclear how you're actually rendering icons. If you're using the ms-Icon--* class names, you're using fabric-core. If you're using the `<Icon iconName='Rocket' />` component, then yes, that would likely be fixed in fabric-react 5.0.0.

**Comment by smoralesd** [comment]
I tried two ways, using _i_ tag
```typescript
<i class="ms-Icon ms-Icon--Rocket" aria-hidden="true"></i>
```
and using the Pivot + PivotItem components
```typescript
<Pivot>
    <PivotItem linkText='My Files' itemIcon='Rocket'>
        <Label>Pivot #1</Label>
    </PivotItem>
</Pivot>
```

Both ways work if I use, let's say, "Emoji2" or "Globe". And both fail if I use the "Rocket".

**Comment by chryw** [comment]
@smoralesd Could be you have an older version of fabric and this is a new icon. Could you try updating to the latest version 4.43.0 and see if you can get the Rocket icon? I had older version where I couldn't find the Rocket icon, but I was able to get it after I update. Someone indirectly asked me the same thing today and I have a feeling that was you 😄 

@dzearing btw I also had the same guess like @smoralesd that the Rocket icon isn't listed [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/b4eee571f31db3c0950938e40aafea9313f73003/packages/styling/src/styles/IconCodes.ts). Turned out it doesn't matter once I updated to 4.43.0, but maybe you meant to have new icons listed there?

**Comment by smoralesd** [comment]
@chryw We're currently using 4.35.1003. I'll try the update and see if that fix my issue. Thanks for your help.

**Comment by erichdev** [comment]
@smoralesd This has been fixed in Fabric 5, please reply if any issues remain
