### ISSUE TITLE
List: Focus handling is not correct when focused item not in view

### ISSUE THREAD

**Issue by cschleiden** [OfficeDev/office-ui-fabric-react#2791]
Repro steps: 

1. Select/focus an item near a page boundary:
![image](https://user-images.githubusercontent.com/2201819/30232565-88b9f98c-94a5-11e7-8d4b-df510be4cd15.png)

2. Scroll down using the mousewheel:
![image](https://user-images.githubusercontent.com/2201819/30232570-9380f8fc-94a5-11e7-917d-68be7867900d.png)

3. Press cursor down

**Expected**: Item 10 is focused/selected
**Actual**: Item 80 is focused/selected and scrolled into view, since that is the next focusable element that exists in the DOM: 
![image](https://user-images.githubusercontent.com/2201819/30232589-acf4c61a-94a5-11e7-8491-e1cf5762e238.png)

**Comment by dzearing** [comment]
The issue is that the List has not materialized items 10-19, so FocusZone moves from item 9 to 80 which happens to be the next focusable thing.

Two possible solutions:

1. Fix List to always materialize the page before and after the page which contains focus. This has some added performance cost of keeping more elements materialized than we do now. Maybe that's ok.

2. Fix FocusZone to behave differently in this case. For example, pages containing materialized items could be decorated with `data-is-virtualized=true`. If FocusZone spots this, it scrolls to the focused element, waits for a delay, and then attempts the focus move requested. This would give time for the List to materialize the content. But it would be a little error prone in the case that the delay is not long enough for the content to materialize.

**Comment by cschleiden** [comment]
I don't really like 1., I think we are already rendering too much.. we might do that async, but we should render only what we absolutely need. 

2. sounds better except for the delay. Some richer interaction between List and FocusZone might be better. Something like this, for example:
https://codepen.io/cschleiden/pen/ZJgGeV?editors=1011 

When the List is rendered within a `FocusZone` it registers with it and the `FocusZone` can instruct it to render a specific/the next item, for example.
