### ISSUE TITLE
Build: change tsconfig.json "lib" to prevent usage of IE11-incompatible APIs

### ISSUE THREAD

**Issue by MLoughry** [OfficeDev/office-ui-fabric-react#2987]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: Outlook

#### Describe the issue:

During the 5.0.0 beta, there was an IE11 runtime break. I'm not sure if it was due to a missing API or something else; but I know Outlook ran into issues where we inadvertently used APIs that IE11 did not implement. We resolved the issue by changing out `tsconfig.json` to only use libraries that IE11 implements

```json
        "lib": ["es5", "es2015.promise", "dom"],
```

I started to look into this myself, but ratholed on @types dependencies that don't play well with these restrictions. So, I need to discuss with interested parties whether to make changes to DefinitelyTyped packages, or change dependencies here.

**Comment by dzearing** [comment]
Hmm. It seems ok to me? I'm not sure enough to make a call. I know that there was a recent issue with the website because some samples were assuming promises existed, but don't in ie11. We added the es6-promise polyfill to resolve.

I am not sure that adding es2015.promise to the lib would be a good idea. Correct me if i'm misunderstanding, but we really want a project to fail when referencing promises unless they've added the polyfill or intend for the caller to have it.

**Comment by MLoughry** [comment]
You can eschew the `es2015.promise` lib if you use other typings, but remembering to include the Promise polyfill is ultimately an orthogonal issue. However, the configuration is currently:
```json
    "lib": [
      "es2017",
      "dom"
    ],
```
which means it will allow several APIs (including `Object.assign()` that don't exist in IE11.
