### ISSUE TITLE
Changes not reflecting in component after changing state if state filed is an object

### ISSUE THREAD

**Issue by Sachin077** [OfficeDev/office-ui-fabric-react#3086]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/sites affected: TFS

#### Describe the issue:

Changes are not reflecting in component after changing the state if the state field is an object. An object is passed by reference and due to this in the below line of code (from **DetailsList.tsx, componentWillReceiveProps** function), the if statement condition becomes false since both newProps.items and items have the updated fields. And due to this, the render function in the Columns does not receive the updated props and render is not called.
   ```
if (newProps.items !== items) {
      this._selection.setItems(newProps.items, shouldResetSelection);
    }
```

#### Actual behavior:

Changes not reflecting due to render function not called on updating state.

#### Expected behavior:

Render function should be called with updated props.

**Comment by dzearing** [comment]
The DetailsList will not re-render everything, by design, by simply mutating something in an item in the array of items. I don't see how the code snippet is relevant to that though.

Your options: 

1. Use immutable data. If you want to update the items, use a new array.
2. Call force update if you mutate the array or set without creating a new one.

If this doesn't help, please reopen this issue and provide a small sample. Ideally in a codepen.

Here's a simple codepen you can fork to recreate your problem:

https://codepen.io/dzearing/pen/XRvXoL
