### ISSUE TITLE
Incompatible with create-react-app

### ISSUE THREAD

**Issue by jckh1234** [OfficeDev/office-ui-fabric-react#3098]
### Bug Report

- __Package version(s)__: 5.7.0
- __Browser and OS versions__: IE11/Chrome Win7

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable)

#### Describe the issue:
Run npm install office-ui-fabric-react remove create-react-app installation

#### Actual behavior:
I created a simple project using create-react-app script. And then I install office-ui-fabric-react.
npm --save install office-ui-fabric-react
It output:
+ office-ui-fabric-react@5.7.0
added 7 packages, removed 1024 packages and updated 16 packages in 108.641s

Then I run "yarn start", out put

yarn start v0.27.5
$ react-scripts start
'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.

Checked the node_modules folder, I found it removed the react and react-dom related files.

#### Expected behavior:
run "yarn start" will launch the react sample app

**Comment by dzearing** [comment]
You probably should have run `yarn add office-ui-fabric-react` rather than `npm --save install office-ui-fabric-react` if you're using yarn (i believe create-react-app uses yarn by default if you have it installed.)

Just something to look for: installing fabric-react shouldn't cause 1024 packages to be removed. :)

I know with a fairly high degree of certainty that create-react-app works with fabric-react here since I just did it yesterday. Try installing using yarn. I think it will work better! :)

If you continue to have issues, please feel free to open another issue.
