### ISSUE TITLE
Unable to control height of dropdown control

### ISSUE THREAD

**Issue by mdmdakbar** [OfficeDev/office-ui-fabric-react#3298]
Unable to control the height of dropdown control using the className prop passed. Need to depend on HtmlElement span to change the height.

Please refer the code pen link to get more details. 

Products/sites affected: (if applicable) VSTS

Codepen Link -
https://codepen.io/anon/pen/KyVPpa

**Comment by Jahnp** [comment]
This looks like a CSS load order issue. The custom CSS you have is being loaded before the CSS for the dropdown is injected into the page, so its `height` setting takes lower priority:

![image](https://user-images.githubusercontent.com/307118/35260153-b60a8fa8-ffbe-11e7-9baa-877776401e6c.png)

Since the root classname is munged, you can't force a higher priority on the custom class name without 1.) using `!important`, which should be avoided if possible, or 2.) configuring the CSS to load after the component styles. 

Really though, dropdown should be adapted to use `@customizable` so you can safely pass in a style object with overrides rather than fragile CSS-only patches. @micahgodbolt, dumb question--this isn't possible today for dropdown, is it?

**Comment by micahgodbolt** [comment]
Everything there seems to have classnames, it's just a question of making a style specific enough, right? As for styles prop, we haven't converted dropdown over yet. It's a big array of buttons, and we're still working on getting button working how we'd like it to.

**Comment by jordandrako** [comment]
@micahgodbolt This seems to be as easy as removing height from the root element and putting it on the `.ms-Dropdown-title` element, possibly via a prop. Any issue with me implementing that fix or should I hold off touching Dropdown?

**Comment by micahgodbolt** [comment]
if it's just a specificity issue combine your classname with the provided classname like

.my-class-dropdown.ms-Dropdown{
  height: 10px;
}

this is why we try to make all selectors 1 classname only, so it's easy to override.

**Comment by micahgodbolt** [comment]
Dropdown is being converted via #5366 to css-in-js. This isn't a bug, but this conversion will make it easier to make these types of changes.
