### ISSUE TITLE
[Tooltip] Tooltip doesn't position correctly in IE

### ISSUE THREAD

**Issue by martellaj** [OfficeDev/office-ui-fabric-react#3411]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: ODSP

#### Describe the issue:

The tooltip doesn't position correctly, and it's reproducible on the Fabric website.

#### Actual behavior (IE):

![image](https://user-images.githubusercontent.com/1019478/32914025-0370f8b6-cac9-11e7-8b09-d747919345e4.png)

#### Expected behavior (non-IE browsers):

![image](https://user-images.githubusercontent.com/1019478/32913989-e136834c-cac8-11e7-8c5f-a16d9056cc4a.png)

**Comment by lambertwang** [comment]
Repro: https://codepen.io/anon/pen/goamNR

It looks like the tooltiphost's bounding rect is not being aligned to its inner elements correctly.
A solution could be to set the callout's target to an inner element of the tooltiphost or to ensure that a specific display style is set on the tooltip host's children. For example, on the Fabric website, setting the display style of button to block fixes the tooltip, but that is probably undesirable since that breaks how button works in a lot of other cases.
