### ISSUE TITLE
Icon Font Usage in Environments with Restricted Group Policies

### ISSUE THREAD

**Issue by jlgoodman** [OfficeDev/office-ui-fabric-react#3502]
I'm working in an environment with a group policy that blocks certain font embeddability settings. It completely blocks the current FabricMDL2Icons files, not just in my work, but also when I go to the [public Microsoft fabric site here](https://developer.microsoft.com/en-us/fabric) . Any possible solutions?

**Comment by aditima** [comment]
@Jahnp @dzearing - any suggestions for this one?

**Comment by Jahnp** [comment]
Hi @jlgoodman, sorry for the delay!

Assuming the app you're working on complies with the [Fabric assets license](https://aka.ms/fabric-assets-license), you can include copies of the icon fonts in a local CDN along with a copy of the license. Then, in the part of your app where you're making a call to `initializeIcons`, pass in the path to the folder for those fonts like this: `initializeIcons('https://my.cdn.com/path/to/icons/');`

See #2784 and the [@uifabric/icons](https://www.npmjs.com/package/@uifabric/icons) page for more details. Note again however that for legal reasons, this solution ONLY applies if your app extends or leverages a Microsoft platform, like Office Add-ins or SharePoint web parts. 

I'm going to go ahead and close this since there are existing solutions for this issue, but please @jlgoodman let me know if you still need help or believe there's an issue to address here. Thanks!
