### ISSUE TITLE
Feature Request: Allow to selectively disable days in Calendar

### ISSUE THREAD

**Issue by yosbelms** [OfficeDev/office-ui-fabric-react#3529]
Would be great if days could be selectively disabled by providing a predicate function or a list of dates to the Calendar component.

## Example use case

A receptionist books appointments using the app by selecting dates in a Calendar component. But she/he must take care of not booking in non business days(holly-days, Sundays ...). The system should not allow her/him to select those non business days by disabling those in the calendar.

## Proposal

1. By providing a predicate:
```ts
function isNotABusinessDay(date: Date): boolean {
    return isSunday(date) || isHollyday(date)
}

<Calendar disableDayIf={isNotABusinessDay}>
```

2. By providing a list of days:
```ts
const notBusinessDays: Date[] = [...sundays, ...hollydays]

<Calendar disableDays={notBusinessDays}>
```

I prefer the first proposal by far, for obvious reasons.

**Comment by aditima** [comment]
@lorejoh12 - seems like a useful ask. What is your though about this?

@betrue-final-final FYI...

**Comment by lorejoh12** [comment]
We evaluated this feature and while we appreciate the usefulness, it's currently low on our backlog. We'd love to do a code review for a PR though if another team has the bandwidth to pick this up!

Should be a fairly straightforward fix, since we already have a minDate and maxDate parameter, could follow the logic similarly with the styling and disabling but would have to update the DateMath utilities to allow for disabling individual days as well.
