### ISSUE TITLE
Clicking on search box clear button is closing the drop down.

### ISSUE THREAD

**Issue by aakash-johari** [OfficeDev/office-ui-fabric-react#3599]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: All browsers

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) VSTS Code/Workitem Search

#### Describe the issue:
We have a filter drop down which is a custom div which hosts the search box. When we click on the cross button to clear the text, the drop down closes. The reason is that the cross button doesn't have a tab index and the blur event doesn't get it as a related target which we use to decide whether we should close the drop down or not.

#### Actual behavior:

The related target is null in the blur event.

#### Expected behavior:

The related target should be the cross button.

**Comment by aakash-johari** [comment]
If we don't want to bring it the tab order, keeping the tab order as -1 also fixes the issue.

**Comment by KevinTCoughlin** [comment]
Thanks for the report @aakash-johari. I'm taking a look at this now.

**Comment by KevinTCoughlin** [comment]
@aakash-johari would a solution similar to [this Codepen](https://codepen.io/kevintcoughlin/pen/OZPYKP?editors=1010) work for you? Not sure we need to change anything in the library to achieve what you need.

Basically, only toggle the state of the Callout when blur is called on the search input & the click occurs outside.

**Comment by KevinTCoughlin** [comment]
Closing as I believe this can be fixed w/o a change in the library. The culprit seems to be the DOM structure on the website facing the bug (VSTS). I was able to write a similar working UI w/ slightly different DOM. If you feel like this is still a bug please re-open and provide a Codepen sample with the DOM structure you believe should be supported and we'll re-assess.

As always thank you for the report and for using Fabric 👍
