### ISSUE TITLE
Accessibility [Details List]: The first Focus is going on complete grid in Firefox, but going to the "select all" checkbox in other browsers (Chrome and edge).

### ISSUE THREAD

**Issue by Sachin077** [OfficeDev/office-ui-fabric-react#3626]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: Firefox

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: TFS

#### Describe the issue:

Accessibility: The first Focus is going on complete grid in Firefox, but going to the "select all" checkbox in other browsers (Chrome and edge).

#### Actual behavior:

The first Focus is going on complete grid in Firefox, but going to the "select all" checkbox in other browsers (Chrome and edge).

#### Expected behavior:

The first focus should go to "select all" checkbox in firefox too.

Focus going to complete grid (this is only happening in Firefox).

![capture1](https://user-images.githubusercontent.com/7456601/34287790-6fb92054-e70f-11e7-9bc1-d81a762c8322.JPG)

Focus going to checkbox.
![capture2](https://user-images.githubusercontent.com/7456601/34287791-6fe11a00-e70f-11e7-9f32-fbd6c4049a3d.JPG)

**Comment by lambertwang** [comment]
The focus is going to the ExampleCard in Firefox. This can be fixed by adding `tabindex={ -1 }` to the `ExampleCard-example` div.

**Comment by lambertwang** [comment]
This is an intentional feature of Firefox. Firefox treats scrollable regions as focusable areas, which is defined in the [HTML living standard](https://html.spec.whatwg.org/multipage/interaction.html#focusable-area). 

> The scrollable regions of elements that are being rendered and are not expressly inert.  

We know that this means that the behavior of example cards is going to vary from browser to browser. We feel that we should not change this behavior as it is defined in the HTML spec. I suppose you will have to wait until other browsers are caught up with the spec to have consistent behavior between browsers.
