### ISSUE TITLE
DatePicker: Does not call onSelectDate when field is cleared and isRequired is set

### ISSUE THREAD

**Issue by jjohnsen** [OfficeDev/office-ui-fabric-react#3716]
### Bug Report

- __Package version(s)__: Latest
- __Browser and OS versions__: 

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

#### Describe the issue:

When DatePicker is created with isRequired and allowTextInput set to true, onSelectDate is not called when the input for the date string is cleared.

If isRequired is set to false onSelectDate is called with null as date value

#### Actual behavior:

onSelectDate callback is not called.

#### Expected behavior:

onSelectDate callback is called with date set to null

**Comment by michaelangotti** [comment]
@jjohnsen Are you still willing to submit a PR for this? :)

**Comment by KevinTCoughlin** [comment]
@jjohnsen can you explain your use-case more? By setting `isRequired=true` it causes the DatePicker to require a date be selected to invoke the `onSelectDate` callback. If no date is selected i.e. `null` then it doesn't select the date because it is required. Instead it sets an error state. If you want to handle empty text input you can drop the `isRequired=true` and that will allow `null` values to be set as the date.
