### ISSUE TITLE
Less globals please

### ISSUE THREAD

**Issue by jonathaneckman** [OfficeDev/office-ui-fabric-react#3730]
Using window.FabricConfig is a pain in the butt. Please use something other than a global for configuration.

**Comment by battletoilet** [comment]
Can you explain your concern a bit more here?

**Comment by jonathaneckman** [comment]
Our environment forbids internal application code sending requests to external resources. By default, fabric is configured to pull fonts from a public CDN. I learned from #3024 and #2118 that I needed to override this with:

```
window.FabricConfig = {
  baseFontUrl: ''
};
```
I struggled to find a way to set this global in my existing app code and bundle it with webpack. I instead had to put it in a separate js file and reference it on the page before my apps bundled code. My feature request is to allow us to configure fabric in our apps entry or boot.

**Comment by dzearing** [comment]
Today, when we initialize the font faces, we do so in file scope, when we initialize the default theme. This makes it easy for consumers; you just import things, and because it gets pulled into the graph, it's done for you on script load. 

But with this in mind, if we initialize the wrong URL because you don't configure sooner, then we have a race condition. The global config was a way to ensure that the config is provided earlier than the code initializes.

The only way I can think of to avoid this is to never have code that initializes the fonts until you start using things. Or, to require the consumer to do the work (e.g. `import { initializeFonts } from ...`)

**Comment by dzearing** [comment]
Will track in #3881.
