### ISSUE TITLE
DatePicker: Use ECMAScript Internationalization API to localize DatePicker strings

### ISSUE THREAD

**Issue by MLoughry** [OfficeDev/office-ui-fabric-react#393]
Rather than have the consumer provide a whole host of strings for the DatePicker, it can all be done with ECMADate.toLocaleString. Then, the consumer need only provide the 'goToToday' string and the locale.

http://stackoverflow.com/a/18648314
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString

**Comment by dzearing** [comment]
The blocker on this one is that these aren't supported below IE11. We *could* provide a HOC that derives values and prepops the DatePicker's string callbacks so that if your minbar is IE11 it's easier.

**Comment by fpintos** [comment]
One additional issue to consider here is that applications like OWA allow the user to choose formatting options in its Regional Settings and it takes that into consideration when displaying things like the Month/Year in the header of the mini-month calendar.

For example, it might be tempting to format the header in [CalendarDay](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx) with `navigatedDate.toLocaleString(userCulture, { month:"long", year:"numeric" })` (assuming we were to pass the desired culture as a property), so we get the string with correct order (for example, in zh-MU the year comes before the month). However, it would still not know about the user's preference in OWA. We would get 'August 2017' in English, but if OWA's regional settings ask for dates to be formatted as "yyyy-MM-dd" then OWA is supposed to show '2017 August', as in fact it does today:
![image](https://user-images.githubusercontent.com/4239171/29695328-1cf346b8-88f7-11e7-91bd-f2c5a7769052.png)

So it almost sounds like we need to let the application do the formatting or we'll need to give a lot more options on how dates are formatted, in order to account for OWA regional settings.

**Comment by battletoilet** [comment]
Assigning to @johannao76, please free to assign to someone else or close it if it doesn't make sense anymore.
