### ISSUE TITLE
Split Button returns group of tabs instead of using the SplitButtonAriaLabel

### ISSUE THREAD

**Issue by divyagandhi01** [OfficeDev/office-ui-fabric-react#3934]
### Bug Report

- __Package version(s)__: NA
- __Browser and OS versions__: NA

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

#### Describe the issue:

The Standard Split button on office Fabric website returns a tab group called- "group".

#### Actual behavior:

The button is narrated as "group"

#### Expected behavior:

The tab group should use the SplitButtonAriaLabel

### If applicable, please provide a codepen repro:

Reproducible from office fabric website

**Comment by michaelangotti** [comment]
Hey @dzearing is there someone on your (new) team that can look at this one?

**Comment by dzearing** [comment]
@jspurlin is this expected?

**Comment by jspurlin** [comment]
@dzearing I wasn't aware of that prop and upon looking, it was introduced by https://github.com/OfficeDev/office-ui-fabric-react/pull/3430 . It looks like it's doing what it is supposed to do.

It's not exactly clear what is being described as the bug in this issue, but the role should be button and if the creator passes in a title or arialabel that will be used for the splitButton. Additionally, the creator can pass in an aria-roledescription to give a more specific role description (e.g. "split button") which gets replaced as the role when read out by screen readers who use that property (rs4 narrator, for example does this).


I think this is a by design bug, there's potential that the splitButtonAriaLabel prop should be renamed because it isn't clear that it maps to the menu launcher button...

**Comment by mikewheaton** [comment]
From @jspurlin's comment above, this doesn't seem to be a bug and there's not enough clarity of what's wanted to make it a feature request.
