### ISSUE TITLE
list navigates while panning with touch

### ISSUE THREAD

**Issue by Khushveerkaur** [OfficeDev/office-ui-fabric-react#4027]
### Bug Report

- __Package version(s)__: Latest
- __Browser and OS versions__: NA

#### Describe the issue:
Panning the list with touch (Surface, etc.) navigates to the item the finger was over.

#### Actual behavior:

Just pan the results list

#### Expected behavior:

On finger release, navigates to the item the finger was over.

### If applicable, please provide a codepen repro:
https://developercommunity.visualstudio.com/content/problem/125846/search-results-list-navigates-while-panning-with-t.html

**Comment by natalieethell** [comment]
Hey @Khushveerkaur thanks for submitting this issue! Just to clarify, when touch scrolling through a DetailsList, the expected behavior is to just pan the results list, but the actual behavior is that on touch, the item in the DetailsList is immediately focused, and in the case of VSTS, it navigates to the item. (by looking at the VSTS link, it looks like you've swapped the Actual and Expected behavior :) ).

This ask seems like a pretty big functionality change for DetailsList, so I'll take a closer look and figure out our best approach!

**Comment by micahgodbolt** [comment]
@ThomasMichon hey Thomas, can you take a look at this one as soon as possible. This bug makes detailslist on ie/edge pretty much unusable on touch devices (i conformed on my surfacebook that the issue is current).

**Comment by khmakoto** [comment]
Hi @Khushveerkaur, sorry for the long time it has taken to reply! This issue doesn't seem to repro for me anymore. Can you check if it is still reproducing on your side? Thanks!
