### ISSUE TITLE
[Nav] How can I set background-color for selected NavItem?

### ISSUE THREAD

**Issue by nguyentoantuit** [OfficeDev/office-ui-fabric-react#4076]
Hi ,
### Support

- __Package version(s)__: 5.55.0

In previous version (I am not sure which version it is) when we have a class name "is-selected", so I will base on that class to add custom css to specify background-color because I don't want to use default background color
![image](https://user-images.githubusercontent.com/6096518/36584532-ad1f802c-18ac-11e8-9b3c-7ccc06dca5e9.png)
In version 5.55.0 this class was removed and I don't see any way to set background color for selected item. Do you have any suggestion for me to set background color for selected NavItem?
![image](https://user-images.githubusercontent.com/6096518/36584731-8c9a5bdc-18ad-11e8-812b-cab5260f2889.png)

#### Expected behavior:
![image](https://user-images.githubusercontent.com/6096518/36584781-d0d15ed6-18ad-11e8-83d2-fe71fd25d4eb.png)

Thanks in advance,
Toan

**Comment by KevinTCoughlin** [comment]
The `.is-selected` selector seems to be available in `5.78.0`, I didn't check a prior version yet to see if it regressed between then and now. In latest it looks to be tricky to override the inner button of the `.is-selected` node's background-color as you're trying to do using CSS-only.

I attempted to do it in this pen: https://codepen.io/kevintcoughlin/pen/oqROxa

But the background style is set on the list item's inner action button node and hard-coded to that instance's selector. If you can somehow override the button style to have no background then you can get the behavior you want by overriding `.is-selected`'s background color. Otherwise the button background masks it.

Not yet sure if there's a way to override the action button's styles while using the `Nav` component.
