### ISSUE TITLE
Please tag releases in GitHub

### ISSUE THREAD

**Issue by daniel-white** [OfficeDev/office-ui-fabric-react#4145]
It would be helpful to know what has changed between different versions of the package. Can you please tag master when a new version is pushed to NPM?

**Comment by Jahnp** [comment]
Hey @daniel-white, what's the use case you have in mind? Each [release](https://github.com/OfficeDev/office-ui-fabric-react/releases) for each package is tagged already:
![image](https://user-images.githubusercontent.com/307118/36873339-042be626-1d5d-11e8-9560-871cf74e2378.png)

I'm going to go ahead and close this for now since as far as I understand it we already support this, but please let me if that's not the case.
