### ISSUE TITLE
request for shipping out "focus-border" mixin

### ISSUE THREAD

**Issue by fengyue1013** [OfficeDev/office-ui-fabric-react#417]
Sometimes in our project we want to use the `focus-border` mixin in file`office-ui-fabric-react/src/common/_focusBorder.scss`. Could you consider ship it out?

**Comment by ericthompson** [comment]
@fengyue1013 - do you mean to place it in [Fabric Core](https://github.com/OfficeDev/office-ui-fabric-core)? Just trying to make sure we understand what you mean by shipping it out.

**Comment by dzearing** [comment]
I am not 100% convinced it's a good idea to expose this yet. We need to have a clear stance on how to generally support focus rectangles correctly (because it's nuanced), but the issue i'm nervous on is how the mixin works. Some things i don't like:

* It messes with the element position to get the positioning of the rectangle correct. Unpredictable.
* It is a very specific rule that it creates, so it becomes messy to override.

**Comment by lijunle** [comment]
Hi, @ericthompson We want to consume the useful [`focus-border` mix-in](https://github.com/OfficeDev/office-ui-fabric-react/blob/b99a5cfa9b3bcb00520f95a639c8cc5181d29381/src/common/_focusBorder.scss#L3) in our project. We do not care about where they are placed.

From my understand, there are two ways to expose it:

1. Move it to fabric-core project.
2. Expose SASS files from fabric-react project.

Personally, I think the second way is better.

Currently, we are copy-paste-ing the mix-in code to our project. We think it is bad to do so.

**Comment by atneik** [comment]
I think it makes sense in Fabric-core and as Fabric-react already distributes fabric-core's sass/css it will be available to consume in projects.

**Comment by dzearing** [comment]
I believe this was exposed in fabric-core.

**Comment by mikewheaton** [comment]
It hasn't been moved to Fabric Core yet. This mixin is still only in Fabric React.

**Comment by dzearing** [comment]
Opened fabric-core issue to track there https://github.com/OfficeDev/office-ui-fabric-core/issues/853

**Comment by fengyue1013** [comment]
Thank you, David
