### ISSUE TITLE
DetailsList is setting empty aria-describedby attributes on the column resizing buttons in the header row.

### ISSUE THREAD

**Issue by niadak** [OfficeDev/office-ui-fabric-react#4372]
Details list is unnecessarily setting empty aria-describedby attributes on the column resize buttons in the header row.

![aria-attributes](https://user-images.githubusercontent.com/11937515/37959657-3f9e0800-31d1-11e8-8126-9cc6a8ea6aff.png)

**Comment by dzearing** [comment]
@ThomasMichon Did you add the tooltip support on these? I'm not sure.

**Comment by KevinTCoughlin** [comment]
@dzearing it looks like its been around for awhile, even before https://github.com/OfficeDev/office-ui-fabric-react/pull/2044/files#diff-f2d0127af8796463799f6b6dceeacbe9R227

Still ramping up here, but it seems like we only need to include `aria-describedby` when a tool-tip is being used for the column header which requires overriding `onRenderColumnHeaderTooltip`. Otherwise the `aria-labelledby` is enough.

Anyone have an example with tool-tips for the column headers implemented? If not I'll write it to get a better idea of the two states before I attempt to remove something that seems necessary in some cases.

**Comment by KevinTCoughlin** [comment]
As pointed out by @natalieethell this should be fixed with https://github.com/OfficeDev/office-ui-fabric-react/pull/4487 👍

**Comment by aditima** [comment]
Right, it should be fixed by https://github.com/OfficeDev/office-ui-fabric-react/pull/4487 . Closing this now. Please reopen if you see more issues here.
