### ISSUE TITLE
Sharepoint React Framework , office ui fabric css not getting applied on components

### ISSUE THREAD

**Issue by harshdamania** [OfficeDev/office-ui-fabric-react#4489]
Requested priority: Blocking

This is the current version of office ui fabric  referened in my package :
![image](https://user-images.githubusercontent.com/11780473/38454760-d2e8d088-3a8a-11e8-9466-2f7b1ba293d6.png)
I am using sharepoint react framework and have used List component : 
Code Link : https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/List/examples/List.Basic.Example.tsx
site link : https://developer.microsoft.com/en-us/fabric#/components/list

But the css is not getting applied ?
![image](https://user-images.githubusercontent.com/11780473/38454774-3c32f244-3a8b-11e8-9bbe-6f2e42f7d149.png)

Is there any specific approach for uploading it

#### Expected behavior:
![image](https://user-images.githubusercontent.com/11780473/38454780-68c3ade4-3a8b-11e8-91d9-1dd3cbb1cbf9.png)

This is very urgent, any help will be appreciated

**Comment by Jahnp** [comment]
Hi @harshdamania , the List control you linked to does not contain any styles on its own. From its description: 

> List provides a base component for rendering large sets of items. It is agnostic of layout, the tile component used, and selection management. These concerns can be layered separately.

However, if you just want to use the styles from the `ListBasicExample` in your ow implementation of `List`, you can import them like this:

```tsx
import 'office-ui-fabric-react/lib/components/List/examples/List.Basic.Example.scss';
```

Just know that you'll need to make sure your implementation matches the DOM from that example. 

@manishgarg1 as FYI since this seems related to SPFx.

I'm going to go ahead and close this, but please let me know if this doesn't resolve your issue.
