### ISSUE TITLE
is there any doc without typescript?

### ISSUE THREAD

**Issue by smilank3** [OfficeDev/office-ui-fabric-react#4500]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) 

Products/sites affected: (if applicable)

**Comment by manishgarg1** [comment]
Hi @smilank3, No, I don't think so. @dzearing, do we have non-typescript docs? Typescript has worked very well for us. It helps us manage and scale the code better. @smilank3, any specific reasons you do not want to use Typescript?

**Comment by KevinTCoughlin** [comment]
I could see the benefit of adding more JSDoc style comment blocks to help with intellisense and auto-generated documentation via a tool like [typedoc](http://typedoc.org/). Not sure if that's the ask here. If it is, it'd have to be scoped and not done for the sake of having comments IMO. My .02.

**Comment by kenotron** [comment]
Currently I'm working with the [Rush](https://github.com/Microsoft/web-build-tools/wiki/Rush) folks to come up with a really good story here. They are actually creating a new project called "tsdoc" that MAY eventually find its way back to Typescript itself. So we're aligning with that. I just came back from vacation and will be tackling this area!

**Comment by dzearing** [comment]
Unfortunately at this time we don't have plans to release JavaScript-only usage examples. There is nothing prohibiting pure JavaScript usage, though you would need a babel setup to consume it.

Everything already does use jsdoc comments, so that should not be an issue AFAIK. The real concern might be not using `PropType` declarations.

If you use create-react-app and npm install Fabric, it should be straightforward to import the components as shown in the examples, as long as you strip types on variable declarations and props.
