### ISSUE TITLE
[Accessibility][DocumentCard] IDocumentCard needs to support .focus()

### ISSUE THREAD

**Issue by daweffe** [OfficeDev/office-ui-fabric-react#4571]
### Bug Report

- __Package version(s)__: 5.54.0
- __Browser and OS versions__: all

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No
Requested priority: Normal

Products/sites affected: Wasabi
#### Describe the issue:

I need to be able to set focus on a the IDocumentCard object returned by the componentRef callback on DocumentCard.

**Comment by jordandrako** [comment]
DocumentCard is a `div` which is not normally interactive. If you need it to have focus, it should probably be wrapped in an interactive tag like `button`.

eg
```tsx
<Button ref={ buttonRef } >
  <DocumentCard ... />
</Button>
```

Then you call buttonRef.current.focus()

**Comment by jordandrako** [comment]
@oengusmacinog  Should we implement the `as` pattern here?

**Comment by mikewheaton** [comment]
@jordandrako Has there been any more discussion about the 'as' pattern since you worked on this? It's not clear from the issue what the next steps are here and if it should be assigned to Shield.

**Comment by dzearing** [comment]
This component is a bit of a mess; it's rendered as a div ...rather than a button when its interactive. But why not a hyperlink ever?

My preference would be for it to use the "button" as a root type and extend button props. Button itself should have "as" support. But I would wait on our button refactor first there.

So...short term? add focus support. It would take about 5 minutes to resolve this.
