### ISSUE TITLE
memoize: add the ability to timeout or manually flush internal cache

### ISSUE THREAD

**Issue by aappddeevv** [OfficeDev/office-ui-fabric-react#4606]
under office-ui-fabric-react/packages/utilities.

Provide the ability to manually flush the cache or timeout the cache. It already has a counter autoflush, but a timed or manual flush would be very helpful when using this function.

**Comment by dzearing** [comment]
Thanks for the suggestion. I was hoping to just get rid of it. Here's what we found:

memoizeFunction works fine with literals and immutables. With mutable objects and arrays however, it will cause friction.

It also is causing issues with SSR rendering, where we want to render the correct rules every time, without short circuiting the styling system which is listening for rules to render. So it breaks SSR.

Flushing would help the SSR scenario. But I'd rather just remove the utility usage, as changing it to do a deeper comparison would be harmful to perf and add unneeded complexity.

If you would like to make a PR to add a very small reset function, we're happy to take PRs. But not planning at this time to actively invest in memoize due to the issues above.

**Comment by aappddeevv** [comment]
Is this still the recommended way, however, to handle reducing processing with merge-styles given the issue you mention above?
