### ISSUE TITLE
DetailsList  component do postback when clicking on selection checkbox. 

### ISSUE THREAD

**Issue by Solwo** [OfficeDev/office-ui-fabric-react#462]
It seems related to #369, the DetailsList has a pretty checkbox column implemented as `<button>` tag. This button have 'submit' behaviour.  When I click on the checkbox, the page submits to the server. Clicking on the rest space in the row works as excepted, the row become selected and event raised.   

```
<DetailsList items={ this.props.items }
                             selectionMode={ SelectionMode.single }
                             onActiveItemChanged={ this.onActiveItemChanged } />
```

My dirty and temporary workaround: wrap control with form and catch the submit event. The onActiveItemChanged event raises before submit, so it works.

```
class SearchResult extends BusinessLogicBase {
    constructor() {
        super();
        super.bind('onActiveItemChanged', 'onSubmit');
    }

    onActiveItemChanged(item, index, ev) {
...
    }

    onSubmit(e) {
        e.preventDefault();
    }


    render() {
        return (<form onSubmit={this.onSubmit}>
            <DetailsList items={ this.props.items }
                         selectionMode={ SelectionMode.single }
                         onActiveItemChanged={ this.onActiveItemChanged }
            />
        </form>);

    }
}
```

Reproduced on 'Advanced DetailsList of 5000 items, variable row heights' example on the https://dev.office.com/fabric#/components/detailslist page:
1. configure single selection mode. while you clicked on the rows, selection works as expected  - you can select only one row.
2. click on the row's checkboxes. - you can select several rows. however, clicking on the rest space of the row still selects one row.

**Comment by dzearing** [comment]
To distill this:

1. Clicking on check buttons acts as a form post when details list inside a form. This is because the event isn't being canceled even though it is handled. Repro here:
http://codepen.io/dzearing/pen/WovrqY?editors=0010

2. In single selection mode, clicking on the checkboxes still allows multiple selection.

3. Also noticed that pressing space bar isn't canceling the event.

I believe these are regressions from another bug fix. Will investigate.

**Comment by dzearing** [comment]
Fixed.
