### ISSUE TITLE
[DatePicker] controlled component

### ISSUE THREAD

**Issue by lrecknagel** [OfficeDev/office-ui-fabric-react#4630]
_I am not sure if this is a bug or a feature request so i explain it with the bug template anyway_

### Bug Report

- __Package version(s)__: tested >= 5.3.0
- __Browser and OS versions__: MacOS Chrome 65, (I think also all others)

#### Describe the issue:

When i pass a value to the DatePicker component it renders correctly. When I then click on the DatePicker to select a other date and its not allowed by any reason and its not set as value for the DatePicker the Picker renders it anyway.

#### Actual behavior:

It renders its internal state beside if the given value is different.

#### Expected behavior:

I thought when I pass a value it should render this value and only showing the value and not its internal state.

### If applicable, please provide a codepen repro:

[![Edit v0kywjv207](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/v0kywjv207)

in the repo i only log the selected date, but doesn't set it to the component state. The component displays it anyway. Its got weirder if I set a harcoded date with setState.

**Comment by lorejoh12** [comment]
Let me see if I understand the issue correctly:

Create a DatePicker and pass a specific value- in our case, pass the value Apr 30th 2018.
![image](https://user-images.githubusercontent.com/8549582/39453569-496e3556-4c8b-11e8-9b97-cf7b30161af7.png)

Click the datePicker, it opens up:
![image](https://user-images.githubusercontent.com/8549582/39453581-564bf718-4c8b-11e8-8f96-9563a3466e8c.png)

Select a new date: lets select May 2nd 2018:
![image](https://user-images.githubusercontent.com/8549582/39453596-6896346a-4c8b-11e8-98fb-ea69572868dc.png)

and your expectation was that, since you passed a value property of Apr 30th 2018  the control continues to display the value Apr 30th 2018, despite firing callbacks for onDateChanged with the newly selected May 2nd, right?

Perhaps a more clear name for the "value" would be "initialValue". This is similar to how the TextField component works. You can pass an initial value, but the component is designed to update based on user input. If you really, really don't want user input to update the display, your current solution of binding to onDateChanged and setting the value back to a specific date will work, although it will fire a re-render. We don't have any plans to implement a way to make the displayed value always the same as the given value.

**Comment by lrecknagel** [comment]
@lorejoh12 I am arguing on a bit different case:

* I pass: Apr 30th 2018 as value (from my state, store, etc.)
* Then a user open the dialog and want to select: May 2nd 2018
    * BUT: the logic in the frontend / backend disallow that because maybe a rule exists: Only dates < May 2018 (for any reason)
    * So the DatePicker should continue displaying the Apr 30th 2018 because the change was not accepted.

* I think its not the initial value by default because changes are allowed but not any. Its more like a controlled component, that the DatePicker show always its passed value prop.

Hope its clearer explained now :)
