### ISSUE TITLE
Some components are exporting unrelated things and expanding the consumer bundle size.

### ISSUE THREAD

**Issue by lijunle** [OfficeDev/office-ui-fabric-react#4651]
When I am investigating the bundle size issue, I found that, the some components are exporting some unrelated things from its `index.ts` file. This is causing the bundle size expanding of my final bundle - I am not using the unrelated thing.

For example,

`Selection` exports `SelectionZone`

https://github.com/OfficeDev/office-ui-fabric-react/blob/6909a93aa53c4d4699eb0be03d25a37555f114a2/packages/office-ui-fabric-react/src/utilities/selection/index.ts#L3

`DetailsList` exports `Selection` (which export the `SelectionZone` implicitly)

https://github.com/OfficeDev/office-ui-fabric-react/blob/6909a93aa53c4d4699eb0be03d25a37555f114a2/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.tsx#L34

And maybe more.

If I directly imports the interfaces/components from inner path, I get a big bundle reduce. See [this](https://onedrive.visualstudio.com/SPPPlat/_git/sp-client/pullrequest/136475?_a=overview) (need permission).

Ideas?

**Comment by dzearing** [comment]
SelectionZone and Selection are closely tied, and makes sense.
DetailsList depends pretty deeply on Selection, and likely users will want to use it.

The imports you linked will indeed cut down bundle size, but are a very bad idea. We can only guarantee the contracts we know about, and from a file import perspective, we can guarantee the top level imports, but not necessarily every individual file name in the entire repo as a contract. That means, today you're importing from /lib/foo/bar/baz/file.js, and tomorrow we rename it to `/lib/foo/bar/baz/somefile.js`. Your reference will break. We only guarantee the top level lib imports. Otherwise it becomes a complete messs to keep anything organized.

Now, all that said, webpack tree shaking will help you tremendously. This is planned for 6.0, which is actively being prepared in the `new_6.0` branch (the 6.0 merge proved to be too difficult.))

Closing the bug as there isn't anything actionable here.
