### ISSUE TITLE
[Accessibility] ContextualMenu: Narrator Reads 'Menu' Twice when User Activates ContextualMenu

### ISSUE THREAD

**Issue by HalcyonPride** [OfficeDev/office-ui-fabric-react#4815]
### Bug Report

- __Package version(s)__: 5.97.1
- __Browser and OS versions__: Narrator on Edge

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: OneDrive Web

#### Describe the issue:

Open a ContextualMenu on Edge with Narrator active.

#### Actual behavior:

Narrator announces 'Menu' twice.

#### Expected behavior:

Narrator announces 'Menu' once.

### If applicable, please provide a codepen repro:

N.A.

**Comment by rebeccaballantyne** [comment]
Worth noting that this only repro's in Edge when you CLICK on the contextual menu button. It is by design that focus should go to the entire container in this situation (for keyboarding, focus should go to the first menu item), but it is not by design that "menu menu" or "aria label aria label" is read twice.
