### ISSUE TITLE
Add 'pattern' to the textField.

### ISSUE THREAD

**Issue by aleksandrenko** [OfficeDev/office-ui-fabric-react#4821]
Please add a pattern to the textField, similar to the default 'patter' attr for <input /> to limit the possible value. Limiting the input to valid values is much better UX then making possible to enter an invalid value and showing errors.

https://www.w3schools.com/tags/att_input_pattern.asp

**Comment by bennettclark** [comment]
I tested on the latest version (5.97.0) and I was able to add `pattern` as a prop on the **textField** and see it successfully render on the input element.

If you're looking for form validation, please take a look at the `onGetErrorMessage` prop.

Closing because this is not an issue on the current version. Please feel free to open a new issue if you are still having any problems!
