### ISSUE TITLE
All components should be able to receive data attributes.

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#486]
Makes it so you can write automation and identify elements.

**Comment by dzearing** [comment]
Maybe @eliblock12 you could help with this. i think it will be needed.

**Comment by oengusmacinog** [comment]
After a bit of research, we concluded that this is not a blanket issue with one consistent solution.  Some components need data attributes on their root element, others need it on a key element like an input field.  The solution requires a bit of subjectivity.

I am closing this Issue due to the fact we will not be setting up every component to accept data attributes in the root element, but the next steps we are taking are to document which ones *do* accept data and aria attributes natively, and then add it to the components it makes sense on, or by request. That issue is tracked [here](https://github.com/OfficeDev/office-ui-fabric-react/issues/531)
