### ISSUE TITLE
Tooltip covers its trigger content if child is a block-level element

### ISSUE THREAD

**Issue by chrismohr** [OfficeDev/office-ui-fabric-react#4892]
### Bug Report

- __Package version(s)__: 5.103.0 and 6.0.0-beta4

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Low 

Products/sites affected: Yammer

#### Describe the issue:

Tooltip covers its trigger content if child is a block-level element.

We can workaround this by overriding css.
```
.ms-TooltipHost {
  display: inline-block;
}
```

Maybe this could/should be the default?

If not, maybe could we make it possible for the tooltip host to accept a `styles` prop? 

#### Actual behavior:

![image](https://user-images.githubusercontent.com/601657/40137805-21905024-5900-11e8-8b78-d194681de210.png)

Tooltip covers trigger content.

#### Expected behavior:

![image](https://user-images.githubusercontent.com/601657/40137855-3d260f72-5900-11e8-9362-e3f0432be8b5.png)

Tooltip to be positioned outside of block.

### If applicable, please provide a codepen repro:

https://codepen.io/chrismohr/pen/yjRzMG

**Comment by micahgodbolt** [comment]
So the issue is that an inline element wrapped around an inline-block element collapses and doesn't assume the child's height.

So there is no problem if the child is display block, but is a problem if it's inline-block.

One thing to consider would be, now that we're up to React 16, use React.fragments to render the tooltip without requiring a wrapper div. That's not a small change, as it removes an inline element everywhere a tooltip was used. I still think it's the right thing to do, but we should be sure to communicate the change if we do so.

**Comment by micahgodbolt** [comment]
also, here's a current repro https://codepen.io/micahgodbolt/pen/XPVyqK
