### ISSUE TITLE
DatePicker does not allow for the timezone offset

### ISSUE THREAD

**Issue by j-te** [OfficeDev/office-ui-fabric-react#4916]
### ~~Bug Report~~ Issue Report

- __Package version(s)__: 5.103.0
- __Browser and OS versions__: Chrome 65.0

#### Describe the issue:

This outlines a potential issue of the default value format.

I believe the datetime value returned should have the correct regional offset applied. This is because js/moment date functions will convert to an incorrect date (misleading).

Of course it should be expected for the developer to parse the values correctly but a change in the component could mitigate the issue:- which is difficult to identify in some instances. 

Please review the CodePen date values.

#### Actual behavior:

`Thu May 31 2018 00:00:00 GMT+0100 (GMT Daylight Time)` < DatePicker value
`Wed May 30 2018 01:00:00 GMT+0100 (GMT Daylight Time)` < DatePicker conversion result using js/moment

#### Expected behavior:

`Thu May 31 2018 01:00:00 GMT+0100 (GMT Daylight Time)` < What I think the value should return

### codepen repro:

[codePen Example outlining the issue](https://codepen.io/anon/pen/yjGJpm)

### Suggestions:
- Have a parameter to allow a forced region (+0)
- Expand the regional options for the default value
- Offset the default value as per the Date function region return value, shown in my examples
- Provide a warning for any unformatted dates

**Comment by micahgodbolt** [comment]
Added to calendar team's backlog

**Comment by lorejoh12** [comment]
From what I understand, the "actual behavior" you have listed above isn't quite accurate.

looking at the codepen, it seems to me that the actual behavior is this:
`Thu May 31 2018 00:00:00 GMT+0100 (GMT Daylight Time)` < DatePicker value
`Wed May 30 2018 23:00:00 GMT+0100 (GMT Daylight Time)` < DatePicker conversion result using js/moment, rather than 01:00:00 as listed above

So basically, the issue is that the DatePicker always returns the date in the machine's local TimeZone, and this js/moment library always by default converts into UTC. So the solution proposed here is to instead always have the DatePicker return a UTC date?

In doing so, I see the exact same issue coming up but more frequently. A timezone at UTC - 2, for example:
Proposed transform after selecting May 31st:
`Thu May 30 2018 22:00:00 GMT-0200 (GMT Daylight Time)` < DatePicker value

That seems significantly worse to me because a consumer who is just using the date part of the selection, and isn't trying to convert using the moment library, suddenly starts getting the wrong date back.

I'd be fine with passing in a timezone parameter, but it seems like our current solution of expecting the end user to do their own parsing rather than optimizing for those using js/moment is cleaner? Similarly to if you called new Date(), you'd have to transform that too since you're getting the same timezone conversion behavior.

Let me know if I'm grossly misunderstanding the issue here. :)

**Comment by lorejoh12** [comment]
I did a little bit more investigation. From what I can tell:

the datePicker returns back a normal Javascript Date value, in the current timezone. like: "Sat Jun 02 2018 00:00:00 GMT-0700 (Pacific Daylight Time)"

consuming a date using js/moment also creates a normal Javascript Date. So if you create a moment from the date given back by the onSelectDate callback, since both are in the system's local timezone, everything should match.

So it sounds like your issue is that you always want to return a UTC time, not that it really doesn't play nicely with the js/moment library but because your Sharepoint controls expect UTC inputs, hence requiring the utcOffset hack above.

In any case, if you'd like to submit a PR to enforce returning times in UTC, I'm happy to code review it! It gets a little hairier if you're trying to allow for ANY arbitrary timezone, but it should be easy enough to transform back to UTC before returning the date by just creating a new Date(Date.UTC(year, month...))

**Comment by j-te** [comment]
@lorejoh12 Thank you for taking a detailed look, I agree with what you're saying. 

In a perfect world it would be good if the DatePicker processed the earliest valid date rather than `00:00` to mitigate offset conversion errors but this is probably too much of an overhead for a component. 

Here's are my 2-cents going forward:

- New TimePicker sub-component (same issues apply here)
- Consider an additional property that returns only a date string IE `05-Sep-2018`, leaving processing to the end-user (should it be the default value?)
- My opinion of **default values** for these component states (people may disagree):

   `<DatePicker />` value =  `05-Sep-2018`

   `<TimePicker />` value =  `12:00AM`

   `<DatePicker timePicker={true}/>` value = `05-Sep-2018 12:00AM`

   `<DatePicker timePicker={true} locale={user}/>` value = `Wed Sep 05 2018 12:00:00 GMT+0100 (British Summer Time)`



I have three component states, Wrapping DatePicker in two. This is my process:

![datetime diagram](https://user-images.githubusercontent.com/34647206/45086444-0f03fe80-b0fb-11e8-9fcc-f44e53c42f1d.png)

**Comment by j-te** [comment]
Closing due to later issue #7046 being more coherent and duplicated
