### ISSUE TITLE
Wrong custom class order on Primary Button and maybe other components too

### ISSUE THREAD

**Issue by StfBauer** [OfficeDev/office-ui-fabric-react#4926]
### Bug Report

Package version(s): 5.21.0

#### Priorities and help requested (not applicable if asking question):
Are you willing to submit a PR to fix? No
Requested priority: Normal

#### Describe the issue:
I created the following react component:

```
import * as React from 'react';
import styles from './Vimeo.module.scss';
import { IVimeoSearchProps } from './IVimeoSearchProps';
import { escape } from '@microsoft/sp-lodash-subset';

import {
    TextField
} from 'office-ui-fabric-react/lib/TextField';
import {
    PrimaryButton
} from 'office-ui-fabric-react/lib/Button';

export default class VimeoSearch extends React.Component<{}, {}> {

    constructor(props) {
        super(props);
    }

    public render(): React.ReactElement<IVimeoSearchProps> {
        return (
            <div className={styles.videoSearchBar}>
                <TextField value="Hello World" className='n8d-searchbox' />
                <PrimaryButton text="Search" className='n8d-searchbutton' />
            </div>
        );
    }
}
```

The TextField uses the custom className 'n8d-searchbox' to apply some additional properties.
The PrimaryButton uses the custom className 'n8d-searchbutton' to apply some additional properties.

When I inspect the element in the browser the loading behaviour of both components is completely different.
TextField renders the custom class as expected at the end.
PrimaryButton renders the custom class at the beginning which means that certain properties get overwritten by the default style sheet classes.

![rant-on-office-ui-fabric](https://user-images.githubusercontent.com/5503835/40269952-83fa4904-5b85-11e8-9013-9a8d9faae6a3.png)

This behaviour is the same in all browsers.

**Comment by cliffkoh** [comment]
This might be fixed in 6.0 - but Jason is confirming. @micahgodbolt for FYI.

**Comment by JasonGore** [comment]
The ordering of the class names shouldn't matter. At the same level of specificity, it's the order of styling that matters.

To try and clear this up a bit more, I've created a [Codepen ](https://codepen.io/jasongore/pen/MGxgVr) which shows button styling in the CSS. Since `background-color` is specified in the default theme, increased specificity is required to override it. However, `box-shadow` and `font-size` do apply using just the custom class name `n8d-searchbutton` that you had in your example. Both of these behaviors are implemented in the linked Codepen.

If this isn't addressing your issue, please modify and reply with a Codepen to show what behavior you are referring. Thanks!

**Comment by StfBauer** [comment]
Thank you @JasonGore somehow it works now. When I created the issue the specificity of the class always got overwritten by the last class in the browser and the auto-generated `css-108` from the screenshot above was empty.
Now all CSS declarations get correctly consolidate in this class. Seems to be a loading issue more than an Office UI Fabric React issue.

I will keep an eye on this behaviour.

Thank you so far.
