### ISSUE TITLE
Allow custom sizes of Spinner

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [OfficeDev/office-ui-fabric-react#4973]
https://developer.microsoft.com/en-us/fabric#/components/spinner

The large size is 28x28px. If you manually change the element's style to custom width and height, it looks fine:

![image](https://user-images.githubusercontent.com/3335181/40495527-b5546b74-5f77-11e8-99b9-bb4d652555e3.png)

What is the recommended way to have a custom size spinner? Is it just passing width & height to `ISpinnerStyles.circle`? Whatever it is, it'd be nice to put it in the docs

**Comment by micahgodbolt** [comment]
Yeah,  you can just change height/width of the circle to get any size that you want. I agree though that we could make this a single, simple prop rather than making someone dive in.  I'll add it to our backlog, otherwise here's a pen showing how you can do it.

https://codepen.io/micahgodbolt/pen/bKVgPx?editors=0010
