### ISSUE TITLE
Split button options not accessible via keyboard

### ISSUE THREAD

**Issue by suztocco** [OfficeDev/office-ui-fabric-react#4978]
### Bug Report

- __Package version(s)__: Current
- __Browser and OS versions__: 

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/sites affected: Calendar, People, VSO

#### Describe the issue:

I cannot use the keyboard to access the options for a split button. It puts focus around the entire button (primary action plus the chevron) and enacts the primary action when entered. There is no way to get to the chevron and its actions.

#### Actual behavior:

Cannot access chevron actions via keyboard

#### Expected behavior:

Should be able to navigate to and act on either the primary action or the chevron actions.

### If applicable, please provide a codepen repro:

![image](https://user-images.githubusercontent.com/20954039/40511695-65f12116-5f55-11e8-9eeb-5172cc12a684.png)

**Comment by dzearing** [comment]
@suztocco @jspurlin @betrue-final-final 

This is an example of confusion.

@suztocco Per accessibility team suggestions (Jeremy, Ben above can chime in), they have recommended to have one single focus target with alt-down arrow to expand the menu.

**Comment by suztocco** [comment]
@dzearing @jspurlin  @betrue-final-final 

I did not know about tthe Alt arrow down command. I just saw this control and tested it and it seemed to "me" non accessible because I assumed I would use the arrow to get to it. 

I also saw on the People workload that you "Could" get to the chevron using the arrow
![image](https://user-images.githubusercontent.com/20954039/40555758-fb103332-5ffe-11e8-8ed5-75256b3652f0.png)

So I do not know what the "right" solution is or if you think the alt arrow is sufficient.

**Comment by betrue-final-final** [comment]
Alt + Down is a common shortcut to invoke a menu. It also works that way in this Angular example https://www.telerik.com/kendo-angular-ui/components/buttons/splitbutton/

We had a really long discussion around this with a number of accessibility drivers from OXO and around OPG, and decided on this pattern. Note this works like that in the Ribbon as well.

**Comment by suztocco** [comment]
Ok, confusion on my part then. If it is accessible, I am clear to launch it in our product.

**Comment by jspurlin** [comment]
// started writing this and stepped away for a few mins, but adding to what @betrue-final-final is saying

@suztocco Alt+DownArrow is a standard way for opening components that have menus (splitButton, contentualMenuButton, comboBox, dropdown, etc...), if you do a quick search you will be able to find a lot of results describing this behavior (including Microsoft, IBM, and many others).

SplitButons are one focus target, and each piece should not be focusable.

You also don't want down to expand the on down arrow in case controls are 2d (and are in a FocusZone) you can get into cases where you can't get to the lower control because you have a component that launches a menu on the first row. On top of that you don't want to change the behavior of a component depending on if it has another component below it. Consistency is important.

**Comment by dzearing** [comment]
Thanks guys. Closing the issue.
