### ISSUE TITLE
BaseButton: checks for text are not consistent between _onRenderTextContents and _onRenderText

### ISSUE THREAD

**Issue by rpsenski** [OfficeDev/office-ui-fabric-react#4979]
### Bug Report

- __Package version(s)__: 5.110.0
- __Browser and OS versions__: Not relevant

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Low

Products/sites affected: Purely a code maintainability issue

#### Describe the issue:

The branching logic of _onRenderTextContents does not match that of _onRenderText. The former has this check
`if (text || typeof (children) === 'string' ...`

the latter has this logic including two checks
```
if (text === undefined && typeof (children) === 'string')
  text = children;
}

if (text) {
  // ...
}
```

The latter will only consider child text if the text property is explicitly undefined, where the former will consider it if text is null OR undefined. Which one is correct is not clear. Trying to refactor this check for text as part of a fix for #4778 to keep it in-sync in several places, but at this time, I'm not comfortable changing the check in _onRenderTextContents to match what's in _onRenderText since the latter is more strict.

#### Actual behavior:

No discernible buggy behavior, just prevents a cleaner refactor of the check for text on the button so that that checking logic can be reused elsewhere within the same class.

**Comment by micahgodbolt** [comment]
we want to support button text from either the text property, or if a string is passed in as a child.

So the first check is to see if there is a string in text, children, or secondaryText….if so, we should render out the text.

The second test checks if there is no text property AND the child is a string. Then it sets text as that child string.

The two tests are different because they accomplish very different things.

A good refactoring might be to switch them around. Determine what the text is (either Text prop or string child) and then test for text or secondary text before rendering that section.

Does this help?
