### ISSUE TITLE
ContextMenu component is throwing an 'unknown function' exception

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/office-ui-fabric-react#5118]
### Bug Report

- __Package version(s)__: 5.101.2
- __Browser and OS versions__:  Internet Explorer 11

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) Office add-ins using Fabric React and ContextMenu component

#### Describe the issue:

A script error is thrown when moving the mouse over the context menu.

![image](https://user-images.githubusercontent.com/13109307/41057775-e052eaee-697c-11e8-9ccb-4f01b4910be3.png)

**Comment by dzearing** [comment]
@joschect I'm a bit unsure here. I don't know what setActive is doing.

@lambertwang did you add this? I see your name on the blame but a little unsure.

**Comment by joschect** [comment]
@dzearing Lambert did this as a fix because IE11 doesn't always handle focus right. 

I believe that this was so focus would be kept within the contextualmenu with hovering focus, so that when the mouse moves out focus is "lost" but kept within the menu. 

This setACtive began throwing errors in ie11 due to a recent change that made the tabindex on this._host conditional. setActive is "smart" enough to know that a div element without a tabindex shouldn't ever be focused, so if you call setActive on a div without a tabindex it throws an error.

The solution is either to remove this entirely or change the target to something that is focusable.

**Comment by dzearing** [comment]
I tried reproing but couldn't. (Win10, ie11)... https://codepen.io/dzearing/pen/WovrbX

**Comment by dzearing** [comment]
IE11 contextual menu just seems buggy. When I hover over things after expanding a submenu it really wants to dismiss. Not repro'd on Chrome.

**Comment by dzearing** [comment]
@joschect Are you ok with just removing the setActive? It clearly throws exceptions constantly in IE11.

We could avoid the focus call in IE11 if it's having issues.
