### ISSUE TITLE
ComboBox: ellipsis needed for text that is too long for dropdown items AND/OR width should automatically increase.

### ISSUE THREAD

**Issue by vivianhoang** [OfficeDev/office-ui-fabric-react#5173]
### Bug Report

- __Package version(s)__: 5.106.1002
- __Browser and OS versions__: Chrome

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: VSTS Analytics Views

#### Describe the issue:

There is a similar issue here #1589 that was fixed recently for Dropdown. The text in the dropdown should include ellipsis when the "useComboBoxAsMenuWidth" prop is set to true and the text is long, but it doesn't:

![image](https://user-images.githubusercontent.com/20330957/41265222-05111180-6da6-11e8-9333-595dee79d202.png)

**The statement above is the main bug that we wanted to point out, but my team also has a feature request:**

_TL;DR: What we are looking for is the dropdown taking the width of the ComboBox as the minimum width, and the width of the dropdown increasing in size when the dropdown items have longer text._

**Feedback/Scenario:**
Having a dropdown shorter than its ComboBox looks odd, and the dropdown should automatically have the same width as the ComboBox:

![image](https://user-images.githubusercontent.com/20330957/41264952-7fba48fe-6da4-11e8-93c7-d77e10f6333e.png)

I see that there are existing props that we can pass that address the issue I just stated above (dropdownWidth & useComboBoxAsMenuWidth); however, this becomes very limiting when we have dropdowns items with short and very long text values - using "dropdownWidth" without knowing the full width of the dropdown values or using "useComboBoxAsMenuWidth" with the proper ellipsis would not be the best way to portray this information:

![image](https://user-images.githubusercontent.com/20330957/41266004-e57d2d0a-6da9-11e8-990e-346bf83f2c5d.png)

**vs.**

![image](https://user-images.githubusercontent.com/20330957/41266063-28de73ce-6daa-11e8-8285-f5483bdf26b4.png)

If there were multiple instances of "zzzz..." with unique information at the end of the text, choosing a value would become confusing.

**Comment by michaelangotti** [comment]
@dzearing Assign appropriately.

**Comment by jspurlin** [comment]
@chang47 Didn't you fix this already?

**Comment by chang47** [comment]
I fix this for our scenario where we wanted to specify a limit for our maxWidth in the combo box, I did not do anything in this scenario where we want to set the width of our combo box as our maxWidth.

However, with the existing change I have made, it's just a matter of setting the maxWidth to be that props value. I'll make a quick change and see how it looks.

**Comment by chang47** [comment]
Made a PR for this: https://github.com/OfficeDev/office-ui-fabric-react/pull/5293

**Comment by chang47** [comment]
@vivianhoang I believe you can do so now after my changes done in this PR: https://github.com/OfficeDev/office-ui-fabric-react/pull/5200

You just need to set the new "dropdownMaxWidth" prop to the max value you want and set "useComboBoxAsMenuWidth" to be true and you should get the effect that you're looking for.

**Comment by JllyGrnGiant** [comment]
@chang47 The problem is we don't know how wide to set the ```dropdownMaxWidth``` because we don't want to specify it. We're letting the combo box fill the space available to it. If I set ```useComboBoxAsMenuWidth``` equal to true I'd expect the final width of the input field to be used as the max width of the dropdown/callout. But today instead we get cut off text with no ellipsis.

An alternative we'd be okay with is having ```useComboBoxAsMenuWidth``` set to true mean that the combo box width is used as the minWidth of the callout so it can grow horizontally to avoid cutting off text. The dropdown/callout the way it's implemented today grows if ```useComboBoxAsMenuWidth``` is set to false. But that means the dropdown/callout looks ugly when all the options are shorter than the width of the combo box.

**Comment by chang47** [comment]
@JllyGrnGiant Got it. The PR above will solve your first problem where you'll be able to have text cutoff if the options are too large.

As for your alternative, we could have a prop that does that, however, I'd imagine we could run a perf problem if we have to let the component calculate the largest size if we  have a large list, I'm sure we can mitigate most of the common cases, we just might have a problem in initial render.

So my question is what would your preferred solution that you'd like to see be?

**Comment by JllyGrnGiant** [comment]
@chang47 
If there is a way for users to discover what the full text is for the options that get truncated with an ellipsis, then your fix is perfectly fine for us and nothing else needs to be done here.

Otherwise there's a possibility users see two truncated options that appear the same or too much text is truncated and users cannot infer what the rest of the text might have been.

We're just trying to figure out how to avoid having another accessibility bug come later for the ellipsis option.
