### ISSUE TITLE
[DetailsList] Horizontal scroll appears with vertical one

### ISSUE THREAD

**Issue by Basek** [OfficeDev/office-ui-fabric-react#5176]
### Bug Report

- __Package version(s)__: 5.112.0
- __Browser and OS versions__: Google Chrome  Version 66.0.3359.181 (Official Build) (64-bit)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

#### Describe the issue:

Horizontal scroll appears with vertical one

#### Actual behavior:

Horizontal scroll appears with vertical

#### Expected behavior:
Horizontal scroll appears only when it is necessary

### If applicable, please provide a codepen repro:

https://codepen.io/anon/pen/VdbmrZ

**Comment by natalieethell** [comment]
Hey @Basek thanks for submitting this issue! After a quick look, it seems to be similar to something we encountered with the Callout component's vertical scrollbar in the past. A solution included manually calculating overflow to determine if Popup (used by Callout) needs a scrollbar, otherwise setting overflow-y to undefined: https://github.com/OfficeDev/office-ui-fabric-react/blob/3ddbf34d984442f6302fad29d21d23d6512b6db1/packages/office-ui-fabric-react/src/components/Popup/Popup.tsx#L87

@aditima what do you think? Could we implement something similar to what we have for Popup's overflow-y, but for overflow-x in this scenario?

**Comment by Basek** [comment]
@natalieethell, I'm not sure about this. It seems to me that the problem seems to be in column width calculation. There is viewport decorator which produce width for DetailsList, but it doesn't calculation vertical scroll width and because of that horizontal scroll appears.

**Comment by micahgodbolt** [comment]
The provided pen appears to be working correctly. Can the author verify if this is still an issue? https://codepen.io/anon/pen/VdbmrZ


![image](https://user-images.githubusercontent.com/1434956/50492682-e6678380-09cd-11e9-9a9e-f58c5b47546d.png)

**Comment by agg23** [comment]
Still occurring in Firefox:

<img width="475" alt="firefox_2018-12-27_12-03-09" src="https://user-images.githubusercontent.com/238679/50492974-778b2a00-09cf-11e9-92aa-926dec16d73e.png">

But not in Chrome. However, on load, Chrome initially has the horizontal scrollbar, then after half a second or so, it disappears.

**Comment by micahgodbolt** [comment]
Oh I see, it's a different container that has the horizontal scrolling

![image](https://user-images.githubusercontent.com/1434956/50494030-bf14b480-09d5-11e9-8f2b-073b8c6425e5.png)

Thanks for the update.

**Comment by dzearing** [comment]
@natalieethell will talk with @KevinTCoughlin

**Comment by KevinTCoughlin** [comment]
> But not in Chrome. However, on load, Chrome initially has the horizontal scrollbar, then after half a second or so, it disappears.

Chrome likely doesn't exhibit this behavior because `ResizeObserver` is kicking-in after some delay, see https://github.com/OfficeDev/office-ui-fabric-react/issues/5280#issuecomment-431195520.
