### ISSUE TITLE
How are styles loaded and overwritten?

### ISSUE THREAD

**Issue by jhsu** [OfficeDev/office-ui-fabric-react#536]
I see that scss files are imported in their corresponding components, but how does `loadStyles` from `load-themed-styles` get called to apply overrides on top of the styles? can this happen at render time or only when something like webpack is used to build the bundle?

thanks!

**Comment by dzearing** [comment]
@jhsu, if you take a look at any of the .scss.js files that get produced in lib, they do this:

```js
require('load-themed-styles').loadStyles('css string')
```

So, if you use webpack and bundle the Button, it will pull in the scss module and load the css on load. So we will only load what you bundle.

**Comment by tleunen** [comment]
Does it mean that all sass variables are transformed into the specific format for `load-themed-styles`?

I wonder, it's more a question for the themed-styles than for fabric-react, but, is it possible to create an external css file with this solution?

**Comment by dzearing** [comment]
yes that's right. They are transformed into an array of strings/objects (as a performance optimization for processing them).

In part it was done because we have theming capabilities at that layer that we plan to refine and extend so that it's really easy for partners to create custom themes.

The other reason was because it removes depending on webpack loaders to process the scss.

We've evaluated other solutions but haven't resolved in something totally perfect that makes everyone happy. Right now it's pretty simple. just import the component and it works without that much complexity on behalf of the consumer. But there are definitely challenges we need to iron our with stylization and customization. I'm more of a fan of ways that can be done on a code contractual level than at a css level which is a terrible contract. (e.g. inline styles would be verifiable through a contract; css modules as well)

**Comment by dzearing** [comment]
Please free to ask additional questions, I'll close this one for now.
