### ISSUE TITLE
Dropdown does not scroll to selected item when opened

### ISSUE THREAD

**Issue by janormanms** [OfficeDev/office-ui-fabric-react#5440]
### Bug Report 
 
- __Package version(s)__: 6.18.0
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
#### Describe the issue:
 
Create a Dropdown with enough items that a scrollbar is necessary
Set the default selected item to be one beyond the visible range
Open the dropdown
 
#### Actual behavior:
 
Opens at the top of the option list
User can arrow up/down and the scroll will jump to the item before/after the selected one, but the dropdown is not scrolled initially
 
#### Expected behavior:
 
Opens scrolled to the selected item

**Comment by JasonGore** [comment]
I can't repro this, it may have been fixed since reported. Here is a [CodePen](https://codepen.io/jasongore/pen/NBExJq) where `Dropdown` scrolls to default `Option s` when expanded. I will close this issue for now, but if you can provide a CodePen showing incorrect behavior, please feel free to reopen this issue. Thanks!

**Comment by natalieethell** [comment]
I am able to repro this on the master branch. Reopening the issue.
![image](https://user-images.githubusercontent.com/14134000/44922074-315fdb80-acf9-11e8-8edd-8eb634b3c646.png)

**Comment by micahgodbolt** [comment]
can you write down the repro steps @natalieethell - it seems that this isn't a consistent bug. I was just looking at jason's example and it worked fine. Curious what the difference is, if it's only when headers/groups are used?

**Comment by natalieethell** [comment]
Definitely! It looks like it's only an issue when using `directionalHintFixed`. I was actually able to repro here: https://codepen.io/naethell/pen/NLdEMz.

**Comment by micahgodbolt** [comment]
digging in to see whats the difference between that pen (which repros) and Jason's which does not https://codepen.io/jasongore/pen/NBExJq

**Comment by micahgodbolt** [comment]
Okay, it's nothing about how we're passing the prop in. Changing directionalHintFixed back to true demonstrate the same behavior. 

@joschect - any thoughts on why dropdown would autoscroll to the selected item when directionalHintFixed is false, but not when it's true?

**Comment by joschect** [comment]
@micahgodbolt I think that this is likely a timing issue/race condition. Something with directionalHintFixed is either preventing a re-render or causing an extra one. If it's preventing a re-render since it's position is more well known, then it's usually a random re-render that will fix it. OTOH if it's causing another re-render it's possible that secondary rerender is losing the scroll. I'll debug real quick and see if I can narrow it down.

**Comment by micahgodbolt** [comment]
@joschect appreciate you taking a look at it!

**Comment by kenotron** [comment]
This bug is introduced here: https://github.com/OfficeDev/office-ui-fabric-react/pull/4524/files#diff-62fc109cb2790b7323c7438be2bd8cf5R389 by @joschect 

We need to either make focuszone's focus to be inside RAF (which further improves perf, but makes testing harder) - maybe behind a prop...

-OR-

We could remove that perf improvement work inside calloutcontent

-OR-

Hack a focus on open inside Dropdown inside a RAF

**Comment by joschect** [comment]
@kenotron Thanks for that investigation! I'll take a look and get a fix!

**Comment by janormanms** [comment]
Looks like this is now fixed, thanks!

**Comment by Vitalius1** [comment]
Tried repro the bug and indeed looks like it was fixed.
@kenotron you labeled it with `needs discussion`. Are we expecting more work with this issue or it's good to be closed?

**Comment by kenotron** [comment]
I'm just gonna closet his since it's been verified fixed :)

**Comment by micahgodbolt** [comment]
@janormanms can you confirm on which version you found this to be fixed? We have a PR open as we speak to resolve the problem. Want to make sure this was actually fixed somewhere.

**Comment by janormanms** [comment]
Looks like when I made that comment we were on 6.61.0. We're still on that build and I'm still unable to repro the issue in the app.

**Comment by micahgodbolt** [comment]
@joschect can you verify if this issue still exists? You did a bunch of work to fix it....I'm assuming that meant you could repro it.

**Comment by micahgodbolt** [comment]
Going to reopen until we know if this issue is actually resolved, or if OP's team just found some workaround.

**Comment by dzearing** [comment]
I'm closing as the codepen repro is no longer broken.
