### ISSUE TITLE
SharePoint classic page: css in classic adds extra space to BUTTON and other elements, which breaks fabric-react styling.

### ISSUE THREAD

**Issue by gabrielruss** [OfficeDev/office-ui-fabric-react#557]
Hello, I am new to React so this could just be an issue with my code but I am seeing an issue with the spacing on the ContextualMenu when adding a href vs a onClick property to the menu items. 

![image](https://cloud.githubusercontent.com/assets/8887997/20352192/6e37abf4-abe4-11e6-865a-1c2a3851cf62.png)

And here is the code snippet from my component.

![image](https://cloud.githubusercontent.com/assets/8887997/20352286/ad2aa672-abe4-11e6-80f7-deaaef2acb8c.png)

Any ideas why the items with the onClick property have that left padding added? You will also notice that it adds a horizontal scroll bar. This only seems to happen if you leave off a href property on an item.

**Comment by gabrielruss** [comment]
Ok I found the culprit...still not sure why it is doing this though. 

![image](https://cloud.githubusercontent.com/assets/8887997/20354274/9b7da54e-abeb-11e6-82af-80ce423ce100.png)

SharePoint's css is placing a margin-left: 10px.

Is this something I will need to manually style back into place?

**Comment by phkuo** [comment]
Hey there,

It looks like you're trying to use our controls in Classic SharePoint, not the Modern experience. In Classic SharePoint, we have a lot of CSS to override browser defaults. That means, if you drop a button on the page, it will automatically be styled to look like all other SharePoint buttons. Fabric React uses a different philosophy, where we don't want to affect anything else on the page, and everything is self contained.

If you want to use Fabric React controls in Classic SharePoint, you will run into many of these issues. For this one in particular, you'll want to overwrite that style like so:
.ms-ContextualMenu button {
    @include margin-left(0);
}

I think the menu automatically changes to using <button>s instead of <a>s if there's no href, hence why you're seeing this.

**Comment by dzearing** [comment]
I've notified the sharepoint folks in chart of the modern webparts integration in classic pages, and they will evaluate how this can be generally avoided on our end.

Thanks.
