### ISSUE TITLE
How to get the css module class name of a component from within code?

### ISSUE THREAD

**Issue by spplante** [OfficeDev/office-ui-fabric-react#5645]
Hi there,

I did find plenty of documentation on how to refer ui fabric styles within our own css module, but is there any way to refer a ui fabric component class name within my own code? For example, lets say the `ContextualMenu` component renders the following HTML markup :

```html
<button type="button" id="ContextualMenuButton1" class="ms-Button ms-Button--default root-57">
    [...]
</button>
```

The `root-57` class is dynamically generated at build time, most likely because of css modules, and I would like to be able to refer it in my own code. Is there a way to do this just like we would do when working with our own css module? Example of what I would be looking for :

```typescript
// Step 1 : Somehow get the ContextualMenu styles?
import contextualMenuStyles from 'office-ui-fabric-react/lib/components/ContextualMenu/contextualMenu.module.scss';

export class MyOwnComponent extends React.Component<{}, {}> {

    public render() {
        return (
            <div className={ styles.checklist }>
                // Step 2 : Reuse a ContextualMenu class name for my own react control?
                <button type="button" className={ contextualMenuStyles.root } />
            </div>
        );
    }
}
```

Any help would be appreciated 👍 

Thanks!

**Comment by cliffkoh** [comment]
Hi @spplante, the `root-57` is actually generated not by CSS modules but by Fabric's JS styling (using the @uifabric/merge-styles library). 

Broadly speaking, there are various "blessed" mechanisms for you to refer to the styles, but not in the specific scenario illustrated by your code snippet above. Could you help us understand what it is you're trying to achieve here?

The fundamental issue with your example is that the full set of classnames generated by Fabric components (e.g. for ContextualMenu) typically depends on what we call "StyleProps" - which can only be determined at runtime during a render. This classname in turn can change between render passes (e.g. jump from `root-53` to `root-82` to `root-93` back to `root-53`. Without actually having a `ContextualMenu` instance that you're rendering, there isn't enough information to generate the set of styles and in turn, determine the classname. You would also likely run into the problem where the classname gets outdated since it can change between render passes.

**Comment by spplante** [comment]
@cliffkoh, gotcha, makes perfect sens. The reason why I was trying to do this is simply because I was trying to use the `onRender` method of the `ContextualMenu` to render the items by myself, but I wanted the recreate the exact same looking without making the effort of reproducing a similar CSS by myself.

Now you'll probably ask why would you want to use the `onRender` function if it's to render the items exactly the same? It's actually because I was trying to use the ContextualMenu right under a SearchBox in order to build myself an autocomplete component, and the way the items are rendered out-of-the-box brings all kinds of focus glitches. Has soon as the ContextualMenu was opening I was loosing the focus on the search box, and the only way I found to make that behavior stop was to either use a FocusTrapZone (which really isn't elegant) or to render the items by myself.

Anyway I will most likely end up using another control because there is too much focus problems with it and I don't seem to have much control over how to reacts. One weird thing while were here, is the fact that the "SearchBox" component **is** documented to have some sort of auto complete feature but when looking at the API there is nothing available, strange?

**Comment by cliffkoh** [comment]
Hmm I am not familiar with Searchbox or its history. I recommend filing a dedicated issue for any inconsistencies or surprising things about that component.

**Comment by cliffkoh** [comment]
I will close this issue as it seems the original issue has been resolved :)

**Comment by spplante** [comment]
No problem thanks!
