### ISSUE TITLE
use office-ui-fabric-react as external js lib

### ISSUE THREAD

**Issue by chatdanai** [OfficeDev/office-ui-fabric-react#584]
(Question)
Hi,

I'm newbie in React and and Fabric.
I create a small type script project and I want to use Fabric as external js.

In webpack.config.js

    externals: {
        "react": "React",
        "react-dom": "ReactDOM",
        "office-ui-fabric-react": "Fabric"
    }

react, and react-dom not include in my final js file.
but Fabric still in my js.

What wrong with my webpack.config.js?
Please help.

Thanks,

**Comment by dzearing** [comment]
My suggestions:

1. Don't externalize fabric.
2. In your imports, use the top-level imports to keep your bundle size small. For example:

```
import { Button } from 'office-ui-fabric-react/lib/Button';
```

This works for babel or typescript setups.

We are working on separating out smaller packages so that you can just import smaller packages, as loading the entirety of fabric-react is large and understanding which top level imports to address requires that you peruse the code here:

https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/office-ui-fabric-react/src

**Comment by chatdanai** [comment]
Thank @dzearing .

I changed import statement to 

import * as Fabric from 'office-ui-fabric-react';
 
or

import { Button } from 'office-ui-fabric-react;

It works now.
