### ISSUE TITLE
Drop Down doesn't open when non modal panel is already open

### ISSUE THREAD

**Issue by riteshbhoi** [OfficeDev/office-ui-fabric-react#5901]
**Bug Report**
Package version(s): v6.48.0 (latest as of Aug 10, 2018)
Browser and OS versions: Chrome

**Describe the issue**
we see an issue when drop downs and non modal panel are used together. When non modal panel is open, drop down selection doesn't work. Drop down does not basically show options.

**Repo Steps**
1. Open codepen link provided below.
2. Click on "Open Panel" to open non modal panel.
3. Try selecting an option in drop down.

Issue: Drop down options doesn't show up.

**Codepen link**
https://codepen.io/nick234/pen/YjdZae?editors=1010

**Comment by natalieethell** [comment]
Hey @riteshbhoi this issue is due to the Panel trapping focus, by default. By adding `forceFocusInsideTrap={false}` to the Panel props, you can still use the dropdown while the panel is open.

I'll go ahead and close this, but feel free to reopen this issue if you have any further questions or if this does not solve your issue!
