### ISSUE TITLE
Please Transpile Lib Files

### ISSUE THREAD

**Issue by dggsax** [OfficeDev/office-ui-fabric-react#5919]
Since we're using the `/lib/` directory to import individual components (which makes sense) issues arise since they are not transpiled ES6 code, and extra work has to be done in the testing configuration to deal with the nontranspiled ui fabric code. Perhaps either having the `/lib` files contain the transpiled files, or storing both the ES6 and transpiled versions, and enabling us to choose the transpiled file when importing.

Our current workaround is that our test call ignores the `office-ui-fabric-react` library as follows:
`"test": "react-scripts-ts test --env=jsdom --transformIgnorePatterns \"node_modules/(?!(office-ui-fabric-react)/)\"",`

Another thing to note, since most react projects use create-react-app, overriding most Jest configurations is heavily restricted.

Hope my request makes sense, please let me know if you need further explanation.

**Comment by kenotron** [comment]
/lib is for es6 code + esm modules
/lib-commonjs is for commonjs modules

To test with any node based (non-webpack) test runner like jest, you will have to transpile these down to commonjs if you're using /lib/. I would have suspected most codebases that use esm syntax would be using either babel-jest or pre-transpiled (should be the case for create-react-app as well):

https://github.com/facebook/jest/tree/master/packages/babel-jest

We prioritize /lib for production output for the sake of treeshaking which makes more sense for us since Fabric is built first and foremost to be used in production web apps (bundle size mostly). Due to this, we won't be transpiling /lib down to commonjs.

**Comment by kenotron** [comment]
One more note, if you're using commonjs in your code base throughout, you should consider using lib-commonjs instead.
