### ISSUE TITLE
Validate Multiplem <PivotItem> controls in <Pivot> 

### ISSUE THREAD

**Issue by realhoffi** [OfficeDev/office-ui-fabric-react#5969]
hi,

i have custom validationControls in my  pages, which i can validate by functions.

If you create a <Pivot> Controls, then you you can validate only the controls which are rendered in the selected tab!
But normally, you need to validate all controls in all tabs (all PivotItems)

So to illustrate it here:
<Pivot>
<PivotItem1><component1/></PivotItem>
<PivotItem2><component2/></PivotItem>
</Pivot>

if PivotItem1 is selected,,this control and subcontrols are rendered and can be validated.
The PivotItem2 can NOT BE validated!

maybe i forgot anything, but i think its a bug :)

**Comment by JasonGore** [comment]
It is pretty standard React behavior that if components are not visible, they are not part of the DOM hierarchy, meaning they are not mounted and rendered. This is how React in general and `Pivot` work; it will not render all `PivotItems`, only the one that is selected and visible.

This is somewhat similar to my input on #5030 in that the parent component of `Pivot` should handle this responsibility by receiving callbacks from your `PivotItem` children. If a user updates `PivotItem` content that you want to validate and track, then that should be handled by the parent of `Pivot` via callbacks/state updates from your `PivotItems`.

If you want to provide a CodePen example of your scenario, I'd be happy to take a look at it for you. I will close this issue for now as I don't see any changes that need to be made to Fabric. Thanks!

**Comment by realhoffi** [comment]
No, it is a unexpected Control-Behavior in my opinion. 
You can render all sub children, and set the visibility to false (display=none).
So my advice is, that you can add an Info-Box to your documentation, that all sub-children are not rendered, only the one, the tab is selected!

Another option is, that you make an option the the control, like "render all content".
its nothing like a simple tabbed list, where all content is rendered in each tab, the tab content can only change, when the content is in the current selected tab.

did you understand what i mean :D?

**Comment by JasonGore** [comment]
There are many similar cases, like 'Nav', `Dropdown`, `CommandBar`, `Tooltip`, `Callout`, `DetailsList` rows, various `Pickers`, where this is not the case. If you were using the `Nav` component, would you also expect all of its non-expanded children to also render? That has perf impacts and React is designed around not rendering unnecessary components, of which visibility is a huge factor.

The default behavior for React and many components is not to render visible components. If invisible components render, that is actually an exception that should be documented. In this case, since the behavior is common for React and Fabric, it's behavior that should be expected and not necessarily documented as it is not exceptional.

As I mentioned earlier, if you have code exhibiting this issue I'd be happy to take a look and show you how component state should be lifted up appropriately. Depending on a component to be rendered when it is invisible to preserve component state is generally not a viable solution in the React ecosphere.
