### ISSUE TITLE
Interactive elements inside tooltip content are not accessible via keyboard

### ISSUE THREAD

**Issue by dabasn** [OfficeDev/office-ui-fabric-react#6005]
Bug reproduction in codepen:
 
https://codepen.io/sorosoro/pen/VGwEZE

 - __Package version(s)__: 5.112.1004
- __Browser and OS versions__: Google Chrome Version 68.0.3440.106
 
Requested priority: Normal
Products affected: Team Foundation Server and Visual Studio Team Services

#### Issue:
 
I have an interactive element inside the tooltip ( a button which is focusable via keyboard);
When I bring the focus on the target element of the tooltip, the tooltip becomes visible;
I want to shift the focus to the button inside the tooltip via keyboard, but there does not seem any way to do so as the tooltip vanishes on further keypress
 
#### Actual behavior:
 
There is no way to focus on interactive elements inside tooltip content
 
#### Expected behavior:
 
There has to be some keyboard shortcut to reach the focusable elements inside tooltip content

**Comment by kkjeer** [comment]
@dabasn thank you for submitting an issue! This behavior is intentional in the Tooltip component. Could you use a Callout here instead? The examples at https://developer.microsoft.com/en-us/fabric#/components/callout include a Callout with actionable buttons. I also forked your codepen to show an example of a Callout with a button: https://codepen.io/kkjeer/pen/ZMYXpe.
