### ISSUE TITLE
onRenderMissingItem not working in DetailsList group 

### ISSUE THREAD

**Issue by hrc7505** [OfficeDev/office-ui-fabric-react#6027]
I am fetching the the list from api and converting it to detailsListItems. I have made a dynamic groupList based on the list. Everything is working fine but onRenderMissingItem stop working when I use group. Without group it is working fine. I am using onRenderMissingItem callback for infinite paging. Is this a bug or need to add something ?

**Comment by hrc7505** [comment]
Please check this pen: [A code pen for detailsList groups](https://codepen.io/hardik-chaudhary/pen/ZMGoOZ?editors=0010)

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin You can see the pen: [A code pen for detailsList groups](https://codepen.io/hardik-chaudhary/pen/ZMGoOZ?editors=0010)

Thanks for the Codepen @hrc7505, that helped me debug this much more easily. In my testing `DetailsList` invokes `onRenderMissingItem` as expected even when the `DetailsList` contains `groups`. Here's an example Codepen demonstrating this behavior: https://codepen.io/kevintcoughlin/pen/Zqqvpg?editors=0010

I believe the bug may be with your implementation of `getGroupList` and perhaps the removal of falsey values via the `if (data)` conditional, which a `null` value will not pass.

It is also worth noting that `onRenderMissingItem` expects a `React.ReactNode` be returned. See:

https://github.com/OfficeDev/office-ui-fabric-react/blob/189d2b2d53ee2bcf318475c393ececa238343c20/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.types.ts#L175

I hope that helps. If you believe the bug to be with OUIFR still, please fork my Codepen with the simplified `onRenderMissingItem` example to demonstrate the bug. Otherwise, I'll close in a few days if I don't hear back.

**Comment by KevinTCoughlin** [comment]
Another thanks, as this issue led to adding some basic unit test coverage for the optional `onRenderMissingItem` prop via #6845. 🎉
