### ISSUE TITLE
Dropdown arrow on ComboBox does not change sides when inside of a RTL div

### ISSUE THREAD

**Issue by RichardCassan** [OfficeDev/office-ui-fabric-react#6073]
CodePen: https://codepen.io/anon/pen/RYWKqW

### Bug Report 
 - __Package version(s)__: Observed on most recent version (6.54)
- __Browser and OS versions__: Observed on Chrome and Edge (haven't tried other browsers)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: OWA Calendar
 
#### Describe the issue:
 
I'm seeing that the side the chevron arrow appears on is not affected by the 'dir' attribute of its parent div, while other controls (e.g.) toggle is impacted by the dir attribute.  
 
#### Actual behavior:
 
When the dir attribute of the parent div is changed to LTR the text direction of the ComboBox changes, but the side the arrow is rendered on does not
![rtl](https://user-images.githubusercontent.com/33036686/44596602-9f4c5600-a781-11e8-9622-7d78c1f755d0.PNG)

#### Expected behavior:
 
Expect the side the dropdown arrow appears on to swap sides as well

**Comment by micahgodbolt** [comment]
@RichardCassan this component should be working properly. The problem is that RTL is a page level change, as it affects how the styles are rendered at runtime. Wrapping a component with dir=rtl won't have any effect on that. 

Here's a copepen of them working.

https://codepen.io/micahgodbolt/pen/vzLKew
