### ISSUE TITLE
Component Slider(vertical slider) doesn't work on Safari

### ISSUE THREAD

**Issue by sampascal** [OfficeDev/office-ui-fabric-react#6223]
### Bug Report 
 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)
 Safari, iOS: 10.12.6
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No
 
Requested priority: (Blocking, High, Normal, Low)  High
 
Products/sites affected: (if applicable)
https://developer.microsoft.com/en-us/fabric#/components/slider
 
#### Describe the issue:
 

 Vertical slider doesn't work on Safari, iOS version 10.12.6
#### Actual behavior:
 Open this page: https://developer.microsoft.com/en-us/fabric#/components/slider
The vertical slider doesn't show at all

 
#### Expected behavior:
 
The vertical slider should show.

**Comment by mikewheaton** [comment]
I'm able to repro this in Safari for macOS:

![image](https://user-images.githubusercontent.com/1382445/47229392-7f4da300-d37c-11e8-9fac-4e641a616b85.png)

The issue appears to be caused by [using a button as a flex container](https://stackoverflow.com/questions/35464067/flexbox-not-working-on-button-or-fieldset-elements). If I change the button to a div it works:

![image](https://user-images.githubusercontent.com/1382445/47229462-a0ae8f00-d37c-11e8-9eed-9ba4d3d622d6.png)

I'm not sure if that's an acceptable solution though, as there are ARIA attributes that may only be valid for buttons. This needs investigation.
