### ISSUE TITLE
Switch to using a real TS parser for the propertiesTable

### ISSUE THREAD

**Issue by kenotron** [OfficeDev/office-ui-fabric-react#6252]
**Describe the feature that you would like added**

Currently, we just try to match with regex the properties when we generate documentation. We should try to do this with a real parser to avoid getting into trouble like with #6219 where prop interface was defined on multiple lines (due to Prettier settings). We can probably glean more information and format the documentation site even better with proper static analysis available. 

We can also investigate the use of tsdoc to generate API documentation that we can link to for even better dev exp

**What component or utility would this be added to**

example-app-base/utilities

**Have you discussed this feature with our team, and if so, who**

This came up from fixing a shield issue referenced above. But it is also something we've seen happen in the past

**Additional context/screenshots**

**Comment by cliffkoh** [comment]
Just to be clear, the regex is only used to identify the sectors of code for the parser (we have a real parser) to generate documentation. But at the same time, the documentation generator was written in 1 day over 2.5 years ago and hasn't really been updated and I think a big part of why we're not innovating there is because of the TSDoc effort @pgonzal is spearheading (minimally, that is why I am doing the bare minimum with regards to parser :)) 

So totally agree with the main gist of this issue. It would be great to converge and use the same set of tools as the rest of the community.

**Comment by micahgodbolt** [comment]
Been meaning to follow up with docs team about using their API extractor. Is that a conversation we should have sooner than later to improve this situation? @kenotron I know you had explored this in the past. Is it time to dive back in again?

**Comment by cliffkoh** [comment]
This work is completed by @natalieethell
