### ISSUE TITLE
Add persist prop to DetailsList

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-ui-fabric-react#6304]
**Describe the feature that you would like added**
Add a "persist" prop  that disables rows removal on unmount
**What component or utility would this be added to**
DetailsList
**Have you discussed this feature with our team, and if so, who**
No
**Additional context/screenshots**
```ts
private _onRowWillUnmount(row: DetailsRowBase): void {
    const { onRowWillUnmount, persist } = this.props;

    const { item, itemIndex } = row.props;
    const itemKey = this._getItemKey(item, itemIndex);
    if(!persist){
      delete this._activeRows[itemKey];
    }

    if (onRowWillUnmount) {
      onRowWillUnmount(item, itemIndex);
    }
  }
```

**Comment by KevinTCoughlin** [comment]
@rachidaoudi can you expand on the use-case for this feature a bit more? What sort of interaction are you trying to support that requires persisting the row?

**Comment by rachidaoudi** [comment]
@KevinTCoughlin I've put the details lists in some tabs (not Pivot) that persist their content ( they set display to none instead of not rendering at all ), so when I navigate between the tabs, the content should already be there, the user sees an empty table for a second (or even a couple seconds in case of big data) which is bad for UX, it seems to the users that  there is a network request each time we open a table.
