### ISSUE TITLE
Horizontal scrollbar is hidden behind Sticky footer

### ISSUE THREAD

**Issue by shagra-ms** [OfficeDev/office-ui-fabric-react#6339]
### Bug Report 
 
 
- __Package version(s)__: 6.53.0 onwards
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 Normal
Products/sites affected: (if applicable)
 
#### Describe the issue:
 
The ScrollablePane adjusts the position of the Sticky footer(s) based on the presence of the horizontal scrollbar. The presence of the scrollbar is checked on various events like window resize etc. But it is not checked based on horizontally expanding content. The horizontal scrollbar shows up if the content overflows horizontally, but is hidden behind the Sticky footer. 

Following steps reproduces this on the ScrollbablePane DetailsList example -

* Ensure that the horizontal scrollbar doesnt exist (reduce the number of colums for this or use a large monitor)
* Resize a column in 'Item List' such that the content overflows (notice the height of the vertical scrollbar as you resize)
 
#### Actual behavior:
 
The horizontal scrollbar is hidden behind the sticky footer. It shows up once you scroll vertically or resize window etc.
 
#### Expected behavior:
 
The sticky footer should move when the horizontal scrollbar is visible.

**Comment by Vitalius1** [comment]
This is a valid bug and can be easily be reproduced in ScrollablePane example page when running locally as the website is behind the updated example with the sticky footer.
@shagra-ms thanks for filling the issue and detailed repro steps. This can help tremendously in debugging.

**Comment by Vitalius1** [comment]
The bug itself might be also coming from DetailsList as it manifests after resizing it's columns.

**Comment by arkogupta** [comment]
@Vitalius1 any update on this ?

**Comment by mikewheaton** [comment]
I've started digging into this. The overall structure is that the ScrollablePane component has a `contentContainer` div, which for this example contains a DetailsList. Whenever the ScrollablePane is rendered, the `_getStickyContainerStyle()` function runs and determines the height (if any) of the horizontal scrollbar. It then positions the footer content appropriately.

This all works correctly when the page is first loaded. However, when the DetailsList columns are resized, this changes the width of the DetailsList. This can cause the `contentContainer` div to show or hide its horizontal scrollbar. The problem is that it does not re-trigger a render of ScrollablePane so that it has the opportunity to reposition the footer.

DetailsList has an `onColumnResize` prop so we can run a callback whenever a column is resized. I think this is the only way for a DetailsList to change in width. When that happens, we could force a re-render of ScrollablePane (in the example) so that it repositions the footer.

I'm not sure about this pattern in general, and there could be performance issues depending on how often the content resizes and whether those events are throttled. I wonder if we have other components that need to update when their children resize? Is there a better way to handle this?

**Comment by mikewheaton** [comment]
Another option could be to expose a function like `repositionFooter()` on ScrollablePane, which could be called by the parent (which is aware of the DetailsList being resized via a callback). This would avoid having to force a re-render.

**Comment by arkogupta** [comment]
> Another option could be to expose a function like `repositionFooter()` on ScrollablePane, which could be called by the parent (which is aware of the DetailsList being resized via a callback). This would avoid having to force a re-render.
> 
> Here's React documentation on [exposing component functions](https://shripadk.github.io/react/tips/expose-component-functions.html).

This looks like a better approach ! Re-rendering the scrollablePane on each column resize is bound to have performance issues as you rightly mentioned, also because all the child components will also re-render. Go ahead with this if everything looks fine with this approach.
