### ISSUE TITLE
IconButton does not output aria-pressed attribute to DOM

### ISSUE THREAD

**Issue by jakob101** [OfficeDev/office-ui-fabric-react#6353]
### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/jawerne/pen/gdKrrE

### Bug Report 
 
- __Package version(s)__: latest
- __Browser and OS versions__: Chrome, Win10
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
#### Describe the issue:
 
IconButton can accept two properties - checked and aria-pressed. Neither of those output aria attributes to the DOM.
 
#### Actual behavior:
 
No observed aria-pressed attributes.
 
#### Expected behavior:
 
aria-pressed="true|false"

**Comment by KevinTCoughlin** [comment]
It looks like this can be achieved once `toggle="true"` is set on the `<IconButton/>` because of this line:

https://github.com/OfficeDev/office-ui-fabric-react/blob/dc56a3a9389725dc364b51be6a1d237fc150bd2e/packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx#L196

https://codepen.io/kevintcoughlin/pen/mGKKPz

**Comment by jakob101** [comment]
Thanks, I'll try that. Would be great to have it documented :)
