### ISSUE TITLE
DetailsList: Horizontal and vertical scrolling when items is empty and column reorder is enabled

### ISSUE THREAD

**Issue by goodoldneon** [OfficeDev/office-ui-fabric-react#6394]
### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/goodoldneon/pen/dqgeGE

### Bug Report 
 
- __Package version(s)__: 6.70.0
- __Browser and OS versions__: Chrome 69.0.3497.92 and macOS 10.13.6
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? I'll try
 
Requested priority: Normal
 
Products/sites affected: N/A
 
#### Describe the issue:
 
The `DetailsList` component scrolls horizontally and vertically when both:
- `props.items === []`
- `props.columnReorderOptions !== null`

The `DetailsList` component scrolls horizontally when:
- `props.columnReorderOptions !== null`
 
#### Expected behavior:
 
No scrolling inside `DetailsList`.

**Comment by micahgodbolt** [comment]
give us a shout if you get stumped

**Comment by goodoldneon** [comment]
I created PR #6402, but I'm not sure whether it's the "right" way to fix this issue. Please let me know what you think.

**Comment by KevinTCoughlin** [comment]
The root cause of this issue is the right-most column header's drop hint is rendered outside the bounds of the `DetailsList` container which has `overflow-x: auto` (scrollbars). This occurs even when the drop-hints are hidden. Their position alone causes the browser to calculate overflow and render scrollbars.

The fix is to either:

- Move the drop-hint(s) within the container's bounds to not cause the container to overflow.

OR

- Use something like a pseudo element for drop-hints which do not take up horizontal space

It looks like this regression was caused when drag & drop behavior was introduced to `DetailsList`.

Here's a screen-capture showing the above problem and how removing the element so it is not causing the container to overflow "fixes" the scrollbar-x overflow.

![dl_drophint_overflow_x](https://user-images.githubusercontent.com/706967/49318982-915c4e80-f4af-11e8-9547-9e99d78e56e8.gif)

cc: @arkogupta

**Comment by arkogupta** [comment]
We'll have a look into it. Thanks for bringing this up.
