### ISSUE TITLE
Documentation Bug - Broken Links for Variants on DetailsList page

### ISSUE THREAD

**Issue by chadsowald** [OfficeDev/office-ui-fabric-react#6404]
1. Visit https://developer.microsoft.com/en-us/fabric#/components/detailslist
2. Click any of the links under "Also available in" on the right (see screenshot)

**Expected**: Goes to that sample clicked.
**Actual**: Broken link

Note 1: The left side navigation links work as expected.
Note 2: Not sure if any other pages have the same issue.

![image](https://user-images.githubusercontent.com/165767/45714090-8a2ad300-bb45-11e8-9988-325f49aa440d.png)

**Comment by KevinTCoughlin** [comment]
Thanks for the report @chadsowald. I believe the website is a few versions behind because on `master` those links are no longer present on the root `DetailsList` page

![image](https://user-images.githubusercontent.com/706967/45719110-26f46d00-bb54-11e8-9d1b-f3ebb11ed7b6.png)

cc: @Jahnp to confirm if possible

**Comment by Jahnp** [comment]
@chadsowald @KevinTCoughlin the site should be updated by tomorrow. Sorry for the delay here!

**Comment by Vitalius1** [comment]
@Jahnp did the site get updated? It looks like we still have this issue present.
