### ISSUE TITLE
DetailsList - Cursor key traversing shows unexpected selection behavior when moving from header row to first item

### ISSUE THREAD

**Issue by Nimelrian** [OfficeDev/office-ui-fabric-react#6416]
### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/nimelrian/pen/BOvpjO

### Bug Report 
 
 
- __Package version(s)__: office-ui-fabric-react@6.71.1
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No, maybe if I can find the cause of it myself. If someone has more experience with the intricacies of `DetailsList`/`Selection`/`SelectionZone` I wouldn't do the same work twice.
 
Requested priority: High, since this may violate invariants which would have to be handled in user code.
 
#### Describe the issue:
 
Prerequisites:
1. A `DetailsList` which has its `Selection` instance supplied from user code via the selection prop
2. The selection mode of both, `DetailsList` and `Selection` instance, is `SelectionMode.single`
3. At least one item is supplied via the `items` prop
 
Reproduction:
1. Click the topmost item in the list
2. Press the "Up" cursor key
3. Press the "Down" cursor key

#### Actual behavior:
 
The selection of the item gets toggled. If it was selected before moving the focus into the header, the selection is cleared after moving down. It it wasn't selected, it is selected after moving the focus.
 
#### Expected behavior:
 
The item should be/stay selected.

In my opinion it would be even better if simple moving around using the cursor keys wouldn't change the selection at all. An additional input (e.g. a press of the spacebar) should be necessary to change the selection status of an item.

**Comment by KevinTCoughlin** [comment]
Thanks for the detailed report @Nimelrian. I was able to modify your Codepen to avoid this bug, by applying the following diff:

```diff
     this._selection = new Selection({
-      selectionMode: SelectionMode.single,
       onSelectionChanged: () => this.setState({ selectionDetails: this._getSelectionDetails() })
     });
 ```

Here's a Codepen showing the removal of the above prop and the behavior working as expected: https://codepen.io/kevintcoughlin/pen/NOoPZB. The `selectionMode` is still configured via prop on `DetailsList` so single selection mode is maintained.

Though the prop in this scenario seems redundant to me, it does seem like a scenario we should support. I'll work on figuring out why the bug is occurring, but in the meantime I'm proposing the above as a workaround.

**Comment by Nimelrian** [comment]
Thanks Kevin! Sorry for answering only so late.
The changes described in the diff work in our code just fine.

The actual issue I had has thus been solved, maybe a note in the docs would be appropriate though.
I'll leave closing this issue to you, in case you want to take further action before closing it out.
