### ISSUE TITLE
onSelectionChanged gets called twice, the second time clears selection.

### ISSUE THREAD

**Issue by justinmwarner** [OfficeDev/office-ui-fabric-react#6446]
### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/anon/pen/oPVPpE

### Bug Report 
 
 
- __Package version(s)__: 6.59.0
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No, not comfortable making a change to this as I'm unsure if I'm consuming it correctly.
 
Requested priority: Normal
 
Products/sites affected: Analytics
 
#### Describe the issue:
 
When using ```onSelectionChanged```, it gets called twice, once with the actual selection, and a second time that clears the selection. Not sure why this happens.
 
#### Actual behavior:
 
onSelectionChanged gets called twice.
 
#### Expected behavior:
 
onSelectionChanged gets called once.

Is there another way to monitor the selection on the details list? We just want to load extra data on the page when a selection occurs.

**Comment by newtonsheikh** [comment]
It gets called twice because you are technically calling it twice:

1. When u click on any item --- selection has changed (and you get the alert)
2. Now when you scroll -- you are loading new data from the server, and this un-selects your previous selection triggering  the onSelectionChanged() event. 

I dont have a solution yet, but the problem is now know. You have to change your code a little so that the selection never get unselected.

**Comment by KevinTCoughlin** [comment]
Hey @justinmwarner 👋 , thank you for the report. I _think_ the problem here is with the `setInterval` within the response handling of paginated data:

```ts
  private _onLoadNextPage() {
      let { subreddit, nextPageToken } = this.state;
      let url = `https://www.reddit.com/r/` +
          `${subreddit}.json` +
          `${nextPageToken ? '?after=' + nextPageToken : ''}`;

    this.setState({ isLoading: true });

      fetch(url).then(
        response => response.json()).then(json => {
        let rows = this._getRowsFromData(json.data);

        setInterval(() => {
          // rows.splice(1, 1);
          
          this.setState({ 
            rows,
            nextPageToken: json.data.after,
            isLoading: false
          });
        }, 3000);

        this._selection.setItems(rows);
      });
  }
```

Once I removed that `setInterval`, I no longer see `this._selection` reset or called twice. I have a Codepen example which outputs the Selection's `count` and `mode` within the `onSelectionChange` callback @ https://codepen.io/kevintcoughlin/pen/XPwyxO?editors=1010. The count looks correct in the console and I haven't seen the selection reset as I un/select items in the list. I also tested using the meta key and drag to append to an existing selection without problem.

I'd avoid the artificial delay and try to invoke both `this.setState` on the `DetailsList` as well as `this._selection.setItems` on the `Selection` in the same cycle to avoid undesirable selection behavior.

**Comment by KevinTCoughlin** [comment]
Going to close as this seems like an implementation error with the component(s). Please re-open if you feel otherwise. We appreciate the report nonetheless.
