### ISSUE TITLE
SearchBox focus styling is different from other controls

### ISSUE THREAD

**Issue by cschleiden** [OfficeDev/office-ui-fabric-react#648]
Text fields have a dark border by default, and become blue when focused:

![image](https://cloud.githubusercontent.com/assets/2201819/20854692/cd423420-b8aa-11e6-8fbc-e198280497d3.png)

The `SearchBox` behaves the other way around:

![image](https://cloud.githubusercontent.com/assets/2201819/20854701/dd0ab95e-b8aa-11e6-9d2b-632103cc3290.png)

Is this by design?

**Comment by mikewheaton** [comment]
It turns out that the designs for SearchBox _do_ call for it to have a blue border by default. We're investigating the history here, with our assumption being that it was to give search more prominence on the page.

Could you include a screenshot of where you're including the SearchBox? I'm guessing it's alongside other form fields and that's why it's sticking out. We should probably have the default SearchBox look like any other form field, and then add a "prominent" variant if that's necessary in multiple contexts.

**Comment by dzearing** [comment]
Closing this and tracking in #662
