### ISSUE TITLE
DetailsList: set items selection required and validate it

### ISSUE THREAD

**Issue by fildahui** [OfficeDev/office-ui-fabric-react#6482]
**Describe the feature that you would like added**
Make items selection in details list required and validate it 

DetailsList provides ways to select its items and it would be nice to set the selection required so that the user has to select one item (or more, depending on the condition) otherwise a validation message (either style around the component or a text message) is shown.
This would come handy when the user has to select items from details list which is placed inside a form element.

**What component or utility would this be added to**
DetailsList

**Have you discussed this feature with our team, and if so, who**
No

**Additional context/screenshots**
I am not so sure whether having a DetailsList inside a form element is a legit scenario or not, but this selection validation feature would be a great addition.

**Comment by KevinTCoughlin** [comment]
At a glance, this seems like something that can be handled by a developer using the `<DetailsList>` rather than an additional feature of the `<DetailsList>` given how specific a use-case it is.

What I'm interested to know is what is blocking a developer from using the `<DetailsList/>` component to achieve this behavior? Whatever they are we should consider addressing them. cc: @micahgodbolt for his thoughts.
