### ISSUE TITLE
Tests for office ui fabric components using jest, enzyme

### ISSUE THREAD

**Issue by liricy** [OfficeDev/office-ui-fabric-react#6519]
#### Describe the issue:

I have a render function as shown below:
```
private render(): JSX.Element {
return (
<div>
{this.props.x && this.state.y &&
   <DefaultButton 
   onClick={this.onDeleteButtonClick}
   >		
   Delete
  </DefaultButton>
}		
</div>
);
}
```

Only when the 2 conditions this.props.x and this.state.y are true, display button. How do I write a test for the same? Please let me know. Thanks?

**Comment by cliffkoh** [comment]
In general, Stack Overflow is the best place for questions like this but in particular because your question isn't specific to OUFR (you could have replaced the usage of Fabric button here with a HTML button and it wouldn't materially change the answer to your question), the OUFR issue board is simply not the right place for questions like this.
