### ISSUE TITLE
Fabric Dropdown Component overlaps the edit box/main box with scroll

### ISSUE THREAD

**Issue by jaduong** [OfficeDev/office-ui-fabric-react#6529]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Project

#### Describe the issue:
![image](https://user-images.githubusercontent.com/32304484/46310035-0e804b80-c573-11e8-925b-7fbeaca950aa.png)

The dropdown contents overlap the main dropdown selector box when there's a scroll. 

#### Actual behavior:

The dropdown contents overlap the main dropdown selector box when there's a scroll. 

#### Expected behavior:

When I'm selecting something from a dropdown, the dropdown doesn't overlap my main dropdown components. I want to be able to what is currently selected and the list of dropdown items in the whole component view.

**Comment by jaduong** [comment]
@dzearing I'm on Edge (also repros on Chrome). If I make my window smaller, then the dropdown list covers the selected area. 
This repros in your codepen.

**Comment by Vitalius1** [comment]
@dzearing this is caused by `directionalHintFixed` set to `false` in this #5771 PR.

@jaduong from your screen looks like the dropdown takes almost the entire width of the div it's contained within. In the PR I mentioned above we changed Dropdown behavior to not be always fixed to bottom of the target so it's rendered Callout will try to position itself when it has scroll. If your dropdown would have a set width of less than 50% of the containing div it would render on the side but in you case it's just covers the target.
A solution to your situation is described in the PR. Just set the` calloutProps` of the dropdown like this and the dropdown will always render at the bottom of the target. You can test it in the codepen.
```
<Dropdown 
    calloutProps={{directionalHintFixed: true}}
    ...rest of the props
>
```

**Comment by adhithyar** [comment]
Hello Team!

I'm Adhithya, an engineer in @jaduong's team. 

@Vitalius1 I tried your suggestion and it is not working. I set the `directionalHintFixed: true` and I am still seeing the same overlap behavior. If I try it on codepen, it works fine. 

My hypotheses is that the version of Fabric React we are using has this issue and once we upgrade it might be fixed. We are on 5.111.2.

**Comment by Vitalius1** [comment]
@adhithyar to know for sure if it's a version issue maybe you could try to setup a codepen simulating your wrapping divs of the dropdown as you have them in your app with about the same restrictions in sizes and see if with the latest version it works.

@dzearing is there a way in a codepen to use a specific version of OUFR?

**Comment by micahgodbolt** [comment]
@adhithyar in 5.111.2 i believe we already fixed the direction hint, so you probably won't see a change. Have you been able to upgrade in 6.x? If you're still having issues can you supply a codepen repro.
