### ISSUE TITLE
The "List of 5000 grid items" example doesn't have enough code to show you how to make your list a grid

### ISSUE THREAD

**Issue by ericame** [OfficeDev/office-ui-fabric-react#6559]
### Please provide a reproduction of the bug in a codepen:
 

How the grid example looks if you copy and paste their logic (with some minor tweaks because the example is not self-contained enough to run on its own).

https://codepen.io/ericame/pen/pxyjGx/

Notice that this is still a columnar list, not a grid-formatted list.

### Bug Report 
 
 
- __Package version(s)__: Office UI Fabric 6.72.2
- __Browser and OS versions__: (fill this out if relevant)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal
 
Products/sites affected: Office UI Fabric site (https://developer.microsoft.com/en-us/fabric#/components/list)

(I'm just prototyping, so this technically does not affect my product.)
 
#### Describe the issue:
 
The first example for the list component is a grid-styled list, but on trying to implement it myself based on the example, I got a columnar list like the one in this codepen: https://codepen.io/ericame/pen/pxyjGx
 
#### Actual behavior:
 
After digging through the GitHub repo for the examples implementation, I can see there's some more styling magic at play that's not visible in the online sample. Based on that, I made some changes to make it act like a grid: https://codepen.io/ericame/pen/mzPEME

You can see in this example that I fixed the issue by adding additional styling to the ms-List-page class. I'm new to using Office UI Fabric, but my understanding is that I'm not really supposed to mess with the built in style classes, just use my own when I need additional styling. However, as far as I can tell, the only way to make this grid-like is to use that class or, if you use float instead of flex, using the ms-List-cell.

You can also see that despite the fact that I copied and pasted the sizing logic, the pages end in uneven rows. 

 
#### Expected behavior:
 
I would really expect that the list just had a property to set it to grid mode, and that would at the very least take care of styling, and ideally also calculate the rows so they line up.

**Comment by Vitalius1** [comment]
@ericame `List` component was never designed to style it's rows. The main purpose of it is to take care of the logic comes with rendering large sets of items like: virtualization, scrolling, splitting into pages and so much more. The component itself has over 1000 lines of code and 0 styles to it (only some classNames hooks for the consumer to target).
It is being used as a base for other components like DetailsList, GroupedList which both provide their own styled rows via `onRenderCell` prop.

To answer your questions about [styling magic ](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/List/examples/List.Grid.Example.scss)we don't provide on the website it's more of an exception. We really try to minimize the behind the scenes styles of our examples and List showing a grid is unique in this matter as it actually needed to have some styles we unfortunately don't expose. @micahgodbolt should we do anything about this?

As for why you see uneven rows is because list split you set of items in pages and that is when you see going to a new row before filling the current one. Again List is not about the styling. As you've seen on the demo page it can render anything you give it and style it however you want.

P.S. For Grid List we have a different component in `@uifabric/experiments` package named `TilesList` which I believe works well in pair with `Tile` within the same package. But I am not sure if it will ever be moved to `office-ui-fabric-react` as it's more product oriented component.

**Comment by ericame** [comment]
@Vitalius1 thanks for this explanation! I was also just looking at the TilesList in digging for solutions, so maybe I'll try it out. If a component is in experiments, does that mean it's not really intended for production use, or just that it's specialized?

**Comment by Vitalius1** [comment]
@ericame experiments package it's not recommended being used in production. Any use of it is at consumer's own risk as there might be frequent breaking API changes.

**Comment by dzearing** [comment]
As @Vitalius1 mentioned think of `List` as a virtualized replacement for arrays of items.

I mocked up a simple "grid" here:

https://codepen.io/dzearing/pen/JmKPLL?editors=1010

I do want to also say a general layout grid (abstraction on css grid that can work with IE11) is on our list of things we want to get done soon.

Full fledged excel-like data grids have also been a long time ask. We have a few teams that have worked on more robust solutions and have considered moving the code into Fabric. I'm curious on what your needs are. Do you need editing? Or is it purely visual? Do you have selection requirements?

**Comment by ericame** [comment]
My requirements are actually closest to the TilesList as we have a series of tiles that we want to basically flex by row. I don't technically need the ListComponent, but I was trying it out for this purpose since there was a grid example and I thought it might add some focus and accessibility benefits as my data is technically list-like. I'm not editing or anything, but there are buttons on my tiles.

**Comment by micahgodbolt** [comment]
@ericame are you still needing anything here in this issue? We have a broad initiative to improve our website examples, if this issue has answered your questions, we'd like to close it up.
