### ISSUE TITLE
SearchBox autoFocus causes an Uncaught TypeError in office-ui-fabric-react (6.76.0)

### ISSUE THREAD

**Issue by avenezia** [OfficeDev/office-ui-fabric-react#6562]
### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/avenezia/pen/RerEox

### Bug Report 
 
 
- __Package version(s)__: office-ui-fabric-react 6.76.0
- __Browser and OS versions__: Chrome 69.0.3497.100, Edge 44.17763.1.0 on Windows 10
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: Power Query Online
 
#### Describe the issue:
 
While migrating our product to the latest version of office-ui-fabric-react (6.76.0), I noticed a bug with the autoFocus of the SearchBox: if set to true, it will cause a "Uncaught TypeError: Cannot read property '__events__' of null".
 
#### Actual behavior:
 
"Uncaught TypeError: Cannot read property '__events__' of null" is thrown when the autoFocus of the SearchBox is set to true: the full stack trace can be found in the codepen
 
#### Expected behavior:
 
No Uncaught TypeError to be thrown

**Comment by micahgodbolt** [comment]
Inputs (and our SearchBox) do not support an autofocus prop

![image](https://user-images.githubusercontent.com/1434956/46487083-fd724d00-c7b3-11e8-9571-6077fdb69ff2.png)

That property seems to only be used on selects https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/autofocus

**Comment by gregdardis** [comment]
@micahgodbolt inputs do support an autofocus attribute I believe:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Global_%3Cinput%3E_attributes (search for autofocus under attributes)

In JSX though it is autoFocus (note the capital F). https://stackoverflow.com/a/28891210

I would like to investigate this issue if it is worth investigating.

**Comment by gregdardis** [comment]
If autoFocus is set, _onFocusCapture is called before the ref is set on the root div.
[Here](https://github.com/OfficeDev/office-ui-fabric-react/blob/c61c1ca08a7c66101006165001e9193419704af2/packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.base.tsx#L157) is the line that has a problem. `this._rootElement.current` is null because the ref hasn't been set yet.

https://github.com/facebook/react/issues/7769 is a relevant issue, but the suggested workaround doesn't seem ideal (it seems to work on my branch though).

**Comment by micahgodbolt** [comment]
Doh :D autoFocus is part of the interface...carry on!

**Comment by avenezia** [comment]
@micahgodbolt @gregdardis Thank you both for the support on this :)
