### ISSUE TITLE
`ScrollablePanel` example with `onScroll` doesnt exist on `DetailsList`

### ISSUE THREAD

**Issue by omakoleg** [OfficeDev/office-ui-fabric-react#6591]
At page describing sample usages of `ScrollablePanel` there is code example for `DetailsList`
https://developer.microsoft.com/en-us/fabric#/components/scrollablepane

But current `DetailsList` docs page do not have `onScroll` defined at
https://developer.microsoft.com/en-us/fabric#/components/detailslist

Maybe another version used at docs page and current don't have it any more.
```
<DetailsList
 ...
   onScroll={this._onScroll}
/>
```

**Comment by dzearing** [comment]
The example has been fixed in this PR a while ago:

https://github.com/OfficeDev/office-ui-fabric-react/commit/e4e90ac74e1eb66844765437438bfb7cfa0df03c#diff-3349a08f4320e23cc4dfd03f6d7accef

The site is being updated shortly; we're blocked on the hosting site loading an old version of React and we're working with the owners to get this resolved asap.

**Comment by omakoleg** [comment]
Thx for fast feedback !
