### ISSUE TITLE
Shimmered DetailsList has no way to style shimmer height

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#6709]
![image](https://user-images.githubusercontent.com/1434956/47027582-88d8d000-d11c-11e8-8bca-0fa4b7573841.png)

Screenshot seemed easiest way to demonstrate.

`IShimmeredDetailsListProps` extends `IDetailsListProps` and then redefines styles as `IStyleFunctionOrObject<IShimmeredDetailsListStyleProps, IShimmeredDetailsListStyles>`

This would be fine except that StyleProps and Styles interface don't also extend DetailsList's StyleProps and Styles.

This means that there is __no typesafe way to provide styles to the DetailsList__.

Also, the root that is specified is passed into the listProps. Not quite following why that was done.

**Comment by micahgodbolt** [comment]
Customer also needs to be able to customize the height of the lines via props

![image](https://user-images.githubusercontent.com/1434956/47032948-72387600-d128-11e8-88c5-0220161ae897.png)

**Comment by micahgodbolt** [comment]
Might be as simple as allowing DEFAULT_SHIMMER_HEIGHT to be customized

**Comment by Vitalius1** [comment]
@micahgodbolt 
Initially when ShimmeredDetailsList was introduced it was passing the correct styles. I think this bug was introduced during the conversion to mergeStyles. This is definitely something that needs to be fixed.

About the possibility to customize the height I think we should leave it internally as this was the design intent to have a default look of 7px line thickness for a default DetailsList without a custom renderer. If the user wants a custom placeholder we allow it through the `onRenderCustomPlaceholder` prop. The one thing we can improve is having to pass the `rowProps` into it so that he can leverage the column measurements coming with it.

**Comment by Vitalius1** [comment]
The styles are past to listProps as that is a fading out to bottom overlay over the list with shimmered items to further emphasize that we don't know what the actual number of items will end up.
