### ISSUE TITLE
TextField: Fluent experiment

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#6747]

**Comment by betrue-final-final** [comment]
Hey, looks good, but these few things:

1. Placeholder looks like it's the wrong color. Should be #605E5C.
 ![image](https://user-images.githubusercontent.com/20363037/47366778-3a36b300-d693-11e8-8a29-eeffb30567e2.png)
2. Border color on hover should be #323130

**Comment by Vitalius1** [comment]
@betrue-final-final 
The color of the placeholder is correct to be #605E5C. It's just the way you are inspecting will not show you the placeholder as it's part of the Shadow DOM.
![screen shot 2018-10-23 at 3 21 17 pm](https://user-images.githubusercontent.com/29514833/47394323-552b1680-d6d7-11e8-87b0-15e9a548b221.png)

Thanks for catching the borderColor. Fixed in #6824

**Comment by marygans** [comment]
Needed Updates: 
- Hover state is currently: #323130. Update to #000000
- update error state to #a80000, currently #d13438 (rest) and #a4262c (on hover)

**Comment by betrue-final-final** [comment]
Current code is actually correct, and from our last meeting we agreed that we didn't need an error hover or focus state.
