### ISSUE TITLE
Windows Narrator says that the Checkbox selection state has changed when visually the checkbox state doesn't change - should use <input> with type=checkbox

### ISSUE THREAD

**Issue by petewu100** [OfficeDev/office-ui-fabric-react#6868]
Bug Report
Package version(s):
6.21.0
Browser and OS versions:
Windows server 2016: Version 1607 OS Build 1493.2339
Internet Explorer 11: Version 11.2239.14393.0

Priorities and help requested:

Are you willing to submit a PR to fix?
Yes

Requested priority:
High

Describe the issue:
Windows narrator will not say whether or not the color is selected when selecting the color.

Reproduction steps:
1. Open I.E 11
2. Navigate to:
    a. https://developer.microsoft.com/en-us/fabric#/components/checkbox
3. Turn on windows narrator
    a. https://support.microsoft.com/en-us/help/22817
4. Tab until you have a checkbox example selected
5. Press 'caps' + 'enter'
 

Actual behavior:
Checkbox does not visibly change state while narrator says the state has changed.
E.g.

1. Checkbox shows as checked.
2. Press 'caps' + 'enter'
3. Narrator says "unchecked"
4. Checkbox shows as checked.

Expected behavior:
Checkbox shows what narrator says the state is "checked" or "unchecked" and checkbox shows as checked or unchecked the same as narrator says it is.

This was previously reported in https://github.com/OfficeDev/office-ui-fabric-react/issues/5425, but nothing was done.  The problem is due to a combination of the fact that the Fabric control uses <button> tag with role="checkbox" and IE doesn't handle Caps+Enter on role="checkbox" per https://microsoft.visualstudio.com/OS/_queries?id=15279491&fullScreen=false&_a=edit.  This bug has been open against IE for a long time, and it seems unlikely to be fixed.

Can the Fabric control use `<input> with `type="checkbox"` instead of a `<button>` tag with `role="checkbox"`?  In general, it is always best to use HTML intrinsic controls with the proper semantics where possible rather than implement something custom.  In this case, HTML has an intrinsic control for a simple checkbox.  See https://www.sitepoint.com/how-to-use-aria-effectively-with-html5/.

**Comment by cliffkoh** [comment]
The suggestion from @petewu100 is to change the implementation of Checkbox to utilize HTML `input` instead of a `button`.

**Comment by cliffkoh** [comment]
Hi @petewu100, I'm not sure when or why Fabric started to use `<button>` instead of using `<input>`, but from what I gathered, there are significant challenges to using `<input>` and making it look correct.

Roughly:
* Styling options are supposedly really limited on input
* Styling focus border to look right when it is an input, and ensuring it is correct in high contrast mode as well.

I've opened #6872 to track a feature work to convert but this is not likely something to be tackled by the core team in short order.

Pull requests are welcome however - we have visual regression tests to help ensure all the visual requirements are not regressed on.
