### ISSUE TITLE
Fluent: Depth 64 uses incorrect colors

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#6904]
This line has an issue: https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/fluent-theme/src/fluent/FluentDepths.ts#L6

The opacity of the shadows for Depth64 should match that of the others.

**Comment by chuanqisun** [comment]
Thank you Mike for opening this up. I just noticed **both** layers of the depth 64 shadow are using a different opacity. `rgba(0, 0, 0, 0.22)` and `rgba(0, 0, 0, 0.18)`, instead of `rgba(0, 0, 0, 0.132)` and `rgba(0, 0, 0, 0.108)`. Maybe it was intentional, maybe not. I'm really curious about the design behind.

**Comment by betrue-final-final** [comment]
Actually this is by design. There's a ramp up of opacity 32px and up.

**Comment by mikewheaton** [comment]
@betrue-final-final The Fluent toolkit has these documented wrong:
![image](https://user-images.githubusercontent.com/1382445/47819510-f63d5100-dd17-11e8-8172-f88950717211.png)

The shadow itself is correct though. :)

**Comment by betrue-final-final** [comment]
Thanks. I will correct that
