### ISSUE TITLE
Unable to apply fluent theme & typography 

### ISSUE THREAD

**Issue by shivam-dev** [OfficeDev/office-ui-fabric-react#6915]
I am not able to apply fluent theme with office fabric as code below.

Fluent theme is not working for me.

```code 
import React from "react";
import { Customizer } from 'office-ui-fabric-react';
import { initializeIcons } from '@uifabric/icons';
import { FluentCustomizations } from '@uifabric/fluent-theme';
import '../styles/App.css';
import Main from './Main/Main.jsx';
initializeIcons();

class App extends React.Component {
	constructor(props){
		super(props)
	}
    render() {
        return (
        	<Customizer {...FluentCustomizations}>
	            <Main/>
        	</Customizer>
    	);
    }
}
export default App;
```

**Comment by micahgodbolt** [comment]
Can you put this into a codepen so that we can fork and attempt to resolve?

aka.ms/fabricpen

**Comment by JasonGore** [comment]
I thought it'd be a good idea to set up CodePen using the new `fluent-theme` package, so I [created one](https://codepen.io/jasongore/pen/mzZoZX). As you can see here, `FluentCustomizations` are applying as expected.

If you replace `Main` with a `Toggle` as I have in the CodePen above, you should see the customizations applying. In the code you pasted, I suspect the issue may be some other styling or theming overriding the `Customizer`, either in the CSS or within `Main` itself.

Since the CodePen is working as expected, I will close this issue for now. Please feel free to reopen or comment if you find any specific issues using Fabric components directly.
