### ISSUE TITLE
Dropdown on re-rendering correct new items. 

### ISSUE THREAD

**Issue by msadahiro** [OfficeDev/office-ui-fabric-react#6916]
### Environment Information 
 
 
- __Package version(s)__: 6.93.0
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/michaelsadahiro/pen/oaRVqW
 
#### Actual behavior:
 
In the CodePen, when we add a user, we are adding the user at the BEGINNING of the array. We are giving the new user a random default key. When we add the user, the dropdown does not get the correct default selected key. 
 
#### Expected behavior:
 
When I add a user, it would get the correct default selected key. 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: High
 
Products/sites affected: Azure Blockchain Workbench

**Comment by JasonGore** [comment]
I spent some time modifying the provided example to make sure that there isn't any issue with the example itself, particularly with using numeric keys and random/floor numeric usage. I've [created a new CodePen](https://codepen.io/jasongore/pen/VEJomQ) that's added a number of working and non-working examples, but I feel all should be working correctly:

```tsx
  private getKey = (person, index) => {
    const indexToAlphaKey = [ '0', 'A', 'B', 'C', 'D', 'E'];
    
    // This does NOT work with string keys in the options:
    return indexToAlphaKey[person.defaultDropdownKey || 3];
    
    // This works with string keys in the options:
    // return (index + 1).toString(); 

    // This does NOT work with string keys in the options:
    // return (person.defaultDropdownKey || 5).toString();

    // This does NOT work with string keys in the options:
    // return (person.defaultDropdownKey).toString();

    // This works with numeric keys in the options:
    // return index + 1; 

    // This works with numeric keys in the options:
    // return parseInt(index + 1); 

    // This does NOT work with numeric keys in the options:
    // return parseInt(person.defaultDropdownKey || 5);
  }
```

There is definitely something odd going on here with `Dropdown`. My initial suspicion would revolve around strict equality key comparisons inside of `Dropdown.base.tsx`, but also raises some questions of how numeric and string keys should equate from a design perspective. (Should a numeric default key match a string representation of that number? What if both string and numeric keys are present? Etc.)

**Comment by JasonGore** [comment]
After chatting with Michael for a bit I realized this example works when newly rendered `Dropdowns` have a different `defaultSelectedKey` as opposed to changing the `defaultSelectedKey` on `Dropdowns` already rendered. That let me to realize it was an issue with `div`'s `key` value preventing existing `Dropdowns` from being rerendered with their newly changed `defaultSelectedKey` prop.

In [another CodePen](https://codepen.io/jasongore/pen/JePPXL) I've made modifications to the `div`'s `key` that ensure it's unique and changes whenever the `defaultSelectedKey` changes. This ensures that any `Dropdown` previously rendered gets rerendered when its `defaultSelectedKey` changes.

As a result, this DOES appear to be an issue with the originally provided example and not with `Dropdown`. I will close this issue since it is not an issue with `Dropdown` itself.

**Comment by JasonGore** [comment]
Just wanted to add a bit more background here to this onion of a problem with multiple layers.

`defaultSelectedKey` prop can't changed after its initial value. `Dropdown` will absorb the initial value on construction and store it in its state as the selected value.

The original CodePen was changing `defaultSelectedKey` prop values on `Dropdowns` that were already rendered, which is why they weren't taking effect.

Possible fixes are:
1. Using the React `key` prop for instanced `Dropdowns` to indicate to React when they should be recreated (in this case when `defaultSelectedKey` changes.)
2. Make sure `Dropdowns` are rendered in the same order as `defaultSelectedKeys` are generated (appending new keys to the people array, in this case.)
