### ISSUE TITLE
Fabric React Tutorial not working

### ISSUE THREAD

**Issue by wonderplayer** [OfficeDev/office-ui-fabric-react#6965]
### Environment Information 

- __Package version(s)__: office-ui-fabric-react@6.98.1
- __Browser and OS versions__: Google Chrome 70.0.3538.77, Windows 10 Pro 64-bit

### Please provide a reproduction of the bug in a codepen:
 
Can't reproduce in codepen. I'm trying to follow just basic tutorial for fabric react in here: https://developer.microsoft.com/en-us/fabric#/get-started#core. Tutorial is for React TypeScript which doesn't work. With React JavaScript everything is fine.
 
#### Actual behavior:
 
Failed to compile.

C:/Users/rolands/source/repos/my-app/node_modules/@uifabric/merge-styles/lib/Stylesheet.d.ts
Type error: Ambient const enums are not allowed when the '--isolatedModules' flag is provided.  TS1209

     5 |  * @public
     6 |  */
     7 | export declare const enum InjectionMode {
       |                           ^
     8 |     /**
     9 |      * Avoids style injection, use getRules() to read the styles.
    10 |      */

 
#### Expected behavior:
 
Show a button on a site

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by Jahnp** [comment]
Thanks for reporting this @wonderplayer! I'll take a run through of this myself to see if I can sort out the issue and solution.

I know the TypeScript option for Create React App was [just recently added](https://github.com/facebook/create-react-app/releases/tag/v2.1.0), so it's possible there're some kinks there that haven't been worked out yet.

**Comment by Jahnp** [comment]
Ok, did a bit of digging.

It turns out this is related to a known issue in Fabric (#6386) that I was not aware of when writing this tutorial. 

Essentially, Fabric exposes a number of `const enum`s like the one you got in your error message, which Create React App's new TypeScript option [does not support](https://facebook.github.io/create-react-app/docs/adding-typescript):
![image](https://user-images.githubusercontent.com/307118/47956572-bf5b7b00-df63-11e8-8e60-4bf4cc244940.png)

One fix might be to set `isolatedModules: false` in your `tsconfig.json`, but the CRA build script will actually force the value back to true. Ejecting the app may let you fix this yourself, but that's *definitely* not desirable!

While we discuss and determine the usage of `const enums` in Fabric, we may need to not recommend using CRA's TypeScript option with Fabric out of the box.

**Comment by Jahnp** [comment]
Hey @wonderplayer , my PR #6967 auto-closed this issue, but to summarize here: since CRA's `--typescript` option doesn't support Fabric's `const enum`s out of the box, we recommend using `react-scripts-ts` instead. I've updated the tutorial to reflect this. Thanks again for reporting this!
