### ISSUE TITLE
DatePicker: the calendar does not change value after input changing

### ISSUE THREAD

**Issue by rlocus** [OfficeDev/office-ui-fabric-react#6992]
### Environment Information 
 
 
- __Package version(s)__: 6.99.0
- __Browser and OS versions__: Chrome, Win10

### Please provide a reproduction of the bug in a codepen:
set allowTextInput property as true
type any date value and open the pop up calendar by Enter key

 
#### Actual behavior:
 the selected date is not changed in the calendar pop up

 
#### Expected behavior:
the selected date should be applied in the calendar after any input text changing

#### Priorities and help requested:
  
Requested priority: (Normal)

**Comment by kenotron** [comment]
I'll try to recreate the repro on codepen now

**Comment by kenotron** [comment]
This needs a bit of discussion because it is actually a feature request. There always is a bit of logic to be discussed when going from a free-form input to a well structure data type (Date). So we can go about it several ways:

1. `new Date(textinput.value)`
2. find a library that can resolve text to date (e.g. 2 days ago) - but questions arise about locale, etc
3. use a third party service via a function prop like `onResolveDateFromTextInput` that can be overridden

We can certainly provide option (3) with (1) as the default fallback. (2) seems very limited and doesn't fit the goal of the Fabric project to be locale agnostic.

**Comment by kenotron** [comment]
Looking at the actual implementation some more, (3) looks to ALREADY have been done:
`parseDateFromString` exists. I'm updating that codepen above to include this functionality to see if it works for you.

**Comment by kenotron** [comment]
I found another issue that you filed, @rlocus - #6949. The whole context is much clearer now. Basically the bug is that `parseDateFromString` is called onBlur, but not on Enter. Okay, so we can definitely address this! On it!

**Comment by rlocus** [comment]
Greate job!
