### ISSUE TITLE
Please disableWarnings for icons by default to avoid 1000 pointless messages in the log on EVERY call to a SharePoint ClientSidePage (compromizing our ability to create professional solutions and making it extremely annoying to debug them)

### ISSUE THREAD

**Issue by frevds** [OfficeDev/office-ui-fabric-react#7040]
Please see this ticket: 

https://github.com/SharePoint/sp-dev-docs/issues/2867

The solution (https://github.com/OfficeDev/office-ui-fabric-react/wiki/Using-icons) is NOT APPLICABLE, since the issue is SharePoint itself, not the extension, and nobody of the devs there seems to care (neither do they have a GitHub page, or do they). 

![image](https://user-images.githubusercontent.com/5341447/48226127-30a19080-e39f-11e8-9ba3-e7fe474e690b.png)

**Comment by dzearing** [comment]
The SharePoint page is calling `registerIcons` multiple times, causing this. The root cause is that, and that code should be ensuring this does not happen. That's the whole reason for the warning, to call this perf issue out. I've forwarded to leads over there to get someone digging in.

It is certainly possible to disable warnings but would hide the problem.

**Comment by frevds** [comment]
Very nice! It's great fun to see you guys in action. Many thanks for the fast solution.

**Comment by dzearing** [comment]
@frevds Happy to help!
