### ISSUE TITLE
Documentation: IE11 polyfill recommendations

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#7077]
Right now, IE11 has some polyfills we'd likely recommend:

* es6-promise - https://www.npmjs.com/package/promise-polyfill
* es6-weakmap - https://github.com/polygonplanet/weakmap-polyfill
* intersectionobserver - https://github.com/w3c/IntersectionObserver/tree/master/polyfill

We should come up with some guidance on this. Maybe we need a `@uifabric/ie11-polyfills` package which can be referenced for ie11 usage.

Recently SharePoint hit an issue where ie11 WeakMap caused bugs when using JSON.serialize resulting objects as keys in a WeakMap. Upon getting the value after setting it, it would return undefined, which caused breaking bugs. Their fix was to use the polyfill.

Without guidance those kinds of issues will come back to blame Fabric components.

**Comment by dzearing** [comment]
Assigning to @kenotron to consider in the grand scheme of how partners should be supporting IE11. This pertains to bootstrap code as well (how can we ensure partners can dynamically load code in IE11 environments only?)

**Comment by kenotron** [comment]
I think our support story will HAVE to be different between 6.x and 7.x. 

For 6.x, since we didn't require polyfills, so I would recommend that we do not add polyfill requirements for this release.

We should plan on 7.0 to maybe require reasonable polyfills and yes, maybe one of the following:

1. go with a @uifabric/ie11-polyfills - increases bundle size
2. create two versions of entry points, letting the consumers maybe create two different bundles optimized for either - we can then target es6 in one build & es5 + polyfill for the other build

**Comment by KevinTCoughlin** [comment]
> * intersectionobserver - https://github.com/w3c/IntersectionObserver/tree/master/polyfill

This polyfill will be necessary for IE11 consumers once `VirtualizedList` is hoisted to OUFR proper.

**Comment by ecraig12345** [comment]
I just added this to the list of things to consider for the 7.0 release. We might also want to consider adding or recommending a promise polyfill (thanks @KevinTCoughlin for making the connection between #8667 and this issue).

**Comment by xugao** [comment]
@dzearing - knowing our current stand on IE11 support, I don't think this issue is relevant any more. Pls confirm
