### ISSUE TITLE
Semibold font weight should be using Semibold font face instead of weight css property.

### ISSUE THREAD

**Issue by brandonthomas** [OfficeDev/office-ui-fabric-react#7085]
### Environment Information 
 
- __Package version(s)__: 6.99

### Please provide a reproduction of the bug in a codepen:
Attempted to provide repro but CDN for react is dead so codepen is busted. Basically just render a calendar so you can see semi-bold fonts. Font-weight is used instead of a font face.
 
#### Actual behavior:
 
We programmatically impact the font weight. This results in closed shapes and incorrect tracking
 
#### Expected behavior:
 
We render an actual semi-bold font.

#### Priorities and help requested:
Yes

Requested priority: High as this means anything with semi-bold isn't rendering properly.
 
Products/sites affected: Admin center, anything using semi-bold.

**Comment by aneeshack4** [comment]
@brandonthomas I'll go ahead and assign this to you as said in the email thread you're willing to submit a fix for this.

**Comment by brandonthomas** [comment]
Sounds good thanks!

**Comment by Jahnp** [comment]
@brandonthomas just checking, is this still an issue you plan to look at?

**Comment by brandonthomas** [comment]
It is but it's just sitting on my backlog :S I've been doing tons of control refactors lately (fixing functional bugs and accessibility) so I'm pretty slammed there. If someone else wants to take it I'm not attached to it but I don't want to close it.

**Comment by micahgodbolt** [comment]
Trying to figure out the requested change here. Is this specifically about calendar? Or are you concerned about any use of font-weight rather than redefining font face?

It's been a bit since I've done font work, but it seems we have a single font mixin that creates light/semi-light/regular/semi-bold/bold variations of our font family name, and renders text with font-file specific to those weights.

![image](https://user-images.githubusercontent.com/1434956/71693130-8afa6f00-2d60-11ea-9fac-ab32a63d5c8e.png)

So by using our font face, and setting font-weight to bold, you will actually be using the bold variant of the font file, not just a fake bold style.
