### ISSUE TITLE
Icons: ascending and descending are identical

### ISSUE THREAD

**Issue by dcowen91** [OfficeDev/office-ui-fabric-react#7099]
The icons for Ascending and Descending are the same. They should point in different directions.

### Environment Information 
 
- __Package version(s)__:  latest 6.103 
- __Browser and OS versions__:  win10, chrome 70

### Please provide a reproduction of the bug in a codepen:

 https://codepen.io/anon/pen/RqpbqE
 
#### Actual behavior:
 
Ascending and Descending icons both point in the same direction
 
#### Expected behavior:
 
Ascending and Descending icons point in opposite direcitons

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: Office Workplace Analytics

**Comment by dzearing** [comment]
I see one has A on top and Z on the bottom. I see one has Z on the top and A on the bottom. I believe this is by design.

But, if you'd like alternating directional sort arrows, you could use `SortUp` and `SortDown`, which is likely better if you're sorting things other than names, like dates or numbers.

**Comment by dcowen91** [comment]
oh wow, I did not notice the A and Z swapping positions. I think in a previous version the arrow changed direction but A and Z were in the same place, so I completely missed that they are switching now. Since they are actually different, I'm going to close this issue. Thanks!

**Comment by dzearing** [comment]
Sure thing!
