### ISSUE TITLE
Add SignIn Icon

### ISSUE THREAD

**Issue by jsedlak** [OfficeDev/office-ui-fabric-react#7140]
**Describe the feature that you would like added**
Icon family currently supports a SignOut icon with a open "C" box racing right with a right arrow on the right side. A matching icon with a right arrow on the left to a reversed C (facing left) should exist with the SignIn name.

**What component or utility would this be added to**
Icon Library

**Have you discussed this feature with our team, and if so, who**
No

**Additional context/screenshots**

SignOut Icon
![image](https://user-images.githubusercontent.com/549309/48667316-0a67a900-eaa1-11e8-9c84-5a014bf53aff.png)

**Comment by Jahnp** [comment]
Hi @jsedlak , that's a fair gap to call out. This might be a silly question given that "Sign out" is a pretty self-explanatory action, but of curiosity, where in your app are you planning to use this icon? The reason I ask is that many apps use simple "Sign in" / "Sign out" strings instead of pairing them with icons. In fact, the original product team that requested the SignIn icon (VSTS/Azure DevOps) uses a string instead of the sign out icon in your screenshot:
![image](https://user-images.githubusercontent.com/307118/48724883-5456a900-ebdf-11e8-853e-1ae68030a4e4.png)

That said, there are two potential "sign in" metaphors already designed that we could simply move into the Fabric set:
![image](https://user-images.githubusercontent.com/307118/48724848-3a1ccb00-ebdf-11e8-99ef-6f36cd653729.png)

Would you be interested in either of those?

**Comment by jsedlak** [comment]
I firmly believe both should be added, relevant to #7141 and general lack of options for subset icons. As "PersonArrowRight" and "PersonKey". 

Instinctively I believe F286 has more implied meaning as it relates to authenticating a user since F054 simply has an arrow. And in a similar vein the existing "SignOut" icon does not posses any natural or implied reference to removing an authentication session. Perhaps a person with a key with a slash through it or a person with an open padlock would at least be closer.

Note that there are underlying consistency issues that should be resolved which is my primary concern. As a developer I'm not attached to a specific icon but only that I have access to a matching pair with which to communicate opposite actions. You wouldn't have a "Delete" icon without an "Add" icon.

**Comment by Jahnp** [comment]
Hi @jsedlak , sorry for the delay--between the holidays and a few other obligations, following up here took a bit of a delay. Apologies!

I hear you on having matching icons for opposing actions. That's totally fair and I agree 100%. I also agree that of the two options, `SignIn` makes more sense as a visual metaphor and as a name. Where we can, I want to make sure we're intentional about which icons are included in Fabric, so unless there's a clear and evident need for `PlayerSignIn`, I'm going to opt to request only `SignIn` be added to Fabric for now. 

I'll submit the request shortly and will add it to the [Fabric icons tool ](https://aka.ms/uifabric-icons) when it's available.

**Comment by Jahnp** [comment]
Hi @jsedlak , apologies for the delay--forgot to follow up here.

I've added `SignIn` to the [Fabric icons tool](https://aka.ms/uifabric-icons), so if you're using a custom icon subset, you can pick it up from there for now until it's added to the default set:
![image](https://user-images.githubusercontent.com/307118/49819744-08ed7180-fd2b-11e8-95e8-6a5034d1e30b.png)

**Comment by jsedlak** [comment]
Thank you - shall we close now or wait for it to be added to the default set?

**Comment by Jahnp** [comment]
If it's ok with you, I'd like to go ahead and close this for now, as there will be another update to the default set that includes new icons in a couple of weeks. Thanks again for bringing this to our attention!
