### ISSUE TITLE
GetClassName used in Contextual Menu always takes in a function for the type IStyleFunctionOrObject

### ISSUE THREAD

**Issue by chang47** [OfficeDev/office-ui-fabric-react#7234]
### Environment Information 
 
- __Package version(s)__: Latest version
- __Browser and OS versions__: All Versions

### Please provide a reproduction of the bug in a codepen:

For a contextual menu in a button, if you try to pass in a object for getClassName, the code should just use the code styles that you provide, If you pass in a function then it'll use the other styles that was also added in. 

However no matter if I pass in a function or object, the extra styles are always applied.

In my own cloned repro I debug through the code and I found that what we pass in for getClassName is always interpreted as a function even if it's an object.

Here's a codepen:
https://codepen.io/JoshChang47/pen/RqyXrr?editors=1010
 
#### Actual behavior:
 
I expect that if I pass in an object I would just have the style that I pass in and not the other default styles, similar to what would happen if you use getMenuClassNames
 
#### Expected behavior:
 
We have extra styles that comes with Fabric's default styling

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: Word Online

**Comment by KevinTCoughlin** [comment]
@chang47, I'm dedicating time tomorrow to investigate this. If its an issue, it _may_ be related to https://github.com/OfficeDev/office-ui-fabric-react/pull/6094.

However, I'm unsure if this is expected behavior or not. The addition of the `styles` prop was to benefit from our [mergeStyles](https://github.com/OfficeDev/office-ui-fabric-react/wiki/mergeStyles) approach to styling in `6.x`. While `getMenuClassNames` is the `classNames` convention for `5.x` kept as-is in `6.x` (or at least I thought so) for legacy reasons.

In your eyes, is this a regression with `getMenuClassNames`?

**Comment by chang47** [comment]
@KevinTCoughlin 

In a way yes it is, I was told that `getMenuClassNames` is being deprecated so the alternative to use would be `styles`. 

It seems like in the PR that you attached, `styles` is also being deprecated now too? If so, what should I be using?

**Comment by micahgodbolt** [comment]
Is this issue still valid?

**Comment by chang47** [comment]
No it's not, closing now.
