### ISSUE TITLE
Do we have any carousel office ui fabric component 

### ISSUE THREAD

**Issue by harshdamaniahd** [OfficeDev/office-ui-fabric-react#7241]
I am looking for carousel component , any suggestions

**Comment by Jahnp** [comment]
Hi @harshdamaniahd , unfortunately Fabric does not currently have a Carousel-like component. There are some patterns in product we've evaluated for pulling in, but that hasn't happened yet. We're tracking this feature request in #6893. We don't have an ETA at this moment, but we'll update that issue when there's something more to share.

As a friendly reminder for future questions, please use one of the [issue templates](https://github.com/OfficeDev/office-ui-fabric-react/issues/new/choose) when opening issues as it helps us route the best support for questions or requests like this. Because this is a duplicate, I'm going to go ahead and close this for now. Thank you for understanding!
