### ISSUE TITLE
In Persona card, the long name and title is not truncated.

### ISSUE THREAD

**Issue by lijunle** [OfficeDev/office-ui-fabric-react#727]
### Bug Report

- __Package version(s)__: latest, aka, v0.82.4
- __Browser and OS versions__: all

#### Describe the issue:

In Persona card, the long name and title is **not** truncated.

![image](https://cloud.githubusercontent.com/assets/1296500/21538326/d4f2deb8-cdd6-11e6-8d0d-acfcf14ba39a.png)

#### Actual behavior:

The strings are shown out of screen.

#### Expected behavior:

The strings should be truncated and show with `...`.

---

#### Proposal solution:

Add `width:100%` to [`.ms-Persona`](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Persona/Persona.scss#L63) class may solve this problem.

**Comment by micahgodbolt** [comment]
Unfortunately adding `width:100%` to `.ms-Persona` gives us 
![image](https://cloud.githubusercontent.com/assets/1434956/21549174/506fc600-cda5-11e6-9b37-eef062777880.png)

It appears that the problem is our use of table layouts as they don't behave properly with width 100%. It's possible there is SOME combination of CSS that will work with tables, but I haven't found it yet. I'm guessing that a move to flexbox will make this much easier. I'll see if we're ready to make that leap or not.

**Comment by lijunle** [comment]
@micahgodbolt The `width:100%` works fine in Chrome. Which browser are you using?

Yes, the problem is caused by `display:table`. But, why do we need `display:table` here? I remove the `table` and `table-cell`, everything is good.

**Comment by micahgodbolt** [comment]
@lijunle strange. I'm also in Chrome on PC. The tables are used to vertically center the content. Flexbox would be the better solution.

**Comment by micahgodbolt** [comment]
Ah, the difference is my screenshot was from the local version of the documentation, not the public website.

**Comment by dzearing** [comment]
This is now checked in.
