### ISSUE TITLE
Should Coachmark render on ComponentMount?

### ISSUE THREAD

**Issue by gbminnock** [OfficeDev/office-ui-fabric-react#7341]
Apologies if I have categorized this incorrectly as I am not sure if I have misunderstood the purpose of Coachmark or I am using it incorrectly.

---
Requirement: Load the coachmark once the component has mount (without any user interaction).

In the sample below I load a button and want the coachmark to show once rendered. I cannot seem to get it to render at all. 

[Codepen](https://codepen.io/gbminnock/pen/EGYJGR)

Tks,
Gary

**Comment by khmakoto** [comment]
The reason why `Coachmark` does not render on component mount is because it still doesn't have access to its `target` since the DOM is not loaded yet. Therefore, `target` is `null` at the time `PositioningContainer` is rendered, `opacity` is 0 and the `position` is not set. A workaround for this (not the best solution but a simple one for demonstration) is to set a timeout in `componentDidMount` and do a `forceUpdate` to have the `Coachmark` appear once the DOM is loaded.

The example you provided modified to do this can be found in the following [codepen](https://codepen.io/khmakoto/pen/oJgZrP).

Please let me know if this doesn't work so I can provide further assistance as necessary.

**Comment by khmakoto** [comment]
Ideally yes, the Coachmark should be used in conjunction with a user interaction to draw attention to the target, which is the way in which the component was designed. It can be, however, tweaked to perform on page/screen load as said before. In the end it all depends on how you want to use it and if it makes sense to use the component that way :)

**Comment by gbminnock** [comment]
Ok, thanks for the information

**Comment by NavaneethaDev** [comment]
@khmakoto Thanks for information. Below is my case
When the user clicks on a button CoachMark is popping up and on mouse over to this CoachMark, TeachingBubbleContent is displaying. Is there a way the TeachingBubbleContent can be displayed automatically after some seconds instead of mouse over? Thanks!
