### ISSUE TITLE
HoverCard support dynamic height for compact card and expand card

### ISSUE THREAD

**Issue by gggjtgxing** [OfficeDev/office-ui-fabric-react#7424]
**Describe the feature that you would like added**
```
compactCardHeight?: number | 'auto';
expandedCardHeight?: number | 'auto';
```

**What component or utility would this be added to**
HoverCard

**Have you discussed this feature with our team, and if so, who**
No

**Additional context/screenshots**
People are using a weird way to set the height dynamically [edit by @ecraig12345 - ask me for link to code example if you need it]

**Comment by Jahnp** [comment]
@atneik @chaofeng2014 FYI

**Comment by atneik** [comment]
@gggjtgxing Due to Animation and Positioning requirements of the `ExpandingHoverCard`, we need a specific `height`. We won't be able to just use `auto`. Here is the [animation issue from w3c working draft](https://github.com/w3c/csswg-drafts/issues/626). We not only use it to animate the bottom expanded card, but also pass the overall height (compact + expanded) to `Callout`. It helps `Callout` position it property while it is growing and when height is updated.

At the moment we let the consumer of the component update the height as they know their scenarios the best (hence the weird way). Thought we could handle the logic in the component itself and alleviate the problem to some extend, but still we will have to introduce a way for consumer to indicate when the content has updated. Not sure if this will cause more confusion. We might also have to introduce a new prop `expandedCardMaxHeight`, which will used to limit how big the card could get.
