### ISSUE TITLE
Ability to close a PivotItem

### ISSUE THREAD

**Issue by liuyangc3** [OfficeDev/office-ui-fabric-react#7437]
**Describe the feature that you would like added**
a Closeable `Pivot` able to close `PivotItem`

**What component or utility would this be added to**
Pivot

**Have you discussed this feature with our team, and if so, who**
no

**Additional context/screenshots**
a loos like demo https://codesandbox.io/s/z2krvoqykm

**Comment by ecraig12345** [comment]
This is an interesting idea. I've marked it as needing backlog review since I'm not sure whether it's something that ought to be included in the Pivot component itself or just implemented by consumers who want it (also because implementing it would require input from a designer).

For convenience, here's a screenshot from the codesandbox mockup (since it takes awhile to load):

![pivot with close button](https://user-images.githubusercontent.com/5864305/50262615-0348f900-03c7-11e9-9c72-b7cdfe466f1d.png)

**Comment by liuyangc3** [comment]
I am looking forward this feature, a closealbe tab is an common usecase

a example in other lib, https://ant.design/components/tabs/

![image](https://user-images.githubusercontent.com/6705844/50265898-7fd9e700-045c-11e9-8c96-7c3bf9c60e4b.png)

**Comment by micahgodbolt** [comment]
i've got a feeling we wouldn't bake this feature into pivots, but we'd provide a way to add a close button which you could use to modify the state driving your UI (i.e. not tracking hidden state in the component).

**Comment by micahgodbolt** [comment]
waiting for #7012 to wrap up, then updating pivots to slots will enable this feature.

**Comment by micahgodbolt** [comment]
actually, i'm just going to close this. We aren't going to do any action on this issue. This will be possible once pivots get converted.
