### ISSUE TITLE
How do I fire on click function when click on enter key?

### ISSUE THREAD

**Issue by piyumi25** [OfficeDev/office-ui-fabric-react#7439]
I need to submit form data when I am hitting the enter key. How do I implement for office ui react button component?

**Comment by micahgodbolt** [comment]
buttons have an onClick callback. 

```
<DefaultButton onClick={(ev) => console.log(ev)} > Click Me </DefaultButton>
```
https://codepen.io/anon/pen/wRgBLW

**Comment by piyumi25** [comment]
Thank you for your reply. But I need to call onclick function when I am hitting on the enter key of the keyboard.

**Comment by KevinTCoughlin** [comment]
> 
> 
> Thank you for your reply. But I need to call onclick function when I am hitting on the enter key of the keyboard.

@piyumi25, React's `onClick` event handler is invoked on _both_ mouse `click` and `keydown` of ENTER and SPACE keys when using OUFR's `Button` and its variants. This is demonstrated in the [Codepen linked above](https://codepen.io/anon/pen/wRgBLW). This is because the `onClick` is assigned to the `<button/>` element rendered which invokes `onclick` in those scenarios _natively_.

The same behavior is exhibited with the native `<button/>` and `onclick` JavaScript handler, see https://jsfiddle.net/c6tzg7e2/.

I've found the following related resources helpful in understanding the above:

- https://reactjs.org/docs/events.html
- https://reactjs.org/docs/handling-events.html
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

**Comment by KevinTCoughlin** [comment]
@piyumi25, a few follow-up questions, if you don't mind.

_How can we improve our documentation to better serve you_?

I've noticed that a number of questions you've raised are related to common app building scenarios such as submitting a form.

_Would you find common end-to-end app building scenarios useful as part of our documentation?_

Some examples I can think of:

- Parsing OUFR input control(s) information to build data to be submitted via form. #7297, #7347
- Handling form submission, perhaps even showing progress using OUFR controls. #7439
- Styling controls. #7239

We appreciate your questions and feedback as it helps inform us in how to better communicate with our customers. However, we do want to reduce the number of questions in our issue queue so that we can better prioritize library fixes, features, and general improvements.

Looking forward to hearing from you 😃!

**Comment by liuyangc3** [comment]
Hi, @KevinTCoughlin  a follow-up questions
I was wondering why onClick is not list in `IButtonProps`

**Comment by ecraig12345** [comment]
`IButtonProps` is defined as extending `React.AllHTMLAttributes<HTMLAnchorElement | HTMLButtonElement | HTMLDivElement | BaseButton | Button>` so it's probably picking up the definition of `onClick` from there. But I agree that's not terribly clear from a website documentation standpoint.

@natalieethell This might be something to think about with the API extractor work--could we indicate certain "essential" props that we want to include in the documentation even if they're inherited from a large built-in interface?
