### ISSUE TITLE
textLeft option in Toggle component

### ISSUE THREAD

**Issue by jpc1976** [OfficeDev/office-ui-fabric-react#7547]
The toggle component in Fabric-JS has a "textLeft" option, as demonstrated in the last example  [here](https://developer.microsoft.com/en-us/fabric-js/components/toggle/toggle).

This option does not however seem to have been ported to the corresponding React "Toggle" component (or if it supported, I cannot find a way to make it work).  

(This could either be a question or a feature request, depending on the situation. Thanks!)

**Comment by Vitalius1** [comment]
This is definitely not a question. It's a feature request from what it looks like. It feels like this is easily achievable with some flex-box styles and a prop and make sure the current look does not regress.
@betrue-final-final is the position of the label on a `Toggle` something we might want to have as an option? If so, in order to implement this, some redlines would be needed. Also, if introducing it we should do it for `left`, `right`, `above` and `below`.

**Comment by betrue-final-final** [comment]
I wouldn't do a text right or bottom option, but left would be ok. Top and left make sense because of our reading order. Right may make sense if you want to have all the toggles align that way. Aligning right would cause some reading issues with the label and the on/off text, and align bottom would cause confusion in a vertical list of toggles.
