### ISSUE TITLE
Pickers do not conform to Fabric toolkit spec

### ISSUE THREAD

**Issue by cliffkoh** [OfficeDev/office-ui-fabric-react#7556]
### Environment Information 
 
N/A

### Please provide a reproduction of the bug in a codepen:

https://fabricweb.z5.web.core.windows.net/oufr/6.120.0/#/examples/pickers

#### Actual behavior:
 
![screen shot 2019-01-07 at 2 53 54 pm](https://user-images.githubusercontent.com/29514833/50798149-265f1e00-128c-11e9-8fa6-653db7f9f075.png)
 
#### Expected behavior:
 
![screen shot 2019-01-07 at 2 50 19 pm](https://user-images.githubusercontent.com/29514833/50798113-fca5f700-128b-11e9-8960-6b91448a5470.png)

Related: https://github.com/OfficeDev/office-ui-fabric-react/pull/7538#issuecomment-452112114

**Comment by Vitalius1** [comment]
@betrue-final-final @joschect 
during some fixes on the `ActionButton` styles which are used in `PeoplePicker`, we discovered that the current height of the suggested items does not conform to the Fabric toolkit specs. The toolkit specifies a height of 44px when in fact we have 50px. The fix for the ActionButton supposes an addition of a 1px transparent border all around which will lead to a 2px white space increase between the suggestions and an overall height of 52px.

Should we try and take into the account the new 1px border and through some styles changes keep it at 50px or we should investigate into the possibility of bringing it to the toolkit specs of 44px?

**Comment by cliffkoh** [comment]
I recommend for the fix to make the height independent of ActionButton (since I don't believe the original design considered that it will be implemented with an action button).

I.e. overwrite the ActionBorder border to be none where it is used in picker and then other fixes that set it to 44px.

**Comment by betrue-final-final** [comment]
I would try and align with the toolkit if possible.

**Comment by cliffkoh** [comment]
@Vitalius1 would you be able to create a PR for this? :)

**Comment by Vitalius1** [comment]
Yes. I am looking into something else and this one is next on my radar. Most likely tomorrow.
