### ISSUE TITLE
Is there any option to load more than 50000 options in to dropdown?

### ISSUE THREAD

**Issue by piyumi25** [OfficeDev/office-ui-fabric-react#7561]
I need to load more than 50000 options to drop down. Is there any option to avoid getting stuck when load such huge options like virtualized combo box.

**Comment by Vitalius1** [comment]
I honestly don't see a use of a `Dropdown` with so many items in it. Why not use the `VirtualizedComboBox` as seen on the `ComboBox` demo page, which will allow the user to type the option he is interested in instead of scrolling. I would hardly see a scenario where you would scroll to the 50000th item in a `Dropdown`.

Would you mind explaining your scenario so that maybe we can direct you to a more suitable component?

@ecraig12345 @cliffkoh any thoughts?

**Comment by piyumi25** [comment]
thank you for your reply. I tried with virtualized combobox but I can not see the values in the text field when I am selecting multi select check boxes. I have to focus out to see the values. That is the issue I have when using virtualized combobox.

**Comment by Vitalius1** [comment]
We looked a little into #7558 too. Apparently, this is not possible now. Moreover, I am interested now about your use case... so assuming you have a multi-select dropdown with 50000 options and the user starts to select let's say 20 of them. You would still not be able to see them all in the text field. Especially that in Dropdown you can not input from the keyboard. In ComboBox even if you would be able to see them in the text field while selecting and also enabling the `allowFreeForm`, which would give you the ability to edit those already selected options, I still think that having already 20 items selected would be very not user friendly to go there and edit them as you would not see past the width of the text field.

Can you please explain your need for seeing the options in the text field while selecting and also have a virtualized Dropdown.

In any case, if you still need this you could probably implement it yourself by following the example of the VirtualizedComboBox which is nothing more than a wrapper for ComboBox injecting a virtualized list. Not sure though how that would work with multi-select.
https://github.com/OfficeDev/office-ui-fabric-react/blob/9c9af6633a74a548915ceae24cc7abb67bd2d13d/packages/office-ui-fabric-react/src/components/ComboBox/VirtualizedComboBox.tsx#L8-L47

**Comment by Vitalius1** [comment]
@ecraig12345 as part of the `ComboBox` and `Dropdown` consolidation should this be a feature to add support in `Dropdown` as we have today in `VirtualizedComboBox`?

**Comment by Vitalius1** [comment]
Even though as @betrue-final-final mentioned that Dropdown should not be used with that many items. Because inherently a dropdown is not supposed to give you the ability to type but instead scroll and select, I don't see much value of having a virtualized list of options in here. Correct me if I am wrong.

**Comment by Vitalius1** [comment]
@piyumi25 https://codepen.io/vitalius1/pen/BvOojj here is something that might interest you. You would have to extend from BasePicker though and create your own picker. I used TagPicker for a quick demo what can be done with pickers and a lot of items to chose from.

**Comment by micahgodbolt** [comment]
this feature is already being tracked in #6030. Going to close this issue down.
