### ISSUE TITLE
TextField: Underlined/multiline/borderless: borders appear and change field height in high contrast mode.

### ISSUE THREAD

**Issue by crazyfraggle** [OfficeDev/office-ui-fabric-react#7565]
### Environment Information 
 
 
- __Package version(s)__: >6.49.0 (all versions on fabric demo seems to be affected)
- __Browser and OS versions__: IE11/Edge in High Contrast mode

### Please provide a reproduction:

Can be seen on website when High Contrast mode is enabled.
https://fabricweb.z5.web.core.windows.net/oufr/6.119.0/#/examples/textfield
 
#### Actual behavior:

Underlined TextFields have all 4 borders, and additional bottom-border from wrapper.
Multiline and Underlined TextFields change height when changing focus/active state.
Borderless TextField gets a border when focused.
 
#### Expected behavior:
 
Unsure if this is by design, or accidental behavior. The height changes are obviously wrong, but should we keep all borders for underlined text fields, or should we strive to look as similar to non-HC mode as possible?

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal
 
Products/sites affected: Outlook web contact editing
 
#### Screenshots

Underlined textfields
![image](https://user-images.githubusercontent.com/1014519/50894746-529daa80-1404-11e9-9fa2-4183b61b7416.png)

Borderless with focus:
![image](https://user-images.githubusercontent.com/1014519/50894790-76f98700-1404-11e9-8b19-6c338cc4723f.png)

Jumping on focus: (Sample from multiline textfield)
![peek 2019-01-09 11-52](https://user-images.githubusercontent.com/1014519/50895041-33534d00-1405-11e9-913a-4cd609e92994.gif)

**Comment by Vitalius1** [comment]
I believe these changes were introduced in #3870 in pursuing to improve the HC styles for focus state for TextField, ComboBox, and Dropdown. Will dust off my Windows machine and see if I can take a look into what is the issue.

Meanwhile, @crazyfraggle, can you put in the description a couple screenshots with the TextField in HC so that our designers can take a look at whether we need to correct the HC borders for underlined variation.
Thanks for bringing awareness on this issue!

**Comment by crazyfraggle** [comment]
@Vitalius1 Added screenshots.
