### ISSUE TITLE
LayerHost: shouldComponentUpdate cancels any update to children

### ISSUE THREAD

**Issue by cschleiden** [OfficeDev/office-ui-fabric-react#761]
### Bug Report

- __Package version(s)__: >= 0.82.0

#### Describe the issue:

The `shouldComponentUpdate` implementation of `LayerHost` just returns false. Why do we do this? This causes any child/wrapped  component to be rendered initially but then not updated. Is this by design? If so, we should probably update the documentation. With the latest changes the examples doesn't actually wrap anything in the `LayerHost`, but still talks about wrapping. 

Example:
http://codepen.io/anon/pen/VPvaQR
When checking/unchecking the checkbox, both counters should increment. But since one is wrapped in the LayerHost it's never updated.
(Loads latest code from localhost:4321/dist since CDN is out of date).

**Comment by dzearing** [comment]
While I understand your repro, I'm not sure we want to change this. Let me explain:

When a `Layer` renders, it needs to project into a target. In my current `Layer` implementation, if you provide a hostId, it will `getElementById` with the ID to identify the element to inject the layer within. If it can't find one, it needs a div appended to the end of the DOM to inject within.

`LayerHost` originally was written such that if you hosted children within it, it would render the children, and then layers at the end. However, it turned out to be rather rigid. There are plenty of cases where you just want to stick layers in a totally unrelated section of the DOM. So, rather than totally deleting LayerHost, I just made it render an uncontrolled DIV to inject content within. Returning `false` in `shouldComponentUpdate` means that layered content can render into it and React won't dom-diff it. Layers own their own rendering, LayerHost just becomes a dumb uncontrolled div.

So in your example, rather than wrapping content in a LayerHost, wrap it in a div, and stick a LayerHost as the last child of the div. The layer will project within the LayerHost, and your content will update.

Does this make sense? There is an example in the demo project (via gulp serve) that does this.

**Comment by dzearing** [comment]
BTW totally open to suggestions.

**Comment by cschleiden** [comment]
It makes sense, but took me by surprise :) My scenario was: I have an app using react-router, and I was using a `Layer` for showing a nav sidebar for a certain screen width. To position the `Layer` I had basically my whole app wrapped in a `LayerHost`. When upgrading to office fabric 81.3, initial rendering worked just fine, but I couldn't navigate to any other route.. 

Maybe we should just call out in the documentation that wrapping has side effects, and/or update the example:

![image](https://cloud.githubusercontent.com/assets/2201819/21786002/c573b6f8-d676-11e6-9596-a54b18ac55d6.png)

**Comment by dzearing** [comment]
The official website hasn't picked up the latest examples; once it does the example on the site will have the update.

**Comment by cschleiden** [comment]
But it will still **talk** about wrapping! :)

**Comment by cschleiden** [comment]
Fixed with #776
