### ISSUE TITLE
Question: Ability to extract styles of all Fabric react components to css/scss for use in other frameworks

### ISSUE THREAD

**Issue by rahulnakmol** [OfficeDev/office-ui-fabric-react#7689]
I am quite excited about office fabric UI and value of fluent design inclusions coming In. Is there a way we can extract the css styles of all components into one css/scss file so we can include the components's look & feel in other frameworks like Vue/angular.

Any direction to generate css/scss files from styles.ts. 
For example  from [Breadcrumb.styles](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.styles.ts) to Breadcrumb.css

I looked at the office Fabric JS (the repo seem to be dead with no traction since '17) and its fabric.component.css is outdated.

**Comment by mikewheaton** [comment]
You may be able to use [server-side rendering with merge-styles](https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/merge-styles#server-side-rendering). This should output the CSS for a component in its default state.

This will get complicated if you want to capture the variations of each component (hundreds of unique combinations based on state and props) and convert those into meaningful CSS class names. It's probably easier to manually write CSS for each component, essentially doing the reverse of what we did in converting the SCSS styles to merge-styles.

**Comment by dzearing** [comment]
I don't think SSR would solve the issue @mikewheaton. Basically just to emphasize your second paragraph, SSR rendering will output a snapshot of the css in time. As props and state mutate, the classes required are different, and the way that mergeStyles works is to avoid pre-registering all css permutations. That means that, yes, you might get the "toggle" css rules if server rendering in the "off" state, but unless you re-render it in the "on" state, you'll be missing rules. And, you'll need to "replay" this rendering on the client, to rehydrate the classes generated. Which just won't work.

There are probably a couple avenues we can take here to better support partners using other frameworks:

1. Short term, there is no reason you couldn't evaluate the rules yourself. Because they're just JavaScript functions which return the rules, it is possible to pull the getStyles function from a given .styles file and execute it in any framework, assuming you have the props. I think there are quite a few caveats and work here. 

2. Longer term, we'll likely transition to web components, once IE11 usage is driven down. Then you could just use `<ms-checkbox ... />` in your Angular app directly. Then you won't need to manage the extraction of styling.

3. On top of web components, integrating css variable output to our theming system would enable the theme values to be injected into any css processing system.
