### ISSUE TITLE
fluent breadcrumb aggressively truncates

### ISSUE THREAD

**Issue by bigbadcapers** [OfficeDev/office-ui-fabric-react#7725]
### Environment Information 
 
- __Package version(s)__: current + fluent theme
- __Browser and OS versions__: all browsers

#### Actual behavior:
![image](https://user-images.githubusercontent.com/20586907/51416618-2a622a00-1b2f-11e9-8462-31370dc6a69b.png)

![image](https://user-images.githubusercontent.com/20586907/51416643-42d24480-1b2f-11e9-8a7c-a26234d8d1ba.png)

in both breadcrumbs, there is room to avoid deleting the folder names and truncation should be avoided
 
#### Expected behavior:
 
caperez has redline updates from mpatruno that i can share via internal mail

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: For Fluent
 
Products/sites affected: All file lists including ItemScope

**Comment by bigbadcapers** [comment]
the original screenshot is from ODB but I think your screenshot shows the requested improvement equally well @mikewheaton , in the first fragment you showed, the middle node is being unnecessesarily and too aggressively truncated even though the window was very likely to show more of the folder's name after the letter "C".   The "max-width: 160px" rule is too aggressive and when there is room for more of the filename the right behavior would be to be more flexible and let that node be wider

**Comment by mikewheaton** [comment]
@bigbadcapers ODB looks to be using the same Knockout component as ODC. So this isn't something we can fix in Fabric React. I'm not sure who the best contact is on the engineering team to look into making a fix for ODB/ODC.

**Comment by bigbadcapers** [comment]
If the fix is localized to the file surfaces that are using ItemScope, that is acceptable, because we are aggressively replacing all the Knockout stuff with ItemScope. 

Doclibs inside teamsites are already using ItemScope. Are those powered by the Fabric React control? If so, that's the right place for this fix.

**Comment by mikewheaton** [comment]
It turns out that a SharePoint document library, like on our ODSP Design team site, *is* using the Fabric React Breadcrumb.

I've tried removing the maximum width and it seems to work fine without it. It will show as many full items as possible, and then place anything that doesn't fit into the overflow menu. See below.

With max width:
![image](https://user-images.githubusercontent.com/1382445/52137375-3bb33800-25ff-11e9-8aca-5735df56762e.png)

Max width removed:
![image](https://user-images.githubusercontent.com/1382445/52137398-466dcd00-25ff-11e9-9c0a-d621e40e3e09.png)

@micahgodbolt, do you know who's most familiar with Breadcrumb? I'm not sure why the max width was added, and am concerned that this might cause some other issue I'm not anticipating.

**Comment by bigbadcapers** [comment]
This looks promisiiiiiiiing :)

**Comment by micahgodbolt** [comment]
@dzearing did the last refactor. You might see if that is just legacy styles from previous conversions or something he added.

**Comment by mikewheaton** [comment]
I found the same max-width in the previous SCSS styles. This also matches what's in the Knockout control, so I'd say we brought this over from the previous Fabric components. At the time we didn't have `OverflowSet` or any logic for moving the items into the overflow. So I think we just set it to show a maximum of 4 items with a 160px max for each to prevent it from getting too wide.

Now that we have a more advanced layout method, we should be fine to remove the max width.
