### ISSUE TITLE
[merge-styles / Checkbox]: generated css rule targets wrong class name when using $-references

### ISSUE THREAD

**Issue by Nimelrian** [OfficeDev/office-ui-fabric-react#7763]
merge-styles seems to resolve $-references incorrectly. I found this issue when trying to override the Checkbox's checkmark element's style when the root element was hovered. The css rule inserted into the 
merge-styles stylesheet references a different class than the one which is applied to the checkmark element.

### Environment Information 
 
- __Package version(s)__: OUFR: 6.129.1

### Please provide a reproduction of the bug in a codepen:

 https://codepen.io/nimelrian/pen/GzgyGo
 
#### Actual behavior:
 
The style with the selector `:hover $checkbox` is applied correctly.
The style with the selector `:hover $checkmark` is not applied, because the generated rule targets the wrong class.
![image](https://user-images.githubusercontent.com/8960836/51590690-22b5d300-1eeb-11e9-8c22-1d23c85364be.png)

 
#### Expected behavior:
 
Both styles should be applied correctly, the $-references should get resolved to the correct classes.

#### Priorities and help requested:
  
Requested priority: Normal

**Comment by leddie24** [comment]
@dzearing, do you have any suggestion regarding this?  Here's a codepen (copied from this issue [#4138] and modified a bit)

https://codepen.io/leddie24/pen/zeGEEQ?editors=1011

mergeStyles doesn't seem to cooperate that well with subComponents.  In the codepen above, it works fine with $a, $b, but not $c, which is under a SubComponent, which is a similar situation for the `Checkbox` component ($checkbox works fine because it's a simple div in the render, but $checkmark is rendered under `<Icon>`).

**Comment by dzearing** [comment]
Let me dig in.

**Comment by dzearing** [comment]
The scenario in your codepen isn't supported. In fact the whole `$` support in merge-styles is deprecated (and docs have been updated.) There was  a perf issue with it, because `$` selectors would need to be re-registered if the targeted part's class were to mutate.  To avoid the perf concern, you can use global class names (or dynamic generated ones that are static):

Also in your codepen, you're not injecting props.className into your component, so that's why your red is not working.

Updated codepen:
https://codepen.io/dzearing/pen/EryEyd?editors=1011

Hope this helps. Please feel free to close if so.

**Comment by Nimelrian** [comment]
Ok, looks like I'll have to do another migration pass over my codebase again if that is the case.

Closing.
