### ISSUE TITLE
Facepile: Descriptive Overflow text is slightly off-centered

### ISSUE THREAD

**Issue by tabrumle** [OfficeDev/office-ui-fabric-react#7773]
### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/tabrumle/pen/MLwbKB
 
#### Actual behavior:
 
Descriptive overflow text is slightly off-centered for the Facepile
 
#### Expected behavior:
 
Descriptive overflow text is centered

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Low
 
Products/sites affected: Office Online

**Comment by leddie24** [comment]
Hi @tabrumle, thanks for submitting your issue.  Is this a horizontal or vertical alignment that you're noticing?  I changed the text from `+8` to `TT` and it looks pretty centered horizontally and vertically.  I can see it's a bit off center horizontally when it's using the original text of `+8`, but that's more of an issue with the font family rather than our styling.

![image](https://user-images.githubusercontent.com/1291968/51637497-d54c5c80-1f10-11e9-8fe5-94762accb97a.png)

**Comment by tabrumle** [comment]
Its vertical alignment that im noticing. It appears that the spacing between the top and bottom of the text to the coins outter circle differs. Specifically 38px for the top vs 33px for the bottom.
![coincentering33](https://user-images.githubusercontent.com/42159057/51638747-11cd8780-1f14-11e9-9165-5e7346cd5023.PNG)
![coincentering38 2](https://user-images.githubusercontent.com/42159057/51638719-f793a980-1f13-11e9-8309-549ca06fd2a2.PNG)
![coincenteringdom](https://user-images.githubusercontent.com/42159057/51638725-f9f60380-1f13-11e9-845b-adadf1f258df.PNG)

**Comment by leddie24** [comment]
This issue is a bit tricky.  It's difficult to vertically align text, especially since it seems to work fine at smaller persona sizes.  We want to avoid creating one-off rules for the larger size100 Persona.  The span that contains the text itself is centered properly.  If a consumer were to ever change the font with this component, then the vertical alignment would differ from font to font.  @betrue-final-final, any thoughts regarding this?  I'm not sure there much we can do.

**Comment by betrue-final-final** [comment]
Yes, @leddie24 is correct. If we only use one font, then we can center it based on caps only, but descender lengths and diacritical spacing varies font to font. If there is some magic to do that then I would love it, but if not, this is the best we can do.
