### ISSUE TITLE
DetailsList renders all checkboxes in some hosts

### ISSUE THREAD

**Issue by elegault** [OfficeDev/office-ui-fabric-react#7808]
I have a repro of an issue where all of the checkboxes suddenly appear in every list item row when an item is selected/checked.  This only occurs in Chrome and in Safari on iOS (not sure about Android).  I have a post about this on StackOverflow: https://stackoverflow.com/questions/54295228/office-ui-fabric-detailslist-checkboxes-rendered-incorrectly-on-mobile-devices/54354947#54354947.

You can also see it with my CodePen here: https://codepen.io/elegault/full/JxGpQg.  Open it in Chrome and enable device emulation mode in DevTools. It should behave like this: https://www.screencast.com/t/qBNx6eUNI.

Is this by design or a bug for those hosts?

**Comment by micahgodbolt** [comment]
Dug in a little on this quick. Seems the visibility of the check is based on opacity, and in the emulation example the opacity is incorrectly set to 1, so it's not some odd style issue, but rather state is set incorrectly, or styles calculated wrong.

**Comment by micahgodbolt** [comment]
![image](https://user-images.githubusercontent.com/1434956/51856046-8bce8980-22e3-11e9-8592-3c114d4cbde4.png)

**Comment by leddie24** [comment]
This is by design, at least from my conversation with @ThomasMichon.  @betrue-final-final, can you take a look at this as well?

The code for it looks intentional as well (with `anySelected` being added).

```
const isCheckVisible = isVisible || selected || anySelected;
```

The idea is that on a touchscreen device, it shows you the checkboxes so you know what can and can't be selected (contrary to a mouse controlled device where they have the option to hover over a row to see the checkbox visible).

**Comment by elegault** [comment]
That makes sense - thank you @leddie24!
