### ISSUE TITLE
How to register all fontawesome icons?

### ISSUE THREAD

**Issue by Edelf** [OfficeDev/office-ui-fabric-react#7815]
I need to implement a feature where the user can pick a FontAwesome icon to be shown on a button, by typing the icon name, e.g. "fab fa-microsoft".

In the [documentation](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Using-icons) it is shown how to register specific icons: 
```
import { registerIcons } from '@uifabric/styling';
import Icon from '@fortawesome/react-fontawesome';

registerIcons({
  icons: {
    'Home': <Icon icon={['fal', 'home']} />,
    'HomeSolid': <Icon icon={['fas', 'home']} />,
  }
});
```
But I need to be able to use/register all available fontawesome icons.

TL;DR: How can i register all fontawesome icons?

**Comment by natalieethell** [comment]
Hey @Edelf from what I can see, I don't believe that Font Awesome has an API that loads all of the icons and/or icon names at once (correct me if I'm wrong). 

Since you must pass in each Font Awesome icon name, in order to register all of the icons, it looks like you may have to loop through all of the names one by one. 

The `registerIcons` function takes in property `icons`, which is a dictionary with keys of type string and values of type string or JSX.Element. Perhaps an option for you is to take the [Font Awesome cheatsheet](https://fontawesome.com/cheatsheet?from=io), store them in a JSON blob, and loop through those to register them. This [StackOverflow article](https://stackoverflow.com/questions/27992992/i-need-list-of-all-class-name-of-font-awesome) shows a way to do that.

I will just mention, lastly, that since Font Awesome has 1500 icons in the free bundle, I do believe it would be a pretty big perf hit if you were to register them all in one go.

Hope this answers your question!

**Comment by Edelf** [comment]
Hi @natalieethell, thank you for the reply.
Fontawesome allows us to add their collection like this:

```
import { library } from '@fortawesome/fontawesome-svg-core';
import { fab } from '@fortawesome/free-brands-svg-icons';
import { far } from '@fortawesome/free-regular-svg-icons';
import { fas } from '@fortawesome/free-solid-svg-icons';

library.add(fab, fas, far);
```

I was hoping that fabric would allow something similar to:
```
import { library } from '@fortawesome/fontawesome-svg-core';
import { fab } from '@fortawesome/free-brands-svg-icons';
import { far } from '@fortawesome/free-regular-svg-icons';
import { fas } from '@fortawesome/free-solid-svg-icons';

library.add(fab, fas, far);
**initializeIcons(library);**
```
Or similar with the same outcome.
