### ISSUE TITLE
Documentation Update - React UI Fabric Dropdown Control

### ISSUE THREAD

**Issue by duffysp** [OfficeDev/office-ui-fabric-react#7819]
Not really sure where I should file this but can selectedKey and defaultSelectedKey be added to the documentation for the React Dropdown Control:
https://developer.microsoft.com/en-us/fabric#/components/dropdown#Implementation
They seem to be missing from the Optional Members section despite having examples of it in the code; Lost a little bit of time on this.

Never filed one of these before so apologies if this is in the wrong area.

Thanks.

**Comment by natalieethell** [comment]
Hey @duffysp! I do see `defaultSelectedKeys` and `selectedKeys` documented in the Implementation section you linked

<img width="1129" alt="screen shot 2019-01-28 at 10 57 22 am" src="https://user-images.githubusercontent.com/14134000/51859267-92f99580-22eb-11e9-8cce-0209a408a5b9.png">
<img width="1131" alt="screen shot 2019-01-28 at 10 57 34 am" src="https://user-images.githubusercontent.com/14134000/51859260-90973b80-22eb-11e9-9159-08bb8e17eb2d.png">

Is it possible that you were also seeing blank spaces in the properties table when loading the page in your browser, as mentioned in [the issue here](https://github.com/OfficeDev/office-ui-fabric-react/issues/7817)?

**Comment by duffysp** [comment]
Hi Natalie, thanks for getting back. 
Although defaultSelectedKeys and selectedKeys (used for multi-select dropdowns) are on the documentation, defaultSelectedKey and selectedKey (used in single choice dropdowns) are both missing.
EG:
![image](https://user-images.githubusercontent.com/45501139/51860200-ee01ab80-2330-11e9-828c-956e2ea03103.png)
Example:
![image](https://user-images.githubusercontent.com/45501139/51860226-04a80280-2331-11e9-9f97-4ecd71493bf6.png)

Hope this helps,
Thanks.

**Comment by natalieethell** [comment]
Ah I see, thank you for clarifying! We definitely want those documented! 

Luckily, this should actually be fixed pretty soon with the work I've been doing to re-vamp the documentation (tracked [here](https://github.com/OfficeDev/office-ui-fabric-react/issues/6780)). It looks like these props, and others, are missing because our current documentation doesn't show what an interface "extends". Those props are coming from `ISelectableDroppableTextProps`, which `IDropdownProps` extends. Our new documentation should make this inheritance more obvious and also link to `ISelectableDroppableTextProps`.

Thanks again for bringing this up. I'll link this issue in the "Re-do Implementation Section" of the issue I liked above to make sure it's tracked.
