### ISSUE TITLE
ESC keypress is re-opening 'TeachingBubble' rather than closing it

### ISSUE THREAD

**Issue by kmrrakesh** [OfficeDev/office-ui-fabric-react#7820]
### Bug Report 
 
- __Package version(s)__: (6.129.4)
- __Browser and OS versions__: (Edge and Windows 10)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)

Requested priority: (Normal) 
 
Products/sites affected: (OfficeFabric)

#### Describe the issue:
 
ESC keypress is re-opening 'TeachingBubble' rather than closing it in edge browser, while in chrome working fine

#### Actual behavior:

ESC keypress is re-opening 'TeachingBubble' rather than closing it in edge browser

#### Expected behavior:

ESC keypress should close 'TeachingBubble'

**Comment by natalieethell** [comment]
Hey @kmrrakesh good catch! It looks like the function passed into `onDismiss` in the TeachingBubble examples are all flipping the value of `isTeachingBubbleVisible`, however, that gets called twice when the ESC key is pressed: once in TeachingBubbleContent, once in Popup, which is rendered within a TeachingBubble. So, the value gets flipped once to false and then once to true. 

It's interesting that this only appears to be happening in Edge and not Chrome, but perhaps that's a timing thing. 

Ultimately, the escape key code logic for `onDismiss` exists in both TeachingBubble and Popup. I wonder if we need this logic in both or if it would be okay to just keep it in Popup. I'll check with @leddie24 tomorrow to see what he thinks, since he added this original logic.

If we want to keep the logic in both places, then our next step would be to change the `_onDismiss` function in the TeachingBubble examples to just set `isTeachingBubbleVisible` to false.

**Comment by natalieethell** [comment]
Just spoke with @leddie24 offline and we agree that we can probably remove the key code escape logic from TeachingBubbleContent since it already exists in Popup. I'll tag this as a bug and get a PR out soon!

**Comment by natalieethell** [comment]
Reopening this issue, as the original fix introduced a regression.

**Comment by natalieethell** [comment]
Reverting the original "fix" here: https://github.com/OfficeDev/office-ui-fabric-react/pull/7981. After that PR, we'll discuss this ESC issue further.
