### ISSUE TITLE
Modal doesn't work in a onRender function

### ISSUE THREAD

**Issue by fc73** [OfficeDev/office-ui-fabric-react#7832]
Hi all, 
I am new to ui-fabric-react, recently I met a problem on using modal. Here is the detail info for the problem:

I render a list in a pivot, and I want  to render modals for each element of the list. I have already binded the showmodal and closemodal function. It works well if I render the modal directly in the pivot. But it doesn't work when I render it in the list.

Any help on this would be really appreciated.

**Comment by fc73** [comment]
The error message is : TypeError: Cannot read property '_showModal' of undefined

**Comment by fc73** [comment]
Hi @natalieethell  I've written some sample code in CodePen. Could you please check it for me?

Here's the link: [https://codepen.io/fc73/pen/gqLgep]

**Comment by natalieethell** [comment]
Hey @fc73 thanks for the CodePen! It looks like the issue here is that `onRenderCell` will only be called for certain events, such as a window resize. If you look at your example, click on one of the "Open Modal" buttons, and then resize, you'll see that the `onRenderCell` is called and the state is reflected in that cell. 

Since you are maintaining your state globally, one way to do this is by forcing an update to your list on a button click.

@KevinTCoughlin and I have a working CodePen here. https://codepen.io/naethell/pen/zeNrGm I hope this helps.
