### ISSUE TITLE
tagpicker auto-selects first list option

### ISSUE THREAD

**Issue by k8rl** [OfficeDev/office-ui-fabric-react#7861]
### Environment Information 
 
- __6.129.1)__: (fill this out) 
- __IE11, Win10__: (fill this out if relevant)

#### Actual behavior:
 
There are two issues:

1) When text has been entered and a suggestion returned, clicking away from the form selects the top suggestion, even though the user did not select anything.

2) After text has been entered, then cleared by pressing the Esc key, clicking away from the form enters the text that had been deleted.
 
#### Expected behavior:

1) If nothing was selected by the user, clicking away should not auto-select an option.

2) If pressing the Esc key clears text, then clicking away from the form should not populate the form with that had been cleared.
 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (Normal,) 
 
Products/sites affected: (if applicable)

**Comment by natalieethell** [comment]
Hey @k8rl thanks for submitting an issue and making your question very readable, much appreciated. I just spoke with @joschect who owns Pickers and it seems like both of those behaviors are intentional.

You can see number 1, specifically, in action on these lines of code:

https://github.com/OfficeDev/office-ui-fabric-react/blob/af108d4db1db03c0497f477054743e3bac52070a/packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx#L159-L164

We do see, however, how this behavior can be pretty subjective and specific. I'll start a discussion with the team to see if we're looking to expand support for custom behavior here soon!

**Comment by k8rl** [comment]
Hi @natalieethell , thanks for the fast response. Yes I can see how the first issue may make sense (and is intentional), and a user can at least clear the selection if needed.

However, point 2 doesn't seem to make a lot of sense for a user - once an entry has been cleared, surely it shouldn't then return when clicked away? Anyway, see what the discussion returns. Thanks!

**Comment by natalieethell** [comment]
@k8rl No problem! So, I spoke with @betrue-final-final offline and it sounds like this ESC key behavior is expected and something we want to keep. ESC should dismiss the menu, and leave the text in the box, that’s it. Clicking away would just leave it.
