### ISSUE TITLE
ColorPicker resets to red when dragged to edge

### ISSUE THREAD

**Issue by thmaur** [OfficeDev/office-ui-fabric-react#7878]
### Environment Information 
 
- __Package version(s)__: 6.126.2
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
 

See demo page:

https://developer.microsoft.com/en-us/fabric#/components/colorpicker
 
#### Actual behavior:

When using the color picker and dragging around in the color square, the hue slider slightly changes/there is a wobble. Then if you hit the left or bottom edge, the whole window changes to red instead of whatever hue you were trying to use. The hue slider however stays the same.

#### Expected behavior:
 
There should be no wobble on the hue slider when moving and hitting an edge should not reset the color window to red.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix?No
 
Requested priority: Normal

**Comment by natalieethell** [comment]
@thmaur whoa weird, thanks for reporting this! Definitely a bug, we'll look into it.

**Comment by ecraig12345** [comment]
Good catch here... I suspect the hue slider wobbles because the color picker converts the chosen color to the closest hex color code (which is a lot less precise than an RGB color). That may actually be causing the issue with snapping back to red too, or closely related. Ideally we should be *displaying* the closest hex code, but not actually forcing the selected color to conform to a hex code unless the user types in the hex field.

**Comment by natalieethell** [comment]
I was trying to debug a bit and found some weirdness. It looks like commenting out `_updateColor` in the basic example fixes the issue. 

https://github.com/OfficeDev/office-ui-fabric-react/blob/900176501c2744491375d31ed46deec0e99e9abb/packages/office-ui-fabric-react/src/components/ColorPicker/examples/ColorPicker.Basic.Example.tsx#L35-L37

This function is passed into `onColorChanged` of ColorPicker and for some reason, results in `_updateColor` in ColorPicker.base.tsx being called twice.

Here's my theory (I could still be wrong):

When the toggle is dragged to the far left, the r, g, and b values are all the same. So in the `rgb2hsv` method, h is set to 0. 

https://github.com/OfficeDev/office-ui-fabric-react/blob/900176501c2744491375d31ed46deec0e99e9abb/packages/office-ui-fabric-react/src/utilities/color/colors.ts#L74-L91

This results in `getColorFromString` returning red, because of the lost hue. The return value of `getColorFromString` is used to update the color in `componentWillReceiveProps`:

https://github.com/OfficeDev/office-ui-fabric-react/blob/900176501c2744491375d31ed46deec0e99e9abb/packages/office-ui-fabric-react/src/components/ColorPicker/ColorPicker.base.tsx#L63-L67

**Comment by natalieethell** [comment]
Assigning @ecraig12345 since here PR fixes this issue.
