### ISSUE TITLE
TeachingBubble: Incorrect position if targetElement is inside an IFrame

### ISSUE THREAD

**Issue by riosn-n** [OfficeDev/office-ui-fabric-react#7886]
### Environment Information 
 
- __Package version(s)__: (6.132.0) 
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/anon/pen/VgbPdx
 
#### Actual behavior:
 
The TeachingBubble's position is off.
 
#### Expected behavior:
 
The TeachingBubble positions itself properly in relation to the target element.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (Blocking) 
 
Products/sites affected: (Microsoft PowerApps, Microsoft Dynamics CRM)

**Comment by kenotron** [comment]
This is actually issue with `Callout` I believe. Will investigate how we can support this.

**Comment by kenotron** [comment]
Ah, so all the calculations do not currently respect separate frames like this. This is actually a feature request in disguise. I'm gonna see if I can add support without adding a lot of bloat.

**Comment by kenotron** [comment]
This isn't a simple fix, unfortunately. I'm going to assign this one to Mark to see what can be done.

**Comment by riosn-n** [comment]
Hi @Markionium, do you have an estimate on when this might get looked at? This is a huge blocker for us because almost everything in Dynamics CRM runs inside an iframe. 

Thanks.

**Comment by Markionium** [comment]
I'm not sure why this has been assigned to me @kenotron? I can't say I'm very familiar with that code :D

I can have a look but I don't have a lot of bandwidth at the moment to take a look at this in the short term.

**Comment by khmakoto** [comment]
@riosn-n sorry for the long delay in replying to this issue! From my understanding this is an impossible ask since the parent can't get the positioning correctly as the bounding rect will be relative to an iframe. I'm going to resolve this as `Resolution: Not an issue`. Please let us know if there is anything else you need or if I'm wrong in anything I said and there is actually a way to get positioning right, in which case I'd be more than happy to spin up a PR to fix it!
