### ISSUE TITLE
[Discussion] Example coding conventions

### ISSUE THREAD

**Issue by engineersamuel** [OfficeDev/office-ui-fabric-react#7907]
I would like to update the coding conventions in all Office Fabric React examples to both leverage language features, use best practices, ect..

Here is a list of proposals:
* Avoid arrow functions in component renders if possible
* Don't export Props or State unless imported elsewhere (rare)
* Don't use ternary if no second condition output, use `&&`
* Don't define a constructor unless necessary
* Don't define return types if unnecessary.  For example the implicit return type of the React render function is ReactNode, I see a lot of JSX.Element, but this isn't needed.
* There are components that have the state type explicitly defined in the generic params, this should be refactored out to an `interface IState`
* Import * as React is no longer necessary
* Remove unnecessary semicolons at the end of private functions in components.

I'll commit to making all of the above changes and any others I may come across when refactoring.  I'd want consensus and agreement on the above.  For an example PR of what the changes will look like see #7905

**Comment by kenotron** [comment]
This is great! I actually think that doing it piece meal is okay (actually preferred). We need take care in testing whether these example changes affect the really touchy codepen code transformer so that we don't break those examples as exported to codepen. I think maybe some of that transform logic relies on exports maybe...

Another thought is whether you can point to some additional tslint rules we should really have from that list of yours?

**Comment by engineersamuel** [comment]
Most of these are practices I've adopted over the years and I don't think they can be linted.   That said, when I start implementing I'll look into if I can enable linting for any of these.  But for example not exporting an interface that isn't imported would require something more complicated than linting most likely.

As for verifying changes don't break codepen, is there a way I can do that locally in development that you can point me to beyond manually copying and pasting the code?

If I do this piecemeal, what would be your suggested approach?  1 PR  per folder of examples?  For example `src/components/Layer/examples` has `Layer.(Basic|Customized|Hosted|NestedLayers).Example.tsx`  I'm happy to take approach whatever makes sense for you as a maintainer.  If we do a PR per folder like this, would you want me to open an issue per PR to correlate them?

**Comment by engineersamuel** [comment]
Excellent, I'll test that tomorrow and let you know if I have any issues.  It's absolutely my pleasure, I'm very happy to contribute as I am a heavy user of this lib and C&P examples all the time :)

**Comment by engineersamuel** [comment]
@cliffkoh @kenotron btw do either of you have an opinion on using interfaces vs. types for Props and State.  I used to use interfaces now I use types exclusively.  There are a few blogs out there on why it makes sense, some referred to @ https://stackoverflow.com/questions/37233735/typescript-interfaces-vs-types  And especially when working with redux the following just feels right: `type Props = OwnProps & ReturnType<typeof mapStateToProps> & ReturnType<typeof mapdispatchToProps>; `

**Comment by kenotron** [comment]
Are you talking about `React.Component<P, S>`? For now we go with interfaces because that's just the convention in the codebase. In a greenfield project maybe we can do something different. Most important being consistency as you've suggested for the example even :)

**Comment by ecraig12345** [comment]
Responding to a few of the points...

**Not exporting props and state interfaces**: Unfortunately those have to be exported if the component is exported--and the example components have to be exported to make doc page scenarios work. So we're stuck with that for now.

**Not defining return types**: I'm not sure why leaving return types implicit would be considered good practice? Though of course if the return types for functions like render are wrong/too narrow compared to the return type in the base class, that's not helpful either...

**Semicolons after private functions**: Unfortunately these semicolons are added by prettier, so we're stuck with them unless you can get prettier to change its formatting style.

**Comment by ecraig12345** [comment]
One more: if I remove `import * as React from 'react'`, I get compile errors (at least with our build setup). So it also seems that one needs to stay for now.

**Comment by kenotron** [comment]
I personally would have preferred if we adopted something like `import React from 'react'` with the `esModuleInterop: true` flag of `tsconfig.json`...

**Comment by engineersamuel** [comment]
@ecraig12345 Good to know on the exports!  As for return types, I'd always advocate for return types on user created functions, but for library functions, like React Component Render, they are already defined by the library, so no reason to re-define those in the implementing subclass as the return type can't change, and is ReactNode.

I'll look into the semicolons with the private functions and what convention is here.  It is strange that prettier is enforcing that on private functions and not on non-private functions, that seems inconsistent.

**Comment by ecraig12345** [comment]
I think prettier only adds semicolons after private functions defined using lambdas:
```
private _foo() {
  return true;
} // no semicolon added

private _bar = () => {
  return true;
}; // semicolon added
```

**Comment by engineersamuel** [comment]
@cliffkoh I have instructions for manually testing examples in codepen, however, I have to imagine there is a better way.  This way works, but it wouldn't scale well to manually verify that each example works in codepen.  Furthermore, it appears the majority of the examples don't even link to codepen only a handful.  What is the guidance here?

Here are my instructions:

- cd packages/office-ui-fabric-react
- npm run codepen
- In your browser go to https://codepen.io
- Create a new Pen
- In the html section C&P the output from the npm run codepen, for example:
```
<script type="text/javascript" src="https://unpkg.com/react@16/umd/react.development.js"></script>
<script type="text/javascript" src="https://unpkg.com/react-dom@16/umd/react-dom.development.js">
</script><script type="text/javascript" src="https://da550822.ngrok.io/office-ui-fabric-react.js"></script> 
<div id='content'></div>
```
- In the JS section, C&P the example from the code, remove the exports, and at the very top dereference the necessary components.

For example, if testing `components/Panel/examples/Panel.Medium.Example.tsx` the JS section would contain:

```
let { DefaultButton, Panel, PanelType } = window.Fabric;

interface IState {
  showPanel: boolean;
}

class PanelMediumExample extends React.Component<{}, IState> {
  state = {
    showPanel: false
  };

  public render() {
    return (
      <div>
        <DefaultButton secondaryText="Opens the Sample Panel" onClick={this._showPanel} text="Open Panel" />
        <Panel isOpen={this.state.showPanel} onDismiss={this._hidePanel} type={PanelType.medium} headerText="Medium Panel">
          <span>Content goes here.</span>
        </Panel>
      </div>
    );
  }

  private _showPanel = (): void => {
    this.setState({ showPanel: true });
  };

  private _hidePanel = (): void => {
    this.setState({ showPanel: false });
  };
}

ReactDOM.render(<PanelMediumExample />, document.getElementById('content'));
```

**Comment by engineersamuel** [comment]
@ecraig12345 Can you detail a bit more on why the state would need to be exported?  State is internal to the component and is not passed in, so why would it need to be referenced by a different module?

**Comment by ecraig12345** [comment]
If you have this:
```ts
interface IFooProps {} // not exported
interface IFooState {} // not exported

export class Foo extends React.Component<IFooProps, IFooState> {
}
```
It will cause a compile error since `Foo` is exported but `IFooProps`/`IFooState` aren't.

**Comment by engineersamuel** [comment]
@ecraig12345 Definitely, however, it looks like there are are 98 instances of exported interfaces in the examples and I can't imagine that any of them are imported anywhere, so no reason to export them.  For example: https://github.com/OfficeDev/office-ui-fabric-react/blob/79997dce09/packages/office-ui-fabric-react/src/components/Button/examples/Button.Toggle.Example.tsx yet the state is not imported anywhere.

I would advocate standardizing the names.  Having the state interface or type be a name that reflects the component adds to the verbosity but not the value I've found.  So instead of `IButtonToggleExampleState` it could just be `IState`.  

I just want to make sure that there was no reason the state was being exported, a full text search in the project is not giving me any hits.

**Comment by ecraig12345** [comment]
The examples themselves need to be exported, which means that the state interfaces must also be exported. Otherwise it will cause compile errors (even if no one ever tries to import the interfaces).

**Comment by kenotron** [comment]
i think that may be because we're doing `declaration: true` which is fine for a library like Fabric.

**Comment by KevinTCoughlin** [comment]
>>**Semicolons after private functions**: Unfortunately these semicolons are added by prettier, so we're stuck with them unless you can get prettier to change its formatting style.

> I think prettier only adds semicolons after private functions defined using lambdas:
> 
> ```
> private _foo() {
>   return true;
> } // no semicolon added
> 
> private _bar = () => {
>   return true;
> }; // semicolon added
> ```

I researched this today for a separate effort and both of the above points are true by @ecraig12345.

**Comment by ecraig12345** [comment]
Should have said this upfront, but thanks for doing this!

Responding to a couple points from earlier :)

#### Example state interface naming
One reason I'd been leaning toward longer names may have been to prevent VS Code's intellisense from being cluttered up with tons of IState interfaces...which is not actually a very strong argument. A slightly better argument for more verbose naming is that people will follow the patterns we set in the examples, and in general, calling your state interface IState isn't a great idea. But I don't have especially strong feelings either way.

#### Testing codepen examples
While `npm run codepen` is useful for making codepens that run against your local changes, it's not the best way to test examples which have export to codepen. Instead what you want to do is:
1. `npm start` (as usual for local testing)
2. Navigate to the example and click "Export to CodePen" -- you'll get a codepen with your updated example code running against the current published version of fabric (which is fine unless you've also modified the component itself)
3. If you make further updates to the example code while running `npm start` and save, the example file will rebuild, but the text file used as the payload for export to codepen won't. To rebuild the examples, open a new terminal, cd to `packages/office-ui-fabric-react`, and run `node ../../scripts/tasks/build-codepen-examples.js`.

I suspect it would be possible to get the build-codepen-examples script running as part of the webpack build, so that the files are updated automatically, but that's not something anyone has had time to look into. (Though we really ought to at least add an npm script for building the examples...) 

#### Why not all examples have export to codepen
In #7653 I outline the process of getting an example to work in codepen--sadly it's less obvious/more painful than you'd think. I opened the issue to document/think through improvements I'd like to see, but actually implementing them isn't something any of the immediate team members have time to do right now. 

#### Also
Another thing you might watch out for with examples is components where the "basic" example is anything *but* basic, or where way too many examples are clumped together into one file. For an example of what I mean, look at #7293. It's not necessarily something you need to fix (though you're welcome to if you want!), but if you find a component that has this problem, it would definitely be worth opening an issue requesting clearer examples.

**Comment by engineersamuel** [comment]
@ecraig12345 Very interesting discussion on the state.  I see state as something specific to the Component.  The exclusively reason it needs to be exported is `declaration: true` therefore the component state has no semantic meaning outside of the component, and within the component, we already know it is the component state so why complicate the name?

**Comment by engineersamuel** [comment]
@ecraig12345 The one counterpoint to myself would be if state is being imported via unit testing for typing reasons, but I've never done that and don't see it done here.  But even if it were to be imported, the import could easily be aliased.

**Comment by kenotron** [comment]
Unassigning from myself as this issue seems like will not have a likely conclusion and has become a discussion instead. Will fix the title accordingly.

**Comment by ecraig12345** [comment]
Someone just shared this with me re: performance concerns about re-creating functions in render. Some of the points apply even without using hooks. Short version, inline functions in render may not be as bad as we thought?
https://reactjs.org/docs/hooks-faq.html#are-hooks-slow-because-of-creating-functions-in-render

**Comment by engineersamuel** [comment]
Interesting, to quote in that link, "No. In modern browsers, the raw performance of closures compared to classes doesn’t differ significantly except in extreme scenarios."  My next question would be, what is the advised practice?  For example something may be equally performant but one style preferred over the other for other reasons, such as avoiding extra objects for garbage collection, or stylistically.  A few reasons I could think of for explicit class member functions (or whatever the official name is) would be:
* Less garbage collection, even if there isn't a performance issue, why add to the objects created ever render (though there appear to be ways around this with hooks)
* Easier to modify such functions if the even needs to be handled or extra code added.  For example when needing to stop the propagation of the event, or to add extra logic to the event handler function.

With React.SFC components then all such functions are recreated each instance, that isn't so avoidable, but even then, I always use explicit function in the function SFC function body instead of inline arrow functions on the event handlers, just easier to modify when need be.

**Comment by kenotron** [comment]
I encourage we continue this already long discussion in a mail thread.
