### ISSUE TITLE
Please add type="button" to the Calender

### ISSUE THREAD

**Issue by h3nn3** [OfficeDev/office-ui-fabric-react#7934]
### Environment Information 
 
- __Package version(s)__: (latest) 
- __Browser and OS versions__: (Chrome (any Browser), Windows)

### Reproduction:
I think this problem is pretty simple and does not need a CodePen. 
The problem is that the Calender component used to render DIVs for the days but now it renders buttons that have not the type="button" attribute.
Since we are running this component in SharePoint every click on such a button will trigger a reload of the page.

#### Actual behavior:
 
Click on the button reloads the page
 
#### Expected behavior:
 
Nothing should be happen except the onSelectDate function should be called

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (Blocking)

**Comment by kenotron** [comment]
Just as an addendum, it looks like the Calendar component uses the `<button>` type now and didn't specify the "type" because it *seemed* redundant. However, it does affect the behavior of the Calendar component because of the default type is "submit" inside a `<form>` tag:

https://www.w3.org/TR/html5/sec-forms.html#element-attrdef-button-type

So we should place a type inside the buttons to prevent users of form elements from submitting inadvertently

**Comment by h3nn3** [comment]
Thanks guys and girls :)
