### ISSUE TITLE
"Got it" button is not adapting the high contrast themes

### ISSUE THREAD

**Issue by kmrrakesh** [OfficeDev/office-ui-fabric-react#7999]
### Bug Report 
 
- __Package version(s)__: (6.132.0)
- __Browser and OS versions__: (Edge and Windows 10)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)

Requested priority: (Normal) 
 
Products/sites affected: (OfficeFabric)

#### Describe the issue:
 
"Got it" button is not adapting the high contrast themes

#### Actual behavior:

"Got it" button is not adapting the high contrast themes

#### Expected behavior:

"Got it" button should adapt the high contrast themes

![image](https://user-images.githubusercontent.com/13743867/52770415-0411aa80-3059-11e9-83f2-f2fa093e37a9.png)

**Comment by JasonGore** [comment]
Just wanted to confirm by "Got it" that you meant "Try it out" button.

This appears to be an issue with `TeachingBubble` as it uses a classname to specify Button's coloring, overriding any high-contrast selectors that button would have.

**Comment by JasonGore** [comment]
I'm not seeing an easy way to fix this without major interface changes to `TeachingBubble` and/or `PrimaryButton`. @khmakoto Could you double-check? Do you see any easy fixes now and/or with new `PrimaryButton`?

Things I've considered:
1. Temporary `not` `HighContrastSelector` in `TeachingBubble.styles`. This approach [doesn't seem to be supported in MS Edge](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-ms-high-contrast).
2. Passing `styles.primaryButton` to `PrimaryButton`. This won't work since `styles` is a function and would need re-evaluation against style props.
3. Reproducing high contrast styling in `TeachingBubble`. This seems excessive.
4. subcomponentStyling usage by `TeachingBubble`. Would require `TeachingBubble` interface changes. Also, subcomponentStyling is something I think we should try to move away from.

**Comment by khmakoto** [comment]
I think this is happening because the `.${classNames.buttonLabel}` selector in line 209 of `TeachingBubble.styles.ts` has a higher specificity as a classname than just the high contrast mode selector. We could stop using that classname and just set the `color` style on the `primaryButton` style. Granted, we'd have to also set it on the `hover`, `active` and `focus` selectors, but we'd get rid of the specificity problem with a relatively simple fix.

It wouldn't create any problems as far as I can see either because there is no `buttonLabel` or anything similar on `ITeachingBubbleStyles`. @JasonGore what do you think of this?

**Comment by JasonGore** [comment]
I agree the issue is with specificity. However, if `color` is set at root instead of at `label`, then the button styling overrides the coloring when hovered. That's why I mentioned subcomponentStyling and such above... I'm not sure if there is a simple solution. 

![image](https://user-images.githubusercontent.com/26070760/61062895-e3554300-a3b3-11e9-9d33-58e5e488e614.png)

**Comment by khmakoto** [comment]
Yeah, that's why I said that we would also have to set the color in the `hover`, `active` and `focus` selectors... I don't think there's a simpler solution than that...

**Comment by dzearing** [comment]
@JasonGore @khmakoto any updates here? Going through needs attention issues.

Would avoid subcomponent styling if possible.

**Comment by khmakoto** [comment]
@dzearing I could shoot for a PR and ask a review from you and @JasonGore later this week to see if my fix is good in this situation.
