### ISSUE TITLE
Callout is immediately dismissed after launching in IE on slower machines

### ISSUE THREAD

**Issue by Dalimil** [OfficeDev/office-ui-fabric-react#8004]
### Environment Information 
 
- __Package version(s)__:
office-ui-fabric-react: 6.129.3
react: 16.8
- __Browser and OS versions__: Internet Explorer 11 on Windows x64

### Bug Description

The `CalloutContent.base.tsx` file adds listeners for the callout dismissal based on focus changes. This is done via a hacky workaround for IE - the comment is included in the code:

https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Callout/CalloutContent.base.tsx#L288
```
    // This is added so the callout will dismiss when the window is scrolled
    // but not when something inside the callout is scrolled. The delay seems
    // to be required to avoid React firing an async focus event in IE from
    // the target changing focus quickly prior to rendering the callout.
```
It uses setTimeout(function, 0) to delay the attachment of the listeners and prevent immediate dismissal of the callout when there are focus changes shortly before opening. However this fails to work properly once there is heavier script load or the machine is simply slower. 

The code suggests this is a workaround, and it should be handled differently.

**Comment by JasonGore** [comment]
I've done some preliminary testing in a very slow environment (20% of 1 CPU) and haven't seen anything too unexpected so far. If the user changes focus before it appears, then it will disappear, but I think this is expected behavior when working in a slow PC environment similar to interacting with app menus or any other UI elements.

What exactly fails to work properly? Can you provide details on your implementation and environment?
