### ISSUE TITLE
DetailsList: Allow text selection when not in multiple selection mode

### ISSUE THREAD

**Issue by cschleiden** [OfficeDev/office-ui-fabric-react#802]
The `DetailsList` prohibits selecting text in cells by default by setting `user-select: none` and `cursor: default`.

Would it make sense to make that configurable (maybe a `blockSelection` property)? In VSTS we've had to override these styles for a few grids, because we do need selection.

**Comment by dzearing** [comment]
Adding @aditima 

The culprit is on `ms-DetailsRow`. The concern is that having user-select allowed plays against row selection/marquee selection/drag drop scenarios we have in OneDrive and SharePoint.

For example, if you disable it, click on the first row and then shift click on the last row to select a range. I think we're doing everything right here in terms of preventing default/stopping propagation, but it still wants to text select.

**Comment by cschleiden** [comment]
Yeah, if you care about selecting whole rows, that makes sense. What if we tie it to the selection mode? We have many use cases where we don't care about selection, but use the `DetailsList` to present data in a nice, tabular, customizable way. It's required for us to allow users to copy data from these tables.

**Comment by dzearing** [comment]
I think that would be totally reasonable. Only set `user-select` to `none` for multiple selection mode.

**Comment by dzearing** [comment]
@aditima you good on this as well? I can't think of anything that would regress.
