### ISSUE TITLE
Layer: componentDidMount get called before props.children's componentDidMount

### ISSUE THREAD

**Issue by YusongLiu** [OfficeDev/office-ui-fabric-react#8104]
### Environment Information 
 
- __Package version(s)__: latest

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/anon/pen/GeKPvG
 
#### Actual behavior:
 
Layer's componentDidMount is called before props.children's componentDidMount
 
#### Expected behavior:
 
props.children's componentDidMount is called before Layer's componentDidMount

**Comment by YusongLiu** [comment]
It seems the logic of `hasMounted` caused this issue but I'm not sure the context about it and why we need that.

**Comment by leddie24** [comment]
@JasonGore can you chime in on this issue? It looks like you added this change (for `hasMounted` in PR #6489) a while ago.

**Comment by JasonGore** [comment]
Yes, #6489 introduced this change so that children of `Layer` can properly be detected for event handling. Before this change, children were rendered but unable to be detected as children of `Layer` because their virtual parent relationship can't be established before initial render. Without this change, focus handlers and such get triggered before the virtual parent relationship is established, causing multiple issues with focus.

The result is that `Layer` has to be rendered before its children, which is why you see `componentDidMount` called on `Layer` before its `children`.

I think `Layer` should be viewed as a special case because of its use of React Portals. It does have props like `onLayerMounted` that could be used to gate behavior, but I'm not sure what your end use case to know what to advise or suggest. Can you tell me more about your use case and what issue you are trying to resolve?
