### ISSUE TITLE
Is there any way to rerender the list when state is updating?

### ISSUE THREAD

**Issue by piyumi25** [OfficeDev/office-ui-fabric-react#8131]
I need to is there any way to re render the onRenderCell function when state is updating? Requirement is I need to update the list after state is updating.

**Comment by KevinTCoughlin** [comment]
@leddie24 I'll take this question as I believe it relates to `List` documentation which addressing #7684 should resolve. @piyumi25, thanks for your question. I will provide an answer in the morning.

In short, if you mutate the `items` prop then `onRenderCell` should be invoked since the List does a reference check for `shouldComponentUpdate`. Will confirm and share a Codepen tomorrow.

Related: https://reactjs.org/docs/optimizing-performance.html#the-power-of-not-mutating-data

**Comment by piyumi25** [comment]
Thanks
I have used the List component (https://developer.microsoft.com/en-us/fabric#/components/list) which in office ui fabric react documentation. I used this component because some times I need to load the large number of items into the list. I am waiting for your immediate response for the issue.

**Comment by KevinTCoughlin** [comment]
@piyumi25, to trigger `onRenderCell` one needs to recreate the `items` array that backs the collection for the `List` component. This must be done so that `List` knows to update when the referential equality check returns `false` when comparing previous and next prop values for `items`.

Here is a Codepen which illustrates this concept:

https://codepen.io/kevintcoughlin/pen/gELGBP?editors=1010

The code most relevant to your question is within `prependItems` which is called when the "Prepend items" button is clicked:

```tsx
this.setState({
  items: [...newItems, ...items]
})
```

Notice that the `items` array used for the `List` is recreated not mutated. When the `List` receives the new props, the referential equality check returns `false`, and the `List` re-renders.. calling `onRenderCell`.

The referential equality check within `List`'s `shouldComponentUpdate` is here:

https://github.com/OfficeDev/office-ui-fabric-react/blob/2d6ffd0f0832e8f5717961bbc15ca8008cd4f32b/packages/office-ui-fabric-react/src/components/List/List.tsx#L336

**Comment by piyumi25** [comment]
Thank you for your reply.
