### ISSUE TITLE
Shimmer: white background when have theme

### ISSUE THREAD

**Issue by callmedhh** [OfficeDev/office-ui-fabric-react#8161]
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:
 When pass a theme to Shimmer, it will have a white background. Which looks wired.
![image](https://user-images.githubusercontent.com/7888341/53618938-6b6a5580-3c28-11e9-9e0a-704b5672b7d4.png)

 
#### Expected behavior:
 Not show the white background.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low)  High.
 
Products/sites affected: (if applicable)

**Comment by Jahnp** [comment]
Thanks for the report @callmedhh . As a reminder, when filing issues, please follow the issue template and provide environment information (e.g. package version(s)) and ideally a Codepen to help us diagnose the issue and think through possible solutions.

@Vitalius1 and/or @atneik , FYI. I think the fix here would be to think through which semantic colors could apply to Shimmer, but not sure what those might be. Thoughts?

**Comment by Vitalius1** [comment]
@callmedhh as @Jahnp said a codepen repro with the exact theme you are using would really nice to have so that we can investigate. This way I can understand what is causing it. [Here](https://codepen.io/vitalius1/pen/gErZVr) is a quick start for you to get started. Keep in mind that the white color you see is the `palette.white` color of the `theme` you provided. How is the blue color around applied? Is it hardcoded, a `theme.palette` color or `theme.semanticColor`. If you can modify the codepen with the exact theme you have and the way you apply the colors to the wrapper I can get you an answer faster.

**Comment by Vitalius1** [comment]
@callmedhh in #8243 I am introducing some new props to make it easier to customize the white space around the shimmering elements.

**Comment by callmedhh** [comment]
Thanks @Vitalius1, thanks for the cool props. 
I find a work around to solve the issue, that is to use a Customizer component to wrap root element, and pass the theme to Customizer. Then theme will work fine for Shimmer.
