### ISSUE TITLE
Callout dismiss when click on checkbox inside the callout in ios

### ISSUE THREAD

**Issue by piyumi25** [OfficeDev/office-ui-fabric-react#8175]
I am using callout to open when click on textfield. There are checkboxes as the content of the callout. when click on that checkbox then the callout dismiss only in ios. How do I fix it?

**Comment by KevinTCoughlin** [comment]
@piyumi25 can you please fill out the following to help us debug this better?



### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
 



 
#### Actual behavior:
 

 
#### Expected behavior:
 


#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by piyumi25** [comment]
Environment Information
Package version(s): 
Browser and OS versions: IOS
Please provide a reproduction of the bug in a codepen:https://codepen.io/piyumi28/pen/moKRvV
Actual behavior: when click on checkbox, the callout is dismissed
Expected behavior: callout should not be dismissed
Priorities and help requested: I need to fix this issue as soon as possible
Are you willing to submit a PR to fix?No

Requested priority:  High
Products/sites affected: (if applicable)

**Comment by aftab-hassan** [comment]
@piyumi25 thank you for providing the codepen. However, I am unable to see the issue here, it opens up a blank page. Could you kindly update the codepen to match the issue you are facing?
