### ISSUE TITLE
DatePicker: isRequired validation bug

### ISSUE THREAD

**Issue by fantua** [OfficeDev/office-ui-fabric-react#822]
### Bug Report

- __Package version(s)__: 0.88

#### Describe the issue:

Create form with TextField and DatePicker components. TextField is controlled component (by value and onChanged), so when typing some data to him - React will re-render form. 

#### Actual behavior:

After re-render validation is fired.

#### Expected behavior:

Validation should fired only when DatePicker loses focus. 

#### Additional question:

How check is DatePicker valid when form is submitting? 
Perhaps better will be also add required prop to DatePicker input element this will prevent form submitting when DatePicker is empty?

**Comment by gitjain** [comment]
@fantua 
I tried to repro the issue and seems TextField validates the date at submission only.
Can you share a codepen and more details if you are still facing the issue.

**Comment by fantua** [comment]
@gitjain http://codepen.io/fant/pen/bqzBZd enter something into the input.

**Comment by Jahnp** [comment]
@fantua, we're cleaning up old issues that haven't had traction on them in awhile--please feel free to reopen if this is still an issue.

@johannao76, since your team owns DatePicker, can you take a look at this and see if this still needs to be addressed?

**Comment by reewen** [comment]
I still have this issue with the latest version of office-ui-fabric-react (5.45.0). Could you guys open this issue again? Thank you! @fantua @Jahnp

**Comment by Jahnp** [comment]
Sure! @johannao76, any chance you or someone from your team could take a look at this when you have a chance?

**Comment by lorejoh12** [comment]
taking a look

**Comment by lorejoh12** [comment]
It looks like since we allow DatePicker to have the value passed as a property, there was some additional logic added to make sure that validation was run during componentWillReceiveProps. However, that fires every rerender (after initial render), and validation was running even though none of the props had actually changed. I added a quick check at the top to make sure the validation doesn't run unless props actually changed, and that appears to fix this issue.

**Comment by reewen** [comment]
@lorejoh12 Thanks for looking at this. But this behavior is still different from other components, like Dropdown and TextField. Rerendering doesn't fire other components(with required=true, and they also accept value passed as a property), so is this inconsistent? Can we make them consistent?

**Comment by lorejoh12** [comment]
Hmm, I don't see any actual validation in Dropdown, maybe you were referring to another component? As for TextField, that actually does seem to be what it's doing, although a little more cleanly:
![image](https://user-images.githubusercontent.com/8549582/35599724-12393fe2-05df-11e8-8dd4-c28dab80ecfb.png)

Rather than comparing all props to see if they've change from past props, TextField just compares the new prop "value" to the state's value to see if it's changed before running any logic/validation, but the idea is the same.

Is it consistent enough here if we do that same check? Check to see if value is different than the state value?

**Comment by reewen** [comment]
Hmm, I find that TextField NEVER fires even if 1) the value change from non-empty to empty, 2) focus in the field and blur without entering text. TextField only fires when there is error message. 
Can the DatePicker go with the same way?

**Comment by lorejoh12** [comment]
TextField seems to fire whenever the value changes, regardless of the empty or non-empty-ness of it. :) DatePicker relies on a few extra checks beyond just value changing. For example, we have a property called minDate and maxDate for validation.

for example, if we have minDate = Jan 1, maxDate = Jan 6th, and value = jan 5th, and then the prop maxDate gets changed down to Jan 4th for whatever reason : we need to validate that prop change, even though 'value' isn't the actual changing prop.

I updated the PR to check only the props we care about in this case, so we only validate if minDate, maxDate, formatDate (they could ask the date formatting to change), isRequired (which would turn off validation), or value changes.

**Comment by lorejoh12** [comment]
I'm not sure I understand what you're referring to by "fires". By fires, I'm referring to the validate method ever being called. TextField certainly fires "componentWillReceiveProps", which checks if value changed and fires delayedValidate, which then fires validate method. This is only one of the ways in which validate gets fired, but it's the one that's broken in DatePicker right now.

DatePicker currently fires validate without checking if the value actually changed. My updated PR will check that one of the properties we care about changed now before doing any validation, which means we'll get consistent behavior with TextField once this goes in.

**Comment by reewen** [comment]
Here, we mean the boarder changes to red.
