### ISSUE TITLE
SplitButton in Touch doesn't work correctly

### ISSUE THREAD

**Issue by MichaelKnightMSFT** [OfficeDev/office-ui-fabric-react#8230]
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:
 https://codepen.io/anon/pen/oVBORo
Click Hello World with mouse
Notice Alert pops up saying hello
Now tap with touch
Notice drop down appears instead with other options

 
#### Expected behavior:
 
Tapping with touch should do the same thing as clicking with mouse

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 No

Requested priority: (Blocking, High, Normal, Low) 
High
 
Products/sites affected: (if applicable)
 Office UI Fabric. Discovered on Sharepoint.

**Comment by aftab-hassan** [comment]
@chang47 Based on this [PR](https://github.com/OfficeDev/office-ui-fabric-react/pull/4353), wanted to get your thoughts on whether this behavior is expected.

**Comment by chang47** [comment]
This is an expected behavior. 

The decision was made by the Athens Accessibility Group that makes the accessibility guidelines that we should follow to be compliant. 

Specifically the concern was that users will have a hard time hitting the menu button and instead would hit the primary button. 

The reason why this is okay is, because in theory, the primary button should also be an option inside the menu button. I believe there was an issue logged in the past where we might automatically add the primary button as a button in the menu, but no action was taken on it.

**Comment by aftab-hassan** [comment]
Discussed this offline, and resolved the current behavior to be as per design.
@jspurlin @betrue-final-final 

@jspurlin's suggestion for the team which raised the issue is to implement two buttons.
"One alternative I just thought of which has precedence in touch scenarios is "touch" vs "touch and hold" where touch would execute the primary and touch and hold would expand the menu. This is similar to "place IP" vs "make selection"/"launch context menu" OR "execute" vs "launch context menu" for a button or link."
