### ISSUE TITLE
The primitive object of CSS in JS pholosophy

### ISSUE THREAD

**Issue by lijunle** [OfficeDev/office-ui-fabric-react#8244]
I am not sure if this is a question or a feature request. May want some clarifications on the CSS in JS philosophy.

---

Let me start with writing a `App` component using some fabric-react components:

```tsx
function App(props) {
  return (
    <div>
      <a>See more</a>
      <Persona {...} />
    </div>
  );
}
```

Then, I write some CSS in JS to prettify the component:

```ts
interface IAppStyles {
  anchor: IStyle;
  persona: IPersonaStyle;
}
function getAppStyles(props): IAppStyles {
  return {
    anchor: { ... },
    persona: {
      root: { ... },
      image: { ... },
    }
  };
}
```

Then, I want to use the styles in my `App` component. The `persona` part is easy:

```tsx
<Persona {...} styles={props.styles.persona} />
```

But, I do need to convert the `IStyle` to `className` for `<a>`. How?

```tsx
const appClassNames = classNamesFunction(props.styles);
<a className={appClassNames.anchor}>
```

Wait, what happen to the `appClassNames.persona`? **We generate it, register a big blob to the page then throw it away!**

---

The story ends and let me back to the CSS in JS philosophy. There are two concepts in the code - `IStyle` and `className`. Which one is the primitive when applying CSS in JS? I do think it is the `IStyle` interface. So, the `App` component should care only about the `IStyle` and always pass it around. The `IStyle->className` convention should only happen inside HTML tags, not inside customized component.

Technically, the code should look like this:

```tsx
function App(props) {
  return (
    <div>
      <a className={styleToClassName(props.styles.anchor)}>See more</a>
      <Persona {...} styles={props.styles.persona} />
    </div>
  );
}
```

Unfortunately, [the `styleToClassName` function](https://github.com/OfficeDev/office-ui-fabric-react/blob/91e8cf63bf2e057f609905f66363ac6ab5b5880e/packages/merge-styles/src/styleToClassName.ts#L277) is not exposed anywhere. As a workaround, I can use `mergeStyles` which is a simple wrapper on top of `styleToClassName` to apply the above philosophy.

**Comment by dzearing** [comment]
FWIW `mergeStyles` is literally `styleToClassName`. It takes `IStyle` and returns a `string`.

The `styles` prop of a component represents an object (or a function which takes in props and returns the object). The object has "parts" of a component, where each can be `IStyle`, or a string, or an array of either. This will be calculated and merged into the style before classnames are evaulated. This helps reduce specificity wars.

You could also use Customizer to provide these app-wide, so that you don't need to pass them in or create a HOC around components:

```
const overrides = {
  scopedSettings: {
    Button: { 
      styles: {
         root: { ... }
     }
  }
};

<Customizer {...overrides}>
  <Button ... />
</Customizer>
```

Long term, we are looking for ways to reduce the runtime evaluation. CSS variables support would open up new doors for us and potentially reduce how much css we need to calculate. That requires us to abandon IE11 though.

**Comment by dzearing** [comment]
Also:

> But, I do need to convert the IStyle to className for <a>. How?

You do not need to convert things passed into styles. We will do that for you.

In cases where you would like to use mergeStyles in your own components, you could always have a styled HOC wrapper:

```
const styled = (Component, styles) => props => <Component {...props} className={ mergeStyles(props.className, styles) }/>;
```

**Comment by lijunle** [comment]
> The object has "parts" of a component, where each can be IStyle, or a string, or an array of either.

If the parameter is a string/className, will the styles from this class override the `IStyle` in same element? For example, `c = mergeStyles({ height: 100 }, 'height-200')`, what is the height of `c` className?

After some practices after writing the original post, I think of the `IStyle` is not a good pattern to be a prop. (Either on `className`.) The styling information should not pass around, but should not encapsulated as a *box component*.

(The following idea is inspired from [Flutter layout elements](https://flutter.dev/docs/development/ui/layout).)

Let me give a concrete example, we have the `Image` component and the `DocumentCard` component. The `DocumentCard` component is using `Image` and *requires* the `Image` fit into a fixed height and width. There are three ways to do it:

1. Declare height and width in CSS/SCSS and pass the generated className to `Image` component in `DocumentCard` component.
2. Declare height and width in CSS in JS and pass the `IStyle` object to `Image` component in `DocumentCard` component.
3. The `Image` component declare `heigth:100%;width:100%` **inside**. Then, in `DocumentCard`, wrap `Image` inside a `div` tag with fixed height/width.

Because the CSS has its inheritance, the `Image` must be fit into the `div` tag. I do think the three way is the *correct* direction. On that direction, we will have some components dedicated for styles - `FlexContainer`/`FlexRow`/`FlexColumn`/`FontStyles`/`FixedBox`/etc. It may be a problem to have extra HTML layers for pure CSS. 

BTW, It will be interesting to check how the community handles CSS in JS in year 2019.

**Comment by lijunle** [comment]
The topic here is ***what is the small unit to pass around styles***.

- Originally, we use `className` but get into the specificity wars.
- Currently, we are using the mix of `IStyle` and `className` but I don't think a mix a proper solution.
- In the first post, I want to check if it is OK to use `IStyle`-only as the small unit to pass around styles. Before some coding, I do think that is still *not* an ideal way. 
- Currently, I am thinking about some dedicated *box components* as the unit for styles.

**Comment by jeremy-coleman** [comment]
Mergestyles = a single css rule
Mergestylesets = stylesheet

If you have used aphrodite or typestyle glamor etc , the experience will be the same

Ignore everything else and dont use any props for styles . You can use the getTheme function to get the global theme object. 

Var Buttoncss = mergestyles({color:’red’}) 

Or

Var buttoncss= mergestylesets({
Root:{..}
Something:{..}
)}

 const Button = props => div classname=buttoncss

**Comment by dzearing** [comment]
@lijunle I don't think we will clearly resolve this here but I think all of the options of styling have benefits and tradeoffs.

We started with only classname as a way to style thing. Pro is that it's fast, pre-calculated. Con is that it's highly fragile to override because of specificity, there's no type safety, it leads to bulk css, there has been limited support for "theme in a box" scenarios, etc.

We moved to css in js; pro is that it's safer for us to merge things in the correct order to reduce specificity problems. We added type safety and we are able to support runtime theme injection scenarios. It also enables scenarios where we can render some static html for server pre-rendering with exactly the minimum set of styles required. Awesome. But css in js also suffers from perf overhead. We are actively working to make this better through memoization of results.

I think the ideal is really css in js, but with optimizations at both the build time layer, and the runtime execution layer. Atomic classes I think would really help with having fewer classes registered overall in the context of many partner. I love the API surfaces of emotion/styled-components, but I think having atomic classnames, some babel plugins to pre-optimize the JS and produce pre-registered rules, and memoization options to reduce redunant classname calcs would signifcantly speed the cost up, while preserving the merits.

Static css (non calculated) is always going to be fastest, but that ends up fighting against theming currently, when we do things in styles like say `background: props.theme.semanticColors.background` which requires runtime evaluation to understand. I think we can move away from this runtime evaluation if we can kill IE11 because css variables could replace this.

So, current state? Use `styles` to inject styling if needed, but ONLY in cases where you believe class names should be generated.

For frequently updated values (like `left` or `top` that track a mouse position), don't use `styles`. Inject those values inline via `style` to avoid classname calculation.

The `classNames` support is still there for backwards compat but be aware that specificity wars still exist there. Not recommended; it's a black box of styling with no consideration of theme or context.

**Comment by lijunle** [comment]
@dzearing I was heard that, v7 is going to release. What is the plan on the CSS related tech?

Are we continuing to support `className` and `styles` (CSS in JS) in component? With adding more and more *supporting* features, the style calculation becomes more and more complex.

**Comment by dzearing** [comment]
`className` will always be supported, for various purposes. The `styles` prop is very useful and we don't plan to change any of that for 7. That said, we want to improve the styling story altogether to bring it closer inline with styled-components or emotion. 

The `styles` prop has one downside; it is very difficult to use. Easy to get access to the parts of a component as well as the state, but difficult to know which elements to style, and what selectors if any to override.

We have `Button` experiment we're looking at adding to Fabric 7, which introduces a `tokens` concept. Instead of using `styles`, we want a flat list of variables that can be tweaked for common things. We're also thinking about this defaulting to a set of CSS variables later on (when we drop IE), as that's a much better devexp for tweaking common settings, than to hunt for the right element(s) and selector(s) to modify.

WRT to the underlying solution (mergeStyles):

We've been looking at runtime perf of cssinjs and how we can improve it. If we used backtick functions for defining the styling, turns out we can have very fast cached calculation of class names. We are evaluating if we can/should do this for mergeStyles, or if we just use `styled-components` or something popular. I built a prototype of the next gen runtime here, which combines the awesome devexp of emotion/styled components with the atomic classnames of fela/styletron:

https://dzearing.github.io/onedrive-mock/

Also to compare perf with emotion:
https://dzearing.github.io/onedrive-mock/?emotion

And styled-components:
https://dzearing.github.io/onedrive-mock/?styled-components
