### ISSUE TITLE
TextField icon is overlapping with placeholder in RTL direction

### ISSUE THREAD

**Issue by raghavendra-kodimala** [OfficeDev/office-ui-fabric-react#8245]
### Environment Information 
 
- __Package version(s)__: (5.122.3) 
- __Browser and OS versions__: (Chrome: 72.0.3626.121 (Official Build) (64-bit), Microsoft Edge: 44.17763.1.0, Microsoft Windows 1809)

#### Actual behavior:
Icon is overlapping placeholder text in RTL direction
<img width="130" alt="textfield-rtl-img" src="https://user-images.githubusercontent.com/48360110/54041599-2462fe00-41ee-11e9-823a-fda2e5e301fd.png">

#### Expected behavior:
 
Icon shouldn't overlap with placeholder text in RTL direction

#### Priorities and help requested:

 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (High) 
 
Products/sites affected: (if applicable)

**Comment by dzearing** [comment]
Please fix.

**Comment by aftab-hassan** [comment]
@raghavendra-kodimala I am unable to see the overlap in `RTL` direction.

**LTR**
![image](https://user-images.githubusercontent.com/8922176/54093050-94899500-4350-11e9-8512-0bc7e25f7cf9.png)

**RTL** (when the element is out of focus shows the left over text as `...`)
![image](https://user-images.githubusercontent.com/8922176/54093063-baaf3500-4350-11e9-8778-cf1f5d5cef92.png)

**RTL** (when the element is in focus - text does not overlap icon)
![image](https://user-images.githubusercontent.com/8922176/54093066-c4389d00-4350-11e9-8970-3018cb9a7c00.png)

Could you please share a codepen to help reproduce this issue?

**Comment by raghavendra-kodimala** [comment]
@aftab-hassan Here is the codepen https://codepen.io/raghavendra-kodimala/pen/EMbrmr. which repro issue.

**Comment by aftab-hassan** [comment]
@raghavendra-kodimala thanks for the codepen. I am able to see the issue here, and will be working on the fix.

**Comment by aftab-hassan** [comment]
@raghavendra-kodimala In the codepen you supplied, the issue occurs because the `dir="rtl"` is only supplied for the `div` as `<div dir="rtl" className="myClass">`
Please try supplying the `dir="rtl"` to the `html` element at the top of the page as `<html lang="en" dir="rtl">` and this issue should not occur.

We currently do not support placing `RTL` on a div for any of our components, but are considering adding this as part of themes. Here is @micahgodbolt's response on this issue.

_RTL needs to be set at the HTML or body tag....we don't support placeing RTL on a div right now. Basically, when we render our styles we look at html/body for the 'dir' value....we don't traverse the entire DOM for those values._

_We're considering adding this to theme in the future, but for now it has to be on HTML/BODY in order for styles to be calculated  correctly._

**Comment by raghavendra-kodimala** [comment]
Thank you @aftab-hassan for providing @micahgodbolt 's comment. I have updated my code pen as per his comment. I have provided dir="rtl" on body tag. I can still see the issue, if I supply dir="rtl" on body tag, while this is not the case in supplying the same on html tag. 

Here is the updated code pen https://codepen.io/raghavendra-kodimala/pen/GezvQw

Currently we're using dir="rtl" for html and body tags in our project. This might be causing the issue.

**Comment by micahgodbolt** [comment]
I'm sorry, I missed that you are having this issue in 5.x . The ability to apply RTL to the body tag wasn't added until somewhere in 6.0. Is it possible to upgrade your version of Fabric?

**Comment by raghavendra-kodimala** [comment]
@micahgodbolt Currently we have no plan to upgrade to 6.x.

**Comment by dzearing** [comment]
https://codepen.io/dzearing/pen/ZPZzmX

The `DIR` attribute should be on `HTML`. Can you move it there @raghavendra-kodimala?

**Comment by micahgodbolt** [comment]
Yeah, we added support for putting 'dir' onto the body tag in the 6.x branch.
