### ISSUE TITLE
Accessibility[Combo-box] selected value highlighted when cursor move out from window, only for Chrome

### ISSUE THREAD

**Issue by MdAmeerMind** [OfficeDev/office-ui-fabric-react#8254]
**Environment Information**

- Package version(s): 6.146.1
- Browser and OS versions: Chrome 72.0.3626.119

**Please provide a reproduction of the bug in a codepen:**
Code: https://codepen.io/anon/pen/OqjBzv?&editable=true

**Actual behavior:**
When user select Combo-box menu option using key board, after selecting option, focus is on combo-box then press tab to move focus on next component and then move out from windows using tab. 
After moving focus out from window
The combo-box selected item show as selected again with grey background.  
And It is confusing user that where is exact focus is.

![image](https://user-images.githubusercontent.com/48435553/54123362-8a859600-4425-11e9-9214-c0ef936349cd.png)

On above image focus is on console button but still Combo-box is showing selected with grey background 

**Expected behavior:**
Combo-box will not show grey background if cursor is moving out from browser window.

**Comment by KevinTCoughlin** [comment]
Thanks for [the Codepen](https://codepen.io/anon/pen/OqjBzv?&editable=true) @MdAmeerMind, this is easily reproable there by TAB focusing out of the input onto the "Console" element outside the framed page. Once performed, the text within the Combobox is highlighted as if it had focus in Webkit.

We'll take a look at the root cause and a fix :).

**Comment by KevinTCoughlin** [comment]
I dug into this a bit more @MdAmeerMind. It looks like this is how Webkit browsers handle highlight when the focus is outside of the frame containing the highlighted text.

See this JSFiddle which contains a single native `<input />` element: https://jsfiddle.net/kevintcoughlin/a3v4eqzy/.

To repro, highlight the text inside of the `input` then shift focus to the browser's address bar using your mouse.

Note that this behavior differs across evergreen browsers.

- Firefox does not highlight once focus is outside of the frame.
- Edge maintains highlight with the same color.
- Chrome / Opera exhibit the behavior noted in this issue.

Tagging this as "By Design" since this is due to browser implementations not the Fabric library itself.
