### ISSUE TITLE
Panel is not passing (ev) to onDismiss in dismissOnOuterClick

### ISSUE THREAD

**Issue by gnanavelum** [OfficeDev/office-ui-fabric-react#8345]
![image](https://user-images.githubusercontent.com/2680177/54465461-7d73ea00-4738-11e9-9663-ae410ae31f13.png)

https://github.com/OfficeDev/office-ui-fabric-react/blob/526fe7fff3c778327ea447ce200b195d9cef3bb1/packages/office-ui-fabric-react/src/components/Panel/Panel.base.tsx#L87

**Comment by KevinTCoughlin** [comment]
@gnanavelum I can see that `ev` is not being passed, but that seems intentional given the following LoC:

https://github.com/OfficeDev/office-ui-fabric-react/blob/526fe7fff3c778327ea447ce200b195d9cef3bb1/packages/office-ui-fabric-react/src/components/Panel/Panel.base.tsx#L206

Can you elaborate on the bug here as per our Bug Template below? It will help me triage this and provide resolution to you.

---

### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
 



 
#### Actual behavior:
 

 
#### Expected behavior:
 


#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)
