### ISSUE TITLE
Narrator will read dialog title again after reading "... dialog editing" when using some textfield in the dialog.

### ISSUE THREAD

**Issue by KeiraYang** [OfficeDev/office-ui-fabric-react#8350]
Narrator will read dialog title again after reading "... dialog editing" when using some textfield in the dialog. Which seems redudant and might comfuse user about whether focus is still in edit field or not.

**Comment by khmakoto** [comment]
Hi @KeiraYang, can you provide a codepen that reproduces the issue so we can take a look at it and check if it's a bug and how to fix it?

**Comment by KeiraYang** [comment]
Hi. @khmakoto Thank you for reply. I've added a codepen, please test [here](https://codepen.io/keirayang/pen/jJeKQQ).
Edge + Narrator will read:
"All emails together, alert dialog, a label for text box, editing test", but then follows up with "alert, dialog, heading level 2, all emails together, a label for text box". This not happens every time. I'm not sure how it will come out. But I tested both in scan mode or scan off mode in Narrator. Both had happened.

**Comment by khmakoto** [comment]
Hi @KeiraYang, I've confirmed that this is happening but I'm unsure if this is our bug in our part or if this is the expected behavior for Narrator. I'll try to get that information before trying a fix and will keep you updated. Thanks!!

**Comment by khmakoto** [comment]
Hi @KeiraYang, after some back and forth I've confirmed that this is the expected behavior for Narrator in this situation. When you open the `Dialog`, focus goes to the new surface's first focusable element and it reads the `Dialog` title (to indicate that you are in a new surface) and then the name of the `TextField`. Since the `TextField` is associated with the label, that label becomes the name that is read. After reading it, the focus reads the inner text of the `Dialog`, reading the title and label again.

As you can see in [this codepen](https://codepen.io/khmakoto/pen/NJVPjM), if you use static text instead of a label, then that text is not read twice (although the Dialog title is because of similar reasons). This is by design in Narrator because of the way it deals with new surfaces popping into view.
