### ISSUE TITLE
Add a prop to disable animations in callouts

### ISSUE THREAD

**Issue by kenotron** [OfficeDev/office-ui-fabric-react#8411]
**Describe the feature that you would like added**

Proposal here is to have a `urgent` prop in Callout, some callouts like in a OWA RTE floatie would benefit from this so that expected UX can be expressed without hacking some styles.

**What component or utility would this be added to**

Callout

**Have you discussed this feature with our team, and if so, who**

@JiuqingSong

**Additional context/screenshots**

**Comment by Jahnp** [comment]
Just a note that this is highly-related to (maybe a dupe of?) #5874, though that issue is specifically for TeachingBubble. There is some discussion on that issue about what the prop should be.

I'm interested in the semantic difference between `urgent` and something like `disableAnimations`. The former almost implies there could be other potential UI/UX changes besides *disabling* animations (e.g. maybe "urgent" could just mean faster animations?), whereas the latter is super explicit about the changes happening.

Thoughts? Would something more straightforward like `disableAnimations` would suffice?

**Comment by kenotron** [comment]
disableAnimations sounds pretty good - not sure that I want a one off now that I'm on the team. I think a general solution related to theming would be a better bet. I'm closing this one.
