### ISSUE TITLE
PeoplePicker: same person can be selected multiple times when using keyboard.

### ISSUE THREAD

**Issue by Elyjohn** [OfficeDev/office-ui-fabric-react#8451]
### Environment Information 
 
- __Package version(s)__: Package version(s): Latest Fabric UI React

#### Actual behavior:
 
When you quickly press the return or tab key in a short time while the suggested people callout window is active, it adds the same person as many times as you pressed the key.

![developer microsoft com_en-us_fabric](https://user-images.githubusercontent.com/6993911/54879812-b9e0cd80-4e3d-11e9-8be0-f58d110f2260.png)
 
#### Expected behavior:
 
Selected person with keyboard can only be add once.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal

**Comment by dzearing** [comment]
Thanks for the response; @joschect can you help take a look?

**Comment by Vitalius1** [comment]
@JoshuaLamusga FYI

**Comment by Vitalius1** [comment]
![2019-03-27 13 35 30](https://user-images.githubusercontent.com/29514833/55111596-03c4f000-5098-11e9-957e-f447b10803b8.gif)

**Comment by ijxsid** [comment]
The main cause of this issue seems to be in the BasePicker Component. `onKeyDown` executes whenever there is a key press event, but the function that updates the suggestions list `_onResolveSuggestions` is a debounced. Therefore, for sometime when the suggestion list is not updated, you can keep selecting the same thing.

Possible Solutions:

1. Hiding the suggestions component in `keyDown` function before `this.completeSuggestion()` is called.
2. Using a state variable which keeps track of what is being selected to avoid the same thing getting selected again.

I am willing to submit a PR if any of the above solutions seems to be at par. @dzearing

**Comment by JoshuaLamusga** [comment]
Maybe if (!pendingKeyDownAction) { pendingKeyDownAction = true; /* normal keyDown logic here */ } and reset the value of pendingKeyDownAction to false when suggestions are ready to be taken again. Then you're not impacting performance by managing the selection (i.e. iterating over it to ensure no duplicates) or affecting the UI.

**Comment by joschect** [comment]
@ijxsid thanks for digging into this! 

Hiding the suggestions is definitely the right way to go IMO. There are some problems with that though regarding the way that it's linked to state. I think @Vitalius1 had suggested debouncing the onKeyDown function as a way to help solve this as well. I'll take another look too.

**Comment by micahgodbolt** [comment]
Checking, and this is still an issue.

**Comment by joschect** [comment]
@micahgodbolt I poked around at this a bit. I think there might be a quick fix using async.throttle.
