### ISSUE TITLE
DetailList Filter and Groups

### ISSUE THREAD

**Issue by FullStackRafik** [OfficeDev/office-ui-fabric-react#8454]
Is there any simple way to filter the results which are grouped?
<Fabric.TextField  onChanged={this._onChange} />
_onChange(text){
  this.setState({
    items: text ? this._MockData.filter(i => i.name.toLowerCase().indexOf(text) > -1) : this._MockData
  });
}

**Comment by Vitalius1** [comment]
Hi @FullStackRafik, thanks for posting a question and in order to help you out with an answer I would really appreciate you elaborate a little bit more on what you are trying to achieve and maybe even provide a starting codepen (you can fork [this one](https://codepen.io/vitalius1/pen/jXzLmb)) in demoing what is the question about.

**Comment by FullStackRafik** [comment]
I resolved the issue.
Thanks.
