### ISSUE TITLE
DetailsList Dynamic grouping

### ISSUE THREAD

**Issue by FullStackRafik** [OfficeDev/office-ui-fabric-react#8455]
Can I group the details list dynamically from a list of object  (each item contains a group property) without declaring the groups(Startindex,count.....)?

**Comment by dzearing** [comment]
You would need to do a filter yourself to translate your grouping into the groups definitions. This gives you an opportunity to do clever things, like cache the result so that it's only computed once.

Pushing that filtering to a lower layer reduces the optimizability of things. E.g. if we supported this, the items could come in the wrong order, which isn't what you'd expect, which to fix would require us to sort based on group first, which is also what you don't expect.

If you want a codepen to illustrate, I could certainly make one if you need further examples. A sample of your input would help.

**Comment by FullStackRafik** [comment]
I agree with you and I believe that we can translate the grouping that we need with multiple great features like caching ....but I think it would be also great if we have for example a list items as below :
 this._MockData= [
    {
      Name: 'test1',
      Group:"Group1"
   
    },
    {
     Name: 'test2',
     Group:"Group2"
   
    },
    {
      Name: 'test3',
      Group:"Group1"
   
    },
    {
      Name: 'test4',
      Group:"Group2"
   
    }
   ]

So when we create the DetailsList and specify the items property, that can automatically create a details list grouping by a property we specify(Group in our case) and cache, so we component will be like that:
<Fabric.DetailsList items={ this._MockData } GroupBy='Group' cache='True'/>

**Comment by dzearing** [comment]
Great suggestion, though if we baked that into DetailsList, it would mean everyone would pay a bundle size cost regardless of usage. Maybe a simple HOC wrapper would suffice:

```tsx
const DetailsListWithGrouping = (props) => {
  const processedGroups = props.items.reduce((groups, item, index) => {
    // build groups here
  }, []);

 return <DetailsList {...props} groups={groups} />
```

**Comment by dzearing** [comment]
At the moment we likely aren't going to add this directly as it would not be a recommended pattern. Best to have items in the correct order as early as possible to avoid client side sorting. But I think the HOC wrapper could be something you add on your end.

**Comment by FullStackRafik** [comment]
Thanks for your answers, I'll try to do that.

**Comment by FullStackRafik** [comment]
Finally, I get the group by results with a custom function.
