### ISSUE TITLE
Remove the nodejs requirement when running npm install

### ISSUE THREAD

**Issue by cmeks** [OfficeDev/office-ui-fabric-react#8518]
having a requirement for nodejs to be part of *previous* versions is stupid. Leave it up to the developer to decide which nodejs version is correct to run npm install. By the way, this reasoning posted on the rush.json file is *not* a good reason to force developers to downgrade nodejs just to run the office-ui-fabric-react application locally.

**Comment by Vitalius1** [comment]
@kenotron, @ecraig12345, @dzearing this looks like your area to decide 😄

**Comment by ecraig12345** [comment]
The idea of restricting to LTS versions was that it prevents developers from hitting build issues which are actually due to an unstable new Node version, not inherent to our build system. 

The person from a partner team who suggested that we restrict to LTS seemed to be aware of specific instances where people working in their repo had issues due to non-LTS Node bugs (and generally seemed to view non-LTS Node versions as quite unstable). However, I haven't worked on Fabric long enough to know if we ever got reports of issues like that from Fabric developers. @dzearing would have better insight there.

**Comment by cmeks** [comment]
Rush already gives a warning about using a non-LTS nodejs worded like so: "Your version of Node.js (11.6.0) has not been tested with this release of Rush. The Rush team will not accept issue reports for it. Please consider upgrading Rush or downgrading Node.js."

If build errors were to occur when running the build, a developer can already make a guess that it could be related to Node.js.

**Comment by KevinTCoughlin** [comment]
Genuinely curious, does anyone have a summary of what we're currently missing out on outside the range `>=8.9.0 <9.0.0 || >=10.9.0 <11.0.0`? Perhaps we can at least consider modifying the range.

https://node.green/

**Comment by dzearing** [comment]
I agree that it just isn't worth it. If a user installs the latest node and hits a problem, we just intruct them to downgrade. Better than assuming the latest is broken and forcing everyone on LTS.

**Comment by dzearing** [comment]
@kenotron @ecraig12345 let me know if you disagree.
