### ISSUE TITLE
DetailsList virtualization not working in Modal

### ISSUE THREAD

**Issue by wonderplayer** [OfficeDev/office-ui-fabric-react#8548]
### Environment Information 
 
- __Package version(s)__: Codepen?
- __Browser and OS versions__: Mozilla Forefox 66.02, Windows 10

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/wonderplayer/pen/MRWgwX
 
#### Actual behavior:
 
DetailsList doesn't render elements on scroll when in modal component.

#### Expected behavior:
 
Items are being rendered on scroll

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? What is PR?
 
Requested priority: Normal 
 
#### Additional comments
Saw this issue https://github.com/OfficeDev/office-ui-fabric-react/issues/6657 and thought this might help with just replacing Panel element in provided Codepen with Modal, but nope.
Original Codepen: https://codepen.io/kevintcoughlin/pen/bOQpbM

**Comment by kkjeer** [comment]
@wonderplayer thanks for reporting this! This definitely seems like a bug in Modal; I'll keep digging to hopefully find a fix.

**Comment by eveleens** [comment]
I got this to work by adding: 
``` 
<div className={listStyle} data-is-scrollable={true} style={{overflowY: 'scroll', height: '300px'}}>
```
https://codepen.io/anon/pen/pBvqrg

**Comment by wonderplayer** [comment]
@eveleens Thanks for this workaround! Will save it as possible solution :)

**Comment by KevinTCoughlin** [comment]
> CC: @KevinTCoughlin
> 
> Are consumers expected to be adding these containers with styles in modals, or should it be inherent? (This is essentially the same problem that #6657 was discussing. The solution is the same. )

@eveleens, until the `DetailsList` does not leverage scroll event listeners for virtualization, this is expected of the consumer. This is because the `DetailsList` needs to know the container that is `overflow-y: scroll` so that on scroll it de/materializes virtualized content properly.

Even once we move away from scroll event listeners, we'll likely have an API that requests the scrollable container `DOMNode` with an inference fallback. At least in this case, the API will be more obvious and type-safe.

We offer guidance about this specific problem on https://developer.microsoft.com/en-us/fabric#/components/detailslist

>My scrollable content isn't updating on scroll! What should I do?
Add the data-is-scrollable="true" attribute to your scrollable element containing the DetailsList.
>
>By default, the List used within DetailsList will use the BODY element as the scrollable element. If you contain the List within a scrollable DIV using overflow: auto or scroll, the List needs to listen for scroll events on that element instead. On initialization, the List will traverse up the DOM looking for the first element with the data-is-scrollable attribute to know when element to listen to for knowing when to re-evaulate the visible window.

I'm happy to modify / review changes to raise awareness of this constraint as folks regularly seem to run into this problem.

**Comment by kkjeer** [comment]
@KevinTCoughlin thanks for the clarification. I have a possible fix for Modal that should mitigate the need for some of these workarounds. This is what I've found while investigating/debugging:

In order for virtualization to work, DetailsList needs a parent div that meets these conditions:
1. The `data-is-scrollable` HTML attribute must be set to `true`
2. The div must have `overflowY: auto` or `overflowY: scroll`
3. The div must have some restriction on the height (either the `height` or `maxHeight` should be set). If the div is inside a parent with unconstrained height (i.e. `height: auto`), then setting `maxHeight: 100%` on the DetailsList parent div will not be sufficient.

My fix is to constrain the height of the Modal `scrollableContent` div by setting `maxHeight: window.innerHeight`. This allows DetailsList scrolling to work inside a Modal when the DetailsList is the direct child of the Modal, i.e. without being wrapped inside any other divs. If the customer wants to wrap a DetailsList inside any custom divs, those divs must meet the requirements described above.
