### ISSUE TITLE
Create the same grey color for both Dropdown and PeoplePicker

### ISSUE THREAD

**Issue by YaokaiYang-assaultmaster** [OfficeDev/office-ui-fabric-react#8594]
**Describe the feature that you would like added**
Make the disable grey color the same for Dropdown and PeoplePicker by default. 

**What component or utility would this be added to**
Dropdown and PeoplePicker

**Have you discussed this feature with our team, and if so, who**
Not yet. 

**Additional context/screenshots**
The first cell is Dropdown and the second cell is PeoplePicker. Both are disabled. 
![image](https://user-images.githubusercontent.com/18135477/55504955-d97ab180-5606-11e9-954e-3c6da2e00a76.png)

**Comment by cliffkoh** [comment]
@betrue-final-final @joschect @phkuo do you know which one of the two has an incorrect/buggy disabled color at the moment?

**Comment by kkjeer** [comment]
It looks like Dropdown currently uses `semanticColors.disabledBackground` ([see in file](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.styles.ts#L195)) and PeoplePicker uses a hardcoded color: `const disabledOverlayColor = 'rgba(218, 218, 218, 0.29)';` ([see in file](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.styles.ts#L195)).

I would suspect that Dropdown is using the correct color - @betrue-final-final can you confirm?

**Comment by kkjeer** [comment]
Hi @YaokaiYang-assaultmaster, could you please confirm two things:
1. The version of Fabric you're using, and 
2. The background color of the PeoplePicker in your screenshot?

On our [documentation site](https://developer.microsoft.com/en-us/fabric#/components/peoplepicker), the disabled PeoplePicker has a background color of rgba(218, 218, 218, 0.29) or #dadada (note the hex color does not include opacity):

<img width="966" alt="people-picker-disabled" src="https://user-images.githubusercontent.com/6687333/55514226-62501800-561c-11e9-99ed-a8ff756a8a1b.png">

![people-picker-disabled-background-color](https://user-images.githubusercontent.com/6687333/55514244-6aa85300-561c-11e9-9da9-b2aa3e553510.png)

Based on an attempt at extracting the background color from your screenshot, the disabled PeoplePicker has a background color of #E6E6E1 or rgb(230, 230, 225) (this also does not include opacity since I couldn't extract that from your screenshot).

Thanks!

**Comment by YaokaiYang-assaultmaster** [comment]
@kkjeer Hi, the Fabric version I am using is `6.164.1`.  The browser I am using is Chrome Version 72.0.3626.121. The disabled PeoplePicker in my browser also have a background color of rgba(218, 218, 218, 0.29), the same as yours. As shown in the following graph. 

![image](https://user-images.githubusercontent.com/18135477/55522651-b0741400-563a-11e9-9dbf-be05495158cc.png)

**Comment by kkjeer** [comment]
Thanks for confirming @YaokaiYang-assaultmaster. @betrue-final-final can you please confirm the correct disabled color for PeoplePicker?

**Comment by kkjeer** [comment]
Spoke offline with @betrue-final-final who confirmed that rgba(218, 218, 218, 0.29) is the correct disabled color for PeoplePicker.

**Comment by YaokaiYang-assaultmaster** [comment]
@kkjeer Thanks! Let me try to change it with the styles property. However I was wondering why are the two components have different background color by design tho?

**Comment by kkjeer** [comment]
@YaokaiYang-assaultmaster PeoplePicker needs the transparency in its disabled background color.
