### ISSUE TITLE
PeoplePicker does not accept aria-* props.

### ISSUE THREAD

**Issue by lijunle** [OfficeDev/office-ui-fabric-react#863]
The PeoplePicker and BasePicker should provide a way to accept the `aria-*` props for the input box.

**Comment by mdahamiwal** [comment]
In general, we provide some of the required aria attachments for internal controls instead of all aria-* attributes. What are the aria props you are thinking to pass?

**Comment by lijunle** [comment]
I want the `aria-label`.

**Comment by joschect** [comment]
While not typesafe you can currently do this by doing something like the following 
```
    let inputProps = { 'aria-label': 'good aria label' }
    return (
      <PeoplePicker
        onResolveSuggestions={ this._onFilterChanged }
        getTextFromItem={ (persona: IPersonaProps) => persona.primaryText }
        className={ 'ms-PeoplePicker' }
        pickerSuggestionsProps={ suggestionProps }
        key={ 'list' }
        inputProps={ inputProps }
      />
```

inputProps is then applied to the input box. Really the input box, and more of our elements should have aria-* things accepted as properties. It's odd because you can add it directly into the input box without problem, but when you try to do `inputProps= { {'aria-label': 'something'}} ` a type error is thrown.

**Comment by joschect** [comment]
Upon a little more investigation it looks like we could do something like 

```
export interface IInputElement extends React.HTMLAttributes<HTMLInputElement> {
  'aria-label'?: string;
}
...
  inputProps?: IInputElement;
```

It compiles fine and typescript seems happy with it. 

@dzearing  does that seem like a reasonable solution? We could make it part of a base interface, then we can also do a better job of enforcing React.HtmlAttributes rather than have people use React.HtmlProps.

**Comment by dzearing** [comment]
@joschect we have a few places where we use `ariaLabel` but in general I would much prefer we stick with `aria-*` props.

If this method works and maintains typing validation so that we don't have to add something like `[key: string]: string` to the definition, we should use it.

**Comment by dzearing** [comment]
however... i honestly think we're going to end up with the general `[key: string]: string` to support data-* attributes. What we really want is `'aria-*'?: string;`

**Comment by dzearing** [comment]
I'm going to close this; I think we have an acceptable solution here. Use `inputProps`. If that's not enough, please clarify what you need.
