### ISSUE TITLE
DatePicker(disableAutoFocus=true) doesn't auto move focus to calendar when triggering out calendar manually

### ISSUE THREAD

**Issue by fengyue1013** [OfficeDev/office-ui-fabric-react#8650]
## Codepen demonstrating the issue
https://codepen.io/yudma/pen/Pgbxpy

## Actual behavior:
when setting `disableAutoFocus=true`, opening the calendar manually by pressing enter, user need to press tab again to move focus into the calendar pop up.
## Expected behavior:
![image](https://user-images.githubusercontent.com/12523937/55774805-4a1f4380-5ac9-11e9-9431-eb6e224a9b2a.png)
When pressing enter to manually open calendar, focus automatically moves into calendar.
P.S. According to the screenshot above, the `DisableAutoFocus` prop indicates disable **auto-popup** of calendar, but actually, it at the same time disables **auto move focus to calendar** when manually pop up calendar. Then user needs to press tab to focus in.

## Documentation describing expected behavior
Don't know where to find the exact document, but OUFR Dialog, Callout also follow the pattern that focus auto-moves into the popped up UI.
We can see this pattern in their demo pages:
https://developer.microsoft.com/en-us/fabric#/components/dialog
https://developer.microsoft.com/en-us/fabric#/components/callout

**Comment by joschect** [comment]
@fengyue1013 thanks for submitting this and including the codepen! This definitely seems like a case of improperly described props and things not working as expected. I'll start working on a fix.

Just to ensure that I'm understanding correctly the expected behavior is that the calendar shouldn't automatically open (that's working as expected) but that it should receive focus automatically.
