### ISSUE TITLE
after the dialog pop-up window in IE, I don't do anything and then close it, the page is completely white.

### ISSUE THREAD

**Issue by mackcheung** [OfficeDev/office-ui-fabric-react#8670]
here is the error message:

![error](https://user-images.githubusercontent.com/4032031/55849720-43093b80-5b84-11e9-871d-c733a82ceca7.jpeg)

**Comment by joschect** [comment]
@mackcheung Thanks for submitting this issue. I created a [codepen](https://codepen.io/slimemold/pen/qwrQxa?&editable=true) and I can't reproduce the issue in IE 11. Could you fork the codepen and see if you can reproduce this issue? You'll need to edit it in a browser other than IE since IE is not supported by codepen, even though the code runs.
