### ISSUE TITLE
Dropdown: Should use a beakless Callout

### ISSUE THREAD

**Issue by atneik** [OfficeDev/office-ui-fabric-react#87]
For rendering the list items a Dropdown should use a Callout component. 

This will also fix the issue where it currently does not dismiss when clicked outside of the component.

**Comment by mikewheaton** [comment]
This would also fix a related issue. In the screenshot below you can see the Dropdown inside of a container with `overflow: hidden` set. The Dropdown is cut off, because it's contents haven't been lifted out via the LayerHost that Callout and other components use.

![image](https://cloud.githubusercontent.com/assets/1382445/18810355/f2bea23a-8248-11e6-966d-9ca2410f603e.png)

**Comment by dzearing** [comment]
Yes please.

**Comment by dzearing** [comment]
Micah - if you can find time for this, it's low hanging fruit!

**Comment by micahgodbolt** [comment]
I actually already took a first crack at this. Let me see where it's at and push up a PR for review.

**Comment by micahgodbolt** [comment]
#446 is my initial PR. I've moved over to using the callout, but there are several issues I still need to overcome.

1. Because it is on a different layer, the width cannot be assumed. Need to determine best way to measure this.
2. Due to multiple ways to close the dropdown (click on input and regular callout scroll/click outside etc) the dropdown isn't closing properly when you click the input box. Basically the callback fires before the click function has a chance to test "is-closed". Means you can't close it via click.
3. More cleanup around the change of styling and functionality.

**Comment by micahgodbolt** [comment]
I'm trying to wrap up the tooltip, so rather than going down this rabbit hole, I'm going to leave it here until I'm done. If someone else wants to finish up, feel free.

**Comment by dzearing** [comment]
This is now checked in.
