### ISSUE TITLE
Vertical OveflowSet keyboard navigation sticks on the overflow

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#8706]
### Environment Information 
 
- __Package version(s)__: current
- __Browser and OS versions__: all

### Please provide a reproduction of the bug in a codepen:
 
https://developer.microsoft.com/en-us/fabric#/components/overflowset
 
#### Actual behavior:
 
arrowup and down in vertical overflow set, once you put focus on the overflow '...' you can't go back up

**Comment by joschect** [comment]
@micahgodbolt  Thanks for submitting this, we'll get it added to our backlog and taken care of!

**Comment by joschect** [comment]
@micahgodbolt interestingly this is a problem with button, not with overflow. Button has some logic to detect when it should open a menu which calls [preventDefault and stopPropagation](https://github.com/OfficeDev/office-ui-fabric-react/blob/7fd3dad18e743eca3bb582b1e24f8287c323e53d/packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx#L688) This is a complicated fix because the button is kinda working as intended, although it is not correctly opening it's submenu which is a separate issue. Do you have any ideas?

**Comment by micahgodbolt** [comment]
So we can't put buttons in vertical focus groups? Aren't there vertical menus that are just a collection of buttons? Do we simply need to render our buttons in list items to avoid this issue?

**Comment by joschect** [comment]
No, we can, it's just a question of how buttons should behave. If there are menuprops in the button then normally pressing down or up will open the menu, however in the case of a vertical menu up or down should move through the items. So it might be that we need to allow for different buttons to open the menu. Or we should only allow enter to open the menu.

**Comment by micahgodbolt** [comment]
pressing down on a button doesn't do anything. "alt + down" will open the sub menu of buttons.

**Comment by joschect** [comment]
Huh, then button is broken lol. I'll get a fix going.

**Comment by joschect** [comment]
Or I should say, it shouldn't prevent default on a down press if alt isn't already currently pressed.
