### ISSUE TITLE
The month buttons in the year grid table of the Date picker under "Date' filter is announced as 'read-only' by narrator(but that are actionable).

### ISSUE THREAD

**Issue by Anschur** [OfficeDev/office-ui-fabric-react#8736]
## Codepen demonstrating the issue

1. Go to: https://developer.microsoft.com/en-us/fabric#/components/datepicker
2. Navigate to a date picker and activate it and in the year grid table, navigate to the months(Jan, Feb , Mar, Apr, etc.) 
3. Listen to the narrator announcement for the months in the year grid table.

## Actual behavior:
Narrator announces the month columns(Jan, Feb , Mar, Apr, etc.) in the year grid table as 'read-only' although they are buttons and can be invoked using 'Enter'. 
For Ex.: Narrator announces April month as <April 2019, selected, read-only, column>

Suggestive Fix:
The 'aria-readonly' property should be turned to 'false' for the month grid cells.<Attached screenshot read only property of the grid.jpg for reference>>

## Expected behavior:
Narrator should announce the control type of month columns(Jan, Feb , Mar, Apr, etc.) in the year grid table as 'button'.
For Ex.: Narrator announces April month as <April 2019, selected, button, column>

## Documentation describing expected behavior
[MAS 4.1.2 - Name, Role, Value](https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7b248054a6-5e68-4771-9e1e-242fb5025730%7d)

**Comment by joschect** [comment]
@Anschur this is currently working as expected! Readonly just means that you can't edit the content but that you can still operate on it. Check out the https://www.w3.org/TR/wai-aria-1.1/#aria-readonly specs.

Also in the pr that introduced change https://github.com/OfficeDev/office-ui-fabric-react/pull/6664 you can see it was an intentional change since grid will always read as editable, even though you can't actually change the contents of the grid, only select something different.

**Comment by joschect** [comment]
Let me know if you have any questions!

**Comment by jamesedj** [comment]
@joschect I have looked into this and I think there is some confusion about how read-only is meant to work with grids. Under the [grid role](https://www.w3.org/TR/wai-aria-1.1/#grid) ARIA states:

> In a grid that provides cell content editing functions, if the content of a focusable gridcell element is not editable, authors **_MAY_** set aria-readonly to true on the gridcell element.

The key here is the clause "In a grid that provides cell content editing functions". My reading of the standard is that this would be something like an Excel spreadsheet where users can input or edit the internal content of grid cells, but the month picker grid is essentially a layout grid for a series of buttons. In this case, I would recommend removing aria-readonly, as including that code will cause the screen reader to announce that the buttons are read only which could cause confusion because this behavior is usually reserved for when content is currently in a read only state, but could be made editable under different circumstances (such as a cell in an excel grid which is locked for editing).

In looking at this I did notice a separate issue with this grid regarding how it announces which row the user is in #8862, and I think the best solution to each of this issues would be to switch to a [radiogroup model](https://www.w3.org/TR/wai-aria-1.1/#radiogroup), which would be more intuitive to screen reader users, but could still have the same visual layout (see my comment in #8862 for more details)
