### ISSUE TITLE
Accessibility issue with DatePicker

### ISSUE THREAD

**Issue by adidwania** [OfficeDev/office-ui-fabric-react#8746]
When there is more than one DatePicker (i.e. - From and To) used in a ContextualMenu, then after choosing a date from one date picker (use keyboard) and then press 'tab', it should go to the second date picker But it closes the dropdown and control goes to the top of the page.

You can repro it here:
https://codesandbox.io/s/k2yv5rq93o

![image](https://user-images.githubusercontent.com/5864305/56310730-6d697480-6101-11e9-970c-473aadb0044d.png)

**Comment by micahgodbolt** [comment]
@lorejoh12 is this something you can take a look at? Curious if you have similar UI's in calendar.

**Comment by micahgodbolt** [comment]
Chatted with @ecraig12345 quick and she reminded me that this is not really a contextual menu (used for selecting items from a dropdown). This should simply be a callout, which doesn't have the same functionality.

I understand the reason for using contextual menu might be because it's what buttons give you out of the box. I've updated the sandbox to use the 'menuAs' prop to render a custom callout. Note that button still maintains the state properly.

Does this solve your problem?
