### ISSUE TITLE
People picker accessibility regression: aria-valid-attr-value: ARIA attributes must conform to valid values 

### ISSUE THREAD

**Issue by ruoxi-lyu** [OfficeDev/office-ui-fabric-react#8750]
## Codepen demonstrating the issue
https://developer.microsoft.com/en-us/fabric#/components/peoplepicker
## Actual behavior:
Kero scan reveals aria-valid-attr-value issue. We found this issue after upgrade the office-ui-fabric-react package to 6.165.0.

## Expected behavior:
There should not be any accessibility issues from the people picker control
## Documentation describing expected behavior
Scan failure details:
![image](https://user-images.githubusercontent.com/44412540/56319176-cd6a1600-6115-11e9-8bc0-20a2bcf61144.png)

**Comment by ecraig12345** [comment]
This is actually just an issue with the documentation site, not the PeoplePicker control itself. But it's still something we should fix.

**Comment by ruoxi-lyu** [comment]
Looks like this was the pr that broke the behavior: #Pickers: conditionally render the list of selected items. (#8516)

@ecraig12345  I think the problem is more universal than just the documentation site. There was no accessibility issue in the people picker component we used before we upgraded the office-ui-fabric-react package to 6.165.0. Please drive the fix accordingly.

**Comment by ecraig12345** [comment]
That PR just happened to be released shortly before #8610, which is the one that actually introduced this issue--it repros on all component pages, not just PeoplePicker. And the issue is definitely scoped to the documentation site, because the IDs and markup referenced in the error are from a component hierarchy that only exists in the doc site. 

As I mentioned earlier, even though the issue is scoped to the doc site, I still intend to fix it. Should be done within the next couple days.

**Comment by ruoxi-lyu** [comment]
@ecraig12345  the first 4 in the screenshots are indeed as you said, specific to the documentation page. However, we are seeing the 5th issue on our end, powerBI sharing workspace page, and the documentation page. 
![image](https://user-images.githubusercontent.com/44412540/56322811-df03eb80-611e-11e9-8f4e-aa29117ec065.png)

Please investigate further.

**Comment by joschect** [comment]
@ruoxi-lyu Hey! Thanks for submitting this. To help us get a better idea about exactly what broke could you paste the entire error rather than just a screenshot? It's pretty difficult to tell what the exact error is. Thanks for your help!

**Comment by ruoxi-lyu** [comment]
@joschect Let me list down the detailed repro step:

1. install [accessibility insight extension](https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni?hl=en) on chrome
2. Go to Office ui fabric react component [People Picker page](https://developer.microsoft.com/en-us/fabric#/components/peoplepicker), and run "fast pass" mode with the accessibility insight chrome extension.
3. There should be 3 groups of accessibility issues shown as my screenshot. You will find more details about the `.ms-BasePicker-input` class.

You will be interact with the issue report and see the elements with issues highlighted by the chrome extension.

**Comment by joschect** [comment]
@ruoxi-lyu Thanks! While I'm getting that setup could you add the error text to the ticket? It's really helpful for us to get that information initially since it can help us confirm that we're seeing the same errors that you're seeing and it can better inform where we should start looking from the first time we check the ticket. Also it would be useful information to have in the issue to reference and have to make it easier to search for! Thanks again for all your help!

**Comment by ruoxi-lyu** [comment]
@joschect please see the details:
Failure details
Rule
aria-valid-attr-value
: ARIA attributes must conform to valid values 
[MAS 1.3.1,MAS 4.1.1,MAS 4.1.2]
How to fix
Fix all of the following: - Invalid ARIA attribute value: aria-describedby="selected-items-id__54"
Path
input
Repro Steps
Instances
Scan Name	Snippet	Target
```<input spellcheck="false" aria-label="Email list for sharing" placeholder="Enter email address" class="ms-BasePicker-input input-220" aria-expanded="false" aria-haspopup="true" aria-describedby="selected-items-id__54" autocomplete="off" role="combobox" aria-controls=" " aria-autocomplete="both" autocapitalize="off" data-lpignore="true" value="" tabindex="0">```


Apologies for the formatting. Hope it will help!

**Comment by joschect** [comment]
@ruoxi-lyu thanks a bunch! Got a fix going for it.
