### ISSUE TITLE
Type of `targetElement` prop in ITeachinbBubbleProps does not match type of `target` in ICalloutProps

### ISSUE THREAD

**Issue by stmillMSFT** [OfficeDev/office-ui-fabric-react#8786]
### Environment Information 
 
- __Package version(s)__: latest
 
#### issue:
 
since `targetElement` is passed directly into callout's `target` prop, it should share the same type, allowing for passing string selectors instead of just `HTMLElement`.  additionally, `targetElement` isn't typed to allow `null` to be passed in which would be really convenient for using refs
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Low
 
Products/sites affected: internal

**Comment by joschect** [comment]
@stmillMSFT thanks for submitting this! That definitely seems like an oddness, especially since calloutprops will allow you to pass in a targetelement that includes all the possibilities. 

@micahgodbolt do you know if targetElement should be deprecated and that functionality moved solely to the calloutprops?

As for passing in null that's something that the callout doesn't currently allow either. It might be a good idea to allow createRefs to get passed into the callout which would enable that behavior elsewhere but that would require a bit of time to dig into.

**Comment by micahgodbolt** [comment]
Considering that targetElement is just an alias for the callout's 'target', they should certainly be of the same type. 

![image](https://user-images.githubusercontent.com/1434956/56509655-6e711c00-64dc-11e9-9e20-c3d572a0f7cd.png)

I'm okay with having this prop in TeachingBubble. It's a primary prop, so making it easier to access is good and cheap. 

So I'd say maybe `Element | string | MouseEvent | IPoint | null;` needs to be abstracted out to a common type, and shared between the type files. 

You might also argue that targetElement could be deprecated and we should align on 'target'.
