### ISSUE TITLE
Having trouble with building the project since version 1.0.0

### ISSUE THREAD

**Issue by carruthe** [OfficeDev/office-ui-fabric-react#881]
### Bug Report

- __Package version(s)__: v1.0.0 and above
- __Browser and OS versions__: MacOS 10.12.3

#### Describe the issue:

Since version 1.0.0 (when you split out @uifabric/utilities), I have been having difficulty with the build. 

#### Actual behavior:

I ran, as per the instructions,..

```
git clone .....
cd office-ui-fabric-react
npm install
npm run
```

Hoever, I got a ton of errors, starting with "@uifabric/utilities" not found, then a ton of typescript errors.

#### Expected behavior:

It should build and run (not trying to be a smartass)

The Fix for me:

```
1. git clone https://github.com/OfficeDev/office-ui-fabric-react.git
2. cd office-ui-fabric-react
3. npm install react react-dom
4. npm install @uifabric/utilities
5. npm install
6. node_modules/.bin/rush rebuild -q (not sure if this is necessary)
7. npm start
```

Then it works!

Thanks!

**Comment by dzearing** [comment]
Thanks; the problem is that the npm script needs a tweak. Just pulled llatest in a clean enlistment last night to realize the npm start command also doesn't build fully.
This is the shortened build list is:
```ts
git clone <url> <dir>
cd <dir>
npm i
rush build
npm start
```

I will fix this asap.

**Comment by carruthe** [comment]
@dzearing - Thanks!
Keep up the great work, this package has been my gateway drug to React, and I'm loving it.

**Comment by rgarita** [comment]
Confirmed, workaround fixes the issue..., the only thing to keep in mind is update line 4 to `node_modules\.bin\rush.cmd` build if just `rush build` is not working

```
git clone <url> <dir>
cd <dir>
npm I
node_modules\.bin\rush.cmd build
npm start
```

**Comment by dzearing** [comment]
@rgarita thanks; that's OS dependent; it's weird that Windows won't run the .bin stuff by default but Mac does. A nice workaround is that you can always install the rush tool globally;

```ts
npm i -g @microsoft/rush
```

I know that works on either platform.

@carruthe Awesome!

**Comment by dzearing** [comment]
Alrighty we should be good now. I've significantly tweaked the build:

`npm start` now runs the "dev loop", which excludes running tests and linting for quick inner loop.

To run tests  you can still run `npm test` to run all tests in the project. Or, if you go to a specific project you can run `gulp test --production` which should run tests. Note that i included the production flag requirement as a temporary workaround since the `rush` tool doesn't yet have support for passing through custom flags or having custom scripts defined in package.json.
