### ISSUE TITLE
Callout targetElement was reset boundingClientRect to 0.

### ISSUE THREAD

**Issue by yumikohey** [OfficeDev/office-ui-fabric-react#8831]
### Bug Report
- __Browser and OS versions__: Chrome and Edge

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking) 

Products/sites affected: ODSP

#### Describe the issue:

Pass in targetElement with defined boundingClientRect, after `_updateAsyncPosition()` was called, targetElement.getBoundingClientRect is set to 0.

This resulted the callout component shows up on the top left corner.

#### Actual behavior:

Callout component shows up on the top left corner.

#### Expected behavior:

Callout component should always attached underneath targetElement if it's passed.

**Comment by joschect** [comment]
@yumikohey Per our conversation this is likely caused by the way that you're getting the element. React's events are not persistent. That means that when you get the element from the react event it will be removed before the callout has a chance to calculate sizes. To get around this, call `event.persist()`. This will ensure that the react event, and associated element last long enough for the callout to position.
