### ISSUE TITLE
IBasePickerProps<T>: The item in onRemoveSuggestion is typed as IPersonaProps instead of T

### ISSUE THREAD

**Issue by basovic88** [OfficeDev/office-ui-fabric-react#8857]
### Environment Information 
 
- __Package version(s)__: 6.169
- __Browser and OS versions__: Not relevant

### Please provide a reproduction of the bug in a codepen:

Not relevant. 

#### Actual behavior:
 
The `item` in `IBasePickerProps<T>.onRemoveSuggestion(item)` is typed as `IPersonaProps` instead of `T`. This appears to be incorrect.

This means that one cannot extend the BasePicker and use the onRemoveSuggestion, because typescript screams that my T isn't equal to IPersonaProps.

```
/**
     * A callback for when a persona is removed from the suggestion list
     */
    onRemoveSuggestion?: (item: IPersonaProps) => void;
```
 
#### Expected behavior:
 
Change `IPersonaProps` to `T`.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal. We currently use a work around that uses an item's onClick event to remove a suggestion.

**Comment by KevinTCoughlin** [comment]
cc: @Adjective-Object

**Comment by apneer** [comment]
Thank you for reporting. This looks like an inconsistency. I am hesitant to fix it as a minor version. This could break clients. Should we fix this in fabric7 instead? @jdhuntington, does that sound reasonable?

**Comment by Adjective-Object** [comment]
I believe this is a minor change for any users for which this currently works. <T> is the _proper_ type, and <IPersonaProps> is incorrect to the actual implementation.

This is fixed in my FloatingSuggestions pr, and I think it should be fixed in master as well
https://github.com/OfficeDev/office-ui-fabric-react/pull/8720/files#diff-aa80cf8be034867d3aa0ec8525cc38d5R92

**Comment by Adjective-Object** [comment]
See:
https://github.com/OfficeDev/office-ui-fabric-react/blob/1f841ea38ff72b7e0988a6a2e076c3d6cfe52d78/packages/office-ui-fabric-react/src/components/FloatingPicker/BaseFloatingPicker.tsx#L235

where the callback is cast to its actual type (the one proposed by this issue) before calling.

**Comment by Adjective-Object** [comment]
So the only way your code could be working right now would be if `<T = IPersonaProps>`.

It _is_ technically a breaking api contract change.. but only because the current api definition is bugged. I think usage for suggestions onSuggestionRemove is low enough that if fabric as a whole is uncomfortable with making this change in a minor rev I'm okay to delay it, but personally I'd be okay to make the fix in a minor version.

**Comment by apneer** [comment]
Discussed this with @JasonGore, it's ok to fix this bug in minor.
