### ISSUE TITLE
content & subText styling not working in <TooltipHost />

### ISSUE THREAD

**Issue by j-te** [OfficeDev/office-ui-fabric-react#8946]
### Environment Information 
 
- __Package version(s)__: 6.172.0
- __Browser and OS versions__: Chrome 72.0.3626.121, Win7

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/anon/pen/qGWRbQ
 
#### Actual behavior:
 
`styles` prop in `<TooltipHost />` does not accept `content` & `subText` parameters (ITooltipStyles interface) as per the documentation.
 
Only `root` passes styles.

#### Expected behavior:
 
To be able to style the outer tooltip content element.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (Low)

**Comment by atneik** [comment]
@j-te there are two components in play here - `Tooltip` and `TooltipHost`. 

In the documentation `content` & `subText` are under `ITooltipStyles` not  under `ITooltipHostStyles`. Therefore in order to style the Tooltip component you'll have to pass the `styles` through `tooltipProps` in `TooltipHost`. 

These two components can definately cause confusion, here is a codepen: https://codepen.io/atneik/pen/wbaQRw 

Let me know if this works for you.

**Comment by j-te** [comment]
> @j-te there are two components in play here - `Tooltip` and `TooltipHost`.
> 
> In the documentation `content` & `subText` are under `ITooltipStyles` not under `ITooltipHostStyles`. Therefore in order to style the Tooltip component you'll have to pass the `styles` through `tooltipProps` in `TooltipHost`.
> 
> These two components can definately cause confusion, here is a codepen: https://codepen.io/atneik/pen/wbaQRw
> 
> Let me know if this works for you.

Thank you @atneik. I've noticed the documentation site has been updated recently which is looking better. I've got this to work.

`calloutProps` is also required for further styling. Here are the additional props for others: https://codepen.io/anon/pen/GapoEK
