### ISSUE TITLE
Unable to start a demo page 

### ISSUE THREAD

**Issue by miroslavstastny** [OfficeDev/office-ui-fabric-react#9024]
### Environment Information 
 
- __Package version(s)__: current master 
- __Browser and OS versions__: MacOS 10.14.4, node 8.11.3, npm 6.4.0

### Please provide a reproduction of the bug in a codepen:
 
README.md says that to run a demo page I just need to:

1. `git clone https://github.com/OfficeDev/office-ui-fabric-react.git`
2. `cd office-ui-fabric-react`
3. `npm install`
4. `npm start`

#### Actual behavior:
 
Probably caused by #8844, `npm start` fails with errors similar to the following one:
```
ERROR in ./src/components/pages/ActivityItemPage.tsx
Module not found: Error: Can't resolve '@uifabric/api-docs/lib/pages/office-ui-fabric-react/ActivityItem.page.json' in '/Users/mistastn/devel/office-ui-fabric-react/apps/fabric-website-resources/src/components/pages'
 @ ./src/components/pages/ActivityItemPage.tsx 7:124-209
 @ ./src/AppDefinition.tsx
 @ ./src/index.tsx
 @ multi /Users/mistastn/devel/office-ui-fabric-react/common/temp/node_modules/.registry.npmjs.org/webpack-dev-server/3.1.14/webpack@4.29.5/node_modules/webpack-dev-server/client?http://localhost:4322 ./src/index.tsx
```

I have to run `npm run build` before `npm start` to run the demo page. 

#### Expected behavior:
 
README.md in sync with what I need to do.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: (Blocking, High, Normal, Low)

**Comment by KevinTCoughlin** [comment]
Hrm I thought `npm install` ran a full build to avoid this problem cc: @natalieethell re: `@uifabric/api-docs`.

**Comment by khmakoto** [comment]
@KevinTCoughlin it builds all the way up to experiments right now.

For context, `npm install` used to build up to `office-ui-fabric-react`, which created this same problem for people who wanted to `npm start` experiments after building it, which is why the change was made. With that change we moved from building:

![image](https://user-images.githubusercontent.com/7798177/57474955-35f57000-7248-11e9-82ba-b5e8b96395a1.png)

To building:

![image](https://user-images.githubusercontent.com/7798177/57474985-460d4f80-7248-11e9-8c58-4cdb81f18e69.png)

Now, as you can see, none of these actually build `@uifabric/api-docs`, hence why users now can't `npm start` on root. However, I can almost assure you that they can `npm start` from the inner `office-ui-fabric-react` package.

My proposal here would be to change the script to build all the way up to `fabric-website`, which *will* build `office-ui-fabric-react`, `experiments` *and* `api-docs`:

![image](https://user-images.githubusercontent.com/7798177/57475200-b0be8b00-7248-11e9-9e38-447d0946cbe7.png)

A drawback of this is that this would obviously hit the time it takes for `npm install` to run. However, the approach right now is broken so I don't think there's another way to go around this. I wonder what @micahgodbolt and @dzearing think about this.
