### ISSUE TITLE
Link with custom className

### ISSUE THREAD

**Issue by unindented** [OfficeDev/office-ui-fabric-react#905]
Could you allow `className` to be passed to `Link`? I wanted certain links to be less prominent by assigning them a `ms-fontColor-neutralSecondary`.

**Comment by joschect** [comment]
Hey @unindented , you should already be able to pass in a className to link. You will need to override the color right now but it looks like it gets applied. It's a little confusing because the website does not show className as a property, but since ILinkProps extends React.HTMLProps it get's all of the native react properties as well.

**Comment by unindented** [comment]
Ah, you are right, the class does get applied. I have no way of overriding the color if I want to use Fabric Core's class names though. `ms-Link` comes before `ms-fontColor-neutralSecondary`, and I have no way of forcing an `!important` in there...

<img width="778" alt="screen shot 2017-01-30 at 10 00 57" src="https://cloud.githubusercontent.com/assets/69485/22418986/449e39d2-e6d3-11e6-8bad-09e86990c3d1.png">

**Comment by mdahamiwal** [comment]
Its due to CSS load order. Having a local selector in your css file will solve the issue but its bad that we can't use ms-fontColor-* provided by fabric-core.

**Comment by dzearing** [comment]
This is one reason why I'm not a fan of the fabric color classes, really an extension of how terrible css specificity is. Just makes me lean more towards inline styling or some variant.

**Comment by dzearing** [comment]
I think we can close this; it's unfortunately not something we can work around unless we wholesale move away from css.
