### ISSUE TITLE
DetailsList: Scroll bar appearing for both header and list

### ISSUE THREAD

**Issue by siddarthkanted** [OfficeDev/office-ui-fabric-react#9070]
Scroller is coming for both header and list.

It should be appearing only for the list.

![image](https://user-images.githubusercontent.com/13218256/57601341-e2ea2880-7579-11e9-98ac-22bb910e5555.png)

Here we see the scroller is appearing for both header and list. It should generally appear only for list.

**Comment by KevinTCoughlin** [comment]
Hey @siddarthkanted, thanks for the report.

This is by design in the current `DetailsList` and `GroupedList` control. The header resides within the scrollable element therefore the scrollbar appears over it. This is visible on our examples such as https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/basic.

To support the above ask the control would need to be refactored so that the header is outside of the scrollable container. The scrollable container would be the grid's body rows.

This isn't a bug as far as I'm aware.

**Comment by siddarthkanted** [comment]
How to make this change?

**Comment by aneeshack4** [comment]
This doesn't seem like a bug & rather a feature request - but we should really question whether it makes sense for this behavior to be built into this control. Tagging for backlog review for when more work on the DetailsList control is done @aditima

**Comment by khmakoto** [comment]
Hi @siddarthkanted, sorry for the long delay in responding to this! This is by design in the current `DetailsList`, we could explore different approaches if we were to redo the component, but for the moment I'll resolve this as `Resolution: By Design`. Please let us know if there is anything else you need!
