### ISSUE TITLE
Container Classname for dropdown component

### ISSUE THREAD

**Issue by shgopala1** [OfficeDev/office-ui-fabric-react#9096]
**Describe the feature that you would like added**
The current classname is only applied to ms-Dropdown which is inside ms-Dropdown-container. We would like a container classname which can be applied to ms-Dropdown-container

**What component or utility would this be added to**
https://developer.microsoft.com/en-us/fabric#/controls/web/dropdown

**Have you discussed this feature with our team, and if so, who**
No

**Additional context/screenshots**
![image](https://user-images.githubusercontent.com/13006786/57727089-79375080-7645-11e9-9544-c1fb5fa9775a.png)

**Comment by JasonGore** [comment]
You can apply a custom className to any styleable section of `Dropdown` which are listed in `IDropdownStyles`. In this case, `ms-Dropdown-container` can be given a custom classname with `styles.root` as shown in [this Codepen](https://codepen.io/jasongore/pen/YbNWyd):

![image](https://user-images.githubusercontent.com/26070760/57738774-b8759980-7665-11e9-9c1b-2bff663444c9.png)

Does this look like it resolves your issue?

**Comment by sachin9996** [comment]
Hey Jason, thanks for the reply. We're currently planning on using this as a workaround.

Here's some context: The class name we want to add to the container element is for testing purposes, not to add any styling. We're using Selenium to find the dropdown and we want to target the container instead of the dropdown itself since we want to be able to read any error message that pops up (the error is rendered as a sibling of the dropdown, but a child of the container).

**Comment by JasonGore** [comment]
In this example, I didn't apply any styling, I just applied a className. I wouldn't consider this a workaround, this is our standard method for applying classNames to subcomponents. 😄

**Comment by JasonGore** [comment]
Actually rereading I see now that we shouldn't have to do this to root. I'll triage this as a bug.

**Comment by JasonGore** [comment]
Should be fixed with #9396 (I'm not sure why this issue didn't autoclose)
