### ISSUE TITLE
Date picker year up/down doesn't apply until month selected

### ISSUE THREAD

**Issue by tavishf** [OfficeDev/office-ui-fabric-react#9102]
### Bug Report

- __Package version(s)__: 5.128.0 but same behaviour is observable on the [component demo page](https://developer.microsoft.com/en-us/fabric#/controls/web/datepicker) 
- __Browser and OS versions__: N/A

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Possibly but not that likely

Requested priority: Normal

Products/sites affected: N/A

#### Describe the issue:

1. Open a date picker with no initial value
2. Use the year up/down arrow to change the year
3. Click on a day of month WITHOUT selecting a month from the year/month section first

#### Actual behavior:

Date populated is from current year

#### Expected behavior:

Date populated is from year user had selected using year up/down arrows

(This is from feedback from our users who were confused that the date populated was not what they expected they were selecting.)

### If applicable, please provide a codepen repro:

N/A but you can see it on the date picker page: https://developer.microsoft.com/en-us/fabric#/controls/web/datepicker

**Comment by lorejoh12** [comment]
This behavior is by design. We initially considered having the day picker auto navigate while using the up/down arrows in the month picker, but our designers found that to be a slightly confusing experience because if the user is navigating between years, we aren't sure which month to auto select and seeing the day picker change automatically was confusing for them while arrowing multiple times. So, our current design is to have the month picker and day picker part separated, and only actually change the day picker when the month gets selected, not just from navigation.

That being said, I'll pass this feedback along to them and we may pick this up again if they agree with you.

**Comment by tavishf** [comment]
Thanks for the feedback, good to know it's by design. Can definitely see there's arguments for the current behaviour.
