### ISSUE TITLE
DetailsList: Space to select should not scroll, focus on select box should remain visible

### ISSUE THREAD

**Issue by ronak-92** [OfficeDev/office-ui-fabric-react#914]
### Bug Report

- __Package version(s)__: (0.87.0)
- __Browser and OS versions__: (chrome and win 10)

#### Describe the issue:
When using DetailsList component with selection paradigm, if the selection is unchecked the focus treatment(grey background) goes away from the complete row. The keyboard navigation continues to work from that row without any issue.

#### Actual behavior:
The background experience for focus on the entire row is lost.

#### Expected behavior:
Ideally, when the row is unchecked, only the checkbox behaviour should be changed and the row should still have the focus with grey background.

**Comment by dzearing** [comment]
There is no grey treatment on focus, but there is on selection. Do you mean selection? 

![image](https://cloud.githubusercontent.com/assets/1110944/22475075/b444a8e2-e792-11e6-80ba-41fb5eb7af24.png)

We don't reset selection on losing focus. There is a focus rectangle when focus. (You do need your app wrapped in the `Fabric` component for it to show up correctly.)

![image](https://cloud.githubusercontent.com/assets/1110944/22475116/cc647574-e792-11e6-8217-511cd756c0b2.png)

@ronak-92 if you could provide screenshots of what you're observing, that could help to communicate what you're asking. Also what `selectionMode` are you referring to?

I *think* you want a css class on the "active" item so that you can add special css treatment on the item which is "active" meaning if you tab back to it, that will be the tab stop.

**Comment by ronak-92** [comment]
Thanks for clarifying the between the behaviour of focus and selection.

Expected Behavior:
With Selection 
![image](https://cloud.githubusercontent.com/assets/9554299/22499827/03399c60-e887-11e6-8d05-96155214a37e.png)

unselecting using keyboard
![image](https://cloud.githubusercontent.com/assets/9554299/22499851/24e38902-e887-11e6-887d-dd7592fc8a72.png)

If I try to unselect using 'space' key when the focus is on complete row, it unselects the column and maintains the focus, but it scrolls down the page which should not happen.

If I unselect when the focus is on checkbox using the keyboard, it unselects the row and loses the black rectangle border for focus which should have stayed.

**Comment by dzearing** [comment]
The scroll on space sounds like a bug. We should fix that.

The selection button seems to be totally hidden including the focus rect when the row is unselected. Only the button part, not the focus rect around it, should be hidden. That also seems like a small css bug.

If we fix those 2 does that completely address your issues? I want to make sure I'm capturing everything! But those 2 issues I definitely repro and we should fix.

**Comment by ronak-92** [comment]
Yes that would solve the issue.

**Comment by micahgodbolt** [comment]
ev.preventDefault is solving the scroll on spacebar issue. Taking a look at a fix now.
