### ISSUE TITLE
Tooltip is not visible while navigating inside FocusZone with arrow keys

### ISSUE THREAD

**Issue by saini-ankish** [OfficeDev/office-ui-fabric-react#9148]
## Codepen demonstrating the issue
https://codepen.io/anon/pen/QRMoWx?&editable=true
Edge/IE

## Documentation describing expected behavior
https://www.w3.org/TR/wai-aria-1.1/#tooltip

**Comment by marygans** [comment]
@saini-ankish  Thanks for the report! This is an issue with the browser tooltip based on your codepen link and W3C, so resolving this as external for Edge (since that was the targeted browser for the issue). I also have not been able to repro on Chrome or Firefox. Is the assumption I made about you using the browser tooltip correct?

**Comment by saini-ankish** [comment]
@marygans I've just attached a gif for more clarification on this, i don't think it's a browser issue.
It's like tooltip is not visible on arrow keys. And yes it's a browser tooltip.

![FocusZOne](https://user-images.githubusercontent.com/44394750/59598754-923a9200-911a-11e9-940f-23426b045731.gif)
