### ISSUE TITLE
[Regression] Dropdown erases selected option

### ISSUE THREAD

**Issue by PatoBeltran** [OfficeDev/office-ui-fabric-react#9200]
### Environment Information 
 
- __Package version(s)__: 6.184.0

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/PatoBeltran/pen/ZNrPJv

#### Actual behavior:
 
I have a dropdown that uses `selectedKey` to let the me handle the selection myself. If a user changes the selected option, but I don't change the `selectedKey` (In my scenario the user has to confirm after we change the value), the dropdown goes blank.

This is a regression and blocks my scenario since the next time the user tries to open the dropdown the `onChange` handler is being called (as if the user selected a new option) and this makes my scenario popup the confirmation modal, thus making this field not usable anymore.

#### Expected behavior:

I would expect that the dropdown doesn't handle the selection, but only passes the `selectedKey` throught and let me handle the logic for which option to have selected.

Requested priority: **High**

**Comment by micahgodbolt** [comment]
![dropdown](https://user-images.githubusercontent.com/1434956/58285588-ddeb5d00-7d61-11e9-9127-ac71500ed5f4.gif)

I can verify this change

**Comment by khmakoto** [comment]
Pinging @joschect for visibility since this seems to be a pretty bad bug.

**Comment by joschect** [comment]
Thanks for the visibility! I'm getting going on it, hopefully should have a fix soon.

**Comment by joschect** [comment]
Okay, this is the pr that broke it #8992 . It looks like it's setting the state too aggressively. I'll have a fix in tomorrow that will take care of it.

**Comment by mirajp** [comment]
Um is this a bug? @joschect @micahgodbolt @khmakoto 

https://codepen.io/anon/pen/oRJpye

With this change, the parent is no longer notified of an attempted selection change.
Due to this change introduced by #9263 (line 331 of `packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx`)
```
// If this is a controlled component then no state change should take place.
if (selectedKey !== undefined || selectedKeys !== undefined) {
    return;
}
```
this.props.onChange is never called and so the caller never knows a new selection was made/is attempted to be made.

Change the script source of the codepen to:
`<script src="//unpkg.com/office-ui-fabric-react@6.186.1/dist/office-ui-fabric-react.min.js"></script>`
to see what I thought is supposed to happen for the parent component.

**Comment by joschect** [comment]
@mirajp this is definitely a bug. I have a pr #9315 that fixes it.
