### ISSUE TITLE
Pointer-Events should be none maybe on Button html children elements

### ISSUE THREAD

**Issue by sitepodmatt** [OfficeDev/office-ui-fabric-react#9229]
Fabric UI, Latest Chrome (any OS) with Vimium plugin.

Applies to buttons. 

Vimium is placing 2 click markers per button. I think the children of the generated Button html tag should have pointer-events set to none so the event bubbles up.  Also applicable when using GTM (https://stackoverflow.com/questions/36611816/google-tag-manager-click-event-not-bubbling-up-to-parent) to track SPA analytics. 
![image](https://user-images.githubusercontent.com/1687145/58401726-de843c00-805e-11e9-9114-e342f6c9130f.png)

**Comment by khmakoto** [comment]
@sitepodmatt I'm having a hard time understanding your ask. Do you mean that, currently, the children inside Buttons have pointer-events that should be set to none so that only one click marker appears per button? If so, do you have an example of why the current implementation could lead to bad behavior?

It just seems weird to me that this is a problem but I do feel like I'm not getting the whole issue correctly, so a little clarification would definitely be appreciated :)

**Comment by micahgodbolt** [comment]
If you are having an issue where pointer-events: none need to be added to your buttons, is there anything stopping you from adding it via the styles interface, or simply writing the CSS to target that content? We have not found this to be an issue in any of our own applications.

**Comment by sitepodmatt** [comment]
Hi, let me mock up a codepen, I suspect there are fabric team members or internally MS users using vimium or other keyboarder with browsers.  I suspect if Vimium is confused maybe accessibility readers suffer the same.  I could be wrong though.

**Comment by micahgodbolt** [comment]
yeah, if you can get a repro, that'd help. we are just cautious with adding a sweeping change to a highly used control if we can avoid it.
