### ISSUE TITLE
Dropdown: RTL support for display text

### ISSUE THREAD

**Issue by nanivijay** [OfficeDev/office-ui-fabric-react#9302]
### Environment Information 
 
- __Package version(s)__: "//unpkg.com/office-ui-fabric-react/dist/office-ui-fabric-react.js"
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
 https://codepen.io/nanivijay/pen/QRzbzp

 
#### Actual behavior:
 
![image](https://user-images.githubusercontent.com/5945591/58729393-2af0b400-839e-11e9-8313-648cecd76c60.png)

 
#### Expected behavior:
 The display text should be United states (English)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No
 
Requested priority: (Blocking, High, Normal, Low)  Normal
 
Products/sites affected: (if applicable)

**Comment by leddie24** [comment]
Hey @nanivijay, I'm still exploring better solutions than what I have here.  This looks like an issue with how browsers render brackets/parenthesis in RTL.  There's a stack overflow covering this issue here:

https://stackoverflow.com/questions/5741522/brackets-displays-wrongly-for-right-to-left-display-style

I have a Codepen that provides onRender functions to dropdown to append the HTML entity to the end so the text displays properly.  Let me know if this solution works or doesn't for you; I will continue looking at better solutions in the meantime.

https://codepen.io/leddie24/pen/RmErKj?editors=1111

**Comment by nanivijay** [comment]
@leddie24 thank you for the code pen. this is helpful. but this can be done in out of box with fabric drop down.
