### ISSUE TITLE
Panel with scrollable content focuses on the scrollable content container in Firefox

### ISSUE THREAD

**Issue by JoshuaLamusga** [OfficeDev/office-ui-fabric-react#9314]
**Problem**
Panels that have scrolling content cause Firefox to unnecessarily focus on the scrolling content container div after the navbar elements. Here's an example of focus coming to the container after tabbing from the close button (highlighted the focus indicator in red):
![image](https://user-images.githubusercontent.com/30244654/58816202-e18ea780-85dd-11e9-9cdb-2b26b3365559.png)

The scrollable content container shouldn't receive focus, but does.

**Repro Steps**
1. Go to https://developer.microsoft.com/en-us/fabric#/controls/web/panel.
2. Find the example titled "Panel - Scrolling Content Sample".
3. Open the panel, tab through the controls.

**Comment by dzearing** [comment]
This has nothing to do with Fabric components.

Simple example here, using a scrollable div and some buttons. You can tab through and observe the div indeed receives focus:
https://codepen.io/dzearing/pen/mYgMKO

Any element marked `overflow: auto` or `overflow: scroll` in Firefox becomes a focus target. I believe it is done by design in Firefox so that users can use the keyboard to scroll the content. Otherwise, you would not be able to use the keyboard to scroll through the DIV content, unless it contains a focusable element, which means an accessibility concern.

I would recommend we don't work around this by setting `tab-index="-1"` on the element, but rather let the default browser behavior do the right thing.

For reference, here is a Chromium bug complaining that scrollable elements aren't by default focusable.

https://bugs.chromium.org/p/chromium/issues/detail?id=584618
