### ISSUE TITLE
Escape does not reliably dismiss Modal dialogs

### ISSUE THREAD

**Issue by citelao** [OfficeDev/office-ui-fabric-react#9379]
Although the `esc` key correctly dismisses Modal dialogs if keyboard focus is on the modal itself or a descendant, the `esc` key does not dismiss the modal if a user has caused focus to return to the `body`—say, by clicking on static text inside the modal.

This seems to differ from [ARIA spec that recommends `esc` always close the dialog](https://www.w3.org/TR/wai-aria-practices/#dialog_modal) (or, at least, it makes no mention of a case where `esc` shouldn't close the dialog).

## Codepen demonstrating the issue

See [this codepen](https://codepen.io/citelao/pen/rgXxKp?editors=0010). I basically took this from [the Modal docs](https://developer.microsoft.com/en-us/fabric#/controls/web/modal) 😄.

## Actual behavior:

1. Open the modal.
1. Press `esc`. The modal closes.
1. Open the modal again.
1. Click on or select some of the text in the modal.
1. Press `esc`. *The modal does not close*`.

## Expected behavior:

In both cases, I would expect the modal to close.

## Documentation describing expected behavior

* The ARIA authoring practices link above
* [Bootstrap Modals](https://getbootstrap.com/docs/4.0/components/modal/) have the behavior I expect.

Thanks!

**Comment by aneeshack4** [comment]
This has been reported in scan mode - bug 4 of #7990 but I see it repros without screenreader interaction too.

**Comment by JoshuaLamusga** [comment]
Oh wow, I thought this bug was already tracked! I noticed it easy some time ago. Along with escape not actually triggering light dismissal in panels (I wonder if that one is tracked?) You can see that on the demo pages where the button that spawns the panel is hidden only while the panel is active -- eventually, you have no buttons left.

**Comment by aneeshack4** [comment]
@JoshuaLamusga I dug into this quite a bit and spoke about it with the component owner & another engineer who's contributed a bunch to Modal. Here are my findings: the reason you're not able to close the dialog with ESC after click/selecting the text in the modal is because text is not selectable by keyboard, only by mouse. Once you keyboard/tab after opening the modal, focus will go to the first focusable element - the Close button in the Modal example page's case. After that, ESC does successfully close the dialog. Same with SPACE/ENTER - they also work to close the dialog once you tab/keyboard to the first focusable element. Text is only selectable via mouse so that's why we can't expect ESC to close the dialog after using keyboard and not mouse to select the text.
