### ISSUE TITLE
Add JavaScript Support

### ISSUE THREAD

**Issue by Kalaschnik** [OfficeDev/office-ui-fabric-react#9387]
**Describe the feature that you would like added**
As CSS Framework/Library competitors (Material UI, Semantic UI, Bootstrap React) offer primarily JavaScript implementation/examples it is an easy way to test a framework. Since—when learning web dev—one is starting with JavaScript before looking into TypeScript, it can be a hurdle to just offer TypeScript implementation/examples. If one simply just wants try out Fabric Reat TypeScript is a huge hinderer in this position, if one has no prior experience. Therefore, in order to drive user engagement, offer both implementations, similar to Material UI:
https://material-ui.com/components/buttons/

Thanks for any consideration.

**Comment by natalieethell** [comment]
Hey @Kalaschnik thanks for opening this issue! This is a valid concern and definitely something to consider. I'll add it to the backlog for further discussion with the team.

**Comment by khmakoto** [comment]
Hi @Kalaschnik, thank you for filing the issue and sorry for the long delay in response. While this is something that would be nice to have, it is an investment that we won't be making any time soon. I'll be tagging this as `Resolution: By Design` for now, but please know that we'll keep this feedback in our mind when overhauling our website experience. Please let us know if there is anything else I can do to help!

**Comment by Kalaschnik** [comment]
Thanks for the feedback. I know you want to push TypeScript, which is understandable, but don't forget that devs learn JavaScript before TypeScript, always. Moreover, many JS devs might not even consider looking into TS, as they are busy working with JS full time. Anyway, thank for considering it!
