### ISSUE TITLE
CommandBar: Make it composition of Components

### ISSUE THREAD

**Issue by atneik** [OfficeDev/office-ui-fabric-react#94]
Proposal to use SearchBox component in CommandBar instead of its own implementation.

**Comment by dzearing** [comment]
+1. And also to split out a couple extra components:

CommandList - a collapsable list of command buttons
CommandButton - a button styled for a command bar with an optional dropdown 

CommandBar should be a composite of:
* Searchbox
* CommandList for near commands
* CommandList for far commands

That's about it. It should be very little code.

**Comment by dzearing** [comment]
Recommend we split out a CommandList, but just remove Searchbox from command bar completely.

**Comment by micahgodbolt** [comment]
After a little tinkering I'm noticing that the search component is a different fixed height than the fixed height of everything in the CommandBar. I'm wondering why we're messing with fixed heights at all, so this is my proposition. Would like some feedback before putting too much work into this. 

__Proposed Set of Changes__

1. Move to flexbox based layouts
2. Update search and CommandBar Icons to fill the Vspace they are placed into. 
3. Create 3 layout regions (rather than fixing the width of the search component)
4. Create an overflow component to put commands into (seem to recall @dzearing working on one?)
5. Mobile Layout???? 3 rows? Search with Hamburger to expose commands as grid?

**Comment by micahgodbolt** [comment]
Got a jump on this today. Was able to do 1, 2 and 3. Seems the overflow is already set up in the list, so 4 is kinda working as expected.

I got a start on pulling the CommandList out, but there are tons of things I don't know if they belong to the list or the Bar. @dzearing if you wanted to take a look, I'm sure you could seperate the chaff from the wheat much faster.

https://github.com/micahgodbolt/office-ui-fabric-react/tree/CommandBar-componetize

**Comment by betrue-final-final** [comment]
Let's talk about this next week.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by micahgodbolt** [comment]
My todos

- v align of icons
- remove ... from search
- white bg of search box
- remove 'info' from (i)
- Change grid view to tile view

**Comment by betrue-final-final** [comment]
☺

**Comment by geraldhe** [comment]
+1 for using SearchBox instead of own implementation.
Current implementation is useless, because there is no event for text input?

**Comment by jrsell** [comment]
Or, how about adding an 'onRender', similar to how it is done for items in ContextualMenu? Then clients can hang whatever they want off the bar, be it a SearchBox, or whatever else...

**Comment by gitjain** [comment]
Issue got closed almost a month ago. Updating the status.

**Comment by petdun2519** [comment]
@gitjain is this fixed in next release of office fabric? Currently command bar does not respect the onRender of it's items props or it's faritems props. Is this fixed now?
