### ISSUE TITLE
Selected Rows are removed On clicking outside

### ISSUE THREAD

**Issue by vcgupta** [OfficeDev/office-ui-fabric-react#9442]
### Environment Information 
 
Current Version of Fabric on Chrome

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/vcgupta/pen/PrqBdG

#### Actual behavior:
 
* select few rows (or single row)
* Click outside the DetailsList component (on heading)
* selected rows or auto deselected
 
#### Expected behavior:
 
Selected rows should persist, even after clicking anywhere outside DetailsList

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) no
 
Requested priority: (Blocking, High, Normal, Low) High
 
Products/sites affected: (if applicable)

**Comment by vcgupta** [comment]
Please close, if https://github.com/OfficeDev/office-ui-fabric-react/issues/9408 PR fixes this.

**Comment by vcgupta** [comment]
I've found that `selectionPreservedOnEmptyClick` prop needs explicitly to be `true`. I think default value of this should be set to `true`.

**Comment by KevinTCoughlin** [comment]
> I've found that `selectionPreservedOnEmptyClick` prop needs explicitly to be `true`. I think default value of this should be set to `true`.

That prop is the correct solution. However changing the default would break partner teams who rely on existing behavior. Perhaps we can improve the documentation to make it more clear if it is non-obvious.

**Comment by natalieethell** [comment]
Hey @vcgupta thanks for opening this issue. PR #9408 dealt with a slightly different issue. As Kevin mentioned above, changing the default value for `selectionPreservedOnEmptyClick` would break teams relying on existing behavior. I'll label this as by design, but is there any way we can make this more apparent?

Here's what we have under the documentation for `selectionPreservedOnEmptyClick`

![image](https://user-images.githubusercontent.com/14134000/59464214-ab6ed600-8ddc-11e9-9cd7-1b767b979ee9.png)
