### ISSUE TITLE
Panel component's root is missing.

### ISSUE THREAD

**Issue by DanteMustDie** [OfficeDev/office-ui-fabric-react#9540]
The root is missing:
![image](https://user-images.githubusercontent.com/21332987/59893864-f4441180-9410-11e9-9432-2399c335ce1a.png)

After I changed the max-height of ms-Panel-main to 100%:
![image](https://user-images.githubusercontent.com/21332987/59893936-556be500-9411-11e9-983d-ab27d2581781.png)

Not sure if this is reported or fixed.

**Comment by aftab-hassan** [comment]
@DanteMustDie thanks for opening an issue.

Can you provide us with a few more details or provide us a codepen so we can better understand the issue.

1. Do you mean the `footer` is missing ? Could you elaborate on what you mean by _root is missing_ ?
2. What is the version of `Fabric` being used here?
3. What browser are you running this on?

We have a few examples of `Panel` [here](https://developer.microsoft.com/en-us/fabric#/controls/web/panel), and they all show the footer correctly. 

We look forward to understanding the issue and solving it!

**Comment by DanteMustDie** [comment]
@aftab-hassan thanks for your quick reply.

Actually the footer is not missing. It is rendered outside of the bottom of window in our page. And I found the cause why it works well in examples.

In our page, here is a header following by the content. The header's height is 50px, and the content area's height is 1079px. Window.innerheight is 1129px. But ms-Panel-main 's height is 1129px. So 50px is out of the bottom boundary. In examples, there is no header, so everything works well.
![1](https://user-images.githubusercontent.com/21332987/59918445-545da680-9457-11e9-8a07-da74b08e29ec.JPG)

The Fabric version I am using is 6.189.2

**Comment by aftab-hassan** [comment]
@DanteMustDie thank you for your explanation. That explains why you are hitting an issue, which is not seen in the examples. 

@kkjeer, On windows devices, having a header pushes the Panel down and is rendered outside the bottom of the page.

Could it be due to changes introduced in this `PR` https://github.com/OfficeDev/office-ui-fabric-react/pull/9351. The version number seems to be the same, `6.189.2`. Would you be able to take a look at this ?

**Comment by kkjeer** [comment]
@DanteMustDie @aftab-hassan thanks for reporting this! I'm currently investigating possible fixes.

**Comment by kkjeer** [comment]
Hi @DanteMustDie, I have a potential fix that involves removing `height: windowHeight` from the Panel's `main` div. So that I more fully understand your scenario (and can more comprehensively test my fix), could you tell me how you are achieving the styles that put the Panel component underneath your header? (Does the Panel have a custom style that involves `margin` or `top`, is the Panel inside another div with a specified `height`, etc.?) Thanks!

**Comment by aftab-hassan** [comment]
> @DanteMustDie @aftab-hassan thanks for reporting this! I'm currently investigating possible fixes.

thanks @kkjeer !
