### ISSUE TITLE
Ability to toggle DetailsList row and not deselect other rows when clicking

### ISSUE THREAD

**Issue by Pangamma** [OfficeDev/office-ui-fabric-react#9574]
**Describe the feature that you would like added**
https://stackoverflow.com/questions/56692224/how-to-toggle-office-ui-fabric-detailslist-row-selection-using-the-entire-row-as

**What component or utility would this be added to**
DetailsList
https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist

**Have you discussed this feature with our team, and if so, who**
I have not.

**Additional context/screenshots**

I'm using Office UI Fabric React components and i'm trying to improve change the default selection behavior for a [DetailsList][1]. By default, there is a difference between clicking a row and clicking the tiny checkbox on the right. I want the same effects of the checkbox click to apply to the row click. 

When you click the checkbox it **toggles** the row and does not deselect other rows like when I use a row click. You can also use shift click and control click and all the other nice types of clicks as well here. 

**How can I make it so that clicking on a row has the same functionality as clicking on one of the checkboxes?**
[![enter image description here][2]][2]

  [2]: https://i.stack.imgur.com/Kqu27.png

**Comment by KevinTCoughlin** [comment]
Thanks for your question @Pangamma. I believe this is possible with current code albeit not straight forward. I will try to provide a solution and if successful document it on our wiki or similar. If not then we can figure out a design for the feature.

**Comment by KevinTCoughlin** [comment]
@Pangamma, sorry just getting back to this. The default selection behavior _does allow_ for one to toggle selection of an individual row when multiple rows are selected by holding down the `CTRL` or `CMD` key depending on OS. This mimics the Windows File Explorer behavior and is by design.

Relevant LoC:

https://github.com/OfficeDev/office-ui-fabric-react/blob/c86bab4c0cc6d73530a04cdf600b72c356ab2c31/packages/office-ui-fabric-react/src/utilities/selection/SelectionZone.tsx#L523

As for overriding this default behavior, you'd likely have to provide your own `Selection` instance to `DetailsList` and intercept events to circumvent the above-linked logic.

**Comment by Pangamma** [comment]
https://stackoverflow.com/questions/56692224/how-to-toggle-office-ui-fabric-detailslist-row-selection-using-the-entire-row-as/56785728#56785728

Alternative answer found... works pretty well
