### ISSUE TITLE
Edge Specific: DetailsList does not resize to fill width or recompute width

### ISSUE THREAD

**Issue by rcasto** [OfficeDev/office-ui-fabric-react#9662]
### Environment Information 
- __Package version(s)__:  6.192.1
- __Browser and OS versions__: Edge

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/anon/pen/xojrMb

Click the `Toggle Sidebar` button to see whitespace formed in Edge from DetailsList not re-computing width

If you open the console in the codepen and execute:
`window.dispatchEvent(new Event('resize'))`

It does seems to re-trigger a render to compute the width.

#### Actual behavior:
Details list does not re-compute width to fill it in it's entirety
 
#### Expected behavior:
 Details list should re-compute width to fill it in it's entirety

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Maybe, not very familiar with DetailsList code
 
Requested priority: Normal
 
Products/sites affected: Virtual Agent Designer

**Comment by KevinTCoughlin** [comment]
Hmm thought I fixed some of these. This happening in Edge is likely due to this area of code:

https://github.com/OfficeDev/office-ui-fabric-react/blob/044e13c2c8c391885693bbaa493e975fab35f3ea/packages/office-ui-fabric-react/src/utilities/decorators/withViewport.tsx#L83

Mainly due to `ResizeObserver` not being available in Edge -- https://caniuse.com/#feat=resizeobserver&search=resize.

If you handle `viewport` yourself and pass the measurement down thru `DetailsList` then the rows should re-render properly.

**Comment by xugao** [comment]
This only repros in the new Edge browser since resize observer is supported there. I am going to mark this as won't fix, especially given that user has ways to work around this
