### ISSUE TITLE
Only Month and Date in Date Picker

### ISSUE THREAD

**Issue by Ashikpaul** [OfficeDev/office-ui-fabric-react#9726]
A date picker where current year is the default and only be able to select Month and Date. 
Eg : IsYearPickerVisible: false

**Comment by Vitalius1** [comment]
Hi @Ashikpaul , thanks for submitting this feature request. We will take a look into this and discuss the feasibility of adding this to the control.

**Comment by Vitalius1** [comment]
@lorejoh12 any thoughts on adding this feature to the Calendar of having a prop toggling the year picker part of it and default it to the current year?

**Comment by Vitalius1** [comment]
@Ashikpaul, can you please provide a mock of how you expect it to look? From a first look there will be some aligning to adjust when we hide the year picker and this will require a designer input.
Also, if the reason for this ask is to be able to restrict the user to change the year, you could consider setting some date boundaries through `minDate` and `maxDate` props. We would appreciate you providing more information on your specific need so we can asses the value of this feature. Thanks!

**Comment by lorejoh12** [comment]
A mock up of what this would look like would help here. I agree with Vitalie about the `minDate` and `maxDate` prop solution, that was my initial thought.

If you want to restrict the user to only selecting in the current year, and you used those props, you'd get something kind of like: 
![image](https://user-images.githubusercontent.com/8549582/61010727-561adb80-a32c-11e9-87b5-f7c0a675b865.png)
note the arrows for changing the year are disabled. If you'd rather hide them entirely instead of just disabling them, you can achieve that through custom styling. (how you'd do that would depend on whether you upgrade to the new @uifabric/date-time package or not, but we'd be happy to help you with how you could do it)

if you just don't want the decade picker (e.g. this thing, which you get by clicking on the header in the month picker:
![image](https://user-images.githubusercontent.com/8549582/61010751-6df25f80-a32c-11e9-887f-cc3d734c2b19.png)
you can prevent the user from seeing it using the `yearPickerHidden` prop
