### ISSUE TITLE
onKeydown  dosen't work on columnHeader in DetailList,  only in IE11

### ISSUE THREAD

**Issue by shivasai09** [OfficeDev/office-ui-fabric-react#9741]
### Environment Information 
 
- __Package version(s)__:latest version
- __Browser and OS versions__: IE11 windows 10

### Please provide a reproduction of the bug in a codepen:
 

 https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist
#### Actual behavior:
 when we try to sort the detail list with keyboard stroke on the column header , the list is not getting sorted. Only in IE11

whereas in other browsers the list is getting sorted , on keydown on the column header

 
#### Expected behavior:
 when we put focus on the column header and on keyboard stroke(press the enter) the list should get sorted, in IE11

#### Priorities and help requested:
 

 
Requested priority: Normal 
 
Products/sites affected: 
https://scuportalprv.office.com/Adminportal/home#/users

**Comment by Vitalius1** [comment]
@shivasai09 I tried to follow your repro steps and everything is working on my end. I can press `enter` while having focus on a column header and the sort logic gets triggered.

**Comment by shivasai09** [comment]
Hello @Vitalius1  i have a gif for the repro, i am able to repro it. It happens only in IE11

![detaillist](https://user-images.githubusercontent.com/33802398/60942699-34f0c580-a301-11e9-8e01-92c75255d775.gif)

**Comment by Vitalius1** [comment]
Interesting that running on localhost the project allows me to trigger the sort with the keyboard in IE11 but on the public website not. Will have to investigate what is preventing it.

![IE11](https://user-images.githubusercontent.com/29514833/61011549-d727a200-a32f-11e9-88af-68a306dfba81.gif)

**Comment by Vitalius1** [comment]
@shivasai09, the issue you are facing was fixed in #9587 and can be found in OUFR version starting with 7.6.2. It is also being back-ported now to Fabric 6 in #9770 and as soon as it’s merged, the next day release of v6 will have the fix in to be consumed.

That is why I was not able to repro it locally and the website was having the issue due to it being a little behind on the OUFR version it is using.

Let me know if upgrading to the v7 latest of OUFR solves your apps issue. Thanks!
