### ISSUE TITLE
Table/Grid component implementation with dropdown values

### ISSUE THREAD

**Issue by rake93** [OfficeDev/office-ui-fabric-react#9756]
**Describe the feature that you would like added**
I have a requirement where I need to create a Table/Grid with dropdown values using Office UI fabric React library. I have gone through the Microsoft office UI documentation and I don't find any component to achieve it.
**What component or utility would this be added to**
Grid or Table
**Have you discussed this feature with our team, and if so, who**
No
**Additional context/screenshots**
![Sample_Table](https://user-images.githubusercontent.com/823725/60981875-23a9b800-a305-11e9-9cd6-518e9e0347c1.jpg)

Inside image, 1. should have table/grid rows with Dropdown values. 2. when clicking Add, its should add row in the table/grid.

I found this feature from Kendo-react-grid, but I'm expecting the same component model from Office UI since we are using fabric react library for office word-addin development.

Sample Example code from Kendo-react-grid.
[kendo-react-grid sample code](https://stackblitz.com/edit/react-grid-dropdown-editor-separate)

Please provide your suggestions on how to implement using Office UI fabric react.

**Comment by Vitalius1** [comment]
Hi @rake93, I’ve put a [codepen](https://codepen.io/vitalius1/pen/GbzLWw) together to give you an idea on how it can be done. It will also require some custom style overrides to get to your exact mock but in general there is an idea.

As for a Table / Grid component, there are discussions of implementing one to be part of the Fabric suite, but nothing so far and there is determinate date when it will land.

Hope that helps!

**Comment by rake93** [comment]
@Vitalius1 , Thank you so much for the quick response with sample code. I appreciate your effort. I need another help from the above solution code. Consider that from attached snapshot of the issue description, there we have a source dropdown options, based on those dropdown selections we need to refresh the DetailsList i.e. for every option change we need to have new table grid. I have tried and not refreshing the table grid. would you please help me on this?

**Comment by Vitalius1** [comment]
@rake93, I am afraid I don’t have enough cycles and/or context of your scenario requirements to be able to provide you with a solution. With that said, to get a refresh of the `DetailsList` you need to update the `items` prop and in order to do that you would have to control the items in your app’s state. Or as the last resort, there is a public method `forceUpdate` on the `DetailsList` that you can access by passing React ref to `componentRef` prop, but that will still require you to keep a very detailed state of the items (along  with dropdown options that map to those items) and update the state on every selection.
