### ISSUE TITLE
Rating: Cannot set value as 0

### ISSUE THREAD

**Issue by j-te** [OfficeDev/office-ui-fabric-react#9799]
## Bug Report: 

This issue primarily refers to the apparent bug where the state value is incorrectly updating. 

### Environment Information 
 
- __Package version(s)__: `office-ui-fabric-react` `7.7.0`

### Please provide a reproduction of the bug in a codepen:
 
Cannot clear value or set to 0: [CodePen](https://codepen.io/anon/pen/PrgXad)
note: click the rating value: 3 then use toggle.

#### Actual behavior:
 
Component updates too soon: Value refers to state before update.
 
#### Expected behavior:
 
Component render updates to state or allow controlled value input.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (High) 

## Feature request:

When `allowZeroStars={true}`, clicking a star where the new value equals previous value sets the value to `0`. This avoids the requirement of a "clear" button. Note that there is no easy way to wrap this as a feature as `onChange` does not trigger unless the value changes.

**Comment by Vitalius1** [comment]
@j-te thanks for submitting the issue along with a repro. It helped understand and debug faster this issue. I have a fix submitted in #9805 for the controlled behavior and verified it locally and the toggle to 0 works.

As for the feature request to have the ability to click on a rating star of the same value and set it to 0 when `allowZeroStars` enabled, I totally agree that it would be a nice feature and needs to be added because currently in uncontrolled scenario with the `allowZeroStars` enabled you can’t set it back to 0 once you choose a value. Can you please submit a separate issue with requesting this feature to track features and bugs separately. Thanks!
