### ISSUE TITLE
Focus on CommandBar item

### ISSUE THREAD

**Issue by cnamal** [OfficeDev/office-ui-fabric-react#9832]
We would like to focus a button in the `CommandBar` when it is mounted as per this [codepen](https://codepen.io/namal-ms/pen/jgNqmd). However, this doesn't work, probably because the button is initially hidden.
As a temporary workaround, we set focus after 1 second, and that works, but is a bit hacky :D.

A couple of questions:
- Is there a better way of setting the focus with the current OUFR code?
- If not, could `CommandBar` expose a callback we could use to set the focus. I noticed `ResizeGroup` has a `dataDidRender` prop that might be exposed in `CommandBar`. I'm not familiar with these components, but it looks like that prop is called when the button is no longer [hidden](https://github.com/OfficeDev/office-ui-fabric-react/blob/382ec4fe6678eef91be9bc7e66091b11ff92e0a2/packages/office-ui-fabric-react/src/components/ResizeGroup/ResizeGroup.base.tsx#L383).

**Comment by joschect** [comment]
@cnamal thanks for submitting this! I can see the problem that you're experiencing and I'm digging into exactly why it's happening.

**Comment by joschect** [comment]
@cnamal This is happening because Command bar can potentially render several times before it's done moving things around. It's content being hidden is definitely part of the problem. While I think that we can expose dataDidRender since that's a fairly reasonable ask, I don't believe that it would solve your particular problem cleanly. It looks like dataDidRender is called every time the page is resized, so in order to use it to set focus once, you'd need to keep track of the first "real render" that happens. If that's acceptable I can move forward with exposing that prop.

Given the way that command bar works I don't think there are currently any other ways to go about this. @micahgodbolt do you have any other ideas?
