### ISSUE TITLE
[Nav] icon not displaying

### ISSUE THREAD

**Issue by graham-sportsmgmt** [OfficeDev/office-ui-fabric-react#989]
### Bug Report

- __Package version(s)__: 1.6.0
- __Browser and OS versions__: Tested in latest versions of Chrome, Firefox, and Edge

#### Describe the issue:

Adding an icon property to either a LinkGroup or Link results in no icon being displayed.

#### Actual behavior:

No icon is displayed.

#### Expected behavior:

An icon will be displayed next to the text, per the docs.

### If applicable, please provide a codepen repro:

Start with this codepen and add "icon" to any one of the links:

http://codepen.io/dzearing/pen/ZBGNQg?editors=0010

```
        {
        key: '#',
        name: 'Files',
        url: '#',
        icon: 'Documentation',
        linkProps: {
          ['data-foo']: 'bar'
        }
```

**Comment by mdahamiwal** [comment]
Not sure why but Icons are supported only for Button type items. You will need to attach onClick handler as well.  http://codepen.io/mdahamiwal/pen/ygGjez?editors=0010

**Comment by graham-sportsmgmt** [comment]
Interesting, the onClick handler activated the icon.  Should this be documented?

**Comment by micahgodbolt** [comment]
Right now button does support icons whereas link does not (that discrepancy is probably open for debate) as adding icons to links, or just using Button (which can render a button or a tag) for everything.

You're correct that adding an onClick does allow for icons, and here's why if you're curious.

https://github.com/OfficeDev/office-ui-fabric-react/blob/24d41e3383bb3cfe3ee8a557665e6d5976c40f8d/packages/office-ui-fabric-react/src/components/Nav/Nav.tsx#L137

```js
{ !!link.onClick ? this._renderButtonLink(link, linkIndex) : this._renderAnchorLink(link, linkIndex, nestingLevel) }
```

My feeling is that we'd prefer making the interface more consistent (pass an icon, get an icon) rather than updating docs to say "get your icon with this one simple trick".

**Comment by micahgodbolt** [comment]
@dzearing are you thinking that we make all nav items render as Buttons, or is there a need for that switch statement, and we should include a check for an icon being passed in?

**Comment by graham-sportsmgmt** [comment]
I like this a lot, it's far more intuitive:

> pass an icon, get an icon

These are the components I'd want icons in:

- CommandBar
- ContextualMenu
- Nav
- Pivot

**Comment by battletoilet** [comment]
You can render an icon in the link but it's not part of the initial contract for Link.

**Comment by IRRDC** [comment]
When a link is expandable icons are not displayed. It seems like it's not possible to have the expand/collapse icon and a manually set icon. Is this related to the details in this issue or should I create a new issue?
