### ISSUE TITLE
Dropdown: Placeholder text is read out by Narrator screenreader as selected if no list item is selected 

### ISSUE THREAD

**Issue by PavanJagini** [OfficeDev/office-ui-fabric-react#9890]
## Actual behavior:
"Organization Locale" is the place holder for "Organization Locale" dropdown, When combo box gets expanded NVDA announces ordering as 1 of 242 for Placeholder "Organization Locale".

![image](https://user-images.githubusercontent.com/52062804/61654056-4363b780-acd9-11e9-9de3-42484c0f80d7.png)

                <Dropdown
                    placeholder={UUMCONSTANTS.USER_DETAILS.ORGANIZATION_LOCALE}
                    name="orglocaleDropdown"
                    disabled={this.props.disabled}
                    options={this.props.allAvailableLocales.map(locale => ({ ...locale, key: locale.Id, text: locale.Name }))}
                    autoFocus
                    selectedKey={this.props.selectedOrgdetails["Locale"] === undefined ? null : this.props.selectedOrgdetails.Locale.key}
                    onChange={(e, value) => {
                        this.props.onLocaleChanged(value.key)
                        this.props.OrgdetailsChange('Locale', value);
                        this.forceUpdate();
                    }}

## Expected behavior:
Screen reader should not read out Placeholder text "Organization Locale" instead should read out as "Select Organization Locale" same as first-time focus to the control

**Comment by ecraig12345** [comment]
Thanks for submitting this! Is this behavior specific to NVDA, or do other screen readers (such as Narrator) read it the same way? 

Regardless, I'm not sure this is something we'll be able to fix within Fabric since we don't have the ability to provide localized strings such as "Select" built in to our controls.

Also, for future bugs, it would be helpful if you could provide a simplified standalone repro in a CodePen. You can start from either https://aka.ms/fabricpen or "Export to CodePen" on one of the [component examples](https://developer.microsoft.com/en-us/fabric#/controls/web/dropdown).

**Comment by PavanJagini** [comment]
Thanks for reply @ecraig12345!. Using Edge + Narrator, it mentions as 0 of 242 is selected. I will go back to the accessibility team mentioning this is to do with NVDA as its working as expected with the Narrator.
