### ISSUE TITLE
Can you split DocumentCardActivity into smaller components?

### ISSUE THREAD

**Issue by t-zeche** [OfficeDev/office-ui-fabric-react#9906]
Hi all! Now I'm working on Live Persona Card for Highlighted Content web part. What we expect is that the Live Pesrona Card will pop up when hovering or clicking on user's avatar and name(circled part in the pic). But these two small components are integrated together with "Edited Jul 22, 2019", called DocumentCardActivity. So can you guys split DocumentCardActivity into smaller components and expose their interface? It would be much convenient for future development. Thanks!
![Annotation 2019-07-22 195657](https://user-images.githubusercontent.com/53205695/61682319-b73aaa00-ad43-11e9-9c52-7a3a2cb9f07b.png)

**Comment by ecraig12345** [comment]
Do you expect that hovering/clicking the edited date should do something different? If not, it would be easiest to just include the edited date in the hover/click target for showing the persona card. Putting the avatar and name in a separate component from the edited date would be hard since they're laid out within the same DOM element.

**Comment by t-zeche** [comment]
the PM wants both avatar and name can trigger Live Persona Card. I have tried to convince him that just let avatar trigger LPC. we still don't have a final decision. I will keep you updated. Thanks !
