### ISSUE TITLE
ComboBox component defaultSelectedKey not working in IE

### ISSUE THREAD

**Issue by dylankil** [OfficeDev/office-ui-fabric-react#9911]
When opening the dropdown a second time, it's not scrolling with the mouse. defaultSelectedKey is also now missing from the docs.

To reproduce the issue go to https://onenote.com/learningtools in IE
Click on the 'Try It Now' button to launch the Immersive Reader
Open the Read Aloud Options Panel by clicking on the Book IconButton
Open the Translation ComboBox dropdown and select a language
Close the dropdown
Open it again and try to scroll the dropdown options container

**Comment by ecraig12345** [comment]
Thanks for submitting this, but it will be very hard to debug without an isolated repro. Could you please try to create a codepen starting from either the "Export to CodePen" link on one of the [ComboBox examples](https://developer.microsoft.com/en-us/fabric#/controls/web/combobox) or https://aka.ms/fabricpen?

**Comment by ecraig12345** [comment]
I can't reproduce this with an out-of-box dropdown, and it's not possible to debug on your page since it's minified code (and a production build of React). So you'll really need to make a codepen mirroring the setup you're using within your product if you want help addressing this.

Here's a link to use the codepen I made in IE: https://s.codepen.io/ecraig12345/debug/xvREOm/vWkRwazzDxdM

Editable version: https://codepen.io/ecraig12345/pen/xvREOm?editors=0010

To see your edits to the codepen in IE, you'll need to make a free account (debug view is only available if you have an account), fork the codepen, and save it into your account. Then choose debug view from the menu to get a URL which will work in IE.

<img src="https://user-images.githubusercontent.com/5864305/61986634-66d27f00-afc5-11e9-93bc-65dd848b899b.png" width="50%"/>

**Comment by dylankil** [comment]
I managed to narrow it down to a couple of CSS selector properties applied to the div with the class name 'ms-Panel-scrollableContent' - overflow-x and overflow-y, I appended overflow: auto and adjusted the width to hide the horizontal scroll bar and it fixed the issue in the app. Not sue, but IE support of these properties may not be as robust as modern browsers.

**Comment by dylankil** [comment]
Shouldn't effect customers who use Office UI Fabric 'as-is'

**Comment by ecraig12345** [comment]
Thanks for the update!
