### ISSUE TITLE
Focusing on MessageBar buttons in high contrast isn't visible

### ISSUE THREAD

**Issue by cnamal** [OfficeDev/office-ui-fabric-react#9934]
In high contrast when a button of the `MessageBar` is focused, it isn't obvious what element is focused.

We are using OUFR v6.

Impacted products: AI Builder in Powerapps

**Comment by ecraig12345** [comment]
Thanks for filing this, but I'm having trouble reproducing. Could you tell me:
- Which specific high contrast mode you're using
- Which browser and OS
- Which specific buttons within the MessageBar you're referring to: a screenshot and/or codepen would be helpful here

(In the future, please follow the issue template rather than deleting it, since it includes most of the info I'm now having to ask for.)

For a codepen, you can start from the "Export to CodePen" button in the first example from the [Fabric 6 MessageBar docs](https://developer.microsoft.com/en-us/fabric#/controls/web/messagebar?fabricVer=6), make any necessary prop modifications to get the issue to show up, and delete the extra MessageBars.

**Comment by cliffkoh** [comment]
I was able to reproduce this on latest version of Fabric  at https://fabricweb.z5.web.core.windows.net/oufr/7.16.0/#/examples/messagebar. I'll take care of it.

**Comment by ecraig12345** [comment]
Just curious, what settings did you use?

**Comment by cliffkoh** [comment]
I just turned on Windows High Contrast.. 

![image](https://user-images.githubusercontent.com/1003246/61923240-18b37200-af18-11e9-9760-db16a0abb1a6.png)

The problem in the screenshot is that even though I am focused on those buttons, you can't tell.

**Comment by cnamal** [comment]
Apologies @ecraig12345 for not providing repro steps. What @cliffkoh described is indeed the issue I was talking about. Thanks for quick replies/PR :)
Quick question: I believe the PR is targeting OUFR v7. Once it's merged, should I submit a PR that cherry-picks the fix for v6?
