### ISSUE TITLE
IE11 Bug - If you put the date as X/X/19, then the date is pushed to 1919. Default should probably be this century.

### ISSUE THREAD

**Issue by jaduong** [OfficeDev/office-ui-fabric-react#9941]
### Environment Information 
 
- __Package version(s)__: Latest
- __Browser and OS versions__: IE11

### Please provide a reproduction of the bug in a codepen: 

Can't add it because it's only repro in IE11. https://fabricweb.z5.web.core.windows.net/oufr/7.16.0/#/examples/datepicker 

Set the date to 1/1/19
 

 
#### Actual behavior: 
 
Date gets set as 1/1/**1919**
#### Expected behavior:
 
Date gets set as 1/1/**2019**

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (Normal) 
 
Products/sites affected: Project, Roadmap, any other sites using the Date Picker.

**Comment by ecraig12345** [comment]
It looks like this is an issue with IE 11's implementation of `Date.parse()`, since that's what the [default `IDatePickerProps.parseDateFromString` implementation](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.base.tsx#L47) uses. 

Due to all the different date formats that exist, and the fact that you can't directly access the current locale's date format in the browser, this would be hard or maybe impossible to fix within Fabric in a manner that's correct for all locales and use cases:

- Simple string replacement (like `dateStr.replace(/\/(\d\d)$/, '/20$1')`) won't work since the year is in different places per locale: for example, in en-us, the date format is month/day/year, but in other countries it's year/month/day or possible something different entirely.

- Checking if the parsed date is in the early 1900s and adding 100 years isn't a great idea (at least in Fabric itself) since it's possible some consumers may want their users to be able to pick years in the early 1900s.

Even if we can't fix this within Fabric, a workaround would be to supply your own custom `IDatePickerProps.parseDateFromString` implementation which only handles the special cases relevant for your situation. (For example, if you only support recent dates, you could use the second idea above in your custom implementation.)

@lorejoh12 Since you've been working on the date picker, do you have any recommendations for how to handle this, or a possible solution I've missed?

**Comment by ecraig12345** [comment]
Ping @lorejoh12

**Comment by lorejoh12** [comment]
Modern browsers handle this correctly, so this is the first time it's even come up on my radar.

The DatePicker control exposes a prop called "parseDateFromString", to allow the consumer to customize the parsing. If no value is provided, it defaults to: new Date(Date.parse(dateStr)). Since Date.parse(dateStr) doesn't work well in IE11, if a consumer needs additional validation, they can provide it here.

Quick digging shows that we're not the first to run into this:
https://github.com/angular/components/issues/12437
https://github.com/angular-ui/bootstrap/issues/2279

Those other packages seem to have settled on similar solutions, so I think this might be the best we can do for now.

In your case, if you have a large number of IE11 users and want to fix this issue for them, I believe you can require the date format passed in to conform to specific locale strings, i.e. "dd/mm/yyyy", and if their format doesn't match, return null rather than returning the wrong year. Or you can use other date parsing libraries for it, like the momentjs library- we don't include it in Fabric by default because of size concerns. I haven't played with those too much so can't provide much guidance on what the best solution would be.
