### ISSUE TITLE
Detailslist - rows selection cleared on clicking other parts of the row

### ISSUE THREAD

**Issue by taranlabana** [OfficeDev/office-ui-fabric-react#9976]
### Bug Report

- __Package version(s)__: 7.18.0
- __Browser and OS versions__: Chrome, Windows 10

#### Describe the issue:

The rows selection is cleared in details list with checkbox if user clicks on another part of a row. 
[Click here](http://g.recordit.co/Au9I2zOpE5.gif) to take a look.

This behavior can also be reproduced in the example given on [fabric page](https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist)

If it is a feature then can you please suggest a work around to disable it?

#### Actual behavior:

The selected rows are cleared and only one row remains selected.

#### Expected behavior:

Either it should not affect row selection or at least it should not clear the row selection.

**Comment by marygans** [comment]
Hi @taranlabana! 

The actual behavior reported is intended behavior by design. To multi-select rows you can use the SHIFT and META (CMD or CTRL).  This is consistent behavior with Window's native file explorer as well as OneDrive & SharePoint lists. If you would like to further discuss this design decision let me know!

You can customize this default behavior by utilizing the props [`selectionZoneProps`](https://github.com/OfficeDev/office-ui-fabric-react/blob/ba370cc708f709d6225e5ffcf021cfcac225d493/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.types.ts#L128) and providing your own [`ISelection` ](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/utilities/selection/SelectionZone.tsx)instance to DetailsList.

**Comment by taranlabana** [comment]
Thanks @marygans!
I will try it out
